### ISSUE TITLE
activity_id - add ScenarioMIP to Earth3-CC & add RFMIP to EC-Earth3-AerChem

### ISSUE THREAD

**Issue by treerink** [WCRP-CMIP/CMIP6_CVs#1002]
The EC-Earth consortium (institution_id is EC-Earth-Consortium) kindly asks for the following changes in the `CMIP6_CV.json`:
 
- Please add for EC-Earth3-CC            another activity_participation: ScenarioMIP
- Please add for EC-Earth3-AerChem  another activity_participation: RFMIP

Thanks a lot,
Thomas

(tagging also @shutingdk & @MartinaSt)

**Comment by durack1** [comment]
@treerink those tweaks are now in place, please review the details in [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let us know of any further changes required

**Comment by treerink** [comment]
Correct, thanks!
