### ISSUE TITLE
source_id -- add "C4MIP" and "ScenarioMIP" for MIROC-ES2H

### ISSUE THREAD

**Issue by tinoue70** [WCRP-CMIP/CMIP6_CVs#1003]
Please add "C4MIP" and "ScenarioMIP" to "activity_participation" of "MIROC-ES2H".

Thanks in advance.

**Comment by durack1** [comment]
@tinoue70 that tweak is now in place, please review the details in [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let us know of any further changes required
