### ISSUE TITLE
Add activity participation to IPSL-CM5A2-INCA

### ISSUE THREAD

**Issue by glevava** [WCRP-CMIP/CMIP6_CVs#1008]
@durack1  In CMIP6_source_id.json, please add "LUMIP" and "ScenarioMIP" as "activity participation" for "IPSL-CM5A2-INCA" source_id.

Many thanks !

**Comment by glevava** [comment]
Would it be possible to also add "CDRMIP" activity participation to "IPSL-CM6A-LR"? If we get enough computing ressource we may have some CDRMIP data in the future.
Cheers.

**Comment by durack1** [comment]
@glevava all done, take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) those changes are now in place
