### ISSUE TITLE
Activity_id : add FAFMIP for GFDL-ESM4 and GFDL-CM4

### ISSUE THREAD

**Issue by aradhakrishnanGFDL** [WCRP-CMIP/CMIP6_CVs#1010]
At the request of the model runner at GFDL, I’d like to request the addition of FAFMIP for our previously registered models GFDL-ESM4 and GFDL-CM4.  

Please let me know if you’d like additional information. Many thanks!

**Comment by matthew-mizielinski** [comment]
@aradhakrishnanGFDL, I've made the changes; please check [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know if I've missed anything.
