### ISSUE TITLE
"activity_id -- add ‘LUMIP'" to "source_id ACCESS-ESM1-5”

### ISSUE THREAD

**Issue by sjmarsland** [WCRP-CMIP/CMIP6_CVs#1012]

**Comment by durack1** [comment]
@sjmarsland that should be done, please take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know of any additional tweaks required

**Comment by durack1** [comment]
@sjmarsland I'd note that the support for the CMIP6 citation service became intermittent after the 31st January 2021, so simulations published for this new activity may not receive citation support (@martinast ping )
