### ISSUE TITLE
Adding DAMIP to activities for E3SM-1-1 

### ISSUE THREAD

**Issue by mccoy20** [WCRP-CMIP/CMIP6_CVs#1014]
** Note: registered content can be updated after 31st January 2021, but these changes may not be reflected by the CMIP6 citation service, see http://bit.ly/CMIP6_Citation_Search **

Here are instructions both for registering your institution and model for CMIP6 and for raising other issues concerning CMIP6 controlled vocabularies. We can update details iteratively, until you begin writing CMIP6 data.

PLEASE DELETE THESE INSTRUCTIONS BEFORE SUBMITTING YOUR REGISTRATION/ISSUE

*********************************************
## Registering your institution and model
*********************************************
Before publishing CMIP6 model output on ESGF, you must register information about your institution and  model as described in the registration guidance documents available at https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/.github/Institution_registration_template.md and https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/.github/Model_registration_template.md.

*********************************************
## Raising other issues
*********************************************
Your issue "title" should begin with the name of the Controlled Vocabulary of interest and also include a terse indication of the issue (e.g., "activity_id -- add 'PMIP'").

I would like to add DAMIP to activities for E3SM-1-1 (originally added with issue #775 https://github.com/WCRP-CMIP/CMIP6_CVs/issues/775)

label = E3SM 1.1
label_extended = E3SM 1.1 (Energy Exascale Earth System Model)
source_id = E3SM-1-1
institution_id = E3SM-Project
release_year = 2019
activity_participation = [CMIP C4MIP ScenarioMIP LS3MIP **DAMIP**]

**Comment by durack1** [comment]
@mccoy20 thanks for the tweak, the additional of `DAMIP` is now in place - take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know of any further tweaks required
