### ISSUE TITLE
Add GISS-E2.2H as a model

### ISSUE THREAD

**Issue by gavinny** [WCRP-CMIP/CMIP6_CVs#1018]
I'd like to add another model to the CMIP6_source_id.json file. Thanks.

"GISS-E2-2-H":{
            "activity_participation":[
                "CMIP",
                "SIMIP",
                "ScenarioMIP"
            ],
            "cohort":[
                "Registered"
            ],
            "institution_id":[
                "NASA-GISS"
            ],
            "label":"GISS-E2.2H",
            "label_extended":"GISS-E2.2H",
            "model_component":{
                "aerosol":{
                    "description":"Varies with physics-version (p==1 none, p==3 OMA, p==4 TOMAS, p==5 MATRIX)",
                    "native_nominal_resolution":"250 km"
                },
                "atmos":{
                    "description":"GISS-E2.2 (High Top, 2.5x2 degree; 144 x 90 longitude/latitude; 102 levels; top level 0.002 hPa)",
                    "native_nominal_resolution":"250 km"
                },
                "atmosChem":{
                    "description":"Varies with physics-version (p==1 Non-interactive, p>1 GPUCCINI)",
                    "native_nominal_resolution":"250 km"
                },
                "land":{
                    "description":"GISS LSM",
                    "native_nominal_resolution":"250 km"
                },
                "landIce":{
                    "description":"none",
                    "native_nominal_resolution":"none"
                },
                "ocean":{
                    "description":"HYCOM Ocean (~1 degree tripolar grid; 360 x 180 longitude/latitude; 32 levels; top grid cell 0-10 m)",
                    "native_nominal_resolution":"100 km"
                },
                "ocnBgchem":{
                    "description":"none",
                    "native_nominal_resolution":"none"
                },
                "seaIce":{
                    "description":"GISS SI",
                    "native_nominal_resolution":"250 km"
                }
            },
            "release_year":"2021",
            "source_id":"GISS-E2-2-H"
        },

**Comment by durack1** [comment]
@gavinny I assume the sea ice is running at the same resolution as the ocean, so 250 -> 100 km? Also do you have versions of the LSM and SI models to note?

**Comment by gavinny** [comment]
No. SI is on the Atmos grid. No versioning of the LSM/SI models (same as what was used in E2.1 configurations).

Thanks!

Gavin

--
Gavin A. Schmidt
NASA Sr. Advisor on Climate (acting)
Goddard Institute for Space Studies
2880 Broadway, New York NY 10025
Cell: 212 749 0006
Email: ***@***.******@***.***>
URL: https://www.giss.nasa.gov/staff/gschmidt


From: "Paul J. Durack" ***@***.***>
Reply-To: WCRP-CMIP/CMIP6_CVs ***@***.***>
Date: Friday, April 30, 2021 at 2:42 PM
To: WCRP-CMIP/CMIP6_CVs ***@***.***>
Cc: "Schmidt, Gavin A. (GISS-6110)" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [WCRP-CMIP/CMIP6_CVs] Add GISS-E2.2H as a model (#1018)


@gavinny<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgavinny&data=04%7C01%7Cgavin.a.schmidt%40nasa.gov%7C6546203649ca4af9bc7808d90c07b573%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637554049514910700%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Vn0MO%2F9AgXuEJNs40OmZYMUrUdzMh0NV9xGzrqs6QUc%3D&reserved=0> I assume the sea ice is running at the same resolution as the ocean, so 250 -> 100 km? Also do you have versions of the LSM and SI models to note?

**Comment by durack1** [comment]
@gavinny all registered, please take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know of any further tweaks required

**Comment by gavinny** [comment]
Thanks!

--
Gavin A. Schmidt
NASA Sr. Advisor on Climate (acting)
Goddard Institute for Space Studies
2880 Broadway, New York NY 10025
Cell: 212 749 0006
Email: ***@***.******@***.***>
URL: https://www.giss.nasa.gov/staff/gschmidt


From: "Paul J. Durack" ***@***.***>
Reply-To: WCRP-CMIP/CMIP6_CVs ***@***.***>
Date: Friday, April 30, 2021 at 6:03 PM
To: WCRP-CMIP/CMIP6_CVs ***@***.***>
Cc: "Schmidt, Gavin A. (GISS-6110)" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [WCRP-CMIP/CMIP6_CVs] Add GISS-E2.2H as a model (#1018)


@gavinny<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgavinny&data=04%7C01%7Cgavin.a.schmidt%40nasa.gov%7Cd1e3383b86e149c0bb9a08d90c23b9bd%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637554169845931060%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yspIuqu5uqNMKBCrHxovbb%2F82L9NXn0h2RUYSOO6awM%3D&reserved=0> all registered, please take a peek at CMIP6_source_id.html<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwcrp-cmip.github.io%2FCMIP6_CVs%2Fdocs%2FCMIP6_source_id.html&data=04%7C01%7Cgavin.a.schmidt%40nasa.gov%7Cd1e3383b86e149c0bb9a08d90c23b9bd%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637554169845941022%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rarXe7dsgUyJh56gWZY7L9yviOxqnLQi44cqhTxatDo%3D&reserved=0> and let me know of any further tweaks required

**Comment by durack1** [comment]
@gavinny I've just been starting a new OHC analysis and stumbled across the fact that GISS-E2-2-H ['r1i1p1f1'] has 33 vertical levels in the output, whereas the reporting above says 32 - is this a typo that should be fixed? If yes, did you want to reopen this and I'll make the tweak

**Comment by gavinny** [comment]
yes. That's a typo. Let's fix it.

**Comment by durack1** [comment]
I presume this is also and issue for #177, if yes, open that up as well and I'll sort that soon

**Comment by gavinny** [comment]
Yes. It’s been a while since I looked at this and I can’t work out if I can make the edits (on what file?), or if you have to do that? Do you even need anything else from me?

Thanks

Gavin

--
Gavin A. Schmidt
Director, NASA Goddard Institute for Space Studies
2880 Broadway, New York NY 10025
Cell: 212 749 0006
Email: ***@***.******@***.***>
URL: https://www.giss.nasa.gov/staff/gschmidt


From: "Paul J. Durack" ***@***.***>
Reply-To: WCRP-CMIP/CMIP6_CVs ***@***.***>
Date: Wednesday, March 13, 2024 at 2:51 PM
To: WCRP-CMIP/CMIP6_CVs ***@***.***>
Cc: "Schmidt, Gavin A. (GISS-6110)" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] [BULK] Re: [WCRP-CMIP/CMIP6_CVs] Add GISS-E2.2H as a model (#1018)

CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.



I presume this is also an issue for #177<https://github.com/WCRP-CMIP/CMIP6_CVs/issues/177>, if yes, open that up as well and I'll sort that soon

**Comment by gavinny** [comment]
Yes, both instances. Thanks

--

Gavin A. Schmidt
Director, Goddard Institute for Space Studies
2880 Broadway, New York NY 10025
Cell: 212 749 0006
Email: ***@***.******@***.***>
URL: https://www.giss.nasa.gov/staff/gschmidt



From: Paul J. Durack ***@***.***>
Date: Thursday, March 28, 2024 at 4:51 PM
To: WCRP-CMIP/CMIP6_CVs ***@***.***>
Cc: Schmidt, Gavin A. (GISS-6110) ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] [BULK] Re: [WCRP-CMIP/CMIP6_CVs] Add GISS-E2.2H as a model (#1018)
CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.



@gavinny<https://github.com/gavinny> yep over to me for tweaks, BUT, it would be useful for me to know whether the same issue should be fixed for GISS-E2-1-H ['r1i1p1f1'] as well? (this issue is focused on GISS-E2-2-H ['r1i1p1f1'])

**Comment by durack1** [comment]
@gavinny `GISS-E2-2-H` updated to reflect ***33*** (and not 32) vertical ocean levels, see [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) - similar to #177
