### ISSUE TITLE
3hrPt vs 3hr

### ISSUE THREAD

**Issue by chenghaow** [WCRP-CMIP/CMIP6_CVs#1020]
Sorry I accidentally opened this issue while searching for answers, but here is the question I was planning to ask: 
According to CMIP6_frequency.json, there are two frequencies for 3-hourly data: 
        "3hr":"sampled every 3 hours",
        "3hrPt":"sampled 3 hourly, at specified time point within the time period",
Which one is the instantaneous result sampled at the time instant, and which one is the average value over the 3-hr period (the 3-hr period prior to the time instant)?

**Comment by matthew-mizielinski** [comment]
Hi @chenghaow,  the `3hr` and `6hr` frequencies refer to variables with `time: mean` in their cell_methods, i.e. those that are an average over the period specified, but it would be good for this to be a little clearer in the files here as I'm not sure where else this would be documented.

@durack1, I don't think that the descriptive text given as the values corresponding to these keys in CMIP6_frequency.json is used anywhere so I'll throw in a pull request shortly to cover this -- let me know if I'm missing any downstream impacts of this.

**Comment by durack1** [comment]
@martinjuckes @taylor13 @mauzey1 just pinging you on this thread, I forgot whether these strings are reused by the data request, or across the cmip6-cmor-tables? Martin, Chris?

**Comment by mauzey1** [comment]
The strings for `3hr` and `3hrPt` are found in CMIP6_CV.py.
https://github.com/PCMDI/cmip6-cmor-tables/blob/95ae5997c4cb4f994f73c9c0a853082cded4bfb6/Tables/CMIP6_CV.json#L2497-L2498

**Comment by durack1** [comment]
@mauzey1 thanks for that, are these entries used by CMOR or any of the other cmip6-cmor-tables generation?

**Comment by mauzey1** [comment]
@durack1 The descriptions of the frequencies are only found in CMIP6_CV.json.  I can't find anything in CMOR that uses those entries.

**Comment by durack1** [comment]
@mauzey1 thanks for clarifying, it seems that the changes in #1022 will not trip anything over then, will merge this soon

**Comment by durack1** [comment]
Closed by #1022

**Comment by matthew-mizielinski** [comment]
Thanks @dnadeau4, @mauzey1 !

**Comment by durack1** [comment]
@dnadeau4 still receiving kudos for your work on CMIP6/CMOR!!
