### ISSUE TITLE
CMIP6_source_id: Add PAMIP to the E3SM-1-0 activity participation

### ISSUE THREAD

**Issue by sterlingbaldwin** [WCRP-CMIP/CMIP6_CVs#1030]
See PR #1029

**Comment by durack1** [comment]
@sterlingbaldwin thanks for this, please take a peek at [](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know if any additional tweaks are required.

The [PCMDI/cmip6-cmor-tables:Tables/CMIP6_CV.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json) file will be updated by cron at 12 am tonight.

@mauzey1 ping

**Comment by mauzey1** [comment]
@sterlingbaldwin @durack1 The changes have now been merged into the master branch of cmip6-cmor-tables.

**Comment by durack1** [comment]
@mauzey1 thanks for this!
