### ISSUE TITLE
source_id -- set "250km" as native_nominal_resolution for "atmos"-entry of "ICON-ESM-LR"

### ISSUE THREAD

**Issue by sol1105** [WCRP-CMIP/CMIP6_CVs#1034]
Please change the `native_nominal_resolution` for the atmospheric submodel (ICON-A) of ICON-ESM-LR from `100km` to `250km`.

```python
        "ICON-ESM-LR":{
                [...]
                "atmos":{
                    "description":"ICON-A (icosahedral/triangles; 160 km; 47 levels; top level 80 km)",
                    "native_nominal_resolution":"250 km"
```

**Comment by durack1** [comment]
@sol1105 thanks for the correction. That is now in place, please review [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know of any further tweaks required
