### ISSUE TITLE
source_id registration of [TaiESM1-TIMCOM2]

### ISSUE THREAD

**Issue by rceclccr** [WCRP-CMIP/CMIP6_CVs#1040]
I would like to add
label = TaiESM1-TIMCOM2
label_extended = Taiwan Earth System Model 2.0 using TIMCOM ocean model
source_id = TaiESM1-TIMCOM
institution_id = NTU
release_year = 2021
activity_participation = CMIP OMIP

aerosol:
description = SNAP (same grid as atmos)
nominal_resolution = 100 km
atmos:
description = TaiAM1 (0.9x1.25 degree; 288 x 192 longitude/latitude; 30 levels; top level ~2 hPa)
nominal_resolution = 100 km
atmosChem:
description = SNAP (same grid as atmos)
nominal_resolution = 100 km
land:
description = CLM4.0 (same grid as atmos)
nominal_resolution = 100 km
landIce:
description = none
nominal_resolution = none
ocean:
description = TIMCOM (TIMCOMv2.2, primarily 1deg; 320 x 288 longitude/latitude; 55 levels; top grid cell 0-10 m)
nominal_resolution = 100 km
ocnBgchem:
description = none
nominal_resolution = none
seaIce:
description = CICE4
nominal_resolution = 100 km

**Comment by durack1** [comment]
@rceclccr thanks for the update. Your registration is now complete, please take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) noting that I cleaned up a couple of inconsistencies
```
source_id = TaiESM1-TIMCOM2
label_extended = Taiwan Earth System Model 1.0 using TIMCOM ocean model 2.0
seaIce|nominal_resolution = CICE4 (same grid as ocean)
```
Please let me know if any further tweaks are required
