### ISSUE TITLE
Add UCI as a registered institution for the E3SM-1-0 source_id 

### ISSUE THREAD

**Issue by ypeings** [WCRP-CMIP/CMIP6_CVs#1048]
Hello,

We would need to get the institution "UCI" registered as as a registered institution for the E3SM-1-0 source_id.
We were in charge of running E3SM runs here at UCI, but this not a model from our institution.
Thanks,

Yannick Peings

**Comment by durack1** [comment]
@ypeings @chengzhuzhang that change is now made, please update your [cmip6-cmor-tables](https://github.com/PCMDI/cmip6-cmor-tables/), which should include the new registration and enable publication of `UCI:E3SM-1-0` data

**Comment by chengzhuzhang** [comment]
Thank you for a super quick turnaround, Paul!
