### ISSUE TITLE
Add CMIP6 license/rights information per source_id

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#1050]
There is a need to centralize updated information about the licenses associated with CMIP6 data published and available through ESGF. Many waivers have been requested both through the WGCM, in addition to the ESGF mailing list, and direct requests to modeling groups themselves.

All CMIP6 models, as per the [CMIP6: Terms of Use](https://pcmdi.llnl.gov/CMIP6/TermsOfUse/TermsOfUse6-1.html) page is identified as having a `Creative Commons Attribution-ShareAlike 4.0` (CC BY-SA 4.0) license, however, some groups are opting to relax these to the wide-open `No Rights Reserved` (CC0), or the less restrictive `Attribution 4.0 International` (CC BY 4.0).

These license updates need to be captured and centralized in a single location, which will supersede information captured in the NetCDF file global attributes (many of which were written with CMOR defaults to CC BY-SA 4.0)

The proposed path is to add three new attributes (`license_original`, `license_current`, `license_contact` - please suggest better identifiers) to the existing registered information, for e.g.

https://github.com/WCRP-CMIP/CMIP6_CVs/blob/99351a3c469b54c1d0398229aa8c2ab5cc65c70e/CMIP6_source_id.json#L7393-L7456

This will allow the current (and previous, along with the contact email - harvested from the NetCDF file headers) license information to be presented on the [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) HTML rendered page and linked to from other locations - including the Terms of Use page.

Please chime in with clarifications, suggestions etc

@martinjuckes @matthew-mizielinski @MartinaSt @taylor13

**Comment by durack1** [comment]
@mauzey1 the proposed change above will likely require an update to the [cmip6-cmor-tables](https://github.com/PCMDI/cmip6-cmor-tables/), and possibly CMOR, so just looping you into this thread

**Comment by taylor13** [comment]
You could consider placing the 3 new attributes in a nested dictionary with "license" including 3 items: original, current, and contact.  This would be organizationally better I think.  Would it be significantly harder to access the information in that structure?

**Comment by durack1** [comment]
@taylor13 that is a good suggestion, and technically no easier/harder than the original suggestion. Coming up with clear and easy to interpret names is a harder challenge

**Comment by durack1** [comment]
Add lat/lon/depth/height to metadata scour - building CMIPx_CVs

**Comment by matthew-mizielinski** [comment]
To flesh this out a little I've added something like Karl's suggestion below, with a couple of extras (date and link).  Do we need full text for the license here or is the shorthand sufficient?

When it comes to updating the HTML tables based on the JSON files I would be sorely tempted to produce a separate page to document this (happy to draft something)

```json
        "UKESM1-0-LL":{
            "activity_participation":[
                "AerChemMIP",
                ...,
                "VolMIP"
            ],
            "cohort":[
                "Registered"
            ],
            "institution_id":[
                "MOHC",
                "NERC",
                "NIMS-KMA",
                "NIWA"
            ],
            "label":"UKESM1.0-LL",
            "label_extended":"UKESM1.0-N96ORCA1",
            "license":{
                "contact":"cmip6.ukesm1@metoffice.gov.uk",
                "current":"CC-BY 4.0",
                "date":"07-Feb-2022",
                "link":"https://ukesm.ac.uk/licensing-of-met-office-nerc-and-niwa-cmip6-data/",
                "original":"CC-BY-SA 4.0",
            },
            "model_component":{
                "aerosol":{
                    "description":"UKCA-GLOMAP-mode",
                    "native_nominal_resolution":"250 km"
                },
                ...,
                "seaIce":{
                    "description":"CICE-HadGEM3-GSI8 (eORCA1 tripolar primarily 1 deg; 360 x 330 longitude/latitude)",
                    "native_nominal_resolution":"100 km"
                }
            },
            "release_year":"2018",
            "source_id":"UKESM1-0-LL"
        },
```

**Comment by durack1** [comment]
@matthew-mizielinski @MartinaSt thanks for chiming in, I am going through the process of extracting information from the CMIP6 archive (in particular contact info) so I can generate a pull request for review (and tweaks), before we open it up to request feedback from the modeling groups. I think what you've both outlined can be merged, having a link to the license blurb as you have provided @MartinaSt is a good thing to have alongside the identifiers

So something like:
```json
            ...
            "license":{
                "contact":"cmip6.ukesm1@metoffice.gov.uk",
                "url":"https://ukesm.ac.uk/licensing-of-met-office-nerc-and-niwa-cmip6-data/",
                "rights_identifier_original":"CC BY-SA 4.0",
                "date":"Fri Feb 11 17:21:00 2022 -0700", # this could be "rights_updated" or similar
                "rights":"Creative Commons Attribution 4.0 International License (CC BY 4.0)",
                "rights_uri":"https://creativecommons.org/licenses/by/4.0/",
                "rights_identifier":"CC BY 4.0"
            },
            ...
```

**Comment by durack1** [comment]
@matthew-mizielinski @MartinaSt still working on extracting this info, it's taking longer than I thought. Is the above format what we want to finalize on, or are further tweaks required?

**Comment by durack1** [comment]
Also think about compressing information https://datatables.net/examples/styling/compact.html

**Comment by taylor13** [comment]
A couple of suggested tweaks:

1.  replace "date" with "history" which would record date of original license and dates and descriptions of any modifications made.  For example "history":"2018-03-01: initially published under CC BY-SA 4.0; 2021-11-15: relaxed to CC BY 4.0;  2024-01-01: relaxed further to CC0".  This would eliminate the need for "rights_identifier_original".  
2. I think the "rights" statement should be a complete sentence like "Data is made available under the Creative Commons Attribution 4.0 International License (CC by 4.0; https://creativecommons.org/licenses/by/4.0/)".  This is what currently is stored in the "license" global attribute of each CMIP6 netCDF file.

**Comment by taylor13** [comment]
I don't understand what the "styling" is.  Does that change the format of the json file?

**Comment by matthew-mizielinski** [comment]
> @matthew-mizielinski @MartinaSt still working on extracting this info, it's taking longer than I thought. Is the above format what we want to finalize on, or are further tweaks required?

No problem. Feel free to throw the code to me for review if useful.

**Comment by matthew-mizielinski** [comment]
Hi @taylor13,  I think the styling is around the presentation of data in the html tables, e.g. [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) where we can either consider adding more columns or an extra page to present this information. Regarding your point 3 above, I would be tempted to choose an order to present these fields in via a more human readable form (e.g. HTML table), but stick with alphabetic ordering in the JSON for consistency with the rest of the documents.

**Comment by MartinaSt** [comment]
I am fine with the suggestions for the license information. 

Two remarks:
1. I like @taylor13 's `history` attribute because of its flexibility and transparency (showing all historical changes of the license). We never know what modeling centers might want to do...

2. The only part, which I would delete is the `contact`:
I still don't know why we need an additional license-specific contact. These contacts tend to get outdated very quickly.  Secondly, as part of the citation service contacts with different roles are collected from the modeling centers.  To collect some contacts via the CV and others via the citation service is kind of confusing. A minor point is spam for the modeling centers. as we publish unencrypted emails in the web.

**Comment by taylor13** [comment]
@matthew-mizielinski @durack1 .  I understand that in the current CV json files, key words are generally ordered alphabetically, but why is that desirable?   It seems to me that machines don't care about the ordering, so we're ordering things for those humans who might prefer to look at the json files (and not some rendering we might provide).  When all key words in the json file are of equal importance, then I agree that alphabetical ordering may facilitate humans attempting to obtain information (especially if the number of entries is large).  But if we think some of the information is likely to be of more interest to users than other information, we should be free to place the important stuff up front.   I'd prefer, for example, to find the "experiment" and perhaps the "description" entries as the first items under each experiment_id in the experiment_id json files.  (Ordering the experiment_id's themselves alphabetically seems fine, on the other hand, since all experiments are presumably of equal importance.)

**Comment by MartinaSt** [comment]
> I think the "contact" information is there so that any user seeking an exception to the license restrictions knows whom to write. Without that, the WIP will probably get the requests for granting such exceptions. Perhaps we can require the "contact" to be something other than an individual so that it might persist longer.

Thanks Karl, then we should recommend that modeling centers put this email address on their `source-specific_info` page and maintain it, locally.

**Comment by durack1** [comment]
@MartinaSt thanks for chiming in, I am inclined to add this (it's what I am attempting to extract from the archive now), but obscure it to make it machine-unreadable. As @taylor13 notes, having this information alongside the license info will allow an interested party to approach to modeling group to get an exception or license relaxation, which we could then record as an update (and increment the version info, which I also think is a good idea to attempt to capture the evolving situation).

@taylor13 regarding "styling" this was just the HTML rendering of info, so for e.g. the [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) page which contains ALOT of information. I am inclined to not mess too much with the standard json write/read library, and rather let the software sort the information as it likes - as long as we have accurate info, that's the most important thing

**Comment by taylor13** [comment]
my point was that if you're adding license information, you should feel free to order the license information any way you want.  I'm not suggesting you mess with the existing source information.  for CMIP7, we might want to reorder things to our liking rather than be slaves to alphabetical ordering (since machines don't care about the order).

**Comment by taylor13** [comment]
To be explicit, I suggest replacing "contact" with "exceptions_contact".

**Comment by durack1** [comment]
@taylor13 got it, I think we're incrementing toward an end format here. To complete the `history` attribute, we are going to need the metadata that I am currently scouring. I am blown away by how many data inconsistencies I have been hitting that has tripped over assumption after assumption - dealing with "big" data is hard.

So I think we're now coalescing on the format below - note the garbled email address, @MartinaSt does this work for you?
```json
"license":{
      "license_identifier":"CC BY 4.0",
      "rights":"Data is made available under the Creative Commons Attribution 4.0 International License (CC by 4.0; https://creativecommons.org/licenses/by/4.0/)"
      "rights_info":"https://creativecommons.org/licenses/by/4.0/",
      "exceptions_contact":"@metoffice.gov.uk <-cmip6.ukesm1",
      "source-specific_info":"https://ukesm.ac.uk/licensing-of-met-office-nerc-and-niwa-cmip6-data/",
      "history":"2018-03-01: initially published under CC BY-SA 4.0; 2021-11-15: relaxed to CC BY 4.0"
},
```

**Comment by durack1** [comment]
It's likely that we'll have the following licenses to deal with:
CC0 1.0 https://creativecommons.org/publicdomain/zero/1.0/
CC BY 3.0 https://creativecommons.org/licenses/by/3.0/
CC BY 4.0 https://creativecommons.org/licenses/by/4.0/
CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/
CC BY-NC-SA 4.0 https://creativecommons.org/licenses/by-nc-sa/4.0/

@MartinaSt are there any others that folks have discussed (those listed above are the only ones I have encountered thus far)?

**Comment by MartinaSt** [comment]
> It's likely that we'll have the following licenses to deal with: CC0 1.0 https://creativecommons.org/publicdomain/zero/1.0/ CC BY 3.0 https://creativecommons.org/licenses/by/3.0/ CC BY 4.0 https://creativecommons.org/licenses/by/4.0/ CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/ CC BY-NC-SA 4.0 https://creativecommons.org/licenses/by-nc-sa/4.0/
> 
> @MartinaSt are there any others that folks have discussed (those listed above are the only ones I have encountered thus far)?

@durack1 Yes, these are the ones, I have seen so far. Should be sufficient.

**Comment by MartinaSt** [comment]
> So I think we're now coalescing on the format below - note the garbled email address, @MartinaSt does this work for you?
> 
> ```json
> "license":{
>       "rights_identifier":"CC BY 4.0",
>       "rights":"Data is made available under the Creative Commons Attribution 4.0 International License (CC by 4.0; https://creativecommons.org/licenses/by/4.0/)"
>       "rights_info":"https://creativecommons.org/licenses/by/4.0/",
>       "exceptions_contact":"@metoffice.gov.uk <-cmip6.ukesm1",
>       "source-specific_info":"https://ukesm.ac.uk/licensing-of-met-office-nerc-and-niwa-cmip6-data/",
>       "history":"2018-03-01: initially published under CC BY-SA 4.0; 2021-11-15: relaxed to CC BY 4.0"
> },
> ```

Looks good. I have two comments:

1. The `rights` became rather long. We have to check if the rendering in the ESGF CoG and the new Metagrid can deal with this long description. Otherwise, there should not be a problem or at least nothing, which could not be dealt with.
2. I will maintain these DOI landing pages on the long-term. As emphasized already, links and email addresses change over time. To reduce the curation effort on our end, I will only use and display the `source-specific_info` on the landing page. The modeling center has to provide and maintain the contact information on this page, anyway. 

Btw, who will curate the CMIP6 CV information in say 10 years from now and deal with requests about  broken links and no longer existing email addresses?

**Comment by durack1** [comment]
> 1. The `rights` became rather long. We have to check if the rendering in the ESGF CoG and the new Metagrid can deal with this long description. Otherwise, there should not be a problem or at least nothing, which could not be dealt with.

@MartinaSt good question, @sashakames is the current string length (~150 chars) ok, or is this a problem?

> 2. I will maintain these DOI landing pages on the long-term. As emphasized already, links and email addresses change over time. To reduce the curation effort on our end, I will only use and display the `source-specific_info` on the landing page. The modeling center has to provide and maintain the contact information on this page, anyway.

I don't believe we can depend on each modeling group to host their own page, many may be able to, but some won't have that functionality. Regarding the long-term (~10 years from now) curation, good question. We're 10+ years out from CMIP3 and many of the older links that were provided from modeling groups way back when don't exist anymore, in addition to folks who have since retired. I think we're ok to keep this up-to-date over the period from here until ~CMIP7, and then this repo will likely drop into a reference mode (much like CMIP3 and CMIP5 before it).

**Comment by durack1** [comment]
Note to self, make sure that `src/versionHistory.py`, and `src/CMIP6Lib.py` are updated to reflect new repo contents (also relevant for #1042)

**Comment by martinjuckes** [comment]
Hi @durack1, where does the garbled email address syntax used above, `@metoffice.gov.uk <-cmip6.ukesm1` come from? Is there a reference?

**Comment by durack1** [comment]
@martinjuckes that email address (non-garbled) was provided by the institution, with a unique address for the `UKESM1-0*` and `HadGEM3*` model variants. We'd expect a similar address for the other source_id entries, in most instances these are a personal email address, rather than these two examples

**Comment by sashakames** [comment]
Sorry for delayed response.  I don't anticipate an issue with character length with the citation strings; they probably should just wrap.  Are there already examples populated that we can check?

**Comment by durack1** [comment]
@matthew-mizielinski I have now managed to garble together a code that appears to be running (10k and still going strong), and am now using both `xarray` and `cdms2` to read all datasets, defaulting to `cdms2` if `xr` baulks. Previous scans have hit of order 7M files before baulking.

While it's working, there is a lot that could be heavily tweaked to make this less garble, and more python.

Assuming this runs without issues over the next ~6 days or so, it would be nice to get a review and cleanup of this code once the license data that it is sourcing is in hand

**Comment by durack1** [comment]
This is relevant for `GISS*` models https://data.giss.nasa.gov/modelE/cmip6/#datalicense

ping @gavinny

**Comment by durack1** [comment]
It occurred to me that once the data scour is complete, we will have an authoritative list of models that have contributed data to ESGF, and registered models that have not. While we engage with the modeling groups to finalize their license details, we can also consult those who have not contributed data, allowing us to resolve #1028 as part of the work

**Comment by taylor13** [comment]
Agree, but don't think this is particularly high priority.  Also, some models may have contributed to a remote data node, and we may not have replicated any of it.  So, our holdings don't definitively tell us if a modeling group has or has not contributed to CMIP6.

**Comment by MartinaSt** [comment]
@durack1 @matthew-mizielinski I just found the CV on licenses : https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_license.json 

Didn't we agree to make the license part of the CV for source_id?
There are deviations in the CV on licenses from what we discussed here: E.g. there is an "author" instead of an "exceptions_contact" in the CV on licenses., which is quite confusing because of the close relation of licenses to data citation.

**Comment by taylor13** [comment]
@MartinaSt I think that's what been there from the beginning (at least 2017).  There was a single license (with options), and the version metadata is for the CV, not the license.  (You'll notice a similar set of metadata at the end of each of the CVs.)  I don't think @durack1 has started to add model-specific license info. yet to the source CV (or were we going to add it to the institution CV?)

**Comment by durack1** [comment]
@MartinaSt @taylor13 that is correct, the current [CMIP6_license.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_license.json) file was created in February 2017 and is still used as the template for the CMIP6 CMOR inputs. As part of the work resolving this issue, this file will need some revising (the plan was to add the license variants that we are accepting, see [here](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/issue1050_durack1_AddCMIP6LicensePerSource_id/src/writeJson.py#L942-L959)).

I have managed to scour metadata from 22.4M files to date (this is taking a loooong time), which has uncovered the following registered files that have not published to ESGF. We know about `UofT-CCSM4`, but the others were not expected.

|count|source_id|MIPs|LLNL|ESGF|
|--|--|--|--|--|
|1|AWI-ESM-2-1-LR|CMIP PMIP|-|[none](https://esgf-node.llnl.gov/search/cmip6/?source_id=AWI-ESM-2-1-LR)|
|2|BESM-2-9|CMIP DCPP ScenarioMIP|-|[none](https://esgf-node.llnl.gov/search/cmip6/?source_id=BESM-2-9)|
|3|BNU-ESM-1-1|C4MIP CDRMIP CFMIP CMIP GMMIP GeoMIP OMIP RFMIP ScenarioMIP|-|[none](https://esgf-node.llnl.gov/search/cmip6/?source_id=BNU-ESM-1-1)|
|4|CAM-MPAS-HR|HighResMIP|-|[none](https://esgf-node.llnl.gov/search/cmip6/?source_id=CAM-MPAS-HR)|
|5|CAM-MPAS-LR|HighResMIP|-|[none](https://esgf-node.llnl.gov/search/cmip6/?source_id=CAM-MPAS-LR)|
|6|CESM1-WACCM-SC|PAMIP|lots|[96k](https://esgf-node.llnl.gov/search/cmip6/?source_id=CESM1-WACCM-SC)|
|7|CESM2-SE|CMIP HighResMIP|-|[none](https://esgf-node.llnl.gov/search/cmip6/?source_id=CESM2-SE)|
|8|CNRM-ESM2-1-HR|CMIP OMIP ScenarioMIP|-|[none](https://esgf-node.llnl.gov/search/cmip6/?source_id=CNRM-ESM2-1-HR)|
|9|CSIRO-Mk3L-1-3|CMIP PMIP|-|[none](https://esgf-node.llnl.gov/search/cmip6/?source_id=CSIRO-Mk3L-1-3)|
|10|EC-Earth3-GrIS|CMIP ISMIP6 PMIP|-|[none](https://esgf-node.llnl.gov/search/cmip6/?source_id=EC-Earth3-GrIS)|
|11|EC-Earth3-HR|CMIP DCPP HighResMIP|-|[none](https://esgf-node.llnl.gov/search/cmip6/?source_id=EC-Earth3-HR)|
|12|EMAC-2-53-Vol|CMIP VolMIP|-|[none](https://esgf-node.llnl.gov/search/cmip6/?source_id=EMAC-2-53-Vol)|
|13|EMAC-2-54-AerChem|AerChemMIP CMIP|-|[none](https://esgf-node.llnl.gov/search/cmip6/?source_id=EMAC-2-53-AerChem)|
|14|GFDL-ESM2M|FAFMIP|766 files|[404](https://esgf-node.llnl.gov/search/cmip6/?source_id=GFDL-ESM2M)|
|15|GFDL-GLOBAL-LBL|RFMIP|-|[none](https://esgf-node.llnl.gov/search/cmip6/?source_id=GFDL-GLOBAL-LBL)|
|16|IPSL-CM6A-ATM-ICO-HR|HighResMIP|-|[none](https://esgf-node.llnl.gov/search/cmip6/?source_id=IPSL-CM6A-ATM-ICO-HR)|
|17|IPSL-CM6A-ATM-ICO-LR|HighResMIP|-|[none](https://esgf-node.llnl.gov/search/cmip6/?source_id=IPSL-CM6A-ATM-ICO-LR)|
|18|IPSL-CM6A-ATM-ICO-MR|HighResMIP|-|[none](https://esgf-node.llnl.gov/search/cmip6/?source_id=IPSL-CM6A-ATM-ICO-MR)|
|19|IPSL-CM6A-ATM-ICO-VHR|HighResMIP|-|[none](https://esgf-node.llnl.gov/search/cmip6/?source_id=IPSL-CM6A-ATM-ICO-VHR)|
|20|IPSL-CM6A-MR025|CMIP|-|[none](https://esgf-node.llnl.gov/search/cmip6/?source_id=IPSL-CM6A-MR025)|
|21|IPSL-CM6A-MR1|CMIP|-|[none](https://esgf-node.llnl.gov/search/cmip6/?source_id=IPSL-CM6A-MR1)|
|22|NICAM16-9D-L78|CFMIP CMIP|-|[none](https://esgf-node.llnl.gov/search/cmip6/?source_id=NICAM16-9D-L78)|
|23|NorESM2-HH|CMIP HighResMIP|-|[none](https://esgf-node.llnl.gov/search/cmip6/?source_id=NorESM2-HH)|
|24|NorESM2-LME|C4MIP CMIP GeoMIP LUMIP OMIP|-|[none](https://esgf-node.llnl.gov/search/cmip6/?source_id=NorESM2-LME)|
|25|NorESM2-LMEC|AerChemMIP CMIP|-|[none](https://esgf-node.llnl.gov/search/cmip6/?source_id=NorESM2-LMEC)|
|26|NorESM2-MH|AerChemMIP CFMIP CMIP DAMIP OMIP RFMIP ScenarioMIP|-|[none](https://esgf-node.llnl.gov/search/cmip6/?source_id=NorESM2-MH)|
|0|PCMDI-test-1-0|test|test|test|
|27|UofT-CCSM4|CMIP PMIP|-|[none](https://esgf-node.llnl.gov/search/cmip6/?source_id=UofT-CCSM4)|
|28|VRESM-1-0|CMIP DAMIP HighResMIP PMIP ScenarioMIP|-|[none](https://esgf-node.llnl.gov/search/cmip6/?source_id=VRESM-1-0)|

**Comment by durack1** [comment]
Folks a PR #1066 is now in place, please take a peek. I presume that we will also need to update the default [CMIP6_license.json])https://github.com/WCRP-CMIP/CMIP6_CVs/blob/issue1050_durack1_AddCMIP6LicensePerSource_id/CMIP6_license.json#L3) to convert from the `CC BY-SA 4.0` to the `CC BY 4.0` relaxed recommendation?

**Comment by mauzey1** [comment]
@durack1 @taylor13 
CMOR currently adds a `license` attribute that is defined in the user input file.  How do we want to incorporate the new `license_info` attribute for the models in the CV file?  
```
    "license_info":{
        "exceptions_contact":"@awi.de <- tido.semmler",
        "history":"2018-12-18: initially published under CC BY-SA 4.0",
        "id":"CC BY-SA 4.0",
        "license":"Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0; https://creativecommons.org/licenses/by-sa/4.0/)",
        "source_specific_info":"",
        "url":"https://creativecommons.org/licenses/by-sa/4.0/"
    }
```
Do we take all of the info in the above JSON and put it in the NetCDF file?  Or do we just use the `license` attribute?

**Comment by durack1** [comment]
@mauzey1 thanks for the query.

I suggest we use something like:

```
instId = "AWI"
instIdStr = source_id[instId]
licId = source_id[instId]["license_info"]["id"]
licStr = license["license"]
licIdStr = license["license_options"]["license_id"]
licIdUrl = license["license_options"]["license_url"]
# replace institution
licStr = licStr.replace("<Your Institution; see CMIP6_institution_id.json>", instIdStr)
# replace license string
licStr = licStr.replace("<Creative Commons; select and insert a license_id; see below>", licIdStr)
# replace license id and URL
licStr = licStr.replace("<insert the matching license_url; see below>", "; ".join([licId, licIdUrl]))
```
If I got the syntax right, then:

"license":"CMIP6 model data produced by <Your Institution; see CMIP6_institution_id.json> is licensed under a <Creative Commons; select and insert a license_id; see below> License (<insert the matching license_url; see below>). Consult https://pcmdi.llnl.gov/CMIP6/TermsOfUse for terms of use governing CMIP6 output, including citation requirements and proper acknowledgment. Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in this file)[ and at <some URL maintained by modeling group>]. The data producers and data providers make no warranty, either express or implied, including, but not limited to, warranties of merchantability and fitness for a particular purpose. All liabilities arising from the supply of the information (including any liability arising in negligence) are excluded to the fullest extent permitted by law.",

would become:

"license": "CMIP6 model data produced by Alfred Wegener Institute, Helmholtz Centre for Polar and Marine Research, Am Handelshafen 12, 27570 Bremerhaven, Germany is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License (CC BY-SA 4.0; https://creativecommons.org/licenses/by-sa/4.0/). Consult https://pcmdi.llnl.gov/CMIP6/TermsOfUse for terms of use governing CMIP6 output, including citation requirements and proper acknowledgment. Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in this file). The data producers and data providers make no warranty....

**Comment by taylor13** [comment]
I agree that the outcome Paul envisions in the last paragraph of his comment immediately above is what we want.
