### ISSUE TITLE
source_id -- Register UKESM1-1-LL

### ISSUE THREAD

**Issue by matthew-mizielinski** [WCRP-CMIP/CMIP6_CVs#1060]
This is an updated version of UKESM1-0-LL, but with alterations to the SO2 handling within the model to give a better representation of the historical period. Note that the changes made do not affect the large scale components, so other than the source id and label there are very few changes here.

If there are no objections to this approach I'll put in a pull request in a day or so.

```
        "UKESM1-1-LL":{
            "activity_participation":[
                "CMIP",
                "ScenarioMIP",
            ],
            "cohort":[
                "Registered"
            ],
            "institution_id":[
                "MOHC",
                "NERC",
                "NIMS-KMA",
                "NIWA"
            ],
            "label":"UKESM1.1-LL",
            "label_extended":"UKESM1.1-N96ORCA1",
            "model_component":{
                "aerosol":{
                    "description":"UKCA-GLOMAP-mode",
                    "native_nominal_resolution":"250 km"
                },
                "atmos":{
                    "description":"MetUM-HadGEM3-GA7.1 (N96; 192 x 144 longitude/latitude; 85 levels; top level 85 km)",
                    "native_nominal_resolution":"250 km"
                },
                "atmosChem":{
                    "description":"UKCA-StratTrop",
                    "native_nominal_resolution":"250 km"
                },
                "land":{
                    "description":"JULES-ES-1.0",
                    "native_nominal_resolution":"250 km"
                },
                "landIce":{
                    "description":"none",
                    "native_nominal_resolution":"none"
                },
                "ocean":{
                    "description":"NEMO-HadGEM3-GO6.0 (eORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 360 x 330 longitude/latitude; 75 levels; top grid cell 0-1 m)",
                    "native_nominal_resolution":"100 km"
                },
                "ocnBgchem":{
                    "description":"MEDUSA2",
                    "native_nominal_resolution":"100 km"
                },
                "seaIce":{
                    "description":"CICE-HadGEM3-GSI8 (eORCA1 tripolar primarily 1 deg; 360 x 330 longitude/latitude)",
                    "native_nominal_resolution":"100 km"
                }
            },
            "release_year":"2021",
            "source_id":"UKESM1-1-LL"
        },
```

**Comment by taylor13** [comment]
Probably should be considered a "physics variant" on the earlier model; that's why we have that "p".  Perhaps users don't appreciate that though.  Judgement call.

**Comment by durack1** [comment]
@matthew-mizielinski following on the discussion this am (WIP call), I am more than happy with the above. I presume the standard `UKESM1*` licensing info will apply, see https://github.com/WCRP-CMIP/CMIP6_CVs/issues/1050#issuecomment-1044107023

**Comment by taylor13** [comment]
sounds good. Thanks for checking.  

I wonder if we should eliminate physics variant or in some other way better define when it is appropriate to define a variant vs. a new source.

**Comment by taylor13** [comment]
I think in CMIP5 another group used physics variant, but I'd have to check.  I think for CMIP7 we can easily come up with a clear rule for defining forcing variant.  Details to come.

**Comment by durack1** [comment]
@matthew-mizielinski apologies, I had not noticed that you were blocked to tag - upgraded to "Admin" now so that shouldn't be a future problem.

I have just tagged [6.2.56.11](https://github.com/WCRP-CMIP/CMIP6_CVs/releases/tag/6.2.56.11), but this was not date-stamped with the source PR (April 22 vs April 13 merge date)
