### ISSUE TITLE
source_id EC-Earth* change of license agreement

### ISSUE THREAD

**Issue by shutingdk** [WCRP-CMIP/CMIP6_CVs#1076]
The EC-Earth consortium has agreed to change the license agreement to CC BY 4.0 for all EC-Earth models in CMIP6, i.e., for source_id as EC-Earth3, EC-Earth3-AerChem, EC-Earth3-CC, EC-Earth3-GrIS, EC-Earth3-HR, EC-Earth3-LR, EC-Earth3-Veg, EC-earth3-Veg-LP, EC-Earth3P, EC-Earth3P-HR, EC-Earth3p-VHR.

Thanks!

**Comment by durack1** [comment]
Thanks @shutingdk.

It appears there is no published data on ESGF for the [`EC-Earth3-GrIS`](https://esgf-node.llnl.gov/search/cmip6/?source_id=EC-Earth3-GrIS) and [`EC-Earth3-HR`](https://esgf-node.llnl.gov/search/cmip6/?source_id=EC-Earth3-HR) models. If no data will be published, would you like these models to be deregistered as part of the license update process?

**Comment by shutingdk** [comment]
> 

Data from EC-Earth3-HR for DCPP are already on the way. We expect data from EC-Earth3-GrIS will start to publish later this year/early next year. So please keep them in the process, also with the updated license.

**Comment by shutingdk** [comment]
Thanks @durack1

**Comment by durack1** [comment]
@shutingdk those changes are now in place. Please take a peek at [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) and let me know of any issues that need fixing.

I note that as there is no data currently available (and version) for the `EC-Earth3-GrIS` or `EC-Earth3-HR`, the `history` attribute is left blank. Please either reopen this issue, or a new issue when these data are published, so we can round-out this entry to reflect the upcoming data

**Comment by shutingdk** [comment]
@durack1 Everything is fine with the published data. Thanks!

**Comment by durack1** [comment]
@shutingdk there was an additional query we had, for `EC-Earth3P-VHR` we have a personal `@bsc.es` exceptions contact email address listed. Would this be more appropriately updated to the `@ec-earth.org <- cmip6-data` of the other 10 `EC-Earth3*` configurations?

**Comment by durack1** [comment]
@shutingdk it appears that [`EC-Earth3-HR` data for the DCPP activity has been published](https://esgf-node.llnl.gov/search/cmip6/?source_id=EC-Earth3-HR), from metadata, this was published on 2022-06-27, however, your data version is 20201205.

Can you please confirm the publication plans for both `EC-Earth3-HR` and `EC-Earth3-GrIS`, it would be great to cleanup this license loose end ASAP

**Comment by durack1** [comment]
@shutingdk pinging you on this thread.

As noted above, [`EC-Earth3-HR1 data was published on 2022-06-27](https://esgf-node.llnl.gov/search/cmip6/?source_id=EC-Earth3-HR), but the data version is noted as `20201205`. Can you clarify if the `20221205` is correct?

It appears no [`EC-Earth3-GrIS` data has been published, yet](https://esgf-node.llnl.gov/search/cmip6/?source_id=EC-Earth3-GrIS)

**Comment by shutingdk** [comment]
> @shutingdk pinging you on this thread.
> 
> As noted above, [`EC-Earth3-HR1 data was published on 2022-06-27](https://esgf-node.llnl.gov/search/cmip6/?source_id=EC-Earth3-HR), but the data version is noted as `20201205`. Can you clarify if the `20221205` is correct?
> 

This is correct. The version reflects roughly when the data was produced (not cmorised), in this case in 2020. This is a choice taken, not an automatism. 


> It appears no [`EC-Earth3-GrIS` data has been published, yet](https://esgf-node.llnl.gov/search/cmip6/?source_id=EC-Earth3-GrIS)
Yes. The fconfiguration EC-Earth3-GrIS took much longer time than expected. We now is about to start the simulations. We expect to have the data available at the end of this year or early next year.

**Comment by durack1** [comment]
@shutingdk we have been trying to use the ESGF publication version e.g. `20220831` (e.g. today) as the timestamp identifying when data was published and made available.

For your `EC-Earth3` model the license history is identified as `2019-04-05: initially published under CC BY-SA 4.0; 2022-06-02: relaxed to CC BY 4.0` viewable [here](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html).

As you published the `EC-Earth3-HR` data to ESGF on 20220627, but the data has a version id of 20201205 it makes traceability a little more difficult. I'll use the publication date in the license history: `2022-06-27: initially published under CC BY 4.0` - does that make sense?

**Comment by shutingdk** [comment]
Yes. It sounds good. Thanks!

**Comment by durack1** [comment]
@shutingdk ok that change is now in place. Take a peek at [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) to check.

I'll leave this issue open until we have the `EC-Earth3-GrIS` data published and the license update, after which we're all done. When this data is generated, it would be great to attempt to keep the version and the ESGF publication date close as possible, which will simplify explanations

**Comment by durack1** [comment]
@shutingdk just circling around, it appears that [EC_Earth3-GrIS](https://esgf-node.llnl.gov/search/cmip6/?source_id=EC_Earth3-GrIS) data is still not published. Are you expecting this imminently, or should we deregister the model?

**Comment by shutingdk** [comment]
> @shutingdk just circling around, it appears that [EC_Earth3-GrIS](https://esgf-node.llnl.gov/search/cmip6/?source_id=EC_Earth3-GrIS) data is still not published. Are you expecting this imminently, or should we deregister the model?

Please keep it there. We expecte the data will be published at the end of this year or early next year.

**Comment by durack1** [comment]
Hi @shutingdk just circling around again, it appears that [EC_Earth3-GrIS](https://esgf-node.llnl.gov/search/cmip6/?source_id=EC_Earth3-GrIS) data is still not published. As we are in 2023, are you expecting this imminently, or should we deregister the model?

**Comment by durack1** [comment]
Hi @shutingdk just circling around on this query. Do we have any actionable updates, new data timeline, or would a deregistration be suitable?

**Comment by durack1** [comment]
@shutingdk just circling around on old/open issues. Has your team made any further decisions/progress on the [`EC-Earth3-GrIS`](https://esgf-node.llnl.gov/search/cmip6/?source_id=EC-Earth3-GrIS) prep and publication?

**Comment by durack1** [comment]
Closed with issue replaced by #1223
