### ISSUE TITLE
License - relaxing to CC BY 4.0 for IPSL data

### ISSUE THREAD

**Issue by glevava** [WCRP-CMIP/CMIP6_CVs#1078]
Hi @durack1 

In agreement with IPSL modeling center, we are fine relaxing **ALL** IPSL data license to CC BY 4.0. Please apply this change to all IPSL models (i.e., all source_id with prefix "IPSL-*" + "4AOP-v1-5").

I precise that the data won't be republished with the new license in the netCDF attributes (too much piece of work) so we really appreciate your initiative to gather this information at the CMIP6 level.

Best,

Guillaume

**Comment by durack1** [comment]
@glevava thanks, and no problem. Yes, we figured that the only logical path forward that made sense was to manage all this information centrally, thereby (hopefully) reducing the workload (and confusion) across the network!

Two last questions,  1) is the email address `@listes.ipsl.fr <- ipsl-cmip6` suitable?, and 2) we have 7 models that are registered, but haven't published data: `IPSL-CM6A-ATM-ICO-HR`, `IPSL-CM6A-ATM-ICO-LR`, `IPSL-CM6A-ATM-ICO-MR`, `IPSL-CM6A-ATM-ICO-VHR`, `IPSL-CM6A-ATM-LR-REPROBUS`, `IPSL-CM6A-MR025`, `IPSL-CM6A-MR1`. Should these be deregistered, or are we expecting data to be published imminently?

@acaubel ping!

**Comment by glevava** [comment]
Hi @durack1 yes the addresse : ipsl-cmip6@listes.ipsl.fr is suitable to all IPSL data (including all source IDs).

And yes, we will publish soon data for the 7 registered models you point.

**Comment by durack1** [comment]
@glevava those changes are now in place. Please take a peek at [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) and let me know of any issues that need fixing.

I note that as there is no data currently available (and version) for the `IPSL-CM6A-ATM-ICO-HR`, `IPSL-CM6A-ATM-ICO-LR`, `IPSL-CM6A-ATM-ICO-MR`, `IPSL-CM6A-ATM-ICO-VHR`, `IPSL-CM6A-ATM-LR-REPROBUS`, `IPSL-CM6A-MR025`, `IPSL-CM6A-MR1` models, the `history` attribute is left blank. Please either reopen this issue, or a new issue when these data are published, so we can round-out this entry to reflect the upcoming data

**Comment by durack1** [comment]
@glevava @acaubel just so the update for the anticipated publication of data for `IPSL-CM6A-ATM-ICO-HR`, `IPSL-CM6A-ATM-ICO-LR`, `IPSL-CM6A-ATM-ICO-MR`, `IPSL-CM6A-ATM-ICO-VHR`, `IPSL-CM6A-ATM-LR-REPROBUS`, `IPSL-CM6A-MR025`, `IPSL-CM6A-MR1` models doesn't get lost, I am reopening this issue and assigning a tag noting this

**Comment by durack1** [comment]
@glevava @acaubel just circling around to see if any of the data for the new registrations `IPSL-CM6A-ATM-ICO-HR`, `IPSL-CM6A-ATM-ICO-LR`, `IPSL-CM6A-ATM-ICO-MR`, `IPSL-CM6A-ATM-ICO-VHR`, `IPSL-CM6A-ATM-LR-REPROBUS`, `IPSL-CM6A-MR025`, `IPSL-CM6A-MR1` are live yet?

**Comment by glevava** [comment]
Hi @durack1 I’m generating the mapfile file of the corresponding dataset. I plan to publish them beforz my summer holidays !

**Comment by durack1** [comment]
@glevava excellent, please ping this thread when data is live so I can finalize the license info and close this issue out.

Out of curiosity, did you update the metadata templates, so these latest generation outputs follow the CC BY 4.0 (vs CC BY-SA 4.0) license?

**Comment by durack1** [comment]
I've just checked and found that:
[`IPSL-CM6A-ATM-ICO-MR` is published with version 20220720](https://esgf-node.llnl.gov/search/cmip6/?source_id=IPSL-CM6A-ATM-ICO-MR)
[`IPSL-CM6A-ATM-ICO-HR` is published with version 20220721](https://esgf-node.llnl.gov/search/cmip6/?source_id=IPSL-CM6A-ATM-ICO-HR)
[`IPSL-CM6A-ATM-ICO-LR` is published with version 20220721](https://esgf-node.llnl.gov/search/cmip6/?source_id=IPSL-CM6A-ATM-ICO-LR)
[`IPSL-CM6A-ATM-ICO-VHR` is published with version 20220721](https://esgf-node.llnl.gov/search/cmip6/?source_id=IPSL-CM6A-ATM-ICO-VHR)

The following models remain to be published: [`IPSL-CM6A-ATM-LR-REPROBUS`](https://esgf-node.llnl.gov/search/cmip6/?source_id=IPSL-CM6A-ATM-LR-REPROBUS), [`IPSL-CM6A-MR025`](https://esgf-node.llnl.gov/search/cmip6/?source_id=IPSL-CM6A-MR025), and [`IPSL-CM6A-MR1`](https://esgf-node.llnl.gov/search/cmip6/?source_id=IPSL-CM6A-MR1)

@glevava is this correct?

**Comment by glevava** [comment]
Hi @durack1 that's right.
But I don't know when the three remaining IPSL models will be published. Not sure the runs have been done yet.

**Comment by durack1** [comment]
@glevava, no problem, the change is now in place; please take a peek at [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) and let me know of any issues.

I'll leave this issue open, awaiting the publication of the last data from `IPSL-CM6A-ATM-LR-REPROBUS`, `IPSL-CM6A-MR025`, `IPSL-CM6A-MR1`. Please ping this thread when that data is made available, or alternatively if a decision is made to not publish these datasets

**Comment by durack1** [comment]
@glevava just circling around on this, do we have any further progress on these 3 remaining model configurations? It doesn't seem to be the case if [this](https://esgf-node.llnl.gov/search/cmip6/?source_id=IPSL-CM6A-ATM-LR-REPROBUS) is anything to go by

**Comment by glevava** [comment]
@durack1 I don't know yet about IPSL-CM6A-LR-REPROBUS. For MR025 and MR1, datasets are ready to publish I'm waiting for green light of our modeling group.

**Comment by durack1** [comment]
@glevava just circling around, it seems that [`IPSL-CM6A-MR025`](https://esgf-node.llnl.gov/search/cmip6/?source_id=IPSL-CM6A-MR025), and [`IPSL-CM6A-MR1`](https://esgf-node.llnl.gov/search/cmip6/?source_id=IPSL-CM6A-MR1) are not yet published, or the `*REPROBUS` variant - are these still expected, or should be cleanup the registrations?

**Comment by glevava** [comment]
hi @durack1. I'm still waiting for news from my modeling group to publish dataset from MR025 and MR1 which have been produced now.
Models with *REPROBUS variant did not run yet.

**Comment by durack1** [comment]
@glevava just circling around again on this. It seems there is no data for [`IPSL-CM6A-MR025`](https://esgf-node.llnl.gov/search/cmip6/?source_id=IPSL-CM6A-MR025), or [`IPSL-CM6A-MR1`](https://esgf-node.llnl.gov/search/cmip6/?source_id=IPSL-CM6A-MR1), ditto for the [`IPSL-CM6A-ATM-LR-REPROBUS`](https://esgf-node.llnl.gov/search/cmip6/?source_id=IPSL-CM6A-ATM-LR-REPROBUS).

Should we continue to wait, or should these entries be unpublished?

**Comment by glevava** [comment]
Hi @durack1 , MR1 is in my hands, will be publish very soon. The LR-REPROBUS is under quality checking and aim to be published in the coming months.
It's more unlcear for MR025. I asked to my colleague to confirm.
For the time being I would say we should continue to wait. Maybe the MR025 will be unpublished in the near future but the other two IPSL models will have datasets published on the ESGF soon for sure.

**Comment by durack1** [comment]
@glevava great news! Please ping this thread when the data are live (making sure that the ESGF version tag is representative of a recent publication, e.g. `v20230222`

**Comment by durack1** [comment]
@glevava just the usual two-monthly query on the status of the above, any news to share?

**Comment by durack1** [comment]
@glevava just circling around on this long standing open issue, any progress or updates to report?

**Comment by glevava** [comment]
@durack1 I still need to find the time to publish MR1. Runs are under QC, I will finalize their publication this summer when project activity goes down. MR025 won't be finally published.

**Comment by durack1** [comment]
@glevava great, so we can expect MR1 in a ~month or so. Was I reading the above correctly that MR025 won't be published and should be deregistered? Or rather that the timeline for this data submission still needs to be set (but is still expected)?

**Comment by glevava** [comment]
MR025 can be deregistered.

**Comment by durack1** [comment]
@glevava great, `IPSL-CM6A-MR025` is now deregistered. Please ping me when the `*MR1` data is live, and I'll update and close out this issue - or are we also expecting the `*REPROBUS` data to land sometime soon?

**Comment by glevava** [comment]
ok thanks ! I will publish the MR1 during the summer (I have often more time during holidays of everybody :)
I will ask to my colleague regarding the REPROBUS runs and keep you informed in the same time.

**Comment by durack1** [comment]
@glevava I hope summer has been bubbling along nicely. Just circling around on [`IPSL-CM6A-MR1`](https://esgf-node.llnl.gov/search/cmip6/?source_id=IPSL-CM6A-MR1) status, any updates?

**Comment by glevava** [comment]
I'm on it. Need few weeks more to publish data.

**Comment by durack1** [comment]
@glevava just circling around on old issues, any progress/updates we need to address?

**Comment by glevava** [comment]
Always on my todo list ;)

**Comment by durack1** [comment]
@glevava just circling around on this old chestnut -  looks like [`IPSL-CM6A-MR1`](https://aims2.llnl.gov/search/cmip6/?source_id=IPSL-CM6A-MR1) was in fact published a month ago `_timestamp: 2024-03-26T04:18:04.696Z`, can you confirm?

**Comment by glevava** [comment]
Yes I confirm !

**Comment by durack1** [comment]
@glevava finally, it's done and closed out - FYI, the only change has been to the *MR1 entry in [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html). Let me know if other tweaks are required.

As an FYI `IPSL-CM6A-ATM-LR-REPROBUS` is still registered, let me know if this should be unregistered from the CVs?

**Comment by glevava** [comment]
No, we will publish runs for this GCM but I can say when exactly, some simulations are still running.

**Comment by durack1** [comment]
@glevava no problem. When this data is ready to be published, and you remember, ping/reopen this thread and we can update the "Registered" -> "Published" status, with the date to complete the license table
