### ISSUE TITLE
Licence rules for NorESM2-LM and NorESM2_MM

### ISSUE THREAD

**Issue by oyvindseland** [WCRP-CMIP/CMIP6_CVs#1079]
I can confirm that we can relax the licence for use of NorESM2 data to CC BY-SA 4.0

**Comment by durack1** [comment]
Thanks @oyvindseland!

Did you want the `CC BY 4.0` relaxation to apply to [all `NCC` published datasets](https://esgf-node.llnl.gov/search/cmip6/?institution_id=NCC), so for source_id's: `NorCPM1`, 
`NorESM1-F`, `NorESM2-LM`, and `NorESM2-MM`?

In addition, should we deregister `NorESM2-HH`, `NorESM2-LME`, `NorESM2-LMEC` and `NorESM2-MH` as we have no data published for these 4 models.

@IngoBethke ping

**Comment by durack1** [comment]
@oyvindseland @ingobethke just circling around on this open issue - do you have some answers for my queries https://github.com/WCRP-CMIP/CMIP6_CVs/issues/1079#issuecomment-1146374945

**Comment by oyvindseland** [comment]
Hi I think you can likely delete LME and LMEC but will for confirmation @tjiputra
HH also likely. @monsieuralok
MH we will probably keep for some new experiments

**Comment by monsieuralok** [comment]
Hi, For HH, there is not any recent plan. But, for MH there should be data already on ESGF or probably, will be published soon.

**Comment by durack1** [comment]
@oyvindseland @tjiputra @monsieuralok thanks for the replies.

It appears we have [no data published on ESGF for `NorESM2-HH`](https://esgf-node.llnl.gov/search/cmip6/?source_id=NorESM2-HH), but if we are expecting this imminently will leave this registered in anticipation - and we can update the license info once this data is made available - ***please ping this thread when this data is published so we can update the license information (the license information requires the ESGF version identifier to be completed)***.

I will deregister `NorESM2-LME`, `NorESM2-LMEC` and `NorESM2-MH` as per the notes above.

**Comment by durack1** [comment]
@oyvindseland @tjiputra @monsieuralok thanks for the update, all changes noted above are now in place. Please review [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) and let me know of any tweaks required.

I will leave this issue open, awaiting the publication of `NorESM2-HH` data, after which we can update that final license and close the issue

**Comment by oyvindseland** [comment]
IMPORTANT: Note it is MH that should stay as reported by Alok @monsieuralok

**Comment by durack1** [comment]
@oyvindseland whoops, not sure how that happened, I'll revert and fix later today

**Comment by durack1** [comment]
@oyvindseland thanks for catching that error. Please take a peek at [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) and let me know if anything else outstanding needs attention.

We still don't have [`NorESM2-MH` data available on the ESGF CMIP6 project](https://esgf-node.llnl.gov/search/cmip6/?source_id=NorESM2-MH), so will leave this issue open awaiting data publication so we can update this one last license entry and close out this issue

**Comment by durack1** [comment]
@oyvindseland just circling around, it doesn't appear that the [`NorESM2-MH` data is published yet](https://esgf-node.llnl.gov/search/cmip6/?source_id=NorESM2-MH). Are you expecting publication imminently?

**Comment by oyvindseland** [comment]
Probably not at least not on ESGF , but I am tagging two people who should be better positioned to answer @monsieuralok @matsbn

**Comment by durack1** [comment]
@oyvindseland @monsieuralok @matsbn just circling around, are you planning on publishing [`NorESM2-MH`](https://esgf-node.llnl.gov/search/cmip6/?source_id=NorESM2-MH) data, or should this model be deregistered?

**Comment by durack1** [comment]
@oyvindseland @monsieuralok @matsbn just circling around on this very old query. I presume that the [`NorESM2-MH`](https://esgf-node.llnl.gov/search/cmip6/?source_id=NorESM2-MH) data is unlikely to be published, so should I just deregister this model and close this issue?

**Comment by oyvindseland** [comment]
Hi

The people working on the ocean model have agreed that it should stay for now. It is being worked upon and they expect to use ESGF for data sharing in their projects even if they do not expect to redo the major CMIP6 experiments.

Øyvind

**Comment by durack1** [comment]
Hi @oyvindseland it appears that the [`NorESM2-MH`](https://esgf-node.llnl.gov/search/cmip6/?source_id=NorESM2-MH) data is still unpublished. Has there been a change to circumstances that would recommend an unpublication?

**Comment by oyvindseland** [comment]
Will fiorward the question to the people working on the model version. It is used for a number of simulations but I will ask on the time-line for publication of CMIP style experiments

**Comment by durack1** [comment]
@great @oyvindseland looking forward to the update

**Comment by oyvindseland** [comment]
I have discussed it with the main user of the model version and he does not expect result on ESG soon. 
--> Conclusion: Unpublish (for now)

**Comment by durack1** [comment]
@oyvindseland thanks for following that up, I get that deregistration of `NorESM2-MH` completed later today

**Comment by durack1** [comment]
@oyvindseland that deregistration is now complete. If your colleague gets those sims completed and has data to publish, we can reopen this issue
