### ISSUE TITLE
GFDL CMIP6 licensing update from CC BY-SA 4.0 to CC BY 4.0

### ISSUE THREAD

**Issue by johndunne13** [WCRP-CMIP/CMIP6_CVs#1083]
Hello,

In accordance with Paul Durack's email of June 2, 2022 entitled "CMIP6 data licensing update" recommending all existing CC BY-SA 4.0 licenses be relaxed to CC BY 4.0, GFDL agrees to update this licensing to CC BY 4.0 for all its contributions, including: GFDL-ESM4, GFDL-CM4, GFDL-AM4, GFDL-ESM2M, GFDL-CM4C192, GFDL-GLOBAL-LBL, GFDL-GRTCODE, GFDL-OM4p5B, and GFDL-RFM-DISORTN. Please let me know if any additional action is necessary on GFDL's part.

Thanks, John Dunne
On behalf of NOAA/OAR/GFDL

**Comment by durack1** [comment]
@johndunne13 thanks, will get this change implemented.

I note that we have no data published on ESGF for the [`GFDL-GLOBAL-LBL` model](https://esgf-node.llnl.gov/search/cmip6/?source_id=GFDL-GLOBAL-LBL), is that an oversight, are we expecting data imminently, or should we deregister this entry?

**Comment by durack1** [comment]
@johndunne13 thanks. I can get these licenses updated, and await an update from David on `GFDL-GLOBAL-LBL`, after which we can make any final tweaks and close out this issue

**Comment by durack1** [comment]
@johndunne13 thanks for the update, all changes noted above are now in place. Please review [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) and let me know of any tweaks required.

I will leave this issue open, awaiting the update from David RE: `GFDL-GLOBAL-LBL`, after which we can update that final license (or deregister) and close the issue

**Comment by cmip6** [comment]
Hi David, first up congrats on welcoming the new family member! I do hope sleep is abundant in the Paynter household.

I am just circling around on the question regarding data submission of GFDL-GLOBAL-LBL. Did you have a plan to contribute data to RFMIP?

Cheers,

P

From: "Paul J. Durack" ***@***.***>
Reply-To: WCRP-CMIP/CMIP6_CVs ***@***.***>
Date: Wednesday, June 8, 2022 at 12:36 PM
To: WCRP-CMIP/CMIP6_CVs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [WCRP-CMIP/CMIP6_CVs] GFDL CMIP6 licensing update from CC BY-SA 4.0 to CC BY 4.0 (Issue #1083)


@johndunne13<https://urldefense.us/v3/__https:/github.com/johndunne13__;!!G2kpM7uM-TzIFchu!mU3QBcFjDX3ypbnY7ayQth2awkllEDvto5QhFswGrulqik_yjwTMDB_cXzpTdASSaJI$> thanks for the update, all changes noted above are now in place. Please review CMIP6_source_id_licenses.html<https://urldefense.us/v3/__https:/wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html__;!!G2kpM7uM-TzIFchu!mU3QBcFjDX3ypbnY7ayQth2awkllEDvto5QhFswGrulqik_yjwTMDB_cXzpTmAk2QiU$> and let me know of any tweaks required.

I will leave this issue open, awaiting the update from David RE: GFDL-GLOBAL-LBL, after which we can update that final license (or deregister) and close the issue

**Comment by cmip6** [comment]
Hi David, just circling around on this query. Did you have plans to publish GFDL-GLOBAL-LBL output on ESGF, or should we rather deregister this source_id from the database?

Cheers,

P

From: "Durack, Paul J." ***@***.***>
Date: Friday, July 1, 2022 at 1:30 PM
To: ***@***.***" ***@***.***>
Cc: WCRP-CMIP/CMIP6_CVs ***@***.***>, WCRP-CMIP/CMIP6_CVs ***@***.***>, ***@***.***" ***@***.***>
Subject: Re: [WCRP-CMIP/CMIP6_CVs] GFDL CMIP6 licensing update from CC BY-SA 4.0 to CC BY 4.0 (Issue #1083)

Hi David, first up congrats on welcoming the new family member! I do hope sleep is abundant in the Paynter household.

I am just circling around on the question regarding data submission of GFDL-GLOBAL-LBL. Did you have a plan to contribute data to RFMIP?

Cheers,

P

From: "Paul J. Durack" ***@***.***>
Reply-To: WCRP-CMIP/CMIP6_CVs ***@***.***>
Date: Wednesday, June 8, 2022 at 12:36 PM
To: WCRP-CMIP/CMIP6_CVs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [WCRP-CMIP/CMIP6_CVs] GFDL CMIP6 licensing update from CC BY-SA 4.0 to CC BY 4.0 (Issue #1083)


@johndunne13<https://urldefense.us/v3/__https:/github.com/johndunne13__;!!G2kpM7uM-TzIFchu!mU3QBcFjDX3ypbnY7ayQth2awkllEDvto5QhFswGrulqik_yjwTMDB_cXzpTdASSaJI$> thanks for the update, all changes noted above are now in place. Please review CMIP6_source_id_licenses.html<https://urldefense.us/v3/__https:/wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html__;!!G2kpM7uM-TzIFchu!mU3QBcFjDX3ypbnY7ayQth2awkllEDvto5QhFswGrulqik_yjwTMDB_cXzpTmAk2QiU$> and let me know of any tweaks required.

I will leave this issue open, awaiting the update from David RE: GFDL-GLOBAL-LBL, after which we can update that final license (or deregister) and close the issue

**Comment by cmip6** [comment]
Hi Paul,
So sorry for the slow reply, your request got a bit lost in my backlog of
tasks to catch up on. I think the source_id of GFDL-GLOBAL-LBL was created
in error, as we used GFDL-RFM-DISORT source_id for our LBL
calculations.  Thanks
for the congratulations on our new family member.  Unfortunately, sleep is
a commodity we are still in short supply of!
Best
David

**Comment by cmip6** [comment]
Thanks for the update @David! If this is the case, I will deregister the erroneous registration of `GFDL-GLOBAL-LBL`.

And I do wish you well RE: sleep, we’re still running a decent debt with our not yet 2 yr old – I wish you good luck, and long, sweet dreams

From: David Paynter - NOAA Federal ***@***.***>
Date: Wednesday, July 27, 2022 at 5:44 PM
To: "Durack, Paul J." ***@***.***>
Cc: WCRP-CMIP/CMIP6_CVs ***@***.***>, ***@***.***" ***@***.***>
Subject: Re: [WCRP-CMIP/CMIP6_CVs] GFDL CMIP6 licensing update from CC BY-SA 4.0 to CC BY 4.0 (Issue #1083)

Hi Paul,
So sorry for the slow reply, your request got a bit lost in my backlog of tasks to catch up on. I think the source_id of GFDL-GLOBAL-LBL was created in error, as we used GFDL-RFM-DISORT source_id for our LBL calculations.  Thanks for the congratulations on our new family member.  Unfortunately, sleep is a commodity we are still in short supply of!
Best
David

On Wed, Jul 27, 2022 at 6:43 PM Durack, Paul J. ***@***.******@***.***>> wrote:
Hi David, just circling around on this query. Did you have plans to publish GFDL-GLOBAL-LBL output on ESGF, or should we rather deregister this source_id from the database?

Cheers,

P

From: "Durack, Paul J." ***@***.******@***.***>>
Date: Friday, July 1, 2022 at 1:30 PM
To: ***@***.******@***.***>" ***@***.******@***.***>>
Cc: WCRP-CMIP/CMIP6_CVs ***@***.******@***.***>>, WCRP-CMIP/CMIP6_CVs ***@***.******@***.***>>, ***@***.******@***.***>" ***@***.******@***.***>>
Subject: Re: [WCRP-CMIP/CMIP6_CVs] GFDL CMIP6 licensing update from CC BY-SA 4.0 to CC BY 4.0 (Issue #1083)

Hi David, first up congrats on welcoming the new family member! I do hope sleep is abundant in the Paynter household.

I am just circling around on the question regarding data submission of GFDL-GLOBAL-LBL. Did you have a plan to contribute data to RFMIP?

Cheers,

P

From: "Paul J. Durack" ***@***.******@***.***>>
Reply-To: WCRP-CMIP/CMIP6_CVs ***@***.******@***.***>>
Date: Wednesday, June 8, 2022 at 12:36 PM
To: WCRP-CMIP/CMIP6_CVs ***@***.******@***.***>>
Cc: Subscribed ***@***.******@***.***>>
Subject: Re: [WCRP-CMIP/CMIP6_CVs] GFDL CMIP6 licensing update from CC BY-SA 4.0 to CC BY 4.0 (Issue #1083)


@johndunne13<https://urldefense.us/v3/__https:/github.com/johndunne13__;!!G2kpM7uM-TzIFchu!mU3QBcFjDX3ypbnY7ayQth2awkllEDvto5QhFswGrulqik_yjwTMDB_cXzpTdASSaJI$> thanks for the update, all changes noted above are now in place. Please review CMIP6_source_id_licenses.html<https://urldefense.us/v3/__https:/wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html__;!!G2kpM7uM-TzIFchu!mU3QBcFjDX3ypbnY7ayQth2awkllEDvto5QhFswGrulqik_yjwTMDB_cXzpTmAk2QiU$> and let me know of any tweaks required.

I will leave this issue open, awaiting the update from David RE: GFDL-GLOBAL-LBL, after which we can update that final license (or deregister) and close the issue
