### ISSUE TITLE
License change for TaiESM1, HiRAM-SIT-HR, HiRAM-SIT-LR, TaiESM1-TIMCOM, TaiESM1-TIMCOM2

### ISSUE THREAD

**Issue by lamaliang** [WCRP-CMIP/CMIP6_CVs#1088]
Hello 

Please change the license to CC BA 4.0 for AS-RCEC and NTU models. Including TaiESM1, HiRAM-SIT-LR, HiRAM-SIT-HR, TaiESM1-TIMCOM and TaiESM1-TIMCOM2.

Thanks you so much.

----------------------------------------------------
Hsin-Chien Liang
Research Center of Environmental Changes, Academia Sinica.

**Comment by matthew-mizielinski** [comment]
Hi @lamaliang 

I've made the update to the license for the 5 models listed here, please have a look at [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) and let us know if there are any issues.

**Comment by durack1** [comment]
@lamaliang thanks for this! We had one last query, the 3`AS-RCEC` configurations all list a personal `@gate.sinica.edu.tw` exceptions contact email address listed. Is there an institutional mailing list that would be more suitable than numerous personal emails?

For the 2 `TaiESM1-TIMCOM*` `NTU` configurations, we have a personal `@ntu.edu.tw` exceptions contact email address listed. Similarly, we wonder whether there is a better address we should update these entries with?

**Comment by lamaliang** [comment]
Hi @durack1 
Sorry, due to we just a laboratory in our institution, so it is not suitable for using our institution mailing address.  Please using the same exception contact for TaiESM1 and HiRAM-SIT-LR/HR. Thank you.

Therefore, TaiESM1-TIMCOM* is the same. Using personal mail address is better than institutional mailing.

Thank you so much.

**Comment by durack1** [comment]
@lamaliang no problem, understood.

Before closing this out, I might confirm the existing addresses. You have both cytu and leelupin @gate.. for the `AS-RCEC` HiRAM-SIT* and TaiESM1 registrations. And for the `NTU` registrations, tsengyh @ntu is the address for both `TaiESM1-TIMCOM*` source_id entries. Did any of these need an update?

**Comment by lamaliang** [comment]
Hello @durack1  

No, we didn't update any information. Thank you so much.
