### ISSUE TITLE
ACCESS CMIP6 licensing update from CC BY-SA 4.0 to CC BY 4.0

### ISSUE THREAD

**Issue by sjmarsland** [WCRP-CMIP/CMIP6_CVs#1089]
Hi Paul,

Following your email of June 2, 2022 titled "CMIP6 data licensing update" recommending all existing CC BY-SA 4.0 licenses be relaxed to CC BY 4.0, please update licensing to CC BY 4.0 for ACCESS contributions ACCESS-CM2, ACCESS-ESM1-5, ACCESS-OM2, and ACCESS-OM2-025

Thanks, Simon on behalf of ACCESS community.

**Comment by matthew-mizielinski** [comment]
Hi @sjmarsland 

I've made the update to the license for the 4 models listed here, please have a look at [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) and let us know if there are any issues.

**Comment by durack1** [comment]
@sjmarsland thanks for this! One last query that we had, for all 4 `ACCESS*` configurations, we had the `@csiro.au <- access_csiro` exceptions contact email address listed. The `CSIRO-COSIMA` contributions listed no contact info, so just wanted to double check that we're pointing out/recording the correct details

**Comment by sjmarsland** [comment]
@durack1 Thanks Paul. Happy to have all ACCESS models with the same email. I see you have already put that as a place holder CSIRO-COSIMA models in CMIP6_source_id_licenses.html<https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html>  so good to close this one out.

On 11 Jun 2022, at 9:39 am, Paul J. Durack ***@***.******@***.***>> wrote:



@sjmarsland<https://github.com/sjmarsland> thanks for this! One last query that we had, for all 4 ACCESS* configurations, we had the @csiro.au <- access_csiro exceptions contact email address listed. The CSIRO-COSIMA contributions listed no contact info, so just wanted to double check that we're pointing out/recording the correct details

**Comment by durack1** [comment]
@sjmarsland no problem, all looks good to me!
