### ISSUE TITLE
License relaxation for MIROC series (but not for NICAM series for the moment...)

### ISSUE THREAD

**Issue by kawamiyamichi0** [WCRP-CMIP/CMIP6_CVs#1092]
I can confirm that the license can be relaxed from CC BY-SA to CC BY 4.0 for MIROC-ES2H, MIROC-ES2H-NB, MIROC-ES2L, and MIROC6. For the NICAM series of models (I.e., NICAM16-7S, NICAM16-8S, NICAM16-9D-L78, and NICAM16-9S) we need more time for discussion so please wait for a while. I will report the outcome for the NICAM models as soon as we reach the conclusion.

**Comment by durack1** [comment]
@kawamiyamichi0 thanks for the update. Sure we can amend the `MIROC*` models first, and await an update for the `NICAM-*` entries. While we are updating details, these are all registered with a personal email address, not an institutional mailing list (e.g. @iis.u-tokyo.ac.jp <- onuma). Did you want to update this address while we are amending details?

Also, there is [no data published in the CMIP6 ESGF project for the `NICAM16-9D-L78`](https://esgf-node.llnl.gov/search/cmip6/?source_id=NICAM16-9D-L78) configuration. Should we deregister this source_id, or should we be expecting data publication imminently?

**Comment by kawamiyamichi0** [comment]
Dear Paul,

Thank you for your response. You can deregister the source_id
for NICAM16-9D-L78. As for the mailing list issue, please keep the
addresses as they are for the moment. Right now we don't have a dedicated
mailing list, but will discuss it and may come back to you later.

Regards,

Michio

2022年6月13日(月) 13:46 Paul J. Durack ***@***.***>:

**Comment by durack1** [comment]
@kawamiyamichi0 thanks for the update. Those `MIROC*` changes are now in place, and `NICAM16-9D-L78` is now deregistered. Please review the updated contents at [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) and let us know of any further corrections required.

We'll keep this issue open awaiting an updated on the 3 `NICAM*` configurations. Also, please let us know if an amendment to the contact email address is required.
