### ISSUE TITLE
License for NICAM data can also be relaxed

### ISSUE THREAD

**Issue by kawamiyamichi0** [WCRP-CMIP/CMIP6_CVs#1094]
I confirm that the license can be relaxed from CC BY-SA to CC BY 4.0 for the NICAM series of models (I.e., NICAM16-7S, NICAM16-8S, and NICAM16-9S), on top of the MIROC data I reported earlier.

**Comment by durack1** [comment]
@kawamiyamichi0 great, will process this and close #1092 tomorrow. Did you want to update the contact email for these models? Currently all are pointing to `@iis.u-tokyo.ac.jp <- onuma`. For reference [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) displays the license info per model

**Comment by durack1** [comment]
@kawamiyamichi0 thanks for the update, all changes noted above are now in place. Please review [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) and let me know of any tweaks required, or if the email address also requires an update

**Comment by kawamiyamichi0** [comment]
Dear Paul,

Please change the contact points for all the MIROC and NICAM entries from "@
iis.u-tokyo.ac.jp <- onuma" to ***@***.*** <- miroc-cmip6"

Regards,

Michio

2022年6月16日(木) 8:41 Paul J. Durack ***@***.***>:

**Comment by durack1** [comment]
@kawamiyamichi0 no problem, just to confirm the updated address is `miroc-cmip6 AT iis.u-  tokyo  .ac.jp`?

**Comment by kawamiyamichi0** [comment]
No.  "miroc-cmip6 AT jamstec. go. jp" is correct. Sorry for the confusion.
This happens because development of NICAM and MIROC is such a collaborative
effort.

Regards,

Michio

2022年6月21日(火) 1:17 Paul J. Durack ***@***.***>:
