### ISSUE TITLE
License and contact -- Requesting change for E3SM model

### ISSUE THREAD

**Issue by mccoy20** [WCRP-CMIP/CMIP6_CVs#1095]
Please change the license for all E3SM models from CC BY_SA 4.0 to CC BY 4.0. At the same time we would like to update the contact info for all the E3SM models from bader2@llnl.gov to a generic E3SM Data Support email e3sm-data-support@llnl.gov. Thanks!

**Comment by durack1** [comment]
@mccoy20 thanks for the update, all changes noted above are now in place. Please review [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) and let me know of any further tweaks are required
