### ISSUE TITLE
Delete note on the citation service for new issues

### ISSUE THREAD

**Issue by MartinaSt** [WCRP-CMIP/CMIP6_CVs#1098]
@durack1 @matthew-mizielinski : The note on the citation service is outdated and can be deleted. The citation service including the citation search are in sync with the source_id content.

`** Note: registered content can be updated after 31st January 2021, but these changes may not be reflected by the CMIP6 citation service, see http://bit.ly/CMIP6_Citation_Search **`

**Comment by durack1** [comment]
Thanks @MartinaSt, did you want any text in the template? If yes, you can submit a PR by editing https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by MartinaSt** [comment]
@durack1 Thanks for asking. I don't think we need to mention the citation service in these instructions how to open an issue to change the content of the CV. So, please just delete the above note.
