### ISSUE TITLE
MPI-M CMIP6 licensing update from CC BY-SA 4.0 to CC BY 4.0

### ISSUE THREAD

**Issue by johann-git** [WCRP-CMIP/CMIP6_CVs#1099]
In accordance with Paul Durack's email of June 2, 2022 entitled "CMIP6 data licensing update" recommending all existing CC BY-SA 4.0 licenses be relaxed to CC BY 4.0, MPI-M agrees to update this licensing to CC BY 4.0 for all its contributions, including MPI-ESM1.2-HR, MPI-ESM1.2-LR, and MPI-ESM1.2-XR, and ICON-ESM-LR.

Ob behalf of MPI-M
many thanks and best regards

Johann Jungclaus

**Comment by durack1** [comment]
thanks @johann-git. We also have the `ICON-ESM-LR` model listed as an `MPI-M` contributing configuration, which has published data (see [here](https://esgf-node.llnl.gov/search/cmip6/?source_id=ICON-ESM-LR)), however, it appears this is no longer available from the initially published DKRZ node (this also appears to be the case for the other 3 `MPI-ESM1-2-*` configurations). Is there a problem that needs to be resolved?

**Comment by johann-git** [comment]
Hi Paul, sorry, I simply forgot to include ICON-ESM-LR. I have edited the request accordingly.
I am not aware of any problems, maybe a temporary problem? It seems to me that the ICON-ESM data are available at
https://esgf-data.dkrz.de/search/cmip6-dkrz/
cheers
Johann

**Comment by durack1** [comment]
@johann-git no problem, thanks for the update. Those changes are now in place, please take a peek at [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) and let us know of any further tweaks required
