### ISSUE TITLE
CNRM-CERFACS CMIP6 licensing update from CC BY-NC-SA 4.0 to CC BY 4.0

### ISSUE THREAD

**Issue by DavidSYM** [WCRP-CMIP/CMIP6_CVs#1107]
Hi,

In accordance with Paul Durack's email of June 2, 2022 entitled "CMIP6 data licensing update" recommending all existing CC BY-NC-SA 4.0 licenses be relaxed to CC BY 4.0, CNRM-CERFACS agrees to update this licensing to CC BY 4.0 for all its contributions, including: CNRM-ESM2-1, CNRM-CM6-1 and CNRM-CM6-1-HR. Please do not hesitate to come back to us if you have any question.

Thanks, David Salas y Melia
On behalf of CNRM-CERFACS

**Comment by durack1** [comment]
Copied from #1101 

From: SALAS Y MELIA David
Date: Thursday, June 16, 2022 at 12:45 AM
To: Durack, Paul J.
Subject: Re: CMIP6 data licensing update
Hi Paul,

Thanks for your message. Our initial plans were to develop a high-resolution version of our ESM (CNRM-ESM2-1-HR), but actually (by mid-2017 !) we concluded that we would not do so.
Hence we do not plan to publish data from CNRM-ESM2-1-HR, so you can certainly deregister this entry.

Cheers,
David

@rigoudyg @esgpub @mpmoine ping

**Comment by durack1** [comment]
@DavidSYM thanks for that update. All changes noted above are now in place, please review the details at [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) and let us know of any further tweaks required
