### ISSUE TITLE
Models yet to relax to CC BY 4.0 license

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#1113]
@matthew-mizielinski I took a quick review this AM regarding models that are yet to get in contact regarding relaxing licenses to CC BY 4.0 - the list is larger than I assumed (40 currently). We have the non-published contributions under control in #1028, however, figured generating yet another table to capture the remaining models is useful.

It would be great if you could assist with reaching out to these groups and clarifying their license status. As per #1028 it'd be great to use the table below dynamically so we can keep up to date with the evolving status

**Updated 221004 - last merged PR #1169**

|count|institution_id|source_id|MIPs|contact status|
|--|--|--|--|--|
|1| AER | LBLRTM-12-8 | RFMIP | Rick Pernak emailed |
|2| AER | RRTMG-LW-4-91 | RFMIP | Rick Pernak emailed |
|3| AER | RRTMG-SW-4-02 | RFMIP | Rick Pernak emailed |
|4| RTE-RRTMGP-Consortium | RTE-RRTMGP-181204 | RFMIP | Rick Pernak emailed |
|5| NUIST | NESM3 | CMIP DAMIP DCPP GMMIP GeoMIP PMIP ScenarioMIP VolMIP | esmc/jianc@nuist emailed |
|6| SNU | SAM0-UNICON | CMIP ScenarioMIP | sjh11556@snu emailed |
|***Relax***|***completed***|***below***|||
|#1116 #1117| AWI | AWI-CM-1-1-HR | CMIP CORDEX HighResMIP OMIP SIMIP VIACSAB | Chris D, Gerrit L emailed/thread |
|#1116 #1117| AWI | AWI-CM-1-1-LR | CMIP CORDEX HighResMIP OMIP SIMIP ScenarioMIP VIACSAB | Chris D, Gerrit L emailed/thread |
|#1116 #1117| AWI | AWI-CM-1-1-MR | CMIP CORDEX OMIP PAMIP SIMIP ScenarioMIP VIACSAB | Chris D, Gerrit L emailed/thread |
|#1116 #1117| AWI | AWI-ESM-1-1-LR | CMIP PMIP | Chris D, Gerrit L emailed/thread |
|#1118 #1119| CMCC | CMCC-CM2-HR4 | CMIP HighResMIP OMIP | Piergiuseppe/Tomas L emailed  2022-06-27: relaxed to CC BY 4.0 |
|#1118 #1119| CMCC | CMCC-CM2-SR5 | CMIP DCPP GMMIP OMIP ScenarioMIP | Piergiuseppe/Tomas L emailed  2022-06-27: relaxed to CC BY 4.0 |
|#1118 #1119| CMCC | CMCC-CM2-VHR4 | CMIP HighResMIP | Piergiuseppe/Tomas L emailed  2022-06-27: relaxed to CC BY 4.0 |
|#1118 #1119| CMCC | CMCC-ESM2 | C4MIP CMIP LS3MIP LUMIP OMIP ScenarioMIP | Piergiuseppe/Tomas L emailed 2022-06-27: relaxed to CC BY 4.0 |
|#1130 #1138| ECMWF | ECMWF-IFS-HR | HighResMIP | Chris Roberts responded 26 July Fine to relax the license on CMIP6 data to CC BY 4.0, but don’t know how to do this. |
|#1130 #1138| ECMWF | ECMWF-IFS-LR | HighResMIP | Chris Roberts emailed responded 26 July Fine to relax the license on CMIP6 data to CC BY 4.0, but don’t know how to do this |
|#1130 #1138| ECMWF | ECMWF-IFS-MR | HighResMIP | Chris Roberts responded 26 July Fine to relax the license on CMIP6 data to CC BY 4.0, but don’t know how to do this |
|#1132 #1139| THU | CIESM | CFMIP CMIP CORDEX GMMIP HighResMIP OMIP SIMIP ScenarioMIP | yanluan@tsinghua emailed |
|#1140 #1141| UHH | ARTS-2-3 | RFMIP | Oliver Lemke emailed |
|#1137 #1142| HAMMOZ-Consortium | MPI-ESM-1-2-HAM | AerChemMIP CMIP RFMIP ScenarioMIP | David N emailed |
|#1131 #1143| MRI | MRI-AGCM3-2-H | DynVarMIP HighResMIP | yukimoto@mri-jma response 25/07 MRI agree to change from SA 4.0 to BY 4.0 for all contributions. Awaiting JMA headquarters approval, request extension to 8 August for license status change |
|#1131 #1143| MRI | MRI-AGCM3-2-S | CMIP DynVarMIP HighResMIP | yukimoto@mri-jma  response 25/07 MRI agree to change from SA 4.0 to BY 4.0 for all contributions. Awaiting JMA headquarters approval, request extension to 8 August for license status change |
|#1131 #1143| MRI | MRI-ESM2-0 | AerChemMIP C4MIP CFMIP CMIP CORDEX DAMIP DCPP DynVarMIP FAFMIP GMMIP GeoMIP LS3MIP OMIP PMIP RFMIP SIMIP ScenarioMIP VolMIP | yukimoto@mri-jma  response 25/07 MRI agree to change from SA 4.0 to BY 4.0 for all contributions. Awaiting JMA headquarters approval, request extension to 8 August for license status change |
|#1149 #1152| CCCR-IITM | IITM-ESM | CMIP GMMIP ScenarioMIP | Swapna emailed |
|#1150 #1153| INM | INM-CM4-8 | CMIP PMIP ScenarioMIP | Evgeny emailed |
|#1150 #1153|  INM | INM-CM5-0 | CMIP ScenarioMIP | Evgeny emailed |
|#1150 #1153|  INM | INM-CM5-H | CMIP HighResMIP | Evgeny emailed |
|#1151 #1154| CCCma | CanESM5 | C4MIP CDRMIP CFMIP CMIP CORDEX DAMIP DCPP DynVarMIP FAFMIP GMMIP GeoMIP ISMIP6 LS3MIP LUMIP OMIP PAMIP RFMIP SIMIP ScenarioMIP VIACSAB VolMIP | Neil/Greg emailed |
|#1151 #1154| CCCma | CanESM5-CanOE | C4MIP CDRMIP CMIP OMIP ScenarioMIP | Neil/Greg emailed |
|#1155 #1157| FIO-QLNM | FIO-ESM-2-0 | CMIP DCPP GMMIP OMIP ScenarioMIP SIMIP | songroy@fio |
|#1159 #1161| BCC | BCC-CSM2-HR | CMIP HighResMIP | twwu/rongxy@cma emailed |
|#1159 #1161| BCC | BCC-CSM2-MR | C4MIP CFMIP CMIP DAMIP DCPP GMMIP LS3MIP LUMIP RFMIP ScenarioMIP | twwu/rongxy@cma emailed |
|#1159 #1161| BCC | BCC-ESM1 | AerChemMIP CMIP | twwu/rongxy@cma emailed |
|#1160 #1162| NIMS-KMA | KACE-1-0-G | CMIP ScenarioMIP | Yoonjin L/yhbyun@korea emailed |
|#1163 #1164| KIOST | KIOST-ESM | C4MIP CMIP DynVarMIP PMIP ScenarioMIP | yhokim@pknu emailed |
|#1165 #1166| CAMS | CAMS-CSM1-0 | CFMIP CMIP GMMIP HighResMIP ScenarioMIP | rongxy@cma emailed |
|#1168 #1169| CAS | CAS-ESM2-0 | AerChemMIP C4MIP CFMIP CMIP CORDEX DAMIP DynVarMIP FAFMIP GMMIP GeoMIP HighResMIP LS3MIP LUMIP OMIP PMIP SIMIP ScenarioMIP VIACSAB VolMIP | linpf/zhanghe@iap emailed |
|#1168 #1169| CAS | FGOALS-f3-H | CMIP HighResMIP OMIP | linpf/zhanghe@iap emailed |
|#1168 #1169| CAS | FGOALS-f3-L | CMIP DCPP GMMIP HighResMIP OMIP PAMIP PMIP SIMIP ScenarioMIP | linpf/zhanghe@iap emailed |
|#1168 #1169|CAS | FGOALS-g3 | CMIP CORDEX DAMIP DCPP FAFMIP GMMIP LS3MIP OMIP PMIP SIMIP ScenarioMIP | linpf/zhanghe@iap emailed |

**Comment by CMIP-IPO** [comment]
@durack1 COUNT ID 30 E3SM 2.0 (Energy Exascale Earth System Model) the licence it is under is not listed in the github table but I’ve found via the website that it uses a BSD 3-clause license. Looking through that, it looks to me similar to CC BY 4.0.  Should I contact them to request the switch? They’ve gone over to CC BY 4.0 from SA for the other 3 models. BW, Briony

**Comment by durack1** [comment]
@CMIP-IPO thanks for the update. The `"license_info":"history"` attribute (see [`E3SM-1-1-ECA`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L2348) vs [`E3SM-2-0`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L2407)) requires the data of first dataset availability, so as we are yet to see `E3SM-2-0` data published, we're in a holding pattern until this occurs (similar to the other models in which we're in a data publication holding pattern: #1076, #1078, #1079, #1105, #1116, #1127)

**Comment by durack1** [comment]
@CMIP-IPO any more updates for me?

**Comment by durack1** [comment]
@CMIP-IPO we've made a good dent in the 131 models that have published (or plan to publish, imminently) data. Let's keep this open until after 30th September, and close once the new week begins - making sure to finalize the table above to sync with the final state

**Comment by durack1** [comment]
@CMIP-IPO it looks like if we could get CAS and AER to engage, we'd almost be completely done - not sure if an extra nag is warranted?

**Comment by durack1** [comment]
@MartinaSt ping! This is the remaining relaxation tasks, not many remaining!

**Comment by durack1** [comment]
@CMIP-IPO @MartinaSt @matthew-mizielinski we are now down to just 6 models (of 132) that have not relaxed their licenses - I think this is a good job, so will close this issue out.

If the others want to change their license, we can do this at any future point, but this will require them to initiate the change rather than WIP/IPO chasing them down

**Comment by pernak18** [comment]
thanks @durack1!

**Comment by durack1** [comment]
@CMIP-IPO nice work, 100% success - and closed out
