### ISSUE TITLE
Update multiple AWI source_id licenses

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#1116]
From: Christian Stepanek
Date: Wednesday, June 22, 2022 at 2:11 PM
To: "Durack, Paul J.", "tido.semmler", "christopher.danek"
Subject: Re: CMIP6 data licensing update

the mip-contact@ is indeed a multi-person mail address that reaches, among others, Tido and myself.

Christian

On 22.06.22 20:44, Durack, Paul J. wrote:
Excellent, will do.
 
And regarding the contact email, is Tido still happy to be left as the contact, or is the mip-contact@ a preferred *multi-person* mailing list?
 
Cheers,
 
P
 
From: Christian Stepanek
Date: Wednesday, June 22, 2022 at 11:43 AM
To: "Durack, Paul J."
Subject: Re: CMIP6 data licensing update
 
Dear Paul,
 
if this license change is common for other groups then I do not see any reason why we should not agree. I assume that both Gerrit and Tido are fine with this, so from my point of view just change the license.
 
All the best
Christian
 
On 22 Jun 2022 18:42, "Durack, Paul J." wrote:
Hi folks, it really would be great to get these changes clarified and closed out.
 
If you agree to the CC BY-SA 4.0 -> CC BY 4.0 license relaxation, I will get that updated before the end of day.
 
Cheers,
 
P
 
From: "Durack, Paul J."
Date: Monday, June 20, 2022 at 10:13 PM
To: christopher.danek, gerrit.lohmann

Subject: Re: CMIP6 data licensing update
 
In addition to the below, one additional query.
 
For the 5 registered models, we have a contact email as tido.semmler. I assume Tido is not the best contact for ongoing model queries? We are recommending that rather than a single personal email address, a mailing list address is provided, so while we are updating the details as noted below, this contact email address can also be amended.
 
For the latest entries across the existing archive, you can peruse these at [https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html](https:/wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html).
 
Cheers,
 
P
 
From: "Durack, Paul J."
Date: Monday, June 20, 2022 at 9:45 PM
To: christopher.danek, gerrit.lohmann

Subject: Re: CMIP6 data licensing update
 
Hi Chris (et al.), excellent, it seems that the glitch has been worked out, a quick check of https://esgf-node.llnl.gov/search/cmip6/?source_id=AWI-CM-1-1-HR seems like this DKRZ hosted data is live and available.
 
The plan as noted below will be to leave the placeholder registration for the imminent release of the AWI-ESM-2-1-LR data – please notify us when this is live and we will amend the registration information.
 
Regarding the other models that have data available: AWI-CM-1-1-HR, AWI-CM-1-1-LR, AWI-CM-1-1-MR, AWI-ESM-1-1-LR. We are recommending a relaxation from the existing CC BY-SA 4.0 to the CC BY 4.0 license. If you approve of this change, I will amend your current entries to reflect this relaxation, and await the AWI-ESM-2-1-LR data, so we can finalize this once data is available.
 
Cheers,
 
P

@christian-stepanek @tsemmler05

**Comment by durack1** [comment]
@christian-stepanek, @tsemmler05 those changes are now in place. Please take a peek at [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html).

As we are awaiting the publication of `AWI-ESM-2-1-LR` data imminently, I will reopen this issue. When this data is published, please add a comment noting it on this issue and I will clean up the remaining entry and close this out

**Comment by durack1** [comment]
@christian-stepanek, @tsemmler05 just circling around, there doesn't appear to be any [`AWI-ESM-2-1-LR` data published yet](https://esgf-node.llnl.gov/search/cmip6/?source_id=AWI-ESM-2-1-LR), is this due imminently?

**Comment by christian-stepanek** [comment]
Dear @durack1, I am working on that. There was a change and I am currently updating the output.

**Comment by durack1** [comment]
@christian-stepanek no problem, when you have the data published, please ping this issue and I will resolve the remaining license history info

**Comment by durack1** [comment]
@christian-stepanek just circling around, it appears we're yet to see [`AWI-ESM-2-1-LR`](https://esgf-node.llnl.gov/search/cmip6/?source_id=AWI-ESM-2-1-LR) data published, is that correct?

**Comment by durack1** [comment]
@christian-stepanek just circling around on this very old issue. It appears that [`AWI-CM-2-1-LR`](https://esgf-node.llnl.gov/search/cmip6/?source_id=AWI-CM-2-1-LR) data is still not published, and so I am querying whether we should deregister this model and close out this issue

**Comment by durack1** [comment]
@christian-stepanek just circling around of this query again. It seems that no data for [`AWI-CM-2-1-LR`](https://esgf-node.llnl.gov/search/cmip6/?source_id=AWI-CM-2-1-LR) is currently available. Do you expect this, or should we deregister the model?

**Comment by durack1** [comment]
Hi @christian-stepanek just circling around again, do we have any updates, or clearer plans about non-contribution?

**Comment by christian-stepanek** [comment]
Dear Paul, it seems that my answer via email did not make it through.

Hi Paul,

we are still working on it. Is there the need to finish by a specific deadline?

All the best
Christian

**Comment by durack1** [comment]
@christian-stepanek just circling around on this - any updates to provide?

**Comment by durack1** [comment]
Linked to discussion in https://github.com/WCRP-CMIP/CMIP6_CVs/issues/1220#issuecomment-2256539594
