### ISSUE TITLE
ECMWF CMIP6 licensing update from CC BY-SA 4.0 to CC BY 4.0 

### ISSUE THREAD

**Issue by CMIP-IPO** [WCRP-CMIP/CMIP6_CVs#1130]
@durack1 to update ECMWF licenses COUNT ID 2,3 and 4 to CC BY 4.0 -do they need to provide an exceptions contact?

2	ECMWF	ECMWF-IFS-HR
3	ECMWF	ECMWF-IFS-LR
4	ECMWF	ECMWF-IFS-MR

From: Christopher Roberts ecmwf
Sent: 26 July 2022 15:27
To: Briony Turner CMIP IPO
Cc: R Senan ECMWF; S Keeley ECMWF
Subject: Re: CMIP6 licence relaxation -action required by 31st July 

Dear Briony, 

It should be fine for us to relax the license on CMIP6 data to CC BY 4.0, but I don’t know how to do this.

I think the contacts you have for the mailing list are fine.  We do not have a lead responsible person as this data was produced as part of an EU funded project activity and is not part of our core activities at ECMWF. We have continued to support queries under a “best effort” basis but do not have any dedicated resources for this activity. To my knowledge, ECMWF does not rely on CMOR for any core activities and does not host an ESGF data node. 

Thanks,
Chris

From: Briony Turner CMIP IPO
Date: Tuesday, 26 July 2022 at 14:55
To: Christopher Roberts ECMWF
Cc: R Senan ECMWF; S Keeley ECMWF
Subject: CMIP6 licence relaxation -action required by 31st July 
Dear Chris,
 
CMIP6 licence relaxation -action required by 31st July 
 
We are supporting the WGCM Infrastructure Panel (WIP) in their efforts to relax the CMIP6 licences from the existing CC BY-SA 4.0 default license. The WIP wish to complete this process by the end of July.  Are you in the process of relaxing the licence for the following?  If so, when do you expect this to take effect?
 
institution_id	source_id	MIPs
ECMWF	ECMWF-IFS-HR	HighResMIP
ECMWF	ECMWF-IFS-LR	HighResMIP
ECMWF	ECMWF-IFS-MR	HighResMIP
 
 
Please check the current status here -if this is incorrect let me know.

**Comment by durack1** [comment]
@CMIP-IPO that would be ideal, if there is no contact then it will require additional work to ascertain whom to direct such a query (in the chance that a query is raised), so ideally yes, a contact email is required - see [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) for examples, we could just use Chris' email address if no mailing list occurs

@cdr30 ping!

**Comment by cdr30** [comment]
We don't have a specific team responsible for this data so I think it is fine to leave my email address as the contact.

**Comment by durack1** [comment]
@cdr30 that's now done. Please take a peek at [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) and let me know if any further tweaks are required
