### ISSUE TITLE
MRI CMIP6 licensing update from CC BY-SA 4.0 to CC BY 4.0

### ISSUE THREAD

**Issue by CMIP-IPO** [WCRP-CMIP/CMIP6_CVs#1131]
@durack1 this relaxation should be enacted 8 August (see bold below) for 28,29,30
28	MRI	MRI-AGCM3-2-H	
29	MRI	MRI-AGCM3-2-S	
30	MRI	MRI-ESM2-0	

From: Seiji Yukimoto MRI 
Sent: 25 July 2022 08:06
To: CMIP-IPO  Briony Turner 
Cc: 保坂征宏 mhosaka, M Deushi MRI; 神代剛 ,tkoshiro MRI R Mizuta MRI
Subject: Re: Action requested: CMIP6 licence relaxation and metadata + mailing list clean up

Dear Dr. Briony Turner,

• CMIP6 licence relaxation
MRI agree to update all existing CC BY-SA 4.0 licenses to CC BY 4.0 for all its contributions, including MRI-ESM2-0, MRI-AGCM3-2-H, and MRI-AGCM3-2-S. **However, we are waiting for the final decision of our headquarters JMA. We would appreciate it if you could wait two weeks (until 8 August) for the license status change.**

• Mailing list updates
I will be retiring soon and would like the following two persons to replace me as the MRI-ESM2-0 contact:
              Dr. M Deushi  [contact details removed]
              Dr. T Koshiro [contact details removed]The contact for MRI-AGCM2-2-H and MRI-AGCM3-2-S is Dr. R Mizuta [contact details removed] who is already subscribed to the mailling list.

Best regards,

Seiji Yukimoto
Department of Climate and Geochemistry Research Mtetorological Research Institute

> 2022/07/21 20:54、Briony Turner CMIP IPO
> 
> Dear all,
> For those of you who I have not yet been in touch with, I am Briony Turner, the CMIP International Project Office Programme Manager.  
> There are three areas we would appreciate your participation in:
>            • CMIP6 licence relaxation -action required by 31 July.
>            • CMIP metadata -action required by 31 August
>            • Mailing list clean up -action required by 31 July

**Comment by yukimotoster** [comment]
The Agency's approval for the license relaxation has been obtained; please activate the license relaxation for the MRI's CMIP6 data.

**Comment by durack1** [comment]
@yukimotoster thankyou. That change in now in place, please review [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) and let me know of any further tweaks required

@ryo-mizuta ping
