### ISSUE TITLE
THU CMIP6 licensing relaxation from CC BY-SA 4.0 to CC BY 4.0

### ISSUE THREAD

**Issue by Theropod** [WCRP-CMIP/CMIP6_CVs#1132]
Hello, following up the email "Action requested: CMIP6 license relaxation and metadata + mailing list clean up", Tsinghua University (THU) agrees to update CC BY-SA 4.0 licenses to CC BY 4.0, including CIESM. 

Thanks !

**Comment by durack1** [comment]
@Theropod thanks for the update. We have a registered email address for queries with `@tsinghua.edu.cn <- yanluan` (but rather correctly formatted), is this still suitable, or would you prefer an institutional mailing list replaces this personal email address?

@yjyangjie ping

**Comment by Theropod** [comment]
Yes, this email address is still suitable, we do not want to change now. Thanks for your consideration!

**Comment by durack1** [comment]
@Theropod @yjyangjie that change is now in place, please review [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) and let me know of any further tweaks required
