### ISSUE TITLE
MPI-ESM-1-2-HAM CMIP6 licensing relaxation from CC BY-SA 4.0 to CC BY 4.0 

### ISSUE THREAD

**Issue by nedavid** [WCRP-CMIP/CMIP6_CVs#1137]
The HAMMOZ Steering Committee agrees to relax the existing CC BY-SA 4.0 license to CC BY 4.0 for all MPI-ESM-1-2-HAM CMIP6 data.

**Comment by durack1** [comment]
@nedavid thanks for the update. We have a contact email address as `@env.ethz.ch <- david.neubauer` (non-garbled), is this address ok, or would you prefer to update this with an institutional address/mailing list?

**Comment by nedavid** [comment]
@durack1 we would like to update the contact email address with a mailing list, due to various reasons this will only be possible in October

**Comment by durack1** [comment]
@nedavid no problem. Would you like me to process the license relaxation, and leave the contact email address as it is for now? Or would you prefer we park this until October? (My preference is process the license relaxation now, and you can open a new issue to update the email when you have the alternate set up)

**Comment by nedavid** [comment]
@durack1 yes, please process the license relaxation now, I will open a new issue about the email update later

**Comment by durack1** [comment]
@nedavid that change is now done, please take a peek at [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) and let me know of any issues.

Please open a new issue when you have an updated email address to switchout
