### ISSUE TITLE
UHH ARTS-2-3 licensing update from CC BY-SA 4.0 to CC BY 4.0

### ISSUE THREAD

**Issue by olemke** [WCRP-CMIP/CMIP6_CVs#1140]
In response to Paul Durack's mail from June 2 titled "CMIP6 data licensing update", I hereby inform you that we agree to the license change from CC BY-SA 4.0 to CC BY 4.0 for the contributions of UHH ARTS-2-3. Please update the license information accordingly.

**Comment by durack1** [comment]
@olemke thanks for the update. That change is now in place; please take a peek at [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) and let me know of any further tweaks. Note that you have a personal email address as a contact; however, we are recommending an institutional mailing list be used in place of personal emails if a suitable list exists
