### ISSUE TITLE
IITM-ESM relaxation  from the existing CC BY-SA 4.0 to CC BY 4.0.

### ISSUE THREAD

**Issue by CMIP-IPO** [WCRP-CMIP/CMIP6_CVs#1149]
@durack1 licence relaxation:

From: Swapna P [email address removed]
Sent: 27 September 2022 10:39
To: Briony Turner <Briony.Turner@esa>
Subject: Re: CMIP6 licence relaxation

Dear Briony,

Thank you for the mail. The IITM-ESM license can be relaxed from the existing CC BY-SA 4.0 to CC BY 4.0.

Best Regards,
Swapna.

**Comment by durack1** [comment]
@manmeet3591 that change is now in place, please review details in [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) and let me know of any further tweaks required
