### ISSUE TITLE
License relaxation to CC By 4.0 for models INM-CM4-8, INM-CM5-0, INM-CM5-H 

### ISSUE THREAD

**Issue by CMIP-IPO** [WCRP-CMIP/CMIP6_CVs#1150]
@durack1 note licence relaxation on 30 September

From: E Volodin [email address removed] 
Sent: 27 September 2022 12:35
To: Briony Turner
Subject: Re: Action requested: CMIP6 licence relaxation

Dear Briony, 

I confirm license relaxation to CC By 4.0 for models INM-CM4-8, INM-CM5-0, INM-CM5-H at September 30.

Evgeny.

**Comment by durack1** [comment]
@volodin1, that change is now in place. Please review the details at [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) and let me know of any further tweaks required
