### ISSUE TITLE
Licence relaxation  to CC BY 4.0 for CanESM5 and CanESM5-CanOE

### ISSUE THREAD

**Issue by CMIP-IPO** [WCRP-CMIP/CMIP6_CVs#1151]
@durack1 licences can be relaxed 

From: Swart,Neil (ECCC) [email removed]
Sent: 27 September 2022 13:46
To: Briony Turner [email removed]
Cc: Flato, Greg (EC/EC)[email removed]; CMIP-IPO
Subject: RE: CMIP6 license change request

Hello Briony,

This was discussed and there is no issue in relaxing the license effective immediately. Apologies if this was not communicated to you – I was away during the summer.

Thanks,
Neil

Greg: Please note there is no inconsistency between what is proposed and the Open Government License. Previously we similarly made such a relaxation, but in a more focused way, on request from IBM.

**Comment by durack1** [comment]
@jamesAnstey looping you in here too.

We have a standing query, the currently listed email on [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) appears garbled, `"@canada.ca <- ec.cccma.info-info.ccmac.ec", ` so we'll need to ascertain an update for this before finalizing the license relaxation. This is also a standing issue in #1148 (along with other missing info)

**Comment by durack1** [comment]
@slavakharin, @jamesAnstey, @swartn, that license change is now in place. Please review the details at [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) and let me know of any further tweaks required

**Comment by slavakharin** [comment]
@durack1 Looks ok to me but I let @swartn to have the final word on this

**Comment by swartn** [comment]
Yep looks good to me. Thanks. And apologies for the delay.
