### ISSUE TITLE
Update CCCma contact email address

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#1156]
From: Farahani,Ellie
Date: Tuesday, September 27, 2022 at 4:26 PM
To: Durack, Paul J. 
Cc: ec.cccma.info-info.ccmac.ec AT canada.ca
Subject: RE: Checking to make sure this works
Hi Paul,
 
Yes, your email was received via the old alias. However I will be thankful if you can start using EC.F CCCMA Info / Info CCMAC F.EC f.cccma.info DASH info.ccmac.f AT ec   .     gc   .ca
 
Regards,
Ellie
 
 
Dr Ellie Farahani 
(she, her, elle)
 
Manager, Canadian Centre for Climate Modelling and Analysis (CCCma)
Science and Technology Branch | Environment and Climate Change Canada 
ellie.farahani@ec | +1-236-464-1175

 
From: Durack, Paul J.
Sent: Tuesday, September 27, 2022 2:44 PM
To: ec.cccma.info DASH info.ccmac.ec AT   cc anada    .ca
Subject: Checking to make sure this works
 
Just checking to make sure this email is being received – it was retrieved from CCCma data published to the CMIP6 project.
 
Cheers,
 
P

@jamesAnstey @slavakharin @swartn ping

**Comment by slavakharin** [comment]
According to Ellie, the email needs to be changed to `f.cccma.info-info.ccmac.f@ec.gc.ca`
