### ISSUE TITLE
institution_id registration of UnivLeeds

### ISSUE THREAD

**Issue by amtgwm** [WCRP-CMIP/CMIP6_CVs#1178]
This is a request for institution ID for the University of Leeds, in relation to the UKESM submissions to CMIP6-VolMIP.

Dr. Graham Mann (Univ. Leeds) and Dr. Wuhu Feng (National Centre for Atmospheric Science at Univ. Leeds) ran the UKESM simulations for the VolMIP short-term volcano-climate response experiment "volc-pinatubo-full".

The UKESM runs were completed in 2020 on the joint Met Offfice and NERC supercomputer "MONSOON".

I have requested (to Veronika Eyring) that myself and Dr. Wuhu Feng (NCAS, Univ. Leeds) be added as additional UKESM scientific contacts for CMIP6, and for us both to be added to the CMIP6-MODELGROUPS-SCI mailing list

I have been in touch yesterday with the main data-submission and citation contacts for UKESM
(Matthew Mizielinski and Jeremy Walton are), but am also following the instructions on the 
"CMIP6 registration guidance" webpage, to **request an institution id for the University of Leeds** 
(assuming one does not already exist).

Thanks a lot for your help with this,

Best regards,

Cheers
Graham

Dr. Graham Mann
UK lead for UKESM submission to CMIP6-VolMIP

### Background Info re: our role within UKESM submissions to CMIP6:
 
During 2020, myself and Dr. Feng ran the UKESM ensembles for the CMIP6-VolMIP 
short-term volcano-climate response experiment “volc-pinatubo-full”

During 2021, we provided timeseries data-files for the UKESM runs directly to Davide Zanchettin
(the co-ordinator for the MIP) for the 27-member ensemble of runs for volc-pinatubo-full,
and the corresponding unforced 27-member (the PI-control).

The UKESM results were published in the first VolMIP paper presenting results from the
volc-pinatubo-full short-term response experiments (Zanchettin et al., 2022, GMD), 
and the UKESM subnmission validated within that paper alongside the other CMIP6 models:
 
https://doi.org/10.5194/gmd-15-2265-2022
 
and the timeseries datasets provided via WDCC public repository at DKRZ:
 
https://cera-www.dkrz.de/WDCC/ui/Compact.jsp?acronym=VolMIP_pC
https://cera-www.dkrz.de/WDCC/ui/Compact.jsp?acronym=VolMIP_volc
 
Davide kindly allowed us to be included in that 2022 GMD paper, with having 
submitted only the global/tropical/NH/SH-means of the variables analysed in
the paper, but this was on the proviso that we would submit the data from the 
UKESM runs to the CMIP6 archive on the ESGF as soon as we were able to. 
 
In October 2021 I suffered a serious back problem, and was only able to do 
very limited research activities in the autumn and winter last year, over and 
above fulfilling my lecturing and associated teaching commitments in my 
lectureship at Univ. Leeds. 
 
Things got very busy after the Hunga Tonga eruption in January 2022, including with 
my being lead science organiser for an international workshop at Leeds (SSiRC),
originally to take place in March 2022, and then with omicron then was only able 
to take place in May 2022.  
 
I have had on my list of things not yet done since the back problem, to complete
the full data-submission for the UKESM CMIP6-VolMIP runs to ESGF.

But with leading a U.K. grant proposal re: Hunga-Tonga and associated 
international activities, and a recurrence of the back problem in Sep & Oct 2022, 
it’s only now that I’ve been able to secure the time to start the process towards 
achieving the “full submission” of the data from the UKESM runs Wuhu and I did
back in 2020 (that I promised Davide & the team I would do as soon as I was able to). 
 
And we are now proceeding to commence the process towards submitting the 
UKESM data for CMIP6-VolMIP volc-pinatubo-full to the CMIP6 archive on ESGF.
 
I was in touch with Matthew Mizielinski at the UK Met Office (lead CMIP5 data-submisson
contact for UKESM), re: arranging a meeting to plan the steps towards this full data-submission,
to then finally be able to proceed to be submit the full set of CF-netCDFs to ESGF, matching the 
same identifiers and other meta-data specs for the other UKESM submissions to CMIP6.
 
 
**  Dr. Graham Mann, Lecturer in Atmospheric Science              **
**  Institute for Climate & Atmospheric Science T: +44  0113 3431660     **
**  Room 10.108, School of Earth & Environment  F: +44  0113 3435259     **
**  University of Leeds, Leeds, LS2 9JT, U.K.   E: [G.W.Mann@leeds.ac.uk](mailto:G.W.Mann@leeds.ac.uk)  **

**Comment by matthew-mizielinski** [comment]
Hi @amtgwm, I'll cover how we've managed the submissions across UK institutions to date when we have a chat about the processing -- UK academic submissions have been collectively badged with the institution id NERC rather than individual universities needing to register and manage records in various systems (minimises duplication and effort).  

Once we've had that discussion I can advise what the other steps needed here are across all CMIP6 infrastructure.

**Comment by matthew-mizielinski** [comment]
There is nothing further to be done , these submissions will go in under the NERC institution id when ready.
