### ISSUE TITLE
Add funding attribution

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#1181]
We have recognized that there is no attribution to funding agencies that have facilitated much of the work across a number of CMIP6-supporting repos. For this reason, it is a good idea to revisit contributions, and ensure that folks doing the work have their efforts, and their funders recognized.

We have some template text for the PCMDI-centric projects in https://github.com/PCMDI/cmor/issues/692#issuecomment-1416493562, but for these collaborative repos (such as this one), it would be useful to broaden the recognition, in addition to noting repo contributions - ala https://github.com/PCMDI/pcmdi_metrics#contributors (which catches PR contributions). If there is a way to list participants (issue contributors) that would be great to investigate too - see [github docs](https://docs.github.com/en/repositories/viewing-activity-and-data-for-your-repository/viewing-a-projects-contributors)

@matthew-mizielinski do you have some edits to recommend on the [draft text](https://github.com/PCMDI/cmor/issues/692#issuecomment-1416493562)

**Comment by durack1** [comment]
From @matthew-mizielinski:
```
The information hosted in this repository has been provided by many people across the CMIP community,
including members of climate modelling groups and model intercomparison projects (MIPs).
The structure of this data and the tools required to maintain it were developed primarily by climate
and computer scientists from PCMDI at LLNL with assistance from others at the Met Office in the UK and
DKRZ in Germany.
```
https://github.com/MetOffice

**Comment by durack1** [comment]
How about:

The content in this repository has been collected from many contributors representing the Coupled Model Intercomparison Project phase 6 (CMIP6), including those from climate modeling groups and model intercomparison projects (MIPs) around the world. The structure of content and tools required to maintain it was developed by climate and computer scientists from the Program for Climate Model Diagnosis and Intercomparison ([PCMDI](https://pcmdi.llnl.gov/)) at Lawrence Livermore National Laboratory ([LLNL](https://www.llnl.gov/)) with assistance from colleagues at the [UK MetOffice](https://www.metoffice.gov.uk/) and the Deutsches Klimarechenzentrum ([DKRZ](https://www.dkrz.de/en/)) in Germany.

This work is sponsored by the Regional and Global Model Analysis ([RGMA](https://climatemodeling.science.energy.gov/program/regional-global-model-analysis)) program of the Earth and Environmental Systems Sciences Division ([EESSD](https://science.osti.gov/ber/Research/eessd)) in the Office of Biological and Environmental Research ([BER](https://science.osti.gov/ber)) within the Department of Energy ([DOE](https://www.energy.gov/))'s Office of Science ([OS](https://science.osti.gov/)). The work at PCMDI is performed under the auspices of the U.S. Department of Energy by Lawrence Livermore National Laboratory under Contract DE-AC52-07NA27344.

**Comment by durack1** [comment]
@matthew-mizielinski @MartinaST @taylor13 if there are no objections to the above, I'll implement this - along with the DOE/LLNL and any other logos I am pointed to on Friday 3 Mar

**Comment by MartinaSt** [comment]
@durack1 That sounds good to me. Mentioning the contribution from the IS-ENES consortium apart from individual institutions might help to find funding for the planned ENES-RI.

**Comment by durack1** [comment]
@MartinaSt excellent, glad this ticks boxes for you.

I also just found https://allcontributors.org/ so will figure out if that is a way to recognize everyone that has "contributed" to the repo, including folks who have opened issues, replied etc - that might be step 2 after the above https://github.com/WCRP-CMIP/CMIP6_CVs/issues/1181#issuecomment-1445410971 is merged

**Comment by durack1** [comment]
Dropping this link, regarding collecting github user handles from issues etc https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests
