### ISSUE TITLE
Update MPI-ESM-1-2-HAM CMIP6 contact email address

### ISSUE THREAD

**Issue by nedavid** [WCRP-CMIP/CMIP6_CVs#1188]
Please change the contact e-mail address for all data of MPI-ESM-1-2-HAM/the HAMMOZ consortium to:
aerchemmip_echam-ham AT sympa.ethz.ch

**Comment by durack1** [comment]
@nedavid that change is now in place, please review [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) to double check the update

**Comment by nedavid** [comment]
@durack1 that's correct, thanks!
