### ISSUE TITLE
experiment_id --add 'esm-ssp*'

### ISSUE THREAD

**Issue by chrisdane** [WCRP-CMIP/CMIP6_CVs#1192]
Hi

`grep "^        \"ssp" CMIP6_experiment_id.json` yields a rather long list compared to `grep "^        \"esm-ssp" CMIP6_experiment_id.json`. That means,  a lot of `esm-ssp`-experiments are missing in the CVs although forcing data are available (e.g. `esm-ssp126`, `esm-ssp245`, or `esm-ssp370`).

The non-existence of these CVs hinders publication of model data on an ESGF node. Is it planned to include them? 

Thanks a lot and cheers,
Chris

**Comment by taylor13** [comment]
Hi Chris (@chrisdane)
The main emissions-driven experiment requested by any of the MIPs involved in CMIP6 was the esm-ssp585 experiment, which was a tier 1 experiment as part of C4MIP.  The CMIP6 archive hosts only results from experiments requested by one of the participating MIPs.  If several modeling groups have performed simulations with one or more of the other SSPs and want to make their results available, we might consider that as a special case.  
Karl

**Comment by durack1** [comment]
@chrisdane, just circling, are there additional emissions forcing data not published into input4MIPs? - https://esgf-node.llnl.gov/search/input4mips/?mip_era=CMIP6&target_mip_list=ScenarioMIP

**Comment by chrisdane** [comment]
Thanks for your replies. 

The problem is not missing forcing data, but missing entries in `CMIP6_CVs/CMIP6_experiment_id.json`.

> If several modeling groups have performed simulations with one or more of the other SSPs and want to make their results available, we might consider that as a special case.

Yes, in addition to the default C4MIP experiment `esm-ssp585` ([Jones et al. 2016](https://gmd.copernicus.org/articles/9/2853/2016/)) we have conducted `esm-ssp126`, `esm-ssp245`, `esm-ssp370` and `esm-ssp534-over`. It would be great to have a `CMIP6_CV` for them as well. This seems possible as there is e.g. `esm-ssp534-over` in `CMIP6_experiment_id.json` with `activity_id: "CDRMIP"` and `parent_activity_id: "C4MIP"`. Would a similar solution be possible for the other experiments, too?

Thanks a lot for your help,
Chris

**Comment by taylor13** [comment]
If I can summarize the discussion in issue https://github.com/WCRP-CMIP/CMIP6_CVs/issues/982, the policy is that the CMIP6 archive is for hosting multi-model ensembles of simulations.  It is not a general purpose archive for hosting model output that simply conforms to the data requirements and data reference syntax imposed on CMIP6 data.   If a MIP activity (like scenarioMIP) has an interest in and assumes responsibility for new experiments (not included in the list originally endorsed by the CMIP panel) _**and**_ if multiple groups were to run those experiments, then we would _consider_ adding those additional experiments to the CMIP6 archive.  Given severe resource constraints, there can be no open-ended commitment to hosting new experiments.

As discussed in https://github.com/WCRP-CMIP/CMIP6_CVs/issues/982, it is recommended that for climate model output that does not meet the criteria for inclusion in the CMIP6 multi-model data archive, you prepare your data consistent with CMIP6 data standards and publish it independently.  That way researchers can analyze your results using some of the same tools they have used to analyze CMIP6 simulations.

This is my personal interpretation of current policy and the practical considerations that underlie it.  I'll ping the chairs of the WGCM infrastructure panel (@durack1 @matthew-mizielinski ) to see if they have a different perspective.
