### ISSUE TITLE
activity_id -- add 'LESFMIP'

### ISSUE THREAD

**Issue by IngoBethke** [WCRP-CMIP/CMIP6_CVs#1196]
LESFMIP is a new MIP that is documented in Smith et al. 2022 (https://doi.org/10.3389/fclim.2022.955414). It is closely aligned with CMIP6 DAMIP and as such fully complies with CMIP6 standards. The intention is to cmorize the output from LESFMIP and then publish it through ESGF along with the existing CMIP6 output. 

I would much appreciate if following entry could be added to CMIP6_CVs 
        "LESFMIP":"Large Ensemble Single Forcing Model Intercomparison Project",

ps: I will create separate issues for experiment_id and source_id modifications

**Comment by IngoBethke** [comment]
I just realised that a number of LESFMIP experiments (e.g., hist-GHG, hist-aer, hist-sol, hist-volc, hist-nat) are already defined in DAMIP (the rest of the LESFMIP experiments are new). The only differences are in the "activity_id" (which would change from DAMIP to LESFMIP), the end_year (would change from 2014 to 2020) and some of the tier values. 

It might be confusing to define multiple entries of the same experiment. A better solution could be to add the missing experiments to DAMIP. I will check with Doug Smith (who is the PI of LESFMIP and DAMIP) what he thinks.

**Comment by matthew-mizielinski** [comment]
HI @IngoBethke 

Unfortunately CMIP6 is closed for new activities and experiments -- the systems where changes would be needed to support this are no longer being developed and focus has turned to future planning for CMIP7.

However, the LESFMIP definition includes many of the DAMIP experiments and you can publish these to CMIP6 under the DAMIP activity id -- I've been doing exactly this for Doug Smith over recent months.

We are getting close, within a month or so, of having a new mip era set up to handle this, CMIP6Plus, (just looking to get the last approval we need from WGCM). We're planning for LESFMIP to be the first activity included alongside "CMIP" for the DECK + historical runs.

When we set up LESFMIP we will include all of the experiments defined in Doug's paper (i.e. including the CMIP6 experiments from DAMIP), but we would recommending adding to the CMIP6 archive under DAMIP where possible.

When CMIP6Plus is started there will be a discontinuity in the assignment of variables to MIP tables, but there will be a simple mapping (i.e. `tas_Amon` -> `tas_APmon`).

@durack1, anything more to add here?

**Comment by durack1** [comment]
@matthew-mizielinski you've covered all the pertinent points. We should have a couple of new activities listed before the end of the year is my guess, but the expectation is that it will be fairly low volume, mostly used for evaluating forcing datasets as they are prepared for CMIP7 prime time through the _historical_ experiments.

@IngoBethke we are currently still working on these updated repos, but once we have these in shape to share, we'll make sure that you and others are notified, so you can migrated your workflows across to the latest updated configs.

**Comment by IngoBethke** [comment]
Hi @matthew-mizielinski and @durack1 

Thanks a lot for the detailed info. 

We won't start the cmor-ization before August, so waiting for the CMIP6plus sounds like the best option for us (also considering that we have output for some experiments like LESFMIPhist-lu that are not defined under DAMIP). 

Kind regards, Ingo
