### ISSUE TITLE
CNRM-ESM2-1 activity_id -- add 'DCPP'

### ISSUE THREAD

**Issue by esgpub** [WCRP-CMIP/CMIP6_CVs#1211]
Registered activity_id’s (missing)

CNRM-ESM2-1: AerChemMIP C4MIP CDRMIP CMIP CORDEX GMMIP GeoMIP LS3MIP LUMIP OMIP RFMIP ScenarioMIP (DCPP missing)

**Comment by durack1** [comment]
@esgpub great, that change is now in place, see [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html). We'll let the changes propagate and retrigger the republication of the CNRM-ESM2-1 DCPP data tomorrow
