### ISSUE TITLE
TaiESM1 missing activity_id = RFMIP

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#1213]
@lamaliang @rceclccr we have replicated data for the below, but do not have an `RFMIP` activity noted in the 

Issue:
activity_id.institution_id.source_id.experiment_id
RFMIP.AS-RCEC.TaiESM1.piClim-control
Registered activity_id entries:
TaiESM1: AerChemMIP CFMIP CMIP GMMIP LUMIP PAMIP PMIP ScenarioMIP (RFMIP missing)

See below
https://github.com/WCRP-CMIP/CMIP6_CVs/blob/a4bd0d38e958aef3da5bdbe6212f2ca7afdf9a56/CMIP6_source_id.json#L7638-L7648

Is this an expectedvalid dataset? If yes, to get this effectively replicated and republished we'll need to augment your `activity_participation` field with a new entry - can you please confirm?

**Comment by lamaliang** [comment]
Dear Durack @durack1 

Sorry, the late for reply. Sorry due to some issues, we didn't do RFMIP. Please modify TaiESM1 activity_participation to remove RFMIP.

Thanks.

**Comment by durack1** [comment]
Hi folks, you did do the `piClim-control` experiment, which was identified as an RFMIP experiment, co-sponsored by AerChemMIP, and as such these TaiESM1 datasets are published and noted as an RFMIP contribution - see [here](https://aims2.llnl.gov/search?project=CMIP6&activeFacets=%7B%22activity_id%22%3A%22RFMIP%22%2C%22institution_id%22%3A%22AS-RCEC%22%7D)

To correct the index, assuming these data are valid, we'll need to add "RFMIP" to the activity participation field for the model - please confirm

**Comment by lamaliang** [comment]
Hi Durack

Sorry, it is my mistake. Please add "RFMIP" to activity participation field. 

Thanks

**Comment by durack1** [comment]
@lamaliang @rceclccr that change is now in place (see [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html)). We'll get back to replicating and republishing these data at LLNL-ESGF tomorrow.
