### ISSUE TITLE
Would using JSON-schema to define CVs simplify the tooling around CVs ?

### ISSUE THREAD

**Issue by huard** [WCRP-CMIP/CMIP6_CVs#1228]
JSON-Schema is a schema for JSON file that specifies what JSON data is required for a given application. See [docs](https://json-schema.org/learn/getting-started-step-by-step). 

I believe the CVs defined here could be exposed as a JSON-Schema, and then a wide suite of [tools](https://json-schema.org/implementations) could be used across the ESGF software stack to validate content, create web forms, etc. 

JSON schemas are used for instance by the [CMIP6 STAC extension](https://github.com/TomAugspurger/cmip6/blob/main/json-schema/schema.json).  What would be done here would be similar, but would include allowed values for the different facets. 

I was wondering if this had already been discussed. If there is interest, I could submit a PR to generate a schema from the CVs defined here for folks to experiment with.

**Comment by matthew-mizielinski** [comment]
Hi @huard , JSON-Schema has been discussed a couple of times and a colleague had a play with setting it up on a fork of the PCMDI/cmip6-cmor-tables repo.  I'll see whether I can revisit that in the next week or two and apply it to this or the CMIP6Plus_CVs repo in the next month or so.

**Comment by huard** [comment]
Ok, see some experimental code here: https://gist.github.com/huard/6a8f261221497c65cacf8324dcc4045d

Cheers, 

David
