### ISSUE TITLE
Official source for naming schema to construct instance_id from facets and vice versa

### ISSUE THREAD

**Issue by jbusecke** [WCRP-CMIP/CMIP6_CVs#1229]
Hey folks! I am currently keeping a schema like this:

https://github.com/leap-stc/leap-data-management-utils/blob/8c07e4bb5784bc777b57bdc1f2d25e1868669d79/leap_data_management_utils/cmip_catalog.py#L7

`CMIP6_naming_schema_official = 'mip_era.activity_id.institution_id.source_id.experiment_id.member_id.table_id.variable_id.grid_label.version'`

In some repositories to appropriately split/combine an instance_id from facet values. I would like to pull this information from an official source instead of keeping it hardcoded into various repos of mine.

- Is this repo the appropriate source? 
- Does something like this already exist here? I think I could use https://github.com/WCRP-CMIP/CMIP6_CVs/blob/2c9cf667546f31a495cb2e3b8d9d5892bc7abaa2/CMIP6_DRS.json#L5 but wanted to check if that is the appropriate way to do it.

**Comment by durack1** [comment]
@jbusecke you're right, data that is being published most recently using latest versions of the https://github.com/ESGF/esg-publisher are in fact being validated against the CMIP6_CVs registered content, but this was not the case in the early stages of project replication (~2018), @sashakames can describe timelines better than I can (he's the main `esg-publisher` developer).

So in summary, in most cases your template above will work and if cases fail it would be useful to know about them.

Feel free to close this issue when you have the intel that you need. As an FYI, this template is being pushed forward for use in https://github.com/WCRP-CMIP/CMIP6Plus_CVs and is also planned for use, even more rigorously in CMIP7 (yet to be defined formally).

**Comment by durack1** [comment]
@jbusecke I'll keep this open for the remainder of the week and close it if there are no more queries. I think you have what you need, no?

**Comment by jbusecke** [comment]
I got everything I need (implemented upstream check as part of my CI [here](https://github.com/jbusecke/pangeo-forge-esgf/pull/43)). Thanks for the quick turnaround.
