### ISSUE TITLE
institution_id registration of CNRM-CERFACS

### ISSUE THREAD

**Issue by senesis** [WCRP-CMIP/CMIP6_CVs#129]
institution_id = CNRM-CERFACS
    institution = ""CNRM (Centre National de Recherches Meteorologiques, Meteo-France, Toulouse, France) and CERFACS (Centre Europeen de Recherches et de Formation Avancee en Calcul Scientifique, Toulouse, France)"

**Comment by durack1** [comment]
@senesis I have added in a postal code below, if you're happy with this amendment I will update our institution_id list and close this issue:
```
institution_id = CNRM-CERFACS
institution = "CNRM (Centre National de Recherches Meteorologiques, Meteo-France, Toulouse 31057, France), CERFACS (Centre Europeen de Recherches et de Formation Avancee en Calcul Scientifique, Toulouse 31057, France)"
```

**Comment by senesis** [comment]
That's fine, thanks. 
S 

----- Mail original -----

| De: "Paul J. Durack" <notifications@github.com>
| À: "WCRP-CMIP/CMIP6_CVs" <CMIP6_CVs@noreply.github.com>
| Cc: "Stéphane Sénési - work" <stephane.senesi@meteo.fr>, "Mention"
| <mention@noreply.github.com>
| Envoyé: Lundi 7 Novembre 2016 20:00:20
| Objet: Re: [WCRP-CMIP/CMIP6_CVs] institution_id registration of CNRM-CERFACS
| (#129)

| @senesis I have added in a postal code below, if you're happy with this
| amendment I will update our institution_id list and close this issue:
| institution_id = CNRM-CERFACS
| institution = "CNRM (Centre National de Recherches Meteorologiques,
| Meteo-France, Toulouse 31057, France), CERFACS (Centre Europeen de
| Recherches et de Formation Avancee en Calcul Scientifique, Toulouse 31057,
| France)"

| —
| You are receiving this because you were mentioned.
| Reply to this email directly, view it on GitHub , or mute the thread .

-- 
----- Météo-France ----- 
SENESI STEPHANE 
CNRM/GMGEC/ASTER 
stephane.senesi@meteo.fr 
Fixe : +33 561079931
