### ISSUE TITLE
grid_label confirm entries with latest global_atts document

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#130]
As noted by @taylor13 the `gm` entry may need to be checked. Also `Antarctica` and `Greenland`. - see the working [google doc](https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit)

**Comment by durack1** [comment]
@taylor13 is this resolved, the current entries:
```
{
    "grid_label":[
        "gm",
        "gn",
        "gnz",
        "gr",
        "gr1",
        "gr1z",
        "gr2",
        "gr2z",
        "gr3",
        "gr3z",
        "gr4",
        "gr4z",
        "gr5",
        "gr5z",
        "gr6",
        "gr6z",
        "gr7",
        "gr7z",
        "gr8",
        "gr8z",
        "gr9",
        "gr9z",
        "grz"
    ],
    "version_metadata":{
        "author":"Paul J. Durack <durack1@llnl.gov>",
        "creation_date":"Wed Nov 16 10:14:11 2016 -0800",
        "institution_id":"PCMDI",
        "latest_tag_point":"None",
        "note":"Revise AerChemMIP experiment model configurations",
        "previous_commit":"4a9b0aaa2d1bc45564f2aa73dc261f440c0bc265"
    }
}
```
Look good to me (although the Antarctica/Greenland entries may be missing).. When compared to the [working doc](https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit)

**Comment by taylor13** [comment]
To be consistent with version 6.1.0 of the global attributes document (https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit), we need to add two whole sets of gn, gr, and gr[i], but with an "a" suffix (for antarctica) and "g" suffix for greenland.  For example, "gna", "gng", "gra", grg", "gr1a", "gr1g",  etc.

**Comment by durack1** [comment]
@taylor13 would it be suitable to subset these into separate lists? @dnadeau4 pinging you here

**Comment by durack1** [comment]
@taylor13 so we need:
```
gna, gn1a, gn2a, gn3a, gna4, gn5a, gn6a, gn7a, gn8a, gn9a
gng, gn[1-9]g
gra, gr[1-9]a
grg, gr[1-9]g
```

**Comment by taylor13** [comment]
No.  Only need:
gna
gng
gra, gr[1-9]a
grg, gr[1-9]g

**Comment by durack1** [comment]
@taylor13 is this correct (in particular `gm` is my query):
```
grid_label = [
    'gm',
    'gn',
    'gna',
    'gng',
    'gnz',
    'gr',
    'gr1',
    'gr1a',
    'gr1g',
    'gr1z',
    'gr2',
    'gr2a',
    'gr2g',
    'gr2z',
    'gr3',
    'gr3a',
    'gr3g',
    'gr3z',
    'gr4',
    'gr4a',
    'gr4g',
    'gr4z',
    'gr5',
    'gr5a',
    'gr5g',
    'gr5z',
    'gr6',
    'gr6a',
    'gr6g',
    'gr6z',
    'gr7',
    'gr7a',
    'gr7g',
    'gr7z',
    'gr8',
    'gr8a',
    'gr8g',
    'gr8z',
    'gr9',
    'gr9a',
    'gr9g',
    'gr9z',
    'gra',
    'grg',
    'grz'
]
```
