### ISSUE TITLE
source_type confirm entries with latest global_atts document

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#131]
As noted by @taylor13 the following changes are required:
- Replace all occurrences of `BGCM` or `BGM` -> `BGC`
- Replace all occurrences of `ESM` -> `AOGCM, BGC`

For more information see the working [google doc - v6.0.1](https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit)

**Comment by taylor13** [comment]
These changes were the outcome of a discussion mainly between Pierre Friedlingstein and Karl Taylor.  Here is why they are necessary:

Hi Pierre,

[Can't explain this very clearly, I'm afraid;  anyway please respond to the last paragraph if you can.]

Thanks for pointing out the potential confusion around referring to ESM's as either ESM or AOGCM + BGCM (depending on whether emission-driven or concentration-driven) in the CMIP6 data archive.

You suggested they both should be called ESM's, but this would require more complex logic in classifying  "model components" as being either "required" or "optional" in our experiment summary (see below).  The purpose of the summary table (where these source_types appear) is for use in checking that metadata have been correctly recorded in files and in publication on ESGF.  The metadata will be used in ESGF searches.  We want users to be able to limit a search to certain model configurations (e.g., AGCM, OGCM, AOGCM).

For each MIP experiment the summary will list which components are required and which are optional.  For example, in AMIP simulations the required component is: AGCM, but one may optionally also include "CHEM" and/or "AER".  I propose that we isolate identification of the biogeochemical model component (BGCM) from the AGCM and OGCM components, and for emissions-driven experiments, we would indicate this by required_components="AOGCM BGCM", whereas in concentration-driven experiments we would designate "required_components="AOGCM", optional_components="BGCM".

To be sure this table will just indicate the experiment specifications (which components are required and which are optional).  When you prepare your model output, one of the global attributes you must define is "source_type".  This should list all the components you actually included when configuring your model. If you run the historical experiment with an ESM model in  either emissions-driven mode or concentration-driven mode, you would set source_type="AOGCM BGCM" (and you might also include in source_type "AER", "CHEM" or other optional components).  A model that performs a historical simulation but doesn't include the carbon cycle would have source_type="AOGCM".

Anyway I don't think there will be any confusion if we invariably refer to a coupled model configuration that includes a carbon cycle model as "AOGCM BGCM" (both for emissions-driven and concentration-driven experiments).  Do you agree?

thanks,
Karl 

Hi Karl,
Yes I fully agree, that's the way to go, no need for the ESM which is not uniquely defined.

It's also much more consistent with the existing AER and CHEM. These 3 suffixes refer to additional components to the physical model.

One minor suggestion: name it BGC, not BGCM, as you have AER and CHEM, not AERM and CHEMM.

Cheers
Pierre
