### ISSUE TITLE
table_id missing or wrong

### ISSUE THREAD

**Issue by dnadeau4** [WCRP-CMIP/CMIP6_CVs#132]
Please replace or add `"day"` in your list for CMOR.    
https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_table_id.json#L7

**Comment by durack1** [comment]
@dnadeau4 this is a duplicate of #128 - resolving #128 will also solve this. Is it holding up your progress with `CMOR 3.2.x`?

@taylor13 will likely need your input here

**Comment by durack1** [comment]
Closing this as a duplicate of #128 - @dnadeau4 please response to the open question in #128 and we should be able to get a short term workaround until the `table_id` values are finalised
