### ISSUE TITLE
CMIP6_license.json

### ISSUE THREAD

**Issue by dnadeau4** [WCRP-CMIP/CMIP6_CVs#133]
This is the template I am using for CMOR.  Should we update your license file file or just put in my `regular expression`????

* ***"CMIP6 model data produced by .\* is licensed under a Creative Commons Attribution \"Share Alike\" 4.0 International License (http://creativecommons.org/licenses/by/4.0/). Use of the data should be acknowledged following guidelines found at.\*Permissions beyond the scope of this license may be available at.\* Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in data files). The data producers and data providers make no warranty, either express or implied, including, but not limited to, warranties of merchantability and fitness for a particular purpose. All liabilities arising from the supply of the information (including any liability arising in negligence) are excluded to the fullest extent permitted by law."***

* [CMIP6_license.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_license.json#L3)

**Comment by dnadeau4** [comment]
`.*` in the expression means:  **followed by zero or many characters.**

**Comment by durack1** [comment]
@taylor13 is there a refined and "final" version of the license available now?

**Comment by dnadeau4** [comment]
:+1:

**Comment by durack1** [comment]
@dnadeau4 not sure with the `0.beta.41` release this morning if anything has changed.. Probably worth checking..

**Comment by MartinaSt** [comment]
@taylor13 @dnadeau4 : Somehow the obligation to cite data got lost. If I look into the global attributes document it states "...Use of the data should be acknowledged following guidelines found at https://pcmdi.llnl.gov/home/CMIP6/citation.html...." Either such a link to the terms of use or a sentence like "Individuals using the data should include data citations in reference lists." needs to be part of this extended license statement.

**Comment by dnadeau4** [comment]
@MartinaSt I can put that missing section back,  I had difficulty matching the URLs.  Using a "extended" regular expression made it way more simple.  

* Note: this string is for the "Control Vocabulary" file for CMIP6.   If the user defined license does not match this string, people won't be able to publish CMIP6 data into ESGF.

**Comment by taylor13** [comment]
@MartinaSt @dnadeau4 :  I asked Martin to hold off on updating the license because the WGCM was discussing some changes.  We'll make sure something like what was in there originally gets included.

**Comment by MartinaSt** [comment]
@taylor13 @dnadeau4  Thanks Karl, thanks Denis !

**Comment by durack1** [comment]
@dnadeau4 @taylor13 I recall seeing a thread on this over the last week.. Is this resolved? Do we have a final license spiel to be committed so we can close this

**Comment by taylor13** [comment]
@dnadeau4 @durack1 Still working on this.  Look for something in a few days.

**Comment by durack1** [comment]
@taylor13 I just took a peek at [License spiel](https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit#bookmark=id.yee3uo6hvz8m)

Do you want me to create https://pcmdi.llnl.gov/home/CMIP6/citation.html? And what should be on it?

**Comment by taylor13** [comment]
@dnadeau4 @durack1 Here is the "license statement":
------------------
CMIP6 model data produced by <Your Centre Name> is licensed under a Creative Commons Attribution “[NonCommercial] Share Alike” 4.0 International License (http://creativecommons.org/licenses/by/4.0/). Use of the data should be acknowledged following guidelines found at https://pcmdi.llnl.gov/home/CMIP6/citation.html.   Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in this file)[ and at <some URL maintained by modeling group>].  The data producers and data providers make no warranty, either express or implied, including, but not limited to, warranties of merchantability and fitness for a particular purpose. All liabilities arising from the supply of the information (including any liability arising in negligence) are excluded to the fullest extent permitted by law.
-------------------
text in [] is optional
<some text> should be replaced by text provided by modeling groups, which can't be checked by CMOR (or "PrePARE").
We need to move the document at https://goo.gl/955nnG to https://pcmdi.llnl.gov/home/CMIP6/citation.html before closing this ticket.

**Comment by MartinaSt** [comment]
We would replace "Use of the data should be acknowledged" by the stronger "Use of the data has to be acknowledged".

**Comment by durack1** [comment]
@taylor13 14:51 PM 21 December 2016

Here is the new wording for the license:

"CMIP6 model data produced by is licensed under a Creative Commons Attribution "[*] Share Alike" 4.0 International License (http://creativecommons.org/licenses/by/4.0/). Use of the data should be acknowledged following guidelines found at https://pcmdi.llnl.gov/home/CMIP6/CitationRequirements6-0.html. Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in data files)[and at ]. The data producers and data providers make no warranty, either express or implied, including, but not limited to, warranties of merchantability and fitness for a particular purpose. All liabilities arising from the supply of the information (including any liability arising in negligence) are excluded to the fullest extent permitted by law."

**Comment by durack1** [comment]
@taylor13 above there is a missing entry..

```
Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in data files)[and at ]. The data
```
Seems to me like there are some bits missing, want to revise and update in this thread

**Comment by durack1** [comment]
From @taylor13 (this was an issue with github markdown dealing with \<\> characters)

“CMIP6 model data produced by \<Your Centre Name\> is licensed under a Creative Commons Attribution “[NonCommercial] Share Alike” 4.0 International License (http://creativecommons.org/licenses/by/4.0/). Use of the data should be acknowledged following guidelines found at https://pcmdi.llnl.gov/home/CMIP6/CitationRequirements6-0.html. Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in this file)[ and at \<some URL maintained by modeling group\>]. The data producers and data providers make no warranty, either express or implied, including, but not limited to, warranties of merchantability and fitness for a particular purpose. All liabilities arising from the supply of the information (including any liability arising in negligence) are excluded to the fullest extent permitted by law.”

**Comment by MartinaSt** [comment]
@taylor13 : Karl, haven't we agreed during the last WIP telco on changing the phrase "Use of the data should be acknowledged" to the stronger "Use of the data **has to be** acknowledged"?

**Comment by durack1** [comment]
@taylor13 @MartinaSt the revised license with text `Use of the data has to be acknowledged..` is now updated in the file [CMIP6_license.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_license.json)

**Comment by MartinaSt** [comment]
@durack1 @taylor13 thanks for the update of the license. If I want to point a user to the current Citation Requirements, could I then use a non-versioned URL, e.g. https://pcmdi.llnl.gov/home/CMIP6/CitationRequirements.html ? On the citation landing page I need to refer to the current citation requirements as information for a potential data user.

**Comment by taylor13** [comment]
"has to be" is awkward.  "must be" is better.  The reason I delayed in changing the phrase was that usually if something that "must be" done isn't done, there are consequences (penalties).  In the case of failing to cite data, I don't thing those who are remiss will suffer and penalties, so it is kind of an empty threat.  I hate empty threats, so I used the phrase "should be" (implying an obligation).

**Comment by durack1** [comment]
@taylor13 @MartinaSt I will change to whatever you consider is appropriate..

**Comment by MartinaSt** [comment]
@durack1 @taylor13 Thanks for putting the Citation and Acknowledgement web page online. May I remind you of my request about referring to its latest version from the citation landing page?
"If I want to point a user to the current Citation Requirements, could I then use a non-versioned URL, e.g. https://pcmdi.llnl.gov/home/CMIP6/CitationRequirements.html ? On the citation landing page I need to refer to the current citation requirements as information for a potential data user."
So my question is: Which persistent link to the current citation requirements do I use on the DOI landing page?

**Comment by durack1** [comment]
@taylor13 this could be solved with a symlink, so the link above ..CitationRequirements.html then points to the latest version.. Do you want me to implement that?

**Comment by taylor13** [comment]
@durack1 @MartinaSt I'm not sure how to handle this.  The license that applies to a dataset is the one that is in the files containing the data, where it appears as a global attribute.  So if we ever change the license (which I hope we don't), users should not necessarily assume the "latest" license is the correct license.  Therefore, I don't think we should leave off the version number from any URL's.   Can you just indicate that the official licensing agreement appears in the file?

**Comment by MartinaSt** [comment]
@taylor13 @durack1 The citation is on a coarse granularity. Thus, if the license get changed the data citation would have multiple license statements in the dataset headers depending on the date of dataset publication. But the page about proper citation and acknowledgement contains the terms of use. Thus it is the information to data users what they should do. That is an important information for the DOI landing page. What I could do instead is link to the data citation guidelines directly (http://bit.ly/2gBCuqM ), which would restrict the terms of use to the pure citation guidelines.

**Comment by taylor13** [comment]
@MartinaSt @durack1 -- On your DOI landing page, I would provide a rather short statement that Users must abide by:
1) the "terms-of-use" for CMIP6 data, and (with "terms-of-use" linked to https://pcmdi.llnl.gov/home/CMIP6/CitationRequirements6-0.html).
2) any license restrictions appearing in the global attribute named "license" found in every file containing CMIP6 data.  
To simplify things for users, I think we should add anything from your data citation document http://bit.ly/2gBCuqM that isn't already in https://pcmdi.llnl.gov/home/CMIP6/CitationRequirements6-0.html and have only a single document containing all the terms of use.
Would that be o.ik.?

**Comment by MartinaSt** [comment]
@taylor13 @durack1 Yes, a short statement with a reference to the CMIP6 terms of use page is the best. From the data citation point of view, the landing page should include an information on how to cite (citation string), an information about the evolving nature of the data, the reference to the CC-BY license as part of the metadata, and a terms of use statement. 
I suggest the following text on the DOI landing page:

> CMIP6 model data is evolving in the sense that datasets are changed and added as new versions. The author list and the title are not final, either. Cite this data collection including the latest dataset version or if not available the download date as "creators. publication year. title. version: YYYYMMDD. publisher. doi" according to the Data Citation Guidelines (http://bit.ly/2gBCuqM ).
> Individuals using the data must abide to the terms of use for CMIP6 data (https://pcmdi.llnl.gov/home/CMIP6/CitationRequirements6-0.html ). Details on any license restrictions is recorded as a global attribute in the files.

The remaining open question is: What do we do in case the Terms of Use change. The user should abide to the current terms of use. So, could we take up Pauls suggestion and use https://pcmdi.llnl.gov/home/CMIP6/CitationRequirements.html instead of the specific version I used above with a symlink to the current version?

**Comment by taylor13** [comment]
This ticket is really for Martina's site, but I want to make sure she rewords things consistent with us.  Reopened to serve as a reminder.

**Comment by MartinaSt** [comment]
@taylor13 @durack1 I think we can close this ticket on the license: The version-independent link to the terms of use is now: https://pcmdi.llnl.gov/CMIP6/TermsOfUse . I refer to the terms of use on the landing page as: 
`Individuals using the data must abide to the terms of use for CMIP6 data (https://pcmdi.llnl.gov/CMIP6/TermsOfUse ). Details on any license restrictions are recorded as global attributes in the files.`

**Comment by durack1** [comment]
@MartinaSt thanks for the update.. As you're pointing to the now live PCMDI site I will close this issue
