### ISSUE TITLE
experiment_id -- check parent expt. and parent activity

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#137]
experiment_id:  I don't have time until after Dec. 1 to do this, but just a reminder that we need to check the parent_experiment and parent_activity for all experiments. Some of them might be wrong.

**Comment by durack1** [comment]
See https://github.com/WCRP-CMIP/CMIP6_CVs/commit/1988f00780dab4a6d7438977faeb08f8d6870357 for `xlsx` read code
