### ISSUE TITLE
Remove coordinate, formula_terms and grids

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#139]
@dnadeau4 currently I am sourcing the [`CMIP6_coordinate.json`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/src/writeJson.py#L161) and the [`CMIP6_formula_terms.json`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/src/writeJson.py#L213) contents from the `PCMDI/cmip6-cmor-tables/master/Tables/CMIP6_Amon.json` files. It would be better if the master source of this information was centralised into this (CMIP6_CVs) repo.

Can you provide the most up-to-date contents for each of these (I assume these won't change) and then the master source for this information will be the CMIP6_CVs repo.

Also the [`CMIP6_grids.json`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/src/writeJson.py#L252) file is also sourced from the above (`PCMDI/cmip6-cmor-tables`) - is this stable, and if so, we should centralize this also.

**Comment by dnadeau4** [comment]
@durack1  I created the new table without validate that they are attached to an experiment or a MIP such as GeoMIP, DECK and so on.   Although I disagree with this method, I verify my cf3hr table and it is now consistent with [Martin's web site.](  http://clipc-services.ceda.ac.uk/dreq/u/MIPtable::cf3hr.html )

cf3hr are variables are not linked properly in his XML database.

**Comment by dnadeau4** [comment]
Here are the most up-to-date files as requested.  CMIP6_grids.json is a stable version.

*   [CMIP6_coordinate.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/createalltables/Tables/CMIP6_coordinate.json)
*  [CMIP6_formula_terms.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/createalltables/Tables/CMIP6_formula_terms.json)

**Comment by durack1** [comment]
@dnadeau4 perfect, I'll pull these across tomorrow

**Comment by durack1** [comment]
@dnadeau4 should I also pull across [`CMIP6_grids.json`](https://github.com/PCMDI/cmip6-cmor-tables/blob/createalltables/Tables/CMIP6_grids.json)?

**Comment by dnadeau4** [comment]
Yes it won't change anymore.  I got everything I need in there.

**Comment by durack1** [comment]
As discussed with @taylor13 and @dnadeau4 the information contained within these existing files are not CVs, and should rather be dealt with within the [PCMDI/cmip6-cmor-tables](https://github.com/PCMDI/cmip6-cmor-tables)
