### ISSUE TITLE
grid_resolution:  change name and add 3 new resolution options

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#141]
grid_resolution:  This has been renamed to "nominal_resolution".  Change the name in the file and also the file name.  Also include 3 additional resolutions:

"0.5 km"
"1 km"
"2.5 km"

**Comment by durack1** [comment]
@dnadeau4 are you happy for this direct change? I can implement fairly quickly

**Comment by durack1** [comment]
@dnadeau4 I note that "happy" was a poor choice of words, maybe I should have said "does this change do irreparable damage to your CMOR psyche?"
