### ISSUE TITLE
experiment_id ISMIP experiment names

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#168]
Dear Karl,
I am working on the proofs of the ISMIP6 GMD paper (which are due late next week), and will remove the name for the extension scenario. However, I don’t recall the decision for (or can’t find it in my emails) what is the best way to deal with 1pctCO2 vs 1pctCO2to4x. As you can see in my Table 2, I am using the names  1pctCO2to4x-withism,  ism-1pctCO2to4x-self and ism-1pctCO2to4x-std, but how to best refer in the paper for example in Table 1 or in the main text p6 or p10 (and record in the CMIP archive) the 1pctCO2to4x from the AOGCM taking part in ISMIP6? (see also email below about why we need to record it).

Many thanks,
Sophie

On Oct 25, 2016, at 9:29 PM, Nowicki, Sophie (GSFC-6150) wrote:

Dear Karl,
>  
>> 1) I need to add 3 more experiments that are only applicate to standalone ice sheet models (the last 3 in the attached table from our ISMIP6 GMD paper). For consistency with the other names that you and I worked on, I assume that I need to change the  names so that it follows ism-XXX-std (i.e.: ctrl will be ism-ctrl-std, asmb will be ism-asmb-std etc)?
> yes, these should have the "ism" prefix, and if they are driven by a standard dataset, then "std" is appropriate. 
Great, I will make a new “issue” and create experiment_id.json file

>> 2) the climate models that take part in the ISMIP6 coupled experiments need to do the modified version of the DECK 1pctCO2, which we named 1pctCO2to4x. Since it is not on the current list *CMIP6_experiment_id.html,  I wanted to check with you that I should put a JSON request.
> In your GMD paper isn't this experiment named "1pctCO2-withism"?  And there is an entry already in the CMIP6_experiment_id.json file named " 1pctCO2to4x-withism" .    I slightly prefer the name with "to4x", but either of these would do.  Why is there also a need for "1pcCO2to4x”? 
Indeed, following our discussions, I changed in the revision of the GMD paper 1pctCO2-withism to 1pctCO2to4x-withism, ism-1pctCO2-self to ism-1pctCO2to4x-self, and ism-1pctCO2-std to ism-1pctCO2to4x-std. I had checked that there are CMIP6_experiment_id.json files  for the correct names (the ones that contain “to4x”), but I could not find one for 1pctCO2to4x. 

We need the climate centers that are taking part in the ISMIP6 “withism" experiments to also run 1pctCO2to4x (since the definition of 1pctCO2 has changed compared to CMIP5) because the output of 1pctCO2to4x is used as forcing for ism-1pctCO2to4x-self, and these three experiments (1pctCO2to4x, 1pctCO2to4x-withism, and ism-1pctCO2to4x-self) will be used to explore feedbacks.

So I was trying to understand whether I need to put a 1pctCO2to4x experiment_id.json file “issue” request, but I am more than happy not to have to do so, and I can probably change  the name 1pctCO2to4x back to 1pctCO2 in our GMD paper (of course only when I refer to the AOGCM experiment)

I will simply follow what you advise.

Many thanks,

Sophie

**Comment by taylor13** [comment]
Here are some additional correspondences on this:
10/25/16:

I looked at the "Table 2" you attached in your email and it looks to me that your names are consistent with what is currently in the experiment_id.json CV except for:

1)  You have included experiments named "ssp585ext_withism, ism-ssp585ext-self, and ism-ssp585ext-std.  For CMIP6 we've decided that standard extensions of a scenario doesn't need a new name, so the "ext" should be removed from these.

2)  after much discussion the PMIP folks decided to rename "lig" "lig127k", so "ism-lig-std" should be renamed "ism-lig127k-std".

3)  The last 3 experiments should be renamed as we've already discussed and they should be submitted as new additions to the experiment_id.json (please raise an "issue").

**Comment by taylor13** [comment]
Hi Sophie,

I have looked again at your Table 2 (of the GMD draft) and also at the experiment_id.json file (see also http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html ).  The new variant of the 1pctCO2 run called for by ISMIP6 is to increase CO2 at 1%/yr until quadrupling (which occurs at year 140), then hold constant for at least another 210 years.   In the case of what you call "1pctCO2to4x", modeling groups will have already done their 1pctCO2, and they can simply branch from that run at year 140, holding CO2 constant and run for 210 years.  So you, really are proposing a run that is initialized from year 140 of the 1pctCO2 run and run for 210 years with CO2 concentration held fixed.  This differs from your other 1pctCO2to4x runs (e.g., "1pctCO2to4x-withism"), which will include both the transient CO2 portion *and* the constant 4xCO2 portion.  Consequently, I think we should name your constant 4xCO2 simulation something other than 1pctCO2to4x.  How about "1pctCO2-4xext"?  Or can you think of something better?  Those analyzing ISMIP6 runs will have to concatenate the output from the first 140 years of the standard 1pctCO2 run with the "1pctCO2-4xext" run to get what they need (i.e., a 1pctCO2to4x run).  

If this is agreeable, then we need to add the following experiment to experiment_id.json: 
    "experiment_id":{
        "1pctCO2-4xext":{
            "activity_id":[
                "ISMIP6"
            ],
            "additional_allowed_model_components":[
                "AER",
                "CHEM",
                "BGC"
            ],
            "description":"branched from 1pctCO2 run at year 140 and run with CO2 fixed at 4x pre-industrial concentration",
            "end_year":"",
            "experiment":"extension from year 140 of 1pctCO2 with 4xCO2",
            "min_number_yrs_per_sim":"210",
            "parent_activity_id":[
                "CMIP"
            ],
            "parent_experiment_id":[
                "1pctCO2"
            ],
            "required_model_components":[
                "AOGCM"
            ],
            "start_year":"",
            "sub_experiment":"none",
            "sub_experiment_id":"none",
            "tier":"1 ???"

Please check the tier and other metadata above.

Also, as you know, several of the experiment names in your tables 1 and 2 still need correction.  Make sure the names are consistent with the .json file.

especially check:  cntrl, asmb, bsmb (which all should have a "ism-" prefix and a "-std" suffix)
and ism-lig-std, which should be ism-lig127k-std.   double check I didn't miss something by comparing with http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html  (you can group all your experiments together by clicking on the "activity_id" tab column).
thanks,
Karl

**Comment by durack1** [comment]
@sophienowicki @taylor13 are we done with this issue, or is the "how to show experiment extensions are different tiers" question still unanswered?

**Comment by sophienowicki** [comment]
@durack1 @taylor13 hello, if possible, I would still like to double check that it is OK the way that I describe the differ Tiers in my Table (see file) for the GMD paper, and that it does not conflict with the .json experiment_id file for the ssp585-withism for example that sets the min_number_yrs_per_sim to 286 years and start and end date 2015 to 2300 with tier 2. or is there a better way to do this. Many thanks, sophie
[Table1&2.pdf](https://github.com/WCRP-CMIP/CMIP6_CVs/files/639834/Table1.2.pdf)

**Comment by durack1** [comment]
@taylor13 this likely requires some input from you

**Comment by taylor13** [comment]
@sophienowicki I think your GMD table is clear, which is the important thing.  The numbers in the .json file are used to estimate data volumes, but otherwise ignored as far as I know, so it may not be terribly critical that they be absolutely correct.  Here's what I propose for the json file:

For ssp585-withism (and ism-ssp585-self and ism-ssp585-std), which get extended but with lower priority, I think we should set min number of years as the number in the higher priority period (i.e. 85).  For the end date, we can put 2300, which includes the low priority years.  

For a few experiments, the json file doesn't record the min. no. of years found in your GMD paper.  Are the following numbers in your Table 2 correct?  
piControl-withism - 500
ism-piControl-self  - 500
ism-pdControl-std - 100
ism-lig127k-std - 20,000

If so, I'll correct the json file.

Also, I'm sure its in your paper, but could you tell me why there is no min. no. years for ism-amip-std and ism-historical-std experiments?

**Comment by sophienowicki** [comment]
Hello Karl,

Sorry for not replying sooner.

I like your advise for dealing with ssp585-withism, ism-ssp585-self, and ism-ssp585-std. The numbers (for the min. no of years) in the Table 2 and your email are correct (but I don’t know what the implication are for the data volume, since the ism* runs are standalone ice sheet models only).

For ism-amid-std and ism-historical-std, we could not say what the min number of years should be, because some ice sheet models may not be able to do the full length of the runs mainly because of how standalone ice sheet models currently initialize their simulations: a large groups will initialize using data assimilation, and so the earliest they can start depends on the timing of the observational data that is used for assimilation. ISMIP6 is pushing our community to try to develop new methods, so that these models can one day do a historical run starting in 1850, but right now the earliest that many of these models can do is ~ 1990-2000.

Many thanks,

Sophie

On Jan 18, 2017, at 8:12 PM, taylor13 <notifications@github.com<mailto:notifications@github.com>> wrote:


@sophienowicki<https://github.com/sophienowicki> I think your GMD table is clear, which is the important thing. The numbers in the .json file are used to estimate data volumes, but otherwise ignored as far as I know, so it may not be terribly critical that they be absolutely correct. Here's what I propose for the json file:

For ssp585-withism (and ism-ssp585-self and ism-ssp585-std), which get extended but with lower priority, I think we should set min number of years as the number in the higher priority period (i.e. 85). For the end date, we can put 2300, which includes the low priority years.

For a few experiments, the json file doesn't record the min. no. of years found in your GMD paper. Are the following numbers in your Table 2 correct?
piControl-withism - 500
ism-piControl-self - 500
ism-pdControl-std - 100
ism-lig127k-std - 20,000

If so, I'll correct the json file.

Also, I'm sure its in your paper, but could you tell me why there is no min. no. years for ism-amip-std and ism-historical-std experiments?

**Comment by durack1** [comment]
@sophienowicki take a peek at [CMIP6_experiment_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html) and check the values following the revisions outlined above. If you require any more tweaks either reopen this or create a new issue

**Comment by cmip6** [comment]
thanks, Sophie.
Karl
