### ISSUE TITLE
experiment_id ssp370 activity_id

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#169]
experiment_id ssp370 activity_id:  

 ScenarioMIP and AerChemMIP co-sponsor ssp370, but I think that in the DRS and directory structure ScnearioMIP should appear, so the order should be changed to "ScenarioMIP AerChemMIP"  (currently they are reversed).

Karl

**Comment by claudiatebaldi** [comment]
Fine with me, Karl, thank you.

**Comment by wjcollins** [comment]
Certainly ScenarioMIP should be the main sponsor of ssp370.

**Comment by taylor13** [comment]
This change can be made because both interested parties have agreed.
