### ISSUE TITLE
frequency_id -- add '1hr'

### ISSUE THREAD

**Issue by martinjuckes** [WCRP-CMIP/CMIP6_CVs#178]
Please add a frequncy entry for hourly data. In the data request I am currently using '1hr' for hourly data.

**Comment by durack1** [comment]
@martinjuckes is there a new `table_id` `1hr` that goes with this? It seems we don't have such an entry in [`miptable 01.beta.45`](http://clipc-services.ceda.ac.uk/dreq/index/miptable.html)
