### ISSUE TITLE
source_id registration of HadGEM3 and UKESM1

### ISSUE THREAD

**Issue by alistairsellar** [WCRP-CMIP/CMIP6_CVs#184]
HadGEM3-GC31-LL:
    aerosol = UKCA-GLOMAP-mode
    atmosphere = MetUM-HadGEM3-GA7.1 (192 x 144 N96; 85 levels; top level 85km)    
    atmospheric_chemistry = None
    institution_id = MOHC
    label = HadGEM3-GC31-LL
    label_extended = HadGEM3-GC3.1-N96ORCA1
    land_ice = None
    land_surface = JULES-HadGEM3-GL7.1
    ocean = NEMO-HadGEM3-GO6.0 (ORCA1 tripolar primarily 1 deg latitude/longitude with meridional refinement down to 1/3 degree in the tropics; 75 levels; top grid cell 0-1m)    
    ocean_biogeochemistry = None
    release_year = 2016
    sea_ice = CICE-HadGEM3-GSI8 (ORCA1 tripolar primarily 1 deg latitude/longitude)
    source_id = HadGEM3-GC31-LL
    
HadGEM3-GC31-MM:
    aerosol = UKCA-GLOMAP-mode
    atmosphere = MetUM-HadGEM3-GA7.1 (432 x 324 N216; 85 levels; top level 85km)    
    atmospheric_chemistry = None
    institution_id = MOHC
    label = HadGEM3-GC31-MM
    label_extended = HadGEM3-GC3.1-N216ORCA025
    land_ice = None
    land_surface = JULES-HadGEM3-GL7.1
    ocean = NEMO-HadGEM3-GO6.0 (ORCA025 tripolar primarily 0.25 deg latitude/longitude; 75 levels; top grid cell 0-1m)    
    ocean_biogeochemistry = None
    release_year = 2016
    sea_ice = CICE-HadGEM3-GSI8 (ORCA025 tripolar primarily 0.25 deg latitude/longitude)
    source_id = HadGEM3-GC31-MM
    
HadGEM3-GC31-HM:
    aerosol = UKCA-GLOMAP-mode
    atmosphere = MetUM-HadGEM3-GA7.1 (1024 x 768 N512; 85 levels; top level 85km)    
    atmospheric_chemistry = None
    institution_id = MOHC
    label = HadGEM3-GC31-HM
    label_extended = HadGEM3-GC3.1-N512ORCA025
    land_ice = None
    land_surface = JULES-HadGEM3-GL7.1
    ocean = NEMO-HadGEM3-GO6.0 (ORCA025 tripolar primarily 0.25 deg latitude/longitude; 75 levels; top grid cell 0-1m)    
    ocean_biogeochemistry = None
    release_year = 2016
    sea_ice = CICE-HadGEM3-GSI8 (ORCA025 tripolar primarily 0.25 deg latitude/longitude)
    source_id = HadGEM3-GC31-HM
    
HadGEM3-GC31-HH:
    aerosol = UKCA-GLOMAP-mode
    atmosphere = MetUM-HadGEM3-GA7.1 (1024 x 768 N512; 85 levels; top level 85km)    
    atmospheric_chemistry = None
    institution_id = MOHC
    label = HadGEM3-GC31-HH
    label_extended = HadGEM3-GC3.1-N512ORCA12
    land_ice = None
    land_surface = JULES-HadGEM3-GL7.1
    ocean = NEMO-HadGEM3-GO6.0 (ORCA12 tripolar primarily 1/12 deg latitude/longitude; 75 levels; top grid cell 0-1m)    
    ocean_biogeochemistry = None
    release_year = 2016
    sea_ice = CICE-HadGEM3-GSI8 (ORCA12 tripolar primarily 1/12 deg latitude/longitude)
    source_id = HadGEM3-GC31-HH

UKESM1-0-LL:
    aerosol = UKCA-GLOMAP-mode
    atmosphere = MetUM-HadGEM3-GA7.1 (192 x 144 N96; 85 levels; top level 85km)    
    atmospheric_chemistry = UKCA-StratTrop
    institution_id = MOHC, NERC
    label = UKESM1.0-LL
    label_extended = UKESM1.0-N96ORCA1
    land_ice = BISICLES (only active in ISMIP experiments)
    land_surface = JULES-HadGEM3-GL7.1
    ocean = NEMO-HadGEM3-GO6.0 (ORCA1 tripolar primarily 1 deg latitude/longitude with meridional refinement down to 1/3 degree in the tropics; 75 levels; top grid cell 0-1m)    
    ocean_biogeochemistry = MEDUSA2
    release_year = 2017
    sea_ice = CICE-HadGEM3-GSI8 (ORCA1 tripolar primarily 1 deg latitude/longitude)
    source_id = UKESM1-0-LL
    
UKESM1-0-MMh:
    aerosol = UKCA-GLOMAP-mode (horizontal resolution degraded relative to that used for atmosphere physics)
    atmosphere = MetUM-HadGEM3-GA7.1 (432 x 324 N216; 85 levels; top level 85km)    
    atmospheric_chemistry = UKCA-StratTrop (horizontal resolution degraded relative to that used for atmosphere physics)
    institution_id = MOHC, NERC
    label = UKESM1.0-MMh
    label_extended = UKESM1.0-N216ORCA025hybrid
    land_ice = BISICLES (only active in ISMIP experiments)
    land_surface = JULES-HadGEM3-GL7.1
    ocean = NEMO-HadGEM3-GO6.0 (ORCA025 tripolar primarily 0.25 deg latitude/longitude; 75 levels; top grid cell 0-1m)    
    ocean_biogeochemistry = MEDUSA2 (horizontal resolution degraded relative to that used for ocean physics)
    release_year = 2018
    sea_ice = CICE-HadGEM3-GSI8 (ORCA025 tripolar primarily 0.25 deg latitude/longitude)
    source_id = UKESM1-0-MMh

**Comment by durack1** [comment]
@alistairsellar take a peek at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and verify your new `source_id` entries, if any tweaks are required just reopen this issue

**Comment by alistairsellar** [comment]
@durack1 all present and correct. Thanks!

**Comment by durack1** [comment]
@alistairsellar we augmented the fields captured for each registered model, and require the additional fields `activity_participation` and `nominal_resolution` (for each active component). I also amended a number of the entries below to explicitly include a `XXX x XXX longitude/latitude;` entry as this format allows the total grid count to be determined, rather than the vague text `primarily 1/12 degree` and is the format most of the other registered entries now follow. If you can copy the entries below and tweak these to correct my `XXX x XXX` guesses, and also add in the missing `activity_participation` and `nominal_resolution` pieces I'll update your registered entries

[HadGEM3-GC31-HH](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L1673-L1721)
```
"HadGEM3-GC31-HH":{
"activity_participation":[
   ""
],
"cohort":[
   "Registered"
],
"institution_id":[
   "MOHC"
],
"label":"HadGEM3-GC31-HH",
"label_extended":"HadGEM3-GC3.1-N512ORCA12",
"model_component":{
"aerosol":
"description":"UKCA-GLOMAP-mode",
"nominal_resolution":""
"atmos":
"description":"MetUM-HadGEM3-GA7.1 (N512; 1024 x 768 longitude/latitude; 85 levels; top level 85 km)",
"nominal_resolution":""
"atmosChem":
"description":"none",
"nominal_resolution":"none"
"land":
"description":"JULES-HadGEM3-GL7.1",
"nominal_resolution":""
"landIce":
"description":"none",
"nominal_resolution":"none"
"ocean":
"description":"NEMO-HadGEM3-GO6.0 (ORCA12 tripolar primarily 1/12 deg; 4320 x 2160 longitude/latitude; 75 levels; top grid cell 0-1 m)",
"nominal_resolution":""
"ocnBgchem":
"description":"none",
"nominal_resolution":"none"
"seaIce":
"description":"CICE-HadGEM3-GSI8 (ORCA12 tripolar primarily 1/12 deg; 4320 x 2160 longitude/latitude)",
"nominal_resolution":""
}
"release_year":"2016",
"source_id":"HadGEM3-GC31-HH"
}
```
[HadGEM3-GC31-HM](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L1722-L1770)
```
"HadGEM3-GC31-HM":{
"activity_participation":[
   ""
],
"cohort":[
   "Registered"
],
"institution_id":[
   "MOHC"
],
"label":"HadGEM3-GC31-HM",
"label_extended":"HadGEM3-GC3.1-N512ORCA025",
"model_component":{
"aerosol":
"description":"UKCA-GLOMAP-mode",
"nominal_resolution":""
"atmos":
"description":"MetUM-HadGEM3-GA7.1 (N512; 1024 x 768 longitude/latitude; 85 levels; top level 85 km)",
"nominal_resolution":""
"atmosChem":
"description":"none",
"nominal_resolution":"none"
"land":
"description":"JULES-HadGEM3-GL7.1",
"nominal_resolution":""
"landIce":
"description":"none",
"nominal_resolution":"none"
"ocean":
"description":"NEMO-HadGEM3-GO6.0 (ORCA025 tripolar primarily 0.25 deg; 1440 x 720 longitude/latitude; 75 levels; top grid cell 0-1 m)",
"nominal_resolution":""
"ocnBgchem":
"description":"none",
"nominal_resolution":"none"
"seaIce":
"description":"CICE-HadGEM3-GSI8 (ORCA025 tripolar primarily 0.25 deg; 1440 x 720 longitude/latitude)",
"nominal_resolution":""
}
"release_year":"2016",
"source_id":"HadGEM3-GC31-HM"
}
```
[HadGEM3-GC31-LL](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L1771-L1819)
```
"HadGEM3-GC31-LL":{
"activity_participation":[
   ""
],
"cohort":[
   "Registered"
],
"institution_id":[
   "MOHC"
],
"label":"HadGEM3-GC31-LL",
"label_extended":"HadGEM3-GC3.1-N96ORCA1",
"model_component":{
"aerosol":
"description":"UKCA-GLOMAP-mode",
"nominal_resolution":""
"atmos":
"description":"MetUM-HadGEM3-GA7.1 (N96; 192 x 144 longitude/latittude; 85 levels; top level 85 km)",
"nominal_resolution":""
"atmosChem":
"description":"none",
"nominal_resolution":"none"
"land":
"description":"JULES-HadGEM3-GL7.1",
"nominal_resolution":""
"landIce":
"description":"none",
"nominal_resolution":"none"
"ocean":
"description":"NEMO-HadGEM3-GO6.0 (ORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 400 x 180 longitude/latitude; 75 levels; top grid cell 0-1 m)",
"nominal_resolution":""
"ocnBgchem":
"description":"none",
"nominal_resolution":"none"
"seaIce":
"description":"CICE-HadGEM3-GSI8 (ORCA1 tripolar primarily 1 deg; 360 x 180 longitude/latitude)",
"nominal_resolution":""
}
"release_year":"2016",
"source_id":"HadGEM3-GC31-LL"
}
```
[HadGEM3-GC31-MM](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L1820-L1868)
```
"HadGEM3-GC31-MM":{
"activity_participation":[
   ""
],
"cohort":[
   "Registered"
],
"institution_id":[
   "MOHC"
],
"label":"HadGEM3-GC31-MM",
"label_extended":"HadGEM3-GC3.1-N216ORCA025",
"model_component":{
"aerosol":
"description":"UKCA-GLOMAP-mode",
"nominal_resolution":""
"atmos":
"description":"MetUM-HadGEM3-GA7.1 (N216; 432 x 324 longitude/latitude; 85 levels; top level 85 km)",
"nominal_resolution":""
"atmosChem":
"description":"none",
"nominal_resolution":"none"
"land":
"description":"JULES-HadGEM3-GL7.1",
"nominal_resolution":""
"landIce":
"description":"none",
"nominal_resolution":"none"
"ocean":
"description":"NEMO-HadGEM3-GO6.0 (ORCA025 tripolar primarily 0.25 deg; 1440 x 720 longitude/latitude; 75 levels; top grid cell 0-1 m)",
"nominal_resolution":""
"ocnBgchem":
"description":"none",
"nominal_resolution":"none"
"seaIce":
"description":"CICE-HadGEM3-GSI8 (ORCA025 tripolar primarily 0.25 deg; 1440 x 720 longitude/latitude)",
"nominal_resolution":""
}
"release_year":"2016",
"source_id":"HadGEM3-GC31-MM"
```
[UKESM1-0-LL](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L2826-L2875)
```
"UKESM1-0-LL":{
"activity_participation":[
   ""
],
"cohort":[
   "Registered"
],
"institution_id":[
   "MOHC",
   "NERC"
],
"label":"UKESM1.0-LL",
"label_extended":"UKESM1.0-N96ORCA1",
"model_component":{
"aerosol":
"description":"UKCA-GLOMAP-mode",
"nominal_resolution":""
"atmos":
"description":"MetUM-HadGEM3-GA7.1 (N96; 192 x 144 longitude/latitude; 85 levels; top level 85 km)",
"nominal_resolution":""
"atmosChem":
"description":"UKCA-StratTrop",
"nominal_resolution":""
"land":
"description":"JULES-HadGEM3-GL7.1",
"nominal_resolution":""
"landIce":
"description":"BISICLES (only active in ISMIP experiments)",
"nominal_resolution":""
"ocean":
"description":"NEMO-HadGEM3-GO6.0 (ORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 360 x 180 longitude/latitude; 75 levels; top grid cell 0-1 m)",
"nominal_resolution":""
"ocnBgchem":
"description":"MEDUSA2",
"nominal_resolution":""
"seaIce":
"description":"CICE-HadGEM3-GSI8 (ORCA1 tripolar primarily 1 deg; 360 x 180 longitude/latitude)",
"nominal_resolution":""
}
"release_year":"2017",
"source_id":"UKESM1-0-LL"
```
[UKESM1-0-MMh](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L2876-L2925)
```
"UKESM1-0-MMh":{
"activity_participation":[
   ""
],
"cohort":[
   "Registered"
],
"institution_id":[
   "MOHC",
   "NERC"
],
"label":"UKESM1.0-MMh",
"label_extended":"UKESM1.0-N216ORCA025hybrid",
"model_component":{
"aerosol":
"description":"UKCA-GLOMAP-mode (horizontal resolution degraded relative to that used for atmosphere physics)",
"nominal_resolution":""
"atmos":
"description":"MetUM-HadGEM3-GA7.1 (N216; 432 x 324 longitude/latitude; 85 levels; top level 85 km)",
"nominal_resolution":""
"atmosChem":
"description":"UKCA-StratTrop (horizontal resolution degraded relative to that used for atmosphere physics)",
"nominal_resolution":""
"land":
"description":"JULES-HadGEM3-GL7.1",
"nominal_resolution":""
"landIce":
"description":"BISICLES (only active in ISMIP experiments)",
"nominal_resolution":""
"ocean":
"description":"NEMO-HadGEM3-GO6.0 (ORCA025 tripolar primarily 0.25 deg; 1440 x 720 longitude/latitude; 75 levels; top grid cell 0-1 m)",
"nominal_resolution":""
"ocnBgchem":
"description":"MEDUSA2 (horizontal resolution degraded relative to that used for ocean physics)",
"nominal_resolution":""
"seaIce":
"description":"CICE-HadGEM3-GSI8 (ORCA025 tripolar primarily 0.25 deg; 1440 x 720 longitude/latitude)",
"nominal_resolution":""
}
"release_year":"2018",
"source_id":"UKESM1-0-MMh"
```

**Comment by durack1** [comment]
@alistairsellar @jonseddon are you able to provide the required info above - the missing "activity_participation" and "nominal_resolution" entries? Any other required tweaks would also be welcomed

**Comment by alistairsellar** [comment]
@durack1 Hi Paul, apologies for the delay. Yes, I will check the `XXX x XXX longitude/latitude` entries. Please could you point me to any documentation for the meaning of `activity_participation` and `nominal_resolution`? I can see examples for other models here: https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json, but not sure where to look for a definition of the terms.

I'm guessing that the `activity_participation` is just a list of MIPs, and if so is the DECK called "DECK" or "CMIP6-DECK", or...? Is `nominal_resolution` to be a grid spacing in km at mid-latitudes, or the equator?

**Comment by durack1** [comment]
@alistairsellar thanks, the `activity_participation` fields are the MIPs that you expect to participate in. The DECK experiments are denoted by `CMIP` and the rest are listed in the [CMIP6_activity_id.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_activity_id.json) file.

For `nominal_resolution`, this is the nominal resolution of your global grid with details found in Appendix 2 of the google doc http://goo.gl/v1drZl

**Comment by alistairsellar** [comment]
Thanks. I've copied your lists above and adapted them...

**HadGEM3-GC31-HH**
```
"HadGEM3-GC31-HH":{
"activity_participation":[
   "HighResMIP"
],
"cohort":[
   "Registered"
],
"institution_id":[
   "MOHC"
],
"label":"HadGEM3-GC31-HH",
"label_extended":"HadGEM3-GC3.1-N512ORCA12",
"model_component":{
"aerosol":
"description":"UKCA-GLOMAP-mode",
"nominal_resolution":"50 km"
"atmos":
"description":"MetUM-HadGEM3-GA7.1 (N512; 1024 x 768 longitude/latitude; 85 levels; top level 85 km)",
"nominal_resolution":"50 km"
"atmosChem":
"description":"none",
"nominal_resolution":"none"
"land":
"description":"JULES-HadGEM3-GL7.1",
"nominal_resolution":"50 km"
"landIce":
"description":"none",
"nominal_resolution":"none"
"ocean":
"description":"NEMO-HadGEM3-GO6.0 (ORCA12 tripolar primarily 1/12 deg; 4320 x 2160 longitude/latitude; 75 levels; top grid cell 0-1 m)",
"nominal_resolution":"10 km"
"ocnBgchem":
"description":"none",
"nominal_resolution":"none"
"seaIce":
"description":"CICE-HadGEM3-GSI8 (ORCA12 tripolar primarily 1/12 deg; 4320 x 2160 longitude/latitude)",
"nominal_resolution":"10 km"
}
"release_year":"2016",
"source_id":"HadGEM3-GC31-HH"
}
```

**HadGEM3-GC31-HM**
```
"HadGEM3-GC31-HM":{
"activity_participation":[
   "HighResMIP"
],
"cohort":[
   "Registered"
],
"institution_id":[
   "MOHC"
],
"label":"HadGEM3-GC31-HM",
"label_extended":"HadGEM3-GC3.1-N512ORCA025",
"model_component":{
"aerosol":
"description":"UKCA-GLOMAP-mode",
"nominal_resolution":"50 km"
"atmos":
"description":"MetUM-HadGEM3-GA7.1 (N512; 1024 x 768 longitude/latitude; 85 levels; top level 85 km)",
"nominal_resolution":"50 km"
"atmosChem":
"description":"none",
"nominal_resolution":"none"
"land":
"description":"JULES-HadGEM3-GL7.1",
"nominal_resolution":"50 km"
"landIce":
"description":"none",
"nominal_resolution":"none"
"ocean":
"description":"NEMO-HadGEM3-GO6.0 (ORCA025 tripolar primarily 0.25 deg; 1440 x 720 longitude/latitude; 75 levels; top grid cell 0-1 m)",
"nominal_resolution":"25 km"
"ocnBgchem":
"description":"none",
"nominal_resolution":"none"
"seaIce":
"description":"CICE-HadGEM3-GSI8 (ORCA025 tripolar primarily 0.25 deg; 1440 x 720 longitude/latitude)",
"nominal_resolution":"25 km"
}
"release_year":"2016",
"source_id":"HadGEM3-GC31-HM"
}
```

**HadGEM3-GC31-LL**
```
"HadGEM3-GC31-LL":{
"activity_participation":[
   "CMIP"
   "CFMIP",
   "DAMIP",
   "FAFMIP",
   "PMIP",
   "RFMIP"
],
"cohort":[
   "Registered"
],
"institution_id":[
   "MOHC"
],
"label":"HadGEM3-GC31-LL",
"label_extended":"HadGEM3-GC3.1-N96ORCA1",
"model_component":{
"aerosol":
"description":"UKCA-GLOMAP-mode",
"nominal_resolution":"250 km"
"atmos":
"description":"MetUM-HadGEM3-GA7.1 (N96; 192 x 144 longitude/latittude; 85 levels; top level 85 km)",
"nominal_resolution":"250 km"
"atmosChem":
"description":"none",
"nominal_resolution":"none"
"land":
"description":"JULES-HadGEM3-GL7.1",
"nominal_resolution":"250 km"
"landIce":
"description":"none",
"nominal_resolution":"none"
"ocean":
"description":"NEMO-HadGEM3-GO6.0 (ORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 400 x 180 longitude/latitude; 75 levels; top grid cell 0-1 m)",
"nominal_resolution":"100 km"
"ocnBgchem":
"description":"none",
"nominal_resolution":"none"
"seaIce":
"description":"CICE-HadGEM3-GSI8 (ORCA1 tripolar primarily 1 deg; 360 x 180 longitude/latitude)",
"nominal_resolution":"100 km"
}
"release_year":"2016",
"source_id":"HadGEM3-GC31-LL"
}
```

**HadGEM3-GC31-MM**
```
"HadGEM3-GC31-MM":{
"activity_participation":[
   "DCPP",
   "GMMIP",
   "LS3MIP",
   "OMIP"
],
"cohort":[
   "Registered"
],
"institution_id":[
   "MOHC"
],
"label":"HadGEM3-GC31-MM",
"label_extended":"HadGEM3-GC3.1-N216ORCA025",
"model_component":{
"aerosol":
"description":"UKCA-GLOMAP-mode",
"nominal_resolution":"100 km"
"atmos":
"description":"MetUM-HadGEM3-GA7.1 (N216; 432 x 324 longitude/latitude; 85 levels; top level 85 km)",
"nominal_resolution":"100 km"
"atmosChem":
"description":"none",
"nominal_resolution":"none"
"land":
"description":"JULES-HadGEM3-GL7.1",
"nominal_resolution":"100 km"
"landIce":
"description":"none",
"nominal_resolution":"none"
"ocean":
"description":"NEMO-HadGEM3-GO6.0 (ORCA025 tripolar primarily 0.25 deg; 1440 x 720 longitude/latitude; 75 levels; top grid cell 0-1 m)",
"nominal_resolution":"25 km"
"ocnBgchem":
"description":"none",
"nominal_resolution":"none"
"seaIce":
"description":"CICE-HadGEM3-GSI8 (ORCA025 tripolar primarily 0.25 deg; 1440 x 720 longitude/latitude)",
"nominal_resolution":"25 km"
}
"release_year":"2016",
"source_id":"HadGEM3-GC31-MM"
}
```

**UKESM1-0-LL**
```
"UKESM1-0-LL":{
"activity_participation":[
   "AerChemMIP",
   "C4MIP",
   "GEOMIP",
   "LUMIP",
   "OMIP",
   "PMIP",
   "ScenarioMIP",
   "VolMIP"
],
"cohort":[
   "Registered"
],
"institution_id":[
   "MOHC",
   "NERC"
],
"label":"UKESM1.0-LL",
"label_extended":"UKESM1.0-N96ORCA1",
"model_component":{
"aerosol":
"description":"UKCA-GLOMAP-mode",
"nominal_resolution":"250 km"
"atmos":
"description":"MetUM-HadGEM3-GA7.1 (N96; 192 x 144 longitude/latitude; 85 levels; top level 85 km)",
"nominal_resolution":"250 km"
"atmosChem":
"description":"UKCA-StratTrop",
"nominal_resolution":"250 km"
"land":
"description":"JULES-HadGEM3-GL7.1",
"nominal_resolution":"250 km"
"landIce":
"description":"none",
"nominal_resolution":"none"
"ocean":
"description":"NEMO-HadGEM3-GO6.0 (ORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 360 x 180 longitude/latitude; 75 levels; top grid cell 0-1 m)",
"nominal_resolution":"100 km"
"ocnBgchem":
"description":"MEDUSA2",
"nominal_resolution":"100 km"
"seaIce":
"description":"CICE-HadGEM3-GSI8 (ORCA1 tripolar primarily 1 deg; 360 x 180 longitude/latitude)",
"nominal_resolution":"100 km"
}
"release_year":"2017",
"source_id":"UKESM1-0-LL"
}
```

**UKESM1-0-MMh**
```
"UKESM1-0-MMh":{
"activity_participation":[
   "AerChemMIP",
   "C4MIP",
   "ScenarioMIP"
],
"cohort":[
   "Registered"
],
"institution_id":[
   "MOHC",
   "NERC"
],
"label":"UKESM1.0-MMh",
"label_extended":"UKESM1.0-N216ORCA025hybrid",
"model_component":{
"aerosol":
"description":"UKCA-GLOMAP-mode (horizontal resolution degraded relative to that used for atmosphere physics)",
"nominal_resolution":"250 km"
"atmos":
"description":"MetUM-HadGEM3-GA7.1 (N216; 432 x 324 longitude/latitude; 85 levels; top level 85 km)",
"nominal_resolution":"100 km"
"atmosChem":
"description":"UKCA-StratTrop (horizontal resolution degraded relative to that used for atmosphere physics)",
"nominal_resolution":"250 km"
"land":
"description":"JULES-HadGEM3-GL7.1",
"nominal_resolution":"100 km"
"landIce":
"description":"none",
"nominal_resolution":"none"
"ocean":
"description":"NEMO-HadGEM3-GO6.0 (ORCA025 tripolar primarily 0.25 deg; 1440 x 720 longitude/latitude; 75 levels; top grid cell 0-1 m)",
"nominal_resolution":"25 km"
"ocnBgchem":
"description":"MEDUSA2 (horizontal resolution degraded relative to that used for ocean physics)",
"nominal_resolution":"100 km"
"seaIce":
"description":"CICE-HadGEM3-GSI8 (ORCA025 tripolar primarily 0.25 deg; 1440 x 720 longitude/latitude)",
"nominal_resolution":"25 km"
}
"release_year":"2018",
"source_id":"UKESM1-0-MMh"
}
```

**Comment by durack1** [comment]
@alistairsellar thanks for this, all the changes have been merged so take a peek at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further tweaks are required

**Comment by alistairsellar** [comment]
Thanks Paul @durack1. Mark has spotted an error in the ORCA1 grid dimensions which I missed. For both UKESM1.0-LL and HadGEM3-GC3.1-LL, we should have
```
"description":"NEMO-HadGEM3-GO6.0 (ORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 360 x 292 longitude/latitude; 75 levels; top grid cell 0-1 m)",
```

Sorry about that. Please can you update again? Apart from that everything looks 

P.S. While checking the above, I noticed an error for EC-Earth3-HR:
"NEMO3.6 (ORCA1; tripolar primarily 0.25" (should say ORCA025 I think).

**Comment by durack1** [comment]
@alistairsellar thanks for this, all the changes have been merged so take a peek at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further tweaks are required.

I also raised your EC-EARTH3-HR query in #191, so will confirm that issue and also get that resolved - thanks for triple checking!

**Comment by alistairsellar** [comment]
Great, thanks!
Alistair
