### ISSUE TITLE
source_id registration of several EC-Earth3 configurations

### ISSUE THREAD

**Issue by shutingdk** [WCRP-CMIP/CMIP6_CVs#191]
Here are entries for more EC-Earth configurations:
```
 "EC-Earth-3-Veg":{
            "aerosol":"none",
            "atmosphere":"IFS cy36r4 (TL255, linearly reduced Gaussian grid equivalent to 512 x 256, 91 levels, top level: 1 Pa)", 
            "atmospheric_chemistry":"none",
            "cohort":[
                ""
            ],
            "institution_id":[
                "EC-Earth-Consortium"
            ],
            "label":"EC-Earth 3.2 - Veg",
            "label_extended":"EC-Earth 3.2 - LPJ-GUESS", 
            "land_ice":"none",
            "land_surface":"LPJ-GUESS", 
            "ocean":"NEMO3.6 (ORCA1 tripolar primarily 1 deg latitude/longitude with meridional refinement down to 1/3 degree in the tropics, L75)", 
            "ocean_biogeochemistry":"none",
            "release_year":"2017",
            "sea_ice":"LIM3",  # (Is there any further info here?)
            "source_id":"EC-Earth-3-Veg"
}

"EC-Earth-3-Veg-LR":{
            "aerosol":"none",
            "atmosphere":"IFS cy36r4 (TL159, linearly reduced Gaussian grid equivalent to 320 x 160; 62 levels; top level 5 hPa)", 
            "atmospheric_chemistry":"none",
            "cohort":[
                ""
            ],
            "institution_id":[
                "EC-Earth-Consortium"
            ],
            "label":"EC-Earth 3.2 Veg LR",
            "label_extended":"EC-Earth 3.2 - LPJ-GUESS at low resolution", 
            "land_ice":"none",
            "land_surface":"LPJ-GUESS", 
            "ocean":"NEMO3.6 (ORCA1 tripolar primarily 1 deg latitude/longitude with meridional refinement down to 1/3 degree in the tropics, L75)", 
            "ocean_biogeochemistry":"none",
            "release_year":"2017",
            "sea_ice":"LIM3",  
            "source_id":"EC-Earth-3-Veg-LR"
}

 "EC-Earth-3-GrIS":{
            "aerosol":"none",
            "atmosphere":"IFS cy36r4 (TL255, linearly reduced Gaussian grid equivalent to 512 x 256, 91 levels, top level: 1 Pa)", 
            "atmospheric_chemistry":"none",
            "cohort":[
                ""
            ],
            "institution_id":[
                "EC-Earth-Consortium"
            ],
            "label":"EC-Earth 3.2 - GrIS",
            "label_extended":"EC-Earth 3.2 - PISM", 
            "land_ice":"PISM 0.7 (5 km x 5 km, L442)",
            "land_surface":"H-TESSEL", 
            "ocean":"NEMO3.6 (ORCA1 tripolar primarily 1 deg latitude/longitude with meridional refinement down to 1/3 degree in the tropics, L75)", 
            "ocean_biogeochemistry":"none",
            "release_year":"2017",
            "sea_ice":"LIM3",  
            "source_id":"EC-Earth-3-GrIS"
}

 "EC-Earth-3-AerChem":{
            "aerosol":"none",
            "atmosphere":"IFS cy36r4 (TL255, linearly reduced Gaussian grid equivalent to 512 x 256, 91 levels, top level: 1 Pa)", 
            "atmospheric_chemistry":"TM5",
            "cohort":[
                ""
            ],
            "institution_id":[
                "EC-Earth-Consortium"
            ],
            "label":"EC-Earth 3.2 - AerChem",
            "label_extended":"EC-Earth 3.2 - AerChem", 
            "land_ice":"none",
            "land_surface":"LPJ-GUESS", 
            "ocean":"NEMO3.6 (ORCA1 tripolar primarily 1 deg latitude/longitude with meridional refinement down to 1/3 degree in the tropics, L75)", 
            "ocean_biogeochemistry":"PISCES",
            "release_year":"2017",
            "sea_ice":"LIM3",  
            "source_id":"EC-Earth-3-AerChem"
}
```

**Comment by durack1** [comment]
@shutingdk please review the new entries in [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if anything else needs tweaking before we close this issue.

Please note that I appended some information regarding version information to some of the sub-models (`land_surface` and `sea_ice`) when it was not provided, please check these details in the new entries. I also appended `; top grid cell 5 m` to each of the ocean entries, as these details were not provided - again please check and if everything is ok I'll close this issue

**Comment by durack1** [comment]
@shutingdk I assume your silence means that you're happy with the amendments, so I will close this issue - please reopen if any more edits are required

**Comment by durack1** [comment]
@shutingdk there is still a missing version identifier for `EC-Earth-3-AerChem`:
```
ocean_biogeochemistry: PISCES (#which version#)
```
It would be great if you can provide this information so we can close this issue

**Comment by shutingdk** [comment]
Here are the updates for all eight EC-Earth configurations, with some necessary corrections and harmonizition. Note we would name the model as EC-Earth3 (without the hyphen before "3"). 

 "EC-Earth3":{
            "aerosol":"none",
            "atmosphere":"IFS cy36r4 (TL255, linearly reduced Gaussian grid equivalent to 512 x 256, 91 levels, top level: 0,01 hPa)", 
            "atmospheric_chemistry":"none",
            "cohort":[
                ""
            ],
            "institution_id":[
                "EC-Earth-Consortium"
            ],
            "label":"EC-Earth3",
            "label_extended":"EC-Earth 3.3", 
            "land_ice":"none",
            "land_surface":"HTESSEL (land surface scheme built in IFS)", 
            "ocean":"NEMO3.6 (ORCA1 tripolar primarily 1 deg latitude/longitude with meridional refinement down to 1/3 degree in the tropics; 75 levels; top grid cell 5 m)", 
            "ocean_biogeochemistry":"none",
            "release_year":"2017",
            "sea_ice":"LIM3",  
            "source_id":"EC-Earth3"
}

 "EC-Earth3-AerChem":{
            "aerosol":"TM5",
            "atmosphere":"IFS cy36r4 (TL255, linearly reduced Gaussian grid equivalent to 512 x 256, 91 levels, top level: 0.01 hPa)", 
            "atmospheric_chemistry":"TM5 (3 deg. (long.) x 2 deg. (lat.), 34 levels, top level: 0.1 hPa",
            "cohort":[
                ""
            ],
            "institution_id":[
                "EC-Earth-Consortium"
            ],
            "label":"EC-Earth3-AerChem",
            "label_extended":"EC-Earth 3.3 - AerChem (with atmospheric aerosol and chemistry)", 
            "land_ice":"none",
            "land_surface":"HTESSEL (land surface scheme built in IFS)", 
            "ocean":"NEMO3.6 (ORCA1 tripolar primarily 1 deg latitude/longitude with meridional refinement down to 1/3 degree in the tropics; 75 levels; top grid cell 5 m)", 
            "ocean_biogeochemistry":"none",
            "release_year":"2017",
            "sea_ice":"LIM3",  
            "source_id":"EC-Earth3-AerChem"
}

 "EC-Earth3-CC":{
            "aerosol":"none",
            "atmosphere":"IFS cy36r4 (TL255, linearly reduced Gaussian grid equivalent to 512 x 256, 91 levels, top level: 0.01 hPa)", 
            "atmospheric_chemistry":"TM5 (3 deg. (long.) x 2 deg. (lat.), 34 levels, top level: 0.1 hPa",
            "cohort":[
                ""
            ],
            "institution_id":[
                "EC-Earth-Consortium"
            ],
            "label":"EC-Earth3-CC",
            "label_extended":"EC-Earth 3.3 - CC (with carbon cycle)", 
            "land_ice":"none",
            "land_surface":"LPJ-GUESS v4", 
            "ocean":"NEMO3.6 (ORCA1 tripolar primarily 1 deg latitude/longitude with meridional refinement down to 1/3 degree in the tropics; 75 levels; top grid cell 5 m)", 
            "ocean_biogeochemistry":"PISCES v2",
            "release_year":"2017",
            "sea_ice":"LIM3",  
            "source_id":"EC-Earth3-AerChem"
}
 "EC-Earth3-GrIS":{
            "aerosol":"none",
            "atmosphere":"IFS cy36r4 (TL255, linearly reduced Gaussian grid equivalent to 512 x 256, 91 levels, top level: 0.01 hPa)", 
            "atmospheric_chemistry":"none",
            "cohort":[
                ""
            ],
            "institution_id":[
                "EC-Earth-Consortium"
            ],
            "label":"EC-Earth3-GrIS",
            "label_extended":"EC-Earth 3.3 Coupled with PISM for Greenland ice sheet", 
            "land_ice":"PISM 0.7 (5 km x 5 km, L442)",
            "land_surface":"HTESSEL (land surface scheme built in IFS)", 
            "ocean":"NEMO3.6 (ORCA1 tripolar primarily 1 deg latitude/longitude with meridional refinement down to 1/3 degree in the tropics; 75 levels; top grid cell 5 m)", 
            "ocean_biogeochemistry":"none",
            "release_year":"2017",
            "sea_ice":"LIM3",  
            "source_id":"EC-Earth3-GrIS"
}

 "EC-Earth3-HR":{
            "aerosol":"none",
            "atmosphere":"IFS cy36r4 (TL511, linearly reduced Gaussian grid equivalent to 1024 x 512; 91 levels; top level 0.01 hPa)", 
            "atmospheric_chemistry":"none",
            "cohort":[
                ""
            ],
            "institution_id":[
                "EC-Earth-Consortium"
            ],
            "label":"EC-Earth3-HR",
            "label_extended":"EC-Earth 3.3 at high resolution", 
            "land_ice":"none",
            "land_surface":"HTESSEL (land surface scheme built in IFS)", 
            "ocean":"NEMO3.6 (tripolar, 1442x1921; 75 levels; top grid cell 5m)", 
            "ocean_biogeochemistry":"none",
            "release_year":"2017",
            "sea_ice":"LIM3",  
            "source_id":"EC-Earth3-HR"
}

 "EC-Earth3-LR":{
            "aerosol":"none",
            "atmosphere":"IFS cy36r4 (TL159, linearly reduced Gaussian grid equivalent to 320 x 160; 62 levels; top level 5 hPa)", 
            "atmospheric_chemistry":"none",
            "cohort":[
                ""
            ],
            "institution_id":[
                "EC-Earth-Consortium"
            ],
            "label":"EC-Earth3-LR",
            "label_extended":"EC-Earth 3.3 at low resolution", 
            "land_ice":"none",
            "land_surface":"HTESSEL (land surface scheme built in IFS)", 
            "ocean":"NEMO3.6 (ORCA1 tripolar primarily 1 deg latitude/longitude with meridional refinement down to 1/3 degree in the tropics; 75 levels; top grid cell 5 m)", 
            "ocean_biogeochemistry":"none",
            "release_year":"2017",
            "sea_ice":"LIM3",  
            "source_id":"EC-Earth3-LR"
}
"EC-Earth3-Veg":{
            "aerosol":"none",
            "atmosphere":"IFS cy36r4 (TL255, linearly reduced Gaussian grid equivalent to 512 x 256, 91 levels, top level: 0.01 hPa)", 
            "atmospheric_chemistry":"none",
            "cohort":[
                ""
            ],
            "institution_id":[
                "EC-Earth-Consortium"
            ],
            "label":"EC-Earth3-Veg",
            "label_extended":"EC-Earth 3.3 - LPJ-GUESS", 
            "land_ice":"none",
            "land_surface":"LPJ-GUESS v4", 
            "ocean":"NEMO3.6 (ORCA1 tripolar primarily 1 deg latitude/longitude with meridional refinement down to 1/3 degree in the tropics; 75 levels; top grid cell 5 m)", 
            "ocean_biogeochemistry":"none",
            "release_year":"2017",
            "sea_ice":"LIM3",
            "source_id":"EC-Earth3-Veg"
}

"EC-Earth3-Veg-LR":{
            "aerosol":"none",
            "atmosphere":"IFS cy36r4 (TL159, linearly reduced Gaussian grid equivalent to 320 x 160; 62 levels; top level 5 hPa)", 
            "atmospheric_chemistry":"none",
            "cohort":[
                ""
            ],
            "institution_id":[
                "EC-Earth-Consortium"
            ],
            "label":"EC-Earth3-Veg LR",
            "label_extended":"EC-Earth 3.3 - LPJ-GUESS at low resolution", 
            "land_ice":"none",
            "land_surface":"LPJ-GUESS v4", 
            "ocean":"NEMO3.6 (ORCA1 tripolar primarily 1 deg latitude/longitude with meridional refinement down to 1/3 degree in the tropics; 75 levels; top grid cell 5 m)", 
            "ocean_biogeochemistry":"none",
            "release_year":"2017",
            "sea_ice":"LIM3",  
            "source_id":"EC-Earth3-Veg-LR"
}

**Comment by durack1** [comment]
@shutingdk take a peek at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and double check these edits

**Comment by durack1** [comment]
@shutingdk we have recently augmented the information we are collecting for registration, so we require some additional information from you (specifically the `nominal_resolution` attribute for each realm). I have made some amendments to the existing entries below (noted between the `### entry ###` text), and will require you to fill out the fields with the `###` informational text directing you to descriptive information about the request, or lists of potential entries (I have only included this for the first model `EC-Earth3` as an example)

```
"EC-Earth3":{
   "activity_participation":[
      "" ### See activity list at https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_activity_id.json
   ],
"model_component":
"atmos":
   "description":"IFS cy36r4 (TL255, linearly reduced Gaussian grid#; 512 x 256 longitude/latitude; 91 levels; top level: 0.01 hPa###)",
   "nominal_resolution":"" ### See Appendix 2 in https://goo.gl/v1drZl
"land":
   "description":"HTESSEL (land surface scheme built in IFS)",
   "nominal_resolution":"" ### See Appendix 2 in https://goo.gl/v1drZl (likely same as atmos above)
"ocean":
   "description":"NEMO3.6 (###ORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 360 x 180 longitude/latitude; 75 levels; top grid cell 0-10 m###)",
   "nominal_resolution":""
"seaIce":
   "description":"LIM3",
   "nominal_resolution":"" ### See Appendix 2 in https://goo.gl/v1drZl (likely same as ocean above)


"EC-Earth3-AerChem":{
   "activity_participation":[
      ""
   ],
"model_component":
"aerosol":
   "description":"TM5",
   "nominal_resolution":""
"atmos":
   "description":"IFS cy36r4 (TL255, linearly reduced Gaussian grid###; 512 x 256 longitude/latitude;### 91 levels; top level: 0.01 hPa)",
   "nominal_resolution":""
"atmosChem":
   "description":"TM5 (###3 x 2 degrees longitude/latitude###; 34 levels; top level 0.1 hPa)",
   "nominal_resolution":""
"land":
   "description":"HTESSEL (land surface scheme built in IFS)",
   "nominal_resolution":""
"ocean":
   "description":"NEMO3.6 (###ORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 360 x 180 longitude/latitude; 75 levels; top grid cell 0-10 m###)",
   "nominal_resolution":""
"seaIce":
   "description":"LIM3"
   "nominal_resolution":""


"EC-Earth3-CC":{
   "activity_participation":[
      ""
   ],
"model_component":
"atmos":
   "description":"IFS cy36r4 (TL255, linearly reduced Gaussian grid###; 512 x 256 longitude/latitude;### 91 levels; top level 0.01 hPa)",
   "nominal_resolution":""
"atmosChem":
   "description":"TM5 (###3 x 2 degrees longitude/latitude###; 34 levels; top level 0.1 hPa)",
   "nominal_resolution":""
"land":
   "description":"LPJ-GUESS v4",
   "nominal_resolution":""
"ocean":
   "description":"NEMO3.6 (###ORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 360 x 180 longitude/latitude; 75 levels; top grid cell 0-10 m###)",
   "nominal_resolution":""
"ocnBgchem":
   "description":"PISCES v2",
   "nominal_resolution":""
"seaIce":
   "description":"LIM3",
   "nominal_resolution":""


"EC-Earth3-GrIS":{
   "activity_participation":[
      ""
   ],
"model_component":
"atmos":
   "description":"IFS cy36r4 (TL255, linearly reduced Gaussian grid###; 512 x 256 longitude/latitude;### 91 levels; top level 0.01 hPa)",
   "nominal_resolution":""
"land":
   "description":"HTESSEL (land surface scheme built in IFS)",
   "nominal_resolution":""
"landIce":
   "description":"PISM 0.7 (5 km x 5 km, L442)",
   "nominal_resolution":""
"ocean":
   "description":"NEMO3.6 (###ORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 360 x 180 longitude/latitude; 75 levels; top grid cell 0-10 m###)",
   "nominal_resolution":""
"seaIce":
   "description":"LIM3",
   "nominal_resolution":""


"EC-Earth3-HR":{
   "activity_participation":[
      ""
   ],
"model_component":
"atmos":
   "description":"IFS cy36r4 (TL511, linearly reduced Gaussian grid###; 1024 x 512 longitude/latitude###; 91 levels; top level 0.01 hPa)",
   "nominal_resolution":""
"land":
   "description":"HTESSEL (land surface scheme built in IFS)",
   "nominal_resolution":""
"ocean":
   "description":"NEMO3.6 (tripolar;### 1921 x 1442 longitude/latitude; 75 levels; top grid cell 0-10 m###)",
   "nominal_resolution":""
"seaIce":
   "description":"LIM3",
   "nominal_resolution":""


"EC-Earth3-LR":{
   "activity_participation":[
      ""
   ],
"model_component":
"atmos":
   "description":"IFS cy36r4 (TL159, linearly reduced Gaussian grid; ###320 x 160 longitude/latitude;### 62 levels; top level 5 hPa)",
   "nominal_resolution":""
"land":
   "description":"HTESSEL (land surface scheme built in IFS)",
   "nominal_resolution":""
"ocean":
   "description":"NEMO3.6 (###ORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 360 x 180 longitude/latitude; 75 levels; top grid cell 0-10 m###)",
   "nominal_resolution":""
"seaIce":
   "description":"LIM3",
   "nominal_resolution":""


"EC-Earth3-Veg":{
   "activity_participation":[
      ""
   ],
"model_component":
"atmos":
   "description":"IFS cy36r4 (TL255, linearly reduced Gaussian grid; ###512 x 256 longitude/latitude;### 91 levels; top level 0.01 hPa)",
   "nominal_resolution":""
"land":
   "description":"LPJ-GUESS v4",
   "nominal_resolution":""
"ocean":
   "description":"NEMO3.6 (ORCA1 tripolar primarily 1 deg latitude/longitude with meridional refinement down to 1/3 degree in the tropics; ###360 x 180 longitude/latitude; 75 levels; top grid cell 0-10 m###)",
   "nominal_resolution":""
"seaIce":
   "description":"LIM3",
   "nominal_resolution":""


"EC-Earth3-Veg-LR":{
   "activity_participation":[
      ""
   ],
"model_component":
"atmos":
   "description":"IFS cy36r4 (TL159, linearly reduced Gaussian grid; ###320 x 160 longitude/latitude;### 62 levels; top level 5 hPa)",
   "nominal_resolution":""
"land":
   "description":"LPJ-GUESS v4",
   "nominal_resolution":""
"ocean":
   "description":"NEMO3.6 (ORCA1 tripolar primarily 1 deg latitude/longitude with meridional refinement down to 1/3 degree in the tropics; ### 360 x 180 longitude/latitude; 75 levels; top grid cell 0-10 m###)",
   "nominal_resolution":""
"seaIce":
   "description":"LIM3",
   "nominal_resolution":""
```

**Comment by durack1** [comment]
@shutingdk have you had any luck collecting the information requested above?

**Comment by durack1** [comment]
@shutingdk have you had any luck collecting the information requested above?

**Comment by shutingdk** [comment]
Below are the updated information for the eight EC-Earth model configurations. I also made some corrections to some of the entries. We still missing the nominal resolutions for some model components (eg., atm. chem and land-ice).

"EC-Earth3":{
"activity_participation":["CMIP", "CORDEX", "DCPP", "DynVarMIP", "LS3MIP", “RFMIP”,"SIMIP", "ScenarioMIP", "VIACSAB", "VolMIP" ],
"institution_id":["EC-Earth-Consortium"],
"label":"EC-Earth3",
"label_extended":"EC-Earth 3.3", 
 "model_component":
             "aerosol":"none",
             "atmos":
"description":"IFS cy36r4 (TL255, linearly reduced Gaussian grid equivalent to 512 x 256 longitude/latitude; 91 levels; top level: 0.01 hPa)",
"nominal_resolution":"100 km" 
              "land":
"description":"HTESSEL (land surface scheme built in IFS)",
"nominal_resolution":"100 km" 
      "land_ice":"none",
              "ocean":
"description":"NEMO3.6 (ORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 362 x 292 longitude/latitude; 75 levels; top grid cell 0 - 1 m)",
"nominal_resolution":" 100 km"
              "ocean_biogeochemistry":"none",
              "seaIce":
"description":"LIM3",
 	"nominal_resolution":" 100 km" 
"release_year":"2017",
"source_id":"EC-Earth3"
}

"EC-Earth3-AerChem":{
"activity_participation":["AeroChemMIP", "CMIP", "ScenarioMIP"],
"institution_id":["EC-Earth-Consortium"],
"label":"EC-Earth3-AerChem",
"label_extended":"EC-Earth3-AerChem", 
 "model_component":
              "aerosol":
"description":"TM5 (3 x 2 deg. longitude/latitude, 34 levels, top level: 0.1 hPa)
              "atmos":
"description":"IFS cy36r4 (TL255, linearly reduced Gaussian grid equivalent to 512 x 256 longitude/latitude; 91 levels; top level: 0.01 hPa)",
"nominal_resolution":"100 km" 
              "atmospheric_chemistry":
"description":"TM5 (3 x 2 deg. longitude/latitude; 34 levels; top level: 0.1 hPa)",
              "land":
"description":"HTESSEL (land surface scheme built in IFS)",
"nominal_resolution":"100 km" 
      "land_ice":"none",
              "ocean":
                      "description":"NEMO3.6 (ORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 362 x 292 longitude/latitude; 75 levels; top grid cell 0 - 1 m)",
                      "nominal_resolution":" 100 km"
              "ocean_biogeochemistry":"none",
              "seaIce":
                      "description":"LIM3",
                      "nominal_resolution":" 100 km" 
"release_year":"2017",
"source_id":"EC-Earth3-AerChem"
}
"EC-Earth3-CC":{
"activity_participation":["C4MIP", "CMIP", " LUMIP"],
"institution_id":["EC-Earth-Consortium" ],
"label":"EC-Earth3-CC",
"label_extended":"EC-Earth3-CC", 
 "model_component":
              "aerosol":”none”
              "atmos":
"description":"IFS cy36r4 (TL255, linearly reduced Gaussian grid equivalent to 512 x 256 longitude/latitude; 91 levels; top level: 0.01 hPa)",
"nominal_resolution":"100 km" 
              "atmospheric_chemistry":
"description":"TM5 (3 x 2 deg. longitude/latitude; 34 levels; top level: 0.1 hPa)",
              "land":
"description":"HTESSEL (land surface scheme built in IFS) + LPJ-GUESS v4",
"nominal_resolution":"100 km" 
      "land_ice":"none",
              "ocean":
                      "description":"NEMO3.6 (ORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 362 x 292 longitude/latitude; 75 levels; top grid cell 0 - 1 m)",
                      "nominal_resolution":" 100 km"
              "ocean_biogeochemistry":"PISCES v2",
              "seaIce":
                      "description":"LIM3",
                      "nominal_resolution":" 100 km" 
"release_year":"2017",
"source_id":"EC-Earth3-CC"
}
"EC-Earth3-GrIS":{
"activity_participation":["CMIP", "ISMIP6", "PMIP"],
"institution_id":["EC-Earth-Consortium"],
"label":"EC-Earth3-GrIS",
"label_extended":"EC-Earth3-GrIS", 
 "model_component":
              "aerosol":"none",
              "atmos":
"description":"IFS cy36r4 (TL255, linearly reduced Gaussian grid equivalent to 512 x 256 longitude/latitude; 91 levels; top level: 0.01 hPa)",
"nominal_resolution":"100 km" 
              "land":
"description":"HTESSEL (land surface scheme built in IFS)",
"nominal_resolution":"100 km" 
      "land_ice":
"description":"PISM 0.7 (5 km x 5 km, 442 levels)",
              "ocean":
"description":"NEMO3.6 (ORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 362 x 292 longitude/latitude; 75 levels; top grid cell 0 - 1 m)",
"nominal_resolution":" 100 km"
              "ocean_biogeochemistry":"none",
              "seaIce":
"description":"LIM3",
 	"nominal_resolution":" 100 km" 
"release_year":"2017",
"source_id":"EC-Earth3-GrIS"
}
"EC-Earth3-HR":{
"activity_participation":["HighResMIP","DCPP"],
"institution_id":["EC-Earth-Consortium"],
"label":"EC-Earth3-HR",
"label_extended":"EC-Earth3-HR", 
 "model_component":
             "aerosol":"none",
             "atmos":
"description":"IFS cy36r4 (TL511, linearly reduced Gaussian grid equivalent to 1024 x 512 longitude/latitude; 91 levels; top level: 0.01 hPa)",
"nominal_resolution":"50 km" 
              "land":
"description":"HTESSEL (land surface scheme built in IFS)",
"nominal_resolution":"50 km" 
      "land_ice":"none",
              "ocean":
"description":"NEMO3.6 (ORCA1 tripolar, 1442x1921 longitude/latitude; 75 levels; top grid cell 0 - 1 m)",
"nominal_resolution":"25 km"
              "ocean_biogeochemistry":"none",
              "seaIce":
"description":"LIM3",
 	"nominal_resolution":"25 km" 
"release_year":"2017",
"source_id":"EC-Earth3-HR"
}
"EC-Earth3-LR":{
"activity_participation":["CMIP","PMIP"],
"institution_id":["EC-Earth-Consortium"],
"label":"EC-Earth3-LR",
"label_extended":"EC-Earth3-LR", 
 "model_component":
             "aerosol":"none",
             "atmos":
"description":"IFS cy36r4 (TL159, linearly reduced Gaussian grid equivalent to 320 x 160 longitude/latitude; 62 levels; top level: 5 hPa)",
"nominal_resolution":"250 km" 
              "land":
"description":"HTESSEL (land surface scheme built in IFS)",
"nominal_resolution":"250 km" 
      "land_ice":"none",
              "ocean":
"description":"NEMO3.6 (ORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 362 x 292 longitude/latitude; 75 levels; top grid cell 0 - 1 m)",
"nominal_resolution":" 100 km"
              "ocean_biogeochemistry":"none",
              "seaIce":
"description":"LIM3",
 	"nominal_resolution":" 100 km" 
"release_year":"2017",
"source_id":"EC-Earth3-LR"
}
"EC-Earth3-Veg":{
"activity_participation":["CMIP", “LS3MIP”,"LUMIP",”ScenarioMIP”],
"institution_id":["EC-Earth-Consortium" ],
"label":"EC-Earth3-Veg",
"label_extended":"EC-Earth3-Veg", 
 "model_component":
              "aerosol":”none”
              "atmos":
"description":"IFS cy36r4 (TL255, linearly reduced Gaussian grid equivalent to 512 x 256 longitude/latitude; 91 levels; top level: 0.01 hPa)",
"nominal_resolution":"100 km" 
              "atmospheric_chemistry":”none”
              "land":
"description":"HTESSEL (land surface scheme built in IFS) + LPJ-GUESS v4",
"nominal_resolution":"100 km" 
      "land_ice":"none",
              "ocean":
                      "description":"NEMO3.6 (ORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 362 x 292 longitude/latitude; 75 levels; top grid cell 0 - 1 m)",
                      "nominal_resolution":" 100 km"
              "ocean_biogeochemistry":"none",
              "seaIce":
                      "description":"LIM3",
                      "nominal_resolution":" 100 km" 
"release_year":"2017",
"source_id":"EC-Earth3-Veg"
}
"EC-Earth3-Veg-LR":{
"activity_participation":["CMIP", “PMIP”,”ScenarioMIP”],
"institution_id":["EC-Earth-Consortium" ],
"label":"EC-Earth3-Veg-LR",
"label_extended":"EC-Earth3-Veg-LR", 
 "model_component":
              "aerosol":”none”
              "atmos":
"description":"IFS cy36r4 (TL159, linearly reduced Gaussian grid equivalent to 320 x 160 longitude/latitude; 62 levels; top level: 5 hPa)",
"nominal_resolution":"250 km" 	
              "atmospheric_chemistry":”none”
              "land":
"description":"HTESSEL (land surface scheme built in IFS) + LPJ-GUESS v4",
"nominal_resolution":"250 km" 
      "land_ice":"none",
              "ocean":
                      "description":"NEMO3.6 (ORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 362 x 292 longitude/latitude; 75 levels; top grid cell 0 - 1 m)",
                      "nominal_resolution":" 100 km"
              "ocean_biogeochemistry":"none",
              "seaIce":
                      "description":"LIM3",
                      "nominal_resolution":" 100 km" 
"release_year":"2017",
"source_id":"EC-Earth3-Veg-LR"
}

**Comment by durack1** [comment]
@shutingdk thanks. For any components that exist, we need a `nominal_resolution` entry, so for the example (and many other entries above):
```
"EC-Earth3-AerChem":{
...
"aerosol":
"description":"TM5 (3 x 2 deg. longitude/latitude, 34 levels, top level: 0.1 hPa)
"nominal_resolution":"SOMETHING HERE"
```
We're following the format that the total number of grid cells for each component is included, so the entry above would become:
```
"description":"TM5 (3 x 2 deg; 120 x 90 longitude/latitude; 34 levels; top level: 0.1 hPa)
```
Or the corrected version of the suggested format above (I guessed at the 120 and 90 entries)

Can you please amend the entry above to include the missing info, and revise the format to include grid cell info too?

**Comment by shutingdk** [comment]
Yes. The entry for TM5 in "EC-Earth3-AerChem" and "EC-Earth3-CC" is as:

"description":"TM5 (3 x 2 deg; 120 x 90 longitude/latitude; 34 levels; top level: 0.1 hPa)"
"nominal_resolution":"250 km"

For the land-ice component in "EC-Earth3-GrIS", the nominal_resolution is 5 km, i.e.,

"EC-Earth3-GrIS":{
...
"land-ice":
      "description":"5 km"

**Comment by durack1** [comment]
@shutingdk thanks for this, peek at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further tweaks are required

**Comment by durack1** [comment]
@shutingdk it's been pointed out that the entry:
```
"EC-Earth3-HR":{
 "description":"NEMO3.6 (ORCA1; tripolar primarily 0.25 degrees; 1442 x 1921 longitude/latitude; 75 levels; top grid cell 0-1 m)",
 "nominal_resolution":"25 km"
```
Should be amended to:
```
 "description":"NEMO3.6 (ORCA025; tripolar primarily 0.25 degrees; ...
```
Would you confirm that this change is required?

**Comment by shutingdk** [comment]
Yes. Thank you for spotting the error. It is correct that "EC-Earth3-HR" should be with ORCA025, ie.,

"EC-Earth3-HR":{
 "description":"NEMO3.6 (ORCA025; tripolar primarily 0.25 degrees; 1442 x 1921 longitude/latitude; 75 levels; top grid cell 0-1 m)",
 "nominal_resolution":"25 km"

**Comment by durack1** [comment]
@shutingdk thanks, the change is now implemented in [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html)
