### ISSUE TITLE
New table_id list from Data Request version 1.0.0

### ISSUE THREAD

**Issue by dnadeau4** [WCRP-CMIP/CMIP6_CVs#199]
Many tables have been renamed in version 1.0.0 and table_id is no longer valid.

@durack1 can you replace your list with the following one provided by @martinjuckes ?

Thanks!

3hr
6hrLev
6hrPlev
6hrPlevPt
AERday
AERfx
AERhr
AERmon
AERmonZ
Amon
CF3hr
CFday
CFmon
CFsubhr
CFsubhrOff
day
E1hr
E1hrClimMon
E3hr
E3hrPt
E6hrZ
Eday
EdayZ
Efx
Emon
EmonZ
Esubhr
Eyr
fx
grids
IfxAnt
IfxGre
ImonAnt
ImonGre
IyrAnt
IyrGre
LImon
Lmon
Oclim
Oday
Odec
Ofx
Omon
Oyr
SIday
SImon

**Comment by durack1** [comment]
@dnadeau4 sure will do this before COB today

**Comment by durack1** [comment]
@dnadeau4 apologies for the delay, this should now be in sync with V1.0 of the data request
