### ISSUE TITLE
required attributes in JSON file

### ISSUE THREAD

**Issue by dnadeau4** [WCRP-CMIP/CMIP6_CVs#2]
## Controlled Vocabulary (CV) of interest:

Can we add the required attribute list and their corresponding regular expression for value validation in a separate JSON file. 

I am thinking of something like CMIP6_requiredattributes.json.  This will make it easier for me to recreate CMIP6_CV.json for CMOR 3.

====
```json
        [
        "variant_label",
        "activity_id",
        "branch_method",
        "Conventions",
        "creation_date",
        "mip_era",
        "data_specs_version",
        "experiment_id",
        "experiment",
        "forcing_index",
        "further_info_url",
        "frequency",
        "grid",
        "grid_label",
        "grid_resolution",
        "initialization_index",
        "institution",
        "institution_id",
        "license",
        "physics_index",
        "product",
        "realization_index",
        "realm",
        "variant_label",
        "source",
        "source_id",
        "source_type",
        "sub_experiment",
        "sub_experiment_id",
        "table_id",
        "tracking_id",
        "variable_id"
        ],

    "variant_label": ["^r[[:digit:]]\\{1,\\}i[[:digit:]]\\{1,\\}p[[:digit:]]\\{1,\\}f[[:digit:]]\\{1,\\}$" ],
    "sub_experiment_id": [ "^s[[:digit:]]\\{4,4\\}$", "none" ],

    "product": [ "output" ] ,

    "frequency": [ "3hr", "6hr", "day", "fx", "mon", "monClim", "subhr", "yr" ],

    "further_info_url": ["http://furtherinfo.es-doc.org/[[:alpha:]]\\{1,\\}" ],

```

**Comment by durack1** [comment]
@dnadeau4 [CMIP6_required_global_attributes.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_required_global_attributes.json) and [CMIP6_frequency.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_frequency.json) is done. I am not sure about the rest - these `variant_label`, `product` and `further_info_url` are `CMOR3` specific, so might be better to keep them separated from these generic `CMIP6_CVs` - @taylor13 what is your take?

**Comment by durack1** [comment]
@taylor can you chip in on this?

**Comment by durack1** [comment]
@dnadeau4 @taylor13 we'll need to discuss this on Thursday.. And either close or determine a path forward

**Comment by durack1** [comment]
@taylor13 @dnadeau4 @durack1 agreed that `license` should be added to the CVs, everything else is controlled within CMOR3

**Comment by durack1** [comment]
@dnadeau4 @taylor13 closing as a new of #35
