### ISSUE TITLE
experiment_id: html table rendering

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#20]
## Indicate the Controlled Vocabulary (CV) of interest: experiment_id  (html rendition)

Is it o.k. for me to upload Charles' script (to produce html table from CMIP6_experiment_id.json) into "src" and the CMIP6_experiment_id.html file into CMIP6_CVs?

**Comment by durack1** [comment]
@taylor13 already there: [src/json_to_html.py](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/src/json_to_html.py) if he has tweaked it then it'll need an update..
