### ISSUE TITLE
activity_id HighResMIP -- add additional experiment-id 'spinup-1950'

### ISSUE THREAD

**Issue by robertsmalcolm** [WCRP-CMIP/CMIP6_CVs#202]
In testing the implementation of the HighResMIP protocol, it became clear that we missed categorising the coupled spinup-1950 segment of the simulation explicitly. Currently it could be interpreted as being within the control-1950 experiment_id, but this would be wrong (the control-1950 and highres-future should be parallel, both using the spinup-1950 as their common initial condition). 
The HighResMIP protocol paper will need updating similarly.

We intend to compare how different models spinup from rest at different resolutions. The length of this can be variable, being model dependent (balance of Top-of-Atmosphere radiation or near ocean drift), and hence we would suggest the first 30 years as a minimum for submission. 

experiment_id = spinup-1950
activity_id = HighResMIP
experiment = coupled spinup with fixed 1950's forcings from 1950 initial conditions (with ocean at rest) to provide initial condition for control-1950 and hist-1950. 
tier = 2
parent_experiment_id = None
required_model_components = AOGCM
additional_allowed_model_components = AER CHEM BGC
start_year = 1950
end_year = 1980
min_number_yrs_per_sim = 30
parent_activity_id = HighResMIP
description = Coupled integration from ocean rest state using recommended HighResMIP protocol spinup with 1950 ocean temperature and salinity, using constant 1950's forcing. 

With this change, both
experiment_id = hist-1950 
and
experiment_id = control-1950

with then have a common
parent_experiment_id = spinup-1950

**Comment by durack1** [comment]
@taylor13 this requires a new `experiment_id` definition, the new entry will be `spinup-1950`. Are there any additional steps required to add a new experiment that need review at this late stage?

**Comment by taylor13** [comment]
@robertsmalcolm This shouldn't be a problem.  Here are some comments:
1.   spinup-1950 should have no start_year or end_year (because this is like spinup-piControl, the time does not correspond to the time of evolving conditions and is therefore arbitrary).  Note that the branch_time_in_parent global attribute will record the at one time in spinup-1950 the hist-1950 and control-1950 were initiated; the branch_time_in_parent and branch_time_in_child won't generally be the same.
2.  hist-1950 and control-1950 should probably be assigned the same start time (probably "1950")
3.  the model component should be "BGCM", not "BGC"

**Comment by robertsmalcolm** [comment]
Hi, this all sounds fine, thanks for your help.

**Comment by durack1** [comment]
@taylor13 regarding your 3. #131 suggests that `BGC` is the most up-to-date, is this now not current?
Regarding 2. both experiments have start_year = 1951

**Comment by robertsmalcolm** [comment]
To confirm, the start_year should be 1950 (rather than 1951 wherever that still exists).
I'll check the other issues tomorrow.

**Comment by durack1** [comment]
@robertsmalcolm take a peek at [CMIP6_experiment_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html) and let us know if there are any other remaining issues to be resolved

**Comment by robertsmalcolm** [comment]
OK, I talked with Rein and we think some of the other idealised experiments need to be shorter for the best chance of multiple groups participating. So we think if we use the same period as the CMIP AMIP2 that might work best. These would then take initial conditions from highresSST-present.
highresSST-4co2: start_year = 1979
highresSST-LAI=1979
highresSST-p4K=1979
highresSST-smoothed=1979

Then for the longer runs they start in 1950 (rather than 1951).
highresSST-present: start_year = 1950
hist-1950: start_year = 1950

Thanks
