### ISSUE TITLE
institution_id registration of FIO-SOA

### ISSUE THREAD

**Issue by zhenyasong** [WCRP-CMIP/CMIP6_CVs#205]
# Edit information of FIO

institution_id = FIO-SOA
institution = First Institute of Oceanography, State Oceanic Administration, Qingdao 266061, China

**Comment by durack1** [comment]
@zhenyasong please review the update at [CMIP6_institution_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_institution_id.html) and provide any additional tweaks if required
