### ISSUE TITLE
source_id registration of AWI-CM

### ISSUE THREAD

**Issue by tsemmler05** [WCRP-CMIP/CMIP6_CVs#210]
label = AWI-CM 1.0
  source_id = AWI-CM-1-0
  institution_id = AWI
  release_year = 2017

  aerosol = None
  atmosphere = ECHAM6.3.02p4 (384*192 grid points, T127L95, 95 levels, top level 80000 m)
  atmospheric_chemistry = None
  land_ice = None
  land_surface = JSBACH 3.10
  ocean = FESOM 1.4 (unstructured grid in the horizontal with 830305 wet nodes, 46 vertical levels; top grid cell 0-5 m)
  ocean_biogeochemistry = None
  sea_ice = FESOM 1.4

**Comment by durack1** [comment]
@tsemmler05 those changes have been updated, please take a look at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html)

There are some fields that require further information from you before we close this issue, these include (values between # symbols require replacement):
```
atmosphere: ECHAM6.3.02p4 (#XXX x XXX# T127L95; #XX# levels; top level 80000 m)
ocean: FESOM 1.4 (unstructured grid in the horizontal with 830305 wet nodes; 46 levels; top grid cell #X-X# m)
land_surface: JSBACH (#WHICH VERSION#)
```

**Comment by durack1** [comment]
@tsemmler05 can you provide the information noted above so we can update and close this issue?

**Comment by tsemmler05** [comment]
O.k., now the additional information is saved.

**Comment by durack1** [comment]
@tsemmler05 if you check the current information for `AWI-CM-1-0` [here](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) you'll see that we still need to update the details noted above. Can you please provide these?

**Comment by tsemmler05** [comment]
Dear Paul!

All this information I have already provided several days ago directly in Github.

Regards,
Tido.

Am 04.02.2017 um 10:45 schrieb Paul J. Durack:

**Comment by tsemmler05** [comment]
Maybe you did not see it because I have just edited the original entry (which still occurs at 17 days ago).

**Comment by durack1** [comment]
@tsemmler05 those changes have now been updated, please take a look at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and double check the final entries

**Comment by durack1** [comment]
@tsemmler05 we've amended the information that we're collecting about models and require some additional information from you. The values below need some revision or new information - I've noted `### some text ###` below where I have revised the format between the `#` symbols, or a ### marker where web links to the information sources for new fields that we require additional information from you:
```
"AWI-CM-1-0":{
  "activity_participation":[
    "" ### See activity list at https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_activity_id.json
  ],
  "atmosphere":"ECHAM6.3.02p4 (T127L95; ###384 x 192 longitude/latitude###; 95 levels; top level 80 km)",
  "nominal_resolution_atmos":"", ### See Appendix 2 in https://goo.gl/v1drZl
  "nominal_resolution_landIce":"", ### See Appendix 2 in https://goo.gl/v1drZl
  "nominal_resolution_ocean":"", ### See Appendix 2 in https://goo.gl/v1drZl
},
```

**Comment by tsemmler05** [comment]
{
    "activity_id":[
        "CMIP DECK",
        "CORDEX",
        "HighResMIP",
        "OMIP",
        "PMIP",
        "ScenarioMIP",
        "SIMIP",
        "VIAAB"
    ],
    "version_metadata":{
        "author":"Tido Semmler <tido.semmler@awi.de>",
        "creation_date":"Wed Mar 29 11:00:52 2017 +0200",
        "institution_id":"AWI",
        "latest_tag_point":"1.1 (394)",
        "repository_root":"https://swrepo1.awi.de/svn/awi-cm",
        "repository_UUID":"4630c9d9-8ccb-0410-a7f8-f558f457bccd"
    }
}

**Comment by tsemmler05** [comment]
"atmosphere":"ECHAM6.3.02p4 (T127L95; ### grid = “native atmosphere T127 gaussian grid (128x256 latxlon)” ###; 95 levels; top level 80 km)",

**Comment by durack1** [comment]
@tsemmler05 this is what I have ascertained from your entries above (and the existing registered fields), please copy and update in a new comment below to correct any issues you see:
```
source_id['AWI-CM-1-0']['activity_participation'] = ['CMIP',
                                                     'CORDEX',
                                                     'HighResMIP',
                                                     'OMIP',
                                                     'PMIP',
                                                     'SIMIP',
                                                     'ScenarioMIP',
                                                     'VIACSAB']
source_id['AWI-CM-1-0']['atmosphere'] = 'ECHAM6.3.02p4 (T127L95 native atmosphere T127 gaussian grid; 384 x 192 longitude/latitude; 95 levels; top level 80 km)'
source_id['AWI-CM-1-0']['nominal_resolution_atmos'] = ['100 km']
source_id['AWI-CM-1-0']['nominal_resolution_landIce'] = ['none']
source_id['AWI-CM-1-0']['nominal_resolution_ocean'] = ['25 km']
source_id['AWI-CM-1-0']['ocean'] = 'FESOM 1.4 (unstructured grid in the horizontal with 830305 wet nodes; 46 levels; top grid cell 0-5 m)'
```

**Comment by tsemmler05** [comment]
source_id['AWI-CM-1-0']['activity_participation'] = ['CMIP',
                                                     'CORDEX',
                                                     'HighResMIP',
                                                     'OMIP',
                                                     'PMIP',
                                                     'SIMIP',
                                                     'ScenarioMIP',
                                                     'VIACSAB']
source_id['AWI-CM-1-0']['atmosphere'] = 'ECHAM6.3.02p4 (T127L95 native atmosphere T127 gaussian grid; 384 x 192 longitude/latitude; 95 levels; top level 80 km)'
source_id['AWI-CM-1-0']['nominal_resolution_atmos'] = ['100 km']
source_id['AWI-CM-1-0']['nominal_resolution_landIce'] = ['none']
source_id['AWI-CM-1-0']['nominal_resolution_ocean'] = ['25 km']
source_id['AWI-CM-1-0']['ocean'] = 'FESOM 1.4 (unstructured grid in the horizontal with 830305 wet nodes; 46 levels; top grid cell 0-5 m)'

**Comment by durack1** [comment]
@tsemmler05 thanks for this, we have included some new fields as well which will also need updating - I have guessed at these and noted this with `### text` below - please confirm these are correct and I will update the registration:
```
activity_participation = ['CMIP',
                                        'CORDEX',
                                        'HighResMIP',
                                        'OMIP',
                                        'PMIP',
                                        'SIMIP',
                                        'ScenarioMIP',
                                        'VIACSAB']
aerosol = None
atmosphere = 'ECHAM6.3.02p4 (T127L95 native atmosphere T127 gaussian grid; 384 x 192 longitude/latitude; 95 levels; top level 80 km)'
atmospheric_chemistry = None
institution_id = AWI
label = AWI-CM 1.0
label_extended = AWI-CM 1.0
land_ice = None
land_surface = JSBACH 3.10
nominal_resolution_aerosol = 'None'
nominal_resolution_atmos = '100 km'
nominal_resolution_atmosChem = 'None'
nominal_resolution_land = 100 km' ### Is this correct?
nominal_resolution_landIce = 'None'
nominal_resolution_ocean = '25 km'
nominal_resolution_ocnBgChem = 'None'
nominal_resolution_seaIce = '25 km' ### Is this correct?
ocean = 'FESOM 1.4 (unstructured grid in the horizontal with 830305 wet nodes; 46 levels; top grid cell 0-5 m)'
ocean_biogeochemistry = None
release_year = 2017
sea_ice = FESOM 1.4
source_id = AWI-CM-1-0
```

**Comment by tsemmler05** [comment]
Yes, thanks for adding the extra entries, I can confirm that these are correct.

**Comment by durack1** [comment]
@tsemmler05 thanks, please take a peek at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any other tweaks are required

**Comment by tsemmler05** [comment]
Looks good!
