### ISSUE TITLE
source_id registration of EMAC-2-53-AerChem

### ISSUE THREAD

**Issue by duycai** [WCRP-CMIP/CMIP6_CVs#217]
*********************************************
## Registering EMAC
*********************************************
"EMAC-2-53-AerChem" : {
    "aerosol":"gmxe 2.2.x",
    "atmosphere:"ECHAM5.30.2 (modified; spectral T42; 128 x 64 longitude/latitude; 90 levels; top level 0.001 hPa) " ,
    "atmospheric_chemistry":"MECCA 3.8.x",
    "cohort":[ ""
    ],
    "institution_id":[ "MESSy-Consortium"],
    "label":"EMAC-2-53-AerChem",
    "label_extended":""EMAC-2-53-x-AerChem",
    "land_ice":"None",
    "land_surface":"same as Atmosphere",
    "ocean":"MPIOM 1.3.0-beta (bipolar GR1.5; approximately 1.5deg latitude/longitude; 40 levels; top grid cell 0-12 m)",
    "ocean_biogeochemistry":"None",
    "release_year":"2017",
    "sea_ice":"thermodynamic (Semtner zero-layer) dynamic (Hibler 79) sea ice model",
    "source_id":"EMAC-2-53-AerChem"
}

**Comment by durack1** [comment]
@duycai `EMAC-2-53-AerChem` is now registered, please review the contents of [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and get back to me with any further amendments

**Comment by duycai** [comment]
@durack1 Sorry I just found a typo. The atmosphere model is ECHAM5.3.02 (not ECHAM5.30.2)

**Comment by durack1** [comment]
@duycai that amendment has been made, please recheck the contents of [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html)
