### ISSUE TITLE
Is the CC link in CMIP6_license.json correct?

### ISSUE THREAD

**Issue by jypeter** [WCRP-CMIP/CMIP6_CVs#221]
The link used is
    http://creativecommons.org/licenses/by/4.0/
but this seems to refer to the "Attribution CC BY" license

BUT the text says the data will be
 either    a) Share Alike
 or    b) NonCommercial Share Alike

So, should not the link be
 either    a) Attribution-ShareAlike CC BY-SA
        https://creativecommons.org/licenses/by-sa/4.0/
 or    b) Attribution-NonCommercial-ShareAlike CC BY-NC-SA
        https://creativecommons.org/licenses/by-nc-sa/4.0/

I got the links from the "The Licenses" section of
    https://creativecommons.org/licenses/?lang=en

If this is modified, it will need to be modified in note 12 of
    https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit 
and
    https://pcmdi.llnl.gov/home/CMIP6/CitationRequirements6-0.html

**Comment by taylor13** [comment]
@jypeter If I change the link to https://creativecommons.org/licenses/ would that be o.k.?  I agree it currently points to the wrong license.

I'd like to point to the same place whether or not the "noncommercial" restriction appears.

**Comment by durack1** [comment]
@taylor13 let me know once a solution has been determined and I'll then change the entry. We will have to propagate these changes across the other entries (google docs, PCMDI webpages etc)

**Comment by jypeter** [comment]
@taylor13 the single link looks good to me!

The following 1-page summary pdf is interesting, if you need to post this information somewhere: https://wiki.creativecommons.org/images/6/6d/6licenses-flat.pdf

Note that you should probably also make the following changes. The wording is currently:
 
> Creative Commons Attribution \\"[NonCommercial] Share Alike\\" 4.0 International License

but I think _Attribution_ should be **inside** the quote, since it is a _license condition_ on the same level as *NonCommercial* and *ShareAlike*. Note also that there is **no space** between _Share_ and _Alike_, and that there seems to be **dashes** between the conditions

> Creative Commons \\"Attribution-[NonCommercial-]ShareAlike\\" 4.0 International License

I wonder if you should also include the matching abbreviation somewhere in the sentence
> (CC BY-[NC-]SA 4.0)

I have used the following to help PMIP4 participants: https://pmip4.lsce.ipsl.fr/doku.php/database:drs#details_about_the_creative_commons_licenses

**Comment by taylor13** [comment]
@jypeter Thanks, J-Y.  That was very helpful.  I've made changes to
the global attributes doc, the CMIP6_license_CV, and to the document that will migrate to https://pcmdi.llnl.gov/home/CMIP6/CitationRequirements6-0.html

**Comment by jypeter** [comment]
I see you have removed the quotes around the conditions. That's probably not bad, since the CC licenses do not have quotes in their examples

I wonder if we should have quotes around the full license (and use a lowercase "L" in "license"), to emphasize it, but I'm not too sure. That's up to you

> is licensed under a \\"Creative Commons Attribution-[NonCommercial-]ShareAlike 4.0 International\\" license

The licences' page URL you have specified works, but you may want to add a trailing "/" if you make changes to CMIP6_license.json anyway

> https://creativecommons.org/licenses/

**Comment by durack1** [comment]
@taylor13 I've noted some changes have been made in the [CMIP6_license.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_license.json) file, but it's not clear to me that this issue is resolved with this amendment. Please let me know once this is finalised, and I'll pull the changes back into the master and update the file metadata accordingly

**Comment by jypeter** [comment]
Thanks @durack1 !

By the way, is there an issue section for the CMIP6 web site, more specifically for the https://pcmdi.llnl.gov/home/CMIP6/CitationRequirements6-0.html that will have to be updated because of the license update?

Because I have been asked to add something to **acknowledge the MIPs**. So,should I just send a mail to @taylor13 about that, or can I open an issue somewhere?

And there should be another issue so that somebody adds some metadata keyword information to the page, so that people can discover it when googling *cmip6 acknowledgement* and *cmip6 terms of use*

**Comment by durack1** [comment]
@jypeter good question, I don't believe we have an alternative repo/issue list for your query so it might be best to keep that discussion in this repo (as it relates to the CMIP6 license details anyway). I'll let @taylor13 respond
