### ISSUE TITLE
source_id registration of CIESM

### ISSUE THREAD

**Issue by yjyangjie** [WCRP-CMIP/CMIP6_CVs#226]
```
aerosol = MAM4
atmosphere = CIESM-AM (FV/FD, 288 x 192; 30 levels; top level 2.255 hPa )
atmospheric_chemistry = trop_mam4
institution_id = THU
label = CIESM
label_extended = Community Integrated Earth System Model
land_ice = None
land_surface = CIESM-LM (modified CLM4.5)
ocean = CIESM-OM (FD, SCCGrid Displaced Pole, 720x560; 46 levels)
ocean_biogeochemistry = None
sea_ice = CICE4
source_id = CIESM
```

**Comment by durack1** [comment]
@yjyangjie can you please provide the missing information indicated below between @ symbols?
```
        "CIESM":{
            "aerosol":"MAM4",
            "atmosphere":"CIESM-AM (FV/FD, 288 x 192; 30 levels; top level 2.255 hPa)",
            "atmospheric_chemistry":"trop_mam4",
            "cohort":[
                ""
            ],
            "institution_id":[
                "THU"
            ],
            "label":"CIESM",
            "label_extended":"Community Integrated Earth System Model",
            "land_ice":"None",
            "land_surface":"CIESM-LM (modified CLM4.5)",
            "ocean":"CIESM-OM (FD, SCCGrid Displaced Pole, 720x560; 46 levels; top grid cell @X-X m@)",
            "ocean_biogeochemistry":"None",
            "release_year":"@XXXX@",
            "sea_ice":"CICE4",
            "source_id":"CIESM"
        },
```

**Comment by yjyangjie** [comment]
"CIESM":{
            "aerosol":"MAM4",
            "atmosphere":"CIESM-AM (FV/FD, 288 x 192; 30 levels; top level 2.255 hPa)",
            "atmospheric_chemistry":"trop_mam4",
            "cohort":[
                ""
            ],
            "institution_id":[
                "THU"
            ],
            "label":"CIESM",
            "label_extended":"Community Integrated Earth System Model",
            "land_ice":"None",
            "land_surface":"CIESM-LM (modified CLM4.5)",
            "ocean":"CIESM-OM (FD, SCCGrid Displaced Pole, 720x560; 46 levels; top grid cell 0-3 m)",
            "ocean_biogeochemistry":"None",
            "release_year":"2016",
            "sea_ice":"CICE4",
            "source_id":"CIESM"
        },

**Comment by yjyangjie** [comment]
@durack1 
"CIESM":{
"aerosol":"MAM4",
"atmosphere":"CIESM-AM (FV/FD, 288 x 192; 30 levels; top level 2.255 hPa)",
"atmospheric_chemistry":"trop_mam4",
"cohort":[
""
],
"institution_id":[
"THU"
],
"label":"CIESM",
"label_extended":"Community Integrated Earth System Model",
"land_ice":"None",
"land_surface":"CIESM-LM (modified CLM4.5)",
"ocean":"CIESM-OM (FD, SCCGrid Displaced Pole, 720x560; 46 levels; top grid cell 0-3 m)",
"ocean_biogeochemistry":"None",
"release_year":"2016",
"sea_ice":"CICE4",
"source_id":"CIESM"
},

**Comment by yjyangjie** [comment]
@durack1
"CIESM":{
"aerosol":"MAM4",
"atmosphere":"CIESM-AM (FV/FD, 288 x 192; 30 levels; top level 2.255 hPa)",
"atmospheric_chemistry":"trop_mam4",
"cohort":[
""
],
"institution_id":[
"THU"
],
"label":"CIESM",
"label_extended":"Community Integrated Earth System Model",
"land_ice":"None",
"land_surface":"CIESM-LM (modified CLM4.5)",
"ocean":"CIESM-OM (FD, SCCGrid Displaced Pole, 720x560; 46 levels; top grid cell 0-3 m)",
"ocean_biogeochemistry":"None",
"release_year":"2017",
"sea_ice":"CICE4",
"source_id":"CIESM"
},

**Comment by yjyangjie** [comment]
@durack1
"CIESM":{
"aerosol":"MAM4",
"atmosphere":"CIESM-AM (FV/FD, 288 x 192; 30 levels; top level 2.255 hPa)",
"atmospheric_chemistry":"trop_mam4",
"cohort":[
""
],
"institution_id":[
"THU"
],
"label":"CIESM",
"label_extended":"Community Integrated Earth System Model",
"land_ice":"None",
"land_surface":"CIESM-LM (modified CLM4.5)",
"ocean":"CIESM-OM (FD, SCCGrid Displaced Pole, 720x560; 46 levels; top grid cell 0-6 m)",
"ocean_biogeochemistry":"None",
"release_year":"2017",
"sea_ice":"CICE4",
"source_id":"CIESM"
},

**Comment by durack1** [comment]
@yjyangjie take a peek at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further tweaks are required. We can continue to update this entry until the point that you start writing CMIP6 data

**Comment by durack1** [comment]
@yjyangjie we have recently augmented the information we are collecting for registration, so we will require some additional information from you. I have made some amendments to the existing entries below, and will require you to fill out the fields with the `###` informational text directing you to descriptive information about the request, or lists of potential entries

```
"CIESM":{
   "activity_participation":[
      "" ### See activity list at https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_activity_id.json
   ],
"aerosol":
   "description":"MAM4",
   "nominal_resolution":"" ### See Appendix 2 in https://goo.gl/v1drZl (likely same at atmos below)
"atmos":
   "description":"CIESM-AM (FV/FD; 288 x 192 longitude/latitude; 30 levels; top level 2.255 hPa)",
   "nominal_resolution":"" ### See Appendix 2 in https://goo.gl/v1drZl
"atmosChem":
   "description":"trop_mam4",
   "nominal_resolution":""
"land":
   "description":"CIESM-LM (modified CLM4.5)",
   "nominal_resolution":"" ### See Appendix 2 in https://goo.gl/v1drZl (likely same at atmos above)
"ocean":
   "description":"CIESM-OM (FD, SCCGrid Displaced Pole; 720 x 560 longitude/latitude; 46 levels; top grid cell 0-6 m)",
   "nominal_resolution":"" ### See Appendix 2 in https://goo.gl/v1drZl
"seaIce":
   "description":"CICE4",
   "nominal_resolution":"" ### See Appendix 2 in https://goo.gl/v1drZl (likely same at ocean above)
```

**Comment by yjyangjie** [comment]
@durack1 
"CIESM":{
   "activity_participation":[
       "CFMIP",
       "CORDEX",
       "SIMIP",
       "GMMIP",
       "OMIP",
       "ScenarioMIP",
   ],
"aerosol":
   "description":"MAM4",
   "nominal_resolution":"100 km"
"atmos":
   "description":"CIESM-AM (FV/FD; 288 x 192 longitude/latitude; 30 levels; top level 2.255 hPa)",
   "nominal_resolution":"100 km"
"atmosChem":
   "description":"trop_mam4",
   "nominal_resolution":"100 km"
"land":
   "description":"CIESM-LM (modified CLM4.5)",
   "nominal_resolution":"100 km" 
"ocean":
   "description":"CIESM-OM (FD, SCCGrid Displaced Pole; 720 x 560 longitude/latitude; 46 levels; top grid cell 0-6 m)",
   "nominal_resolution":"50 km"
"seaIce":
   "description":"CICE4",
   "nominal_resolution":"50 km"

**Comment by durack1** [comment]
@yjyangjie I presume you'll also be participating in the `CMIP` activity?

**Comment by yjyangjie** [comment]
@durack1  yes. I am going to participate in the CMIP activity.

**Comment by durack1** [comment]
@yjyangjie thanks for the update, please check the revised entries at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further amendments are required

**Comment by durack1** [comment]
@yjyangjie I've just been starting a new OHC analysis and stumbled across the fact that CIESM ['r1i1p1f1'] has 60 vertical levels in the output, whereas the reporting above says 46 - is this a typo that should be fixed? If yes, please reopen this issue and I'll correct the registration
