### ISSUE TITLE
source_id registration MIROC6

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#229]
@tatebeJAMSTEC please review and provide values for the items indicated between @XXX@ symbols
```
        "MIROC6":{
            "aerosol":"SPRINTARS @VERSION INFO?@",
            "atmosphere":"CCSR AGCM (T85; @XXX x XXX longitude/latitude@; 81 levels; top level 0.004 hPa)",
            "atmospheric_chemistry":"None",
            "cohort":[
                ""
            ],
            "institution_id":[
                "MIROC"
            ],
            "label":"MIROC6",
            "label_extended":"MIROC6",
            "land_ice":"None",
            "land_surface":"MATSIRO @XXX VERSION INFO? XXX@",
            "ocean":"COCO4.9 (360x256x63; tripolar primarily 1deg; 63 levels; top grid cell 0-2 m)",
            "ocean_biogeochemistry":"None",
            "release_year":"2017",
            "sea_ice":"COCO4.9",
            "source_id":"MIROC6"
        },
```

**Comment by tatebeJAMSTEC** [comment]
Dear Dr. Durack,

We are very sorry for the late response!
We have filled the items between @ sysbols, as

"MIROC6":{
            "aerosol":"SPRINTARS6.0",
            "atmosphere":"CCSR AGCM (T85; 256x128; 81 levels; top
level 0.004 hPa)",
            "atmospheric_chemistry":"None",
            "cohort":[
                ""
            ],
            "institution_id":[
                "MIROC"
            ],
            "label":"MIROC6",
            "label_extended":"MIROC6",
            "land_ice":"None",
            "land_surface":"MATSIRO6.0",
            "ocean":"COCO4.9 (360x256x63; tripolar primarily 1deg; 63
levels; top grid cell 0-2 m)",
            "ocean_biogeochemistry":"None",
            "release_year":"2017",
            "sea_ice":"COCO4.9",
            "source_id":"MIROC6"
        },

Soon, we will submit the other source_id of institution_id "MIROC".

Thank you very much for your cooperation.

Hiroaki Tatebe

2017-02-22 2:27 GMT+09:00 Paul J. Durack <notifications@github.com>:

**Comment by durack1** [comment]
@tatebeJAMSTEC take a look at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further edits are required

**Comment by durack1** [comment]
@tatebeJAMSTEC we have augmented the fields that we are capturing in our `source_id`registrations. Can you please add in the `activity_participation` and `nominal_resolution` fields missing in [your `MIROC6` registration](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L2125-L2173) - there are some guidance notes for completing these fields found in [Model_registration_template.md](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/.github/Model_registration_template.md).

**Comment by durack1** [comment]
@tatebeJAMSTEC we have augmented the fields that we are capturing in our `source_id`registrations. Can you please add in the `activity_participation` and `nominal_resolution` fields missing in [your `MIROC6` registration](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L2329-L2377) - there are some guidance notes for completing these fields found in [Model_registration_template.md](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/.github/Model_registration_template.md).

We will also need the same information for [`MIROC-ES2H`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L2231-L2279), `MIROC-ES2L`, [`NICAM16-7S`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L2591-L2639), `NICAM16-8S`, `NICAM16-9D-L78` and `NICAM16-9S`

**Comment by durack1** [comment]
@tatebeJAMSTEC I am curious if you have been able to review the open query above. I wonder are you the appropriate contact to resolve these issues? If not, can you please redirect this query to the appropriate contact?

**Comment by xxx** [comment]
Hello. You summoned me?

**Comment by durack1** [comment]
@tatebeJAMSTEC thanks for the #384 pull request. We have a [controlled vocabulary for the `nominal_resolution` values](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_nominal_resolution.json) so I had to amend your suggested changes to agree with these. The final changes are listed in #385, please take a look at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further edits are required

**Comment by durack1** [comment]
@tatebeJAMSTEC we have amended the `activity_participation` entry for `NICAM16-7S`, `NICAM16-8S`, `NICAM16-9D-L78`, and `NICAM16-9S` to include `CMIP`, as this experiment suite (`piControl` etc) is a required component of contributing to the CMIP6 project

For reference this change was made in WCRP-CMIP/CMIP6_CVs#475
