### ISSUE TITLE
source_id -- change "cohort" entries

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#230]
The correct "cohort" for a model that has been registered, but not yet qualified for any other cohort is "Registered".  So, all the current entries that read 

"cohort":[
                ""
            ],

should be changed to read:

"cohort":[
                "Registered"
            ],

**Comment by durack1** [comment]
@taylor13 is this status being maintained anywhere, or just in this repo?

**Comment by taylor13** [comment]
We're the reference for this.  Those publishing datasets will access it daily to check for any change in status, and then if a change has been made, they will update the ESGF catalogs.

**Comment by durack1** [comment]
@taylor13 yes I did think we were.. How will we be triggered for a status change, when data is being written/published?

**Comment by taylor13** [comment]
Not sure but I think they'll run a chron-like job that obtains the latest .json file, then cycle through all the sources they have published (but not including replicas) at their site and check whether cohort status has changed.  Once changed at the original site, replica sites will get updated quasi-automatically.  Will speak with Sasha about this to confirm.
