### ISSUE TITLE
source_id registration of EMAC-2-53-Vol

### ISSUE THREAD

**Issue by smisios** [WCRP-CMIP/CMIP6_CVs#231]
"EMAC-2-53-Vol" : {
    "aerosol":"gmxe 2.2.x",
    "atmosphere:"ECHAM5.3.2 (modified; spectral T42; 128 x 64 longitude/latitude; 90 levels; top level 0.001 hPa) " ,
    "atmospheric_chemistry":"MECCA 3.8.x",
    "cohort":[ ""
    ],
    "institution_id":[ "MESSy-Consortium"],
    "label":"EMAC-2-53-Vol",
    "label_extended":""EMAC-2-53-x-Vol",
    "land_ice":"None",
    "land_surface":"same as Atmosphere",
    "ocean":"MPIOM 1.3.0-beta (bipolar GR1.5; approximately 1.5deg latitude/longitude; 40 levels; top grid cell 0-12 m)",
    "ocean_biogeochemistry":"None",
    "release_year":"2017",
    "sea_ice":"thermodynamic (Semtner zero-layer) dynamic (Hibler 79) sea ice model",
    "source_id":"EMAC-2-53-Vol"

**Comment by durack1** [comment]
@smisios thanks for this, can you add the additional information contained between @XXX@ symbols below please:
```
"EMAC-2-53-Vol" : {
    "aerosol":"gmxe 2.2.x",
    "atmosphere:"ECHAM5.3.2 (modified; spectral T42; 128 x 64 longitude/latitude; 90 levels; top level 0.001 hPa) " ,
    "atmospheric_chemistry":"MECCA 3.8.x",
    "cohort":[ ""
    ],
    "institution_id":[ "MESSy-Consortium"],
    "label":"EMAC-2-53-Vol",
    "label_extended":""EMAC-2-53-x-Vol",
    "land_ice":"None",
    "land_surface":"same as Atmosphere",
    "ocean":"MPIOM 1.3.0-beta (bipolar GR1.5; approximately 1.5deg, @XXX x XXX@ longitude/latitude; 40 levels; top grid cell 0-12 m)",
    "ocean_biogeochemistry":"None",
    "release_year":"2017",
    "sea_ice":"thermodynamic (Semtner zero-layer) dynamic (Hibler 79) sea ice model @XX VERSION_INFO? XX@",
    "source_id":"EMAC-2-53-Vol"
```

**Comment by durack1** [comment]
@smisios any luck in getting those additional details?

**Comment by smisios** [comment]
Apologies for my slowness. I contacted the model developers but there is no further information to be added, i am afraid.

for @XXX x XXX@ longitude/latitude, the number of lon/lat is variable. All formation is described by "Bipolar GR1.5"
For @XX VERSION_INFO? XX@. No version is provided.

I hope it helps.
Best wishes,
Stergios

**Comment by durack1** [comment]
@smisios the likely ocean resolution (assuming 1.5 degrees) is `240 x 120 longitude/latitude`. If prototype output from the model is available this information should be relatively easy to ascertain.

The sea_ice model version identifier I can't guess however.

**Comment by smisios** [comment]
It is a rotated grid with x:256 and y:220 points with variable grid size. It does not translate one-to-one to lon/lat of constant size. The size at equator is 1.5 degree and becomes smaller towards the poles.
I am afraid i cannot guess either the sea-ice version. I would suggest to keep it as it is in the original description.

Best wishes,
Stergios

**Comment by durack1** [comment]
@smisios take a peek at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further details need to be updated

**Comment by smisios** [comment]
Dear Paul,
it came to my attention an error on the description of EMAC-2-53-Vol
90 levels; top level 0.001 hPa should be 47 levels; top level 0.01 hPa, instead.
Would it be possible to correct this oversight?

Best wishes,
Stergios

**Comment by durack1** [comment]
@smisios good timing, we needed to get some additional details from you for both [`EMAC-2-53-Vol`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L1196-L1244) and [`EMAC-2-53-AerChem`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L1147-L1195). These include the `activity_participation` and the `nominal_resolution` for all active model components (listed below)

I've appended the entries we need for `EMAC-2-53-Vol` below (as well as the amended `atmos` description and other fields for your review), and we'll need similar information for `EMAC-2-53-AerChem`
```
"EMAC-2-53-Vol":{
"activity_participation":[
   ""  ### See activity list at https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_activity_id.json
],
"cohort":[
   "Registered"
],
"institution_id":[
   "MESSy-Consortium"
],
"label":"EMAC-2-53-Vol",
"label_extended":"EMAC-2-53-x-Vol",
"model_component":{
"aerosol":
   "description":"gmxe 2.2.x",
   "nominal_resolution":""  ### See Appendix 2 in https://goo.gl/v1drZl
"atmos":
   "description":"ECHAM5.3.2 (modified; spectral T42; 128 x 64 longitude/latitude; 47 levels; top level 0.01 hPa)",
   "nominal_resolution":""
 "atmosChem":
   "description":"MECCA 3.8.x",
   "nominal_resolution":""
"land":
   "description":"same as Atmosphere",
   "nominal_resolution":""
"ocean":
   "description":"MPIOM 1.3.0-beta (bipolar GR1.5; approximately 1.5deg reducing toward the poles, 256 x 220 longitude/latitude; 40 levels; top grid cell 0-12 m)",
   "nominal_resolution":""
"seaIce":{
   "description":"thermodynamic (Semtner zero-layer) dynamic (Hibler 79) sea ice model",
   "nominal_resolution":""
```

**Comment by durack1** [comment]
@smisios, @PhoebeGraf provided the updates for `EMAC-2-53-AerChem` so we only require the `EMAC-2-53-Vol` updates noted above to close this issue

**Comment by durack1** [comment]
@smisios have you had any luck collecting the information requested above?

**Comment by smisios** [comment]
Sorry for being so slow,
Is this what is needed?
best wishes,
Stergios


   "EMAC-2-53-Vol":{
           "activity_participation":[
                "VolMIP", "CMIP" 
            ],
            "aerosol":"gmxe 2.2.x",
            "nominal_resolution_aerosol":"500 km", 
            "atmosphere":"ECHAM5.3.02 (modified; spectral T42; 128 x 64 longitude/latitude; 47 levels; top level 0.01 hPa)",
            "nominal_resolution_atmos":"500 km", 
            "atmospheric_chemistry":"MECCA 3.8.x",
            "nominal_resolution_atmosChem":"500 km", 
            "cohort":[
                "Registered"
            ],
            "institution_id":[
                "MESSy-Consortium"
            ],
            "label":"EMAC-2-53-Vol",
            "label_extended":"EMAC-2-53-x-Vol",
            "land_ice":"None",
            "nominal_resolution_landIce":"None",
            "land_surface":"same as Atmosphere",
            "nominal_resolution_land":"500 km", 
            "ocean":"MPIOM 1.3.0-beta (bipolar GR1.5; approximately 1.5deg latitude/longitude; 40 levels; top grid cell 0-12 m)",
            "nominal_resolution_ocean":"250 km", 
            "ocean_biogeochemistry":"None",
            "nominal_resolution_ocnBgchem":"None"
            "sea_ice":"thermodynamic (Semtner zero-layer) dynamic (Hibler 79) sea ice model",
            "nominal_resolution_seaIce":"250 km", 
            "release_year":"2017",
            "source_id":"EMAC-2-53-Vol"
},

**Comment by durack1** [comment]
@smisios thanks for this, peek at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further tweaks are required
