### ISSUE TITLE
update of information about source_id MRI-ESM2-0

### ISSUE THREAD

**Issue by yukimotoster** [WCRP-CMIP/CMIP6_CVs#234]
update of information about source_id MRI-ESM2-0

    aerosol = MASINGAR mk2r4
    atmosphere = MRI-AGCM3.5 (320 x 160 TL159; 80 levels; top level 0.01 hPa)   
    atmospheric_chemistry = MRI-CCM2.1
    institution_id = MRI
    label = MRI-ESM2.0
    label_extended = MRI-ESM2.0
    land_ice = None
    land_surface = HAL 1.0
    ocean = MRI.COM4.4 (tripolar primarily 0.5 deg latitude/1 deg longitude with meridional refinement down to 0.3 deg within 10 degrees north and south of the equator; 61 levels; top grid cell 0-2 m)
    ocean_biogeochemistry = MRI.COM4.4
    release_year = 2017
    sea_ice = MRI.COM4.4
    source_id = MRI-ESM2-0

**Comment by durack1** [comment]
@yukimotoster thanks for this, can I confirm that the additional information included below is correct? (The values between the ### ###)
```
 ocean = MRI.COM4.4 (tripolar primarily 0.5 deg latitude/1 deg longitude with meridional refinement down to 0.3 deg within 10 degrees north and south of the equator; ###360 x 360 longitude###/latitude; 61 levels; top grid cell 0-2 m)
```

**Comment by yukimotoster** [comment]
The ocean grid is ###360 x 364 longitude/latitude###.

**Comment by durack1** [comment]
@yukimotoster take a look at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further edits are required
