### ISSUE TITLE
Convert html to https

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#248]
It seems that rawgit is starting to intermittently force `https` connections, when most of the internal links in html files are `http`. To maintain a consistent experience all file headers should be updated to `https`, which will likely require many of the externally sourced files to be duplicated in this repo

@doutriaux1 is a good test case, as he uses Chrome which seems to complain more than Firefox or Safari - ping him once changes are in place

Some relevant links:
http://code.jquery.com/jquery/
https://www.datatables.net/
[Firefox] view-source:http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html
http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html

**Comment by doutriaux1** [comment]
@durack1 yes https seems to be the path forward, unless you keep the local version to allow for offline browsing.

**Comment by durack1** [comment]
@doutriaux1 it was getting too hard to maintain it across the different sources, so forcing it local (with the minimized files to reduce the footprint) was the most ***robust*** path forward that I could ascertain
