### ISSUE TITLE
source_id -- Additional info. to request

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#249]
1.  We should ask groups what activities (i.e., which MIPs) they plan to participate in. 
2.  For each model component, we should ask them to provide the nominal_resolution of the model's *native* grid
3.  In the source attribute, we should specify what information should appear, and any grid information should reflect the model's native grid (which might be different from the grid they plan to provide their output on).

**Comment by durack1** [comment]
@taylor13 we could add in `activity_participation`, `nominal_resolution_atmosphere`, `nominal_resolution_ocean`, `nominal_resolution_landice`

We'll also need to update the [ISSUE_TEMPLATE.md](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/.github/ISSUE_TEMPLATE.md) to reflect the specifics, outline that listed components are **native** resolutions too

**Comment by durack1** [comment]
@taylor13 I am including the following:
```
{
    "source_id":{
         "ACCESS-1-0":{
            "activity_participation":[
                       ''
                       ],
...
            "nominal_resolution_atmos":""
            "nominal_resolution_landIce":""
            "nominal_resolution_ocean":""
...
```
Is that it? And are the types (list, string etc) right?

**Comment by durack1** [comment]
@taylor13 this link should get you to [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/93bc450d87bd21f64230597a6c29d8a3b772b76c/src/CMIP6_source_id.html)

**Comment by taylor13** [comment]
looks good.  correct types, etc.  just need to update template before closing.

**Comment by durack1** [comment]
@taylor13 with the template I think we need to simplify things a lot and declare what info is native grid, and also indicate more clearing what is required, versus what is desired
