### ISSUE TITLE
Tweaks to json_to_html.py

### ISSUE THREAD

**Issue by doutriaux1** [WCRP-CMIP/CMIP6_CVs#25]
Per @taylor13's  email

Indicate the Controlled Vocabulary (CV) of interest: experiment_id (rendering as html table)

When we get to this, three changes are the priority:

for column headings remove all "_", so that text can "wrap" and columns will be better spaced.

Order of columns should be:

experiment id
activity id
experiment
tier
sub experiment id
sub experiment
parent experiment id
required model components
additional allowed model components
start year
end year
min number yrs per sim
parent activity id
description

Can we make it possible to scroll through all rows of the table? Now, you have to keep pressing "next" to get to the next group. (At most you can scroll through 100 rows before pressing "next".) If we can scroll through all rows, then a user could also, I think, print out the table with a single "print" click.
thanks,
Karl

**Comment by durack1** [comment]
@taylor13 @dnadeau4 take a look at this updated format - the 100 limit is determined by an external library.

@taylor13 take a look at the attached file (remove the *.txt so you can view this in a browser) and if this suits, we can close this standing issue
[CMIP6_experiment_id.html.txt](https://github.com/WCRP-CMIP/CMIP6_CVs/files/423148/CMIP6_experiment_id.html.txt)

**Comment by durack1** [comment]
@taylor13 @dnadeau4 the attached file should solve all the requirements for this issue - so have closed
[CMIP6_experiment_id.html.txt](https://github.com/WCRP-CMIP/CMIP6_CVs/files/423196/CMIP6_experiment_id.html.txt)

**Comment by durack1** [comment]
@taylor13 take a peek above - out of inboxes..

**Comment by taylor13** [comment]
@durack1 -- looks pretty good, but it seems that the column widths are set by the the width of the column labels at the top.  We could squeeze the information together if we removed the "_" from the header labels (as I suggested before).  Would that not be a good idea?
Also, if I want to give access to someone on the outside, do I have to send them the CMIP6_experiment_id.html.txt file, or can I point them to a link that will just display the table?
thanks,
Karl

**Comment by durack1** [comment]
@taylor13 this is what needs to be sent as part of the email (either the attachment or the link) that is drafted in the google doc (link in your inbox from yesterday morning)..

Regarding the formatting, we could iterate for the next couple of months on colours, shapes, languages etc.. Or we could just send it :smiley: - to me the most important thing here is the content, not the presentation, the presentation is just a way of conveying the information not a persistent format..

**Comment by durack1** [comment]
@taylor13 having said the above, I *could* also just make the tweak that you suggest.. I have some other stuff to finalize this morning so this could be added to the list..

**Comment by durack1** [comment]
Reopening.. as @taylor13 is not very keen on `"_"` characters..

**Comment by durack1** [comment]
@taylor13 ok so this should appease the html gods.. We can now use this file to interact with MIP co-chairs..
[CMIP6_experiment_id.html.txt](https://github.com/WCRP-CMIP/CMIP6_CVs/files/440372/CMIP6_experiment_id.html.txt)

**Comment by durack1** [comment]
@taylor13 point your browser to:
http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html
and voila!

**Comment by doutriaux1** [comment]
@durack1 what happened to all of the jquery tables niceness? column sorting etc...?

**Comment by durack1** [comment]
@doutriaux1 did you click the link above? Or for your direct pleasure:

http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html

**Comment by durack1** [comment]
@doutriaux1 make sure to use a `"http://"` rather than the default `"https://"` in your viewing

**Comment by doutriaux1** [comment]
@durack1 I clicked on your link.

**Comment by durack1** [comment]
@doutriaux1 try again.. the updated link above..

**Comment by doutriaux1** [comment]
nope, no luck

**Comment by doutriaux1** [comment]
I'm on chrome inside the lab firewall.

**Comment by doutriaux1** [comment]
robust ness issue:
```
Refused to execute script from 'https://raw.githubusercontent.com/WCRP-CMIP/CMIP6_CVs/master/src/jquery.dataTables.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
CMIP6_experiment_id.html:9 Uncaught TypeError: $(...).DataTable is not a function
```

**Comment by durack1** [comment]
@doutriaux1 "robustness" *should* be returned, I now get:
```html
<html>
<head>
<link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.10.12/css/jquery.dataTables.css">
<script type="text/javascript" src="http://code.jquery.com/jquery-1.12.4.js"></script>
<script type="text/javascript" charset="utf8" src="http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/jquery.dataTables.js"></script>
<script>
$(document).ready( function () {
    $('#table_id').DataTable();
    } );
</script>
</head>
```
Wanna try on your problematic browser?
