### ISSUE TITLE
Clean up CMIP6_required_global_attributes.json

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#250]
Some changes to `CMIP6_required_global_attributes.json ` were made by @taylor13 to bring this up-to-date with the latest [CMIP6_global_attributes_filenames_CVs](http://goo.gl/v1drZl).

The details are described in a pdf housed at https://github.com/PCMDI/cmor/issues/145#issue-214874627

@taylor13 just to confirm, you want `branch_method` and the duplicate `variant_label` deleted right?

**Comment by cmip6** [comment]
yes but only *1* of the variant_label entries.

**Comment by durack1** [comment]
@taylor13 done, take a peek at [CMIP6_required_global_attributes.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_required_global_attributes.json)
