### ISSUE TITLE
experiment_id correction to 2 i.d.'s

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#258]
@durack1 Piers Forester and Robert Pincus request the following changes:

experiment_id ="piClim-aerO3" be changed to "piClim-aer"
and 
experiment_id = "piClim-histaer03" be changed to "piClim-histaer"

In the first case the "experiment" should read "effective radiative forcing by present-day aerosols".

(experiment is o.k in the second case).

**Comment by durack1** [comment]
@taylor13 I assume for `piClim-aer` the description also needs amending:
```
"description":"As in RFMIP-ERF-PI-Cntrl but with with present-day aerosols and ozone"
"experiment":"effective radiative forcing by present-day aerosols and ozone"
TO
"description":"As in RFMIP-ERF-PI-Cntrl but with with present-day aerosols"
"experiment":"effective radiative forcing by present-day aerosols"
```
Are any amendments required to `piClim-histaer`? There is no mention of ozone in the `description` or `experiment` fields

**Comment by taylor13** [comment]
no piClim-histaer just had the wrong i.d.  In the other case, yes, please change the experiment_id, the experiment, and the description (leaving out mention of ozone).

**Comment by charliepascoe** [comment]
So to be clear, piClim-aer has present day aerosol forcing and pre-industrial ozone forcing.

**Comment by durack1** [comment]
@charliepascoe did you want to further amend the `description` or `experiment` to make this more explicit?

**Comment by taylor13** [comment]
@charliepascoe As you probably know, you can see the current expt. info. either at  http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html or https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json

**Comment by charliepascoe** [comment]
Hi Paul, No need for updates. I just wanted to be sure, following the discussion, that the RFMIP piClim-aer experiment was the same as then RFMIP piClim-aerO3 experiment.

**Comment by durack1** [comment]
@charliepascoe no probs, we have this updated now take a peek [here](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json#L5234-L5262) - and I think this now closes out any unresolved loose ends
