### ISSUE TITLE
Updates to NorESM2 registered models

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#259]
Hi @IngoBethke, we are centralizing some additional information for each of the registered models and consequently we require this additional information to add to your existing registrations. These new fields are currently blank in your [existing registrations](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L945-L1100).

The `activity_participation` is the **expected** activities/MIPs (by expected, we mean the MIPs that you expect to submit data for) that the model with contribute to, so these include the full MIP list, but may just be limited to `CMIP` for e.g. For the nominal resolution, this is the approximate resolution for the full global grid (so the average) that fits into one of the entries found in the [CMIP6_nominal_resolution.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_nominal_resolution.json) file. I've included the information listed for each model below:
```
NorESM2-HH
activity_participation = ['']  ### See activity list at https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_activity_id.json ###
nominal_resolution_atmos = '' ### See Appendix 2 in https://goo.gl/v1drZl ###
nominal_resolution_landIce = '' ### See Appendix 2 in https://goo.gl/v1drZl ###
nominal_resolution_ocean = '' ### See Appendix 2 in https://goo.gl/v1drZl ###
NorESM2-LM
activity_participation = ['']
nominal_resolution_atmos = ''
nominal_resolution_landIce = ''
nominal_resolution_ocean = ''
NorESM2-LME
activity_participation = ['']
nominal_resolution_atmos = ''
nominal_resolution_landIce = ''
nominal_resolution_ocean = ''
NorESM2-LMEC
activity_participation = ['']
nominal_resolution_atmos = ''
nominal_resolution_landIce = ''
nominal_resolution_ocean = ''
NorESM2-MH
activity_participation = ['']
nominal_resolution_atmos = ''
nominal_resolution_landIce = ''
nominal_resolution_ocean = ''
NorESM2-MM
activity_participation = ['']
nominal_resolution_atmos = ''
nominal_resolution_landIce = ''
nominal_resolution_ocean = ''
```

**Comment by IngoBethke** [comment]
Hi Paul, 

Sorry for late reply. Here is some input: 

NorESM2-HH
activity_participation = ['HighResMIP']  ### See activity list at https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_activity_id.json ###
nominal_resolution_atmos = '25 km' ### See Appendix 2 in https://goo.gl/v1drZl ###
nominal_resolution_landIce = '25 km ' ### See Appendix 2 in https://goo.gl/v1drZl ###
nominal_resolution_ocean = '25 km' ### See Appendix 2 in https://goo.gl/v1drZl ###
NorESM2-LM
activity_participation = ['AerChemMIP','CFMIP','DAMIP','DCPP','LUMIP','OMIP','PMIP','RFMIP','ScenarioMIP','VolMIP']
nominal_resolution_atmos = '250 km'
nominal_resolution_landIce = '250 km'
nominal_resolution_ocean = '100 km'
NorESM2-LME
activity_participation = ['C4MIP','GeoMIP','OMIP','LUMIP']
nominal_resolution_atmos = '250 km'
nominal_resolution_landIce = '250 km'
nominal_resolution_ocean = '100 km'
NorESM2-LMEC
activity_participation = ['AerChemMIP']
nominal_resolution_atmos = '250 km'
nominal_resolution_landIce = '250 km'
nominal_resolution_ocean = '100 km'
NorESM2-MH
activity_participation = ['AerChemMIP','CFMIP','RFMIP','DAMIP','OMIP','ScenarioMIP']
nominal_resolution_atmos = '100 km'
nominal_resolution_landIce = '100 km'
nominal_resolution_ocean = '25 km'
NorESM2-MM
activity_participation = ['AerChemMIP','CFMIP','RFMIP','DAMIP','OMIP','ScenarioMIP']
nominal_resolution_atmos = '100 km'
nominal_resolution_landIce = '100 km'
nominal_resolution_ocean = '100 km'

**Comment by durack1** [comment]
@IngoBethke great, I assume that at least one of these models will be contributing to the CMIP6 DECK experiments (piControl, 1pctCO2, amip, historical ..) and therefore we're missing a `CMIP` entry in the above.. Do you also want to amend the post above removing the `###` placeholder text just so we're on the same page with what will be written

**Comment by IngoBethke** [comment]
done

**Comment by durack1** [comment]
@IngoBethke thanks for providing these updates which are now merged, please take one last look at the registered entries by browsing [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if there are any other tweaks required..

**Comment by IngoBethke** [comment]
Thanks for updating our entries.

To be consistent with the other entries, I'd suggest to change the extended label of NorESM2-MH to "NorESM2-MH (medium atmosphere-high ocean resolution, GHG concentration driven)".

Otherwise, everything looks fine.

**Comment by durack1** [comment]
@IngoBethke great, that's done. Thanks!
