### ISSUE TITLE
experiment_id  AerChemMIP piClim_aer expt. deleted?

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#261]
piClim_aer appeared under both AerChemMIP and RFMIP, and somehow got deleted without notice from AerChemMIP.  It should only appear once, but we haven't decided yet whether it should be under RFMIP or AerChemMIP.

**Comment by durack1** [comment]
@taylor13 `pClim_aer` does not appear to be included in the excel file that you provided.. I wonder what else went missing

**Comment by durack1** [comment]
@taylor13 this issue, and the current details for `piClim-aer` can be seen directly [here](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json#L5234-L5261)

**Comment by taylor13** [comment]
@durack1 We can go ahead and add "AerChemMIP" to the list of activities (following the "RFMIP" entry).

Also, Please change the "description" to read:
"As in RFMIP-ERF-PI-Cntrl but with with present-day aerosols.  Note that this experiment is considered to be tier 1 by RFMIP but tier 2 by AerChemMIP"

All else looks good.
