### ISSUE TITLE
HighResMIP start date incorrect 

### ISSUE THREAD

**Issue by dnadeau4** [WCRP-CMIP/CMIP6_CVs#263]
This issue seems to be related to experiment_id.json file.
https://github.com/PCMDI/cmip6-cmor-tables/issues/43

**Comment by durack1** [comment]
@dnadeau4 why do you say it's incorrect? What is the info source?

**Comment by dnadeau4** [comment]
I am not saying it is incorrect @jonseddon is saying so.

**Comment by taylor13** [comment]
we should check with the co-chairs before changing

**Comment by jonseddon** [comment]
The details are now correct in this repository for HighResMIP, the changes just haven't been pulled through to https://github.com/PCMDI/cmip6-cmor-tables yet. They should appear in the next version of PCMDI/cmip6-cmor-tables. We're happy that everything's good and just need to be more patient.

**Comment by dnadeau4** [comment]
@jonseddon I just updated CMIP6_CV.json in the https://github.com/PCMDI/cmip6-cmor-tables repository.  I need to add this to my check list when I update the tables... Thanks for letting us know.

**Comment by durack1** [comment]
@dnadeau4 @jonseddon @taylor13 ok it seems everything is ok here, so closing this issue
