### ISSUE TITLE
all -- scope = CMIP6 or scope = global

### ISSUE THREAD

**Issue by momipsl** [WCRP-CMIP/CMIP6_CVs#265]
@taylor13:

I am writing tooling to simplify vocabulary management.  In particular I am pulling in WCRP CMIP6 vocabs and rewriting them in a normalised format:

https://github.com/ES-DOC/pyessv
https://github.com/ES-DOC/pyessv-archive

It seems to me that there are several WCRP-CMIP6 CVs, such as institution_id, that are actually **global in scope**, i.e. not constrained to CMIP6.  Would you agree with this assertion ?  If so which of the CMIP6 CVs would you consider to be 'global' in scope ?

**Comment by taylor13** [comment]
By global do you mean that the same institution_id might appear outside of CMIP6 (e.g., CMIP5, obs4MIPs, etc.)?  The answer I think is "yes".  But I'm sure CMIP6 only will include a subset of all institutions involved in climate research, so it is an incomplete list.  Does that disqualify it from being designated "global"?  Also I don't know if other projects have something called "institution_id", but without the rules we use in CMIP6 to decide what is a valid i.d. (e.g., we don't allow certain characters).  Could we still consider "institution_id" to be global if there are other institution_id's outside of CMIP6 that don't follow our rules?

**Comment by durack1** [comment]
@momipsl good question, and there isn't a clear answer.

For example, in addition to the CMIP6 `institution_id` in [CMIP6_institution_id.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_institution_id.json), we also have `institution_id` identified for the [`input4MIPs`](https://github.com/PCMDI/input4MIPs-cmor-tables/blob/master/input4MIPs_institution_id.json) and [`obs4MIPs`](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/obs4MIPs_institution_id.json) projects. While in theory these `institution_id` values should be global (so unique across all the repos/use cases), there are different contributors to each of these projects from the same (or similar) institution, and so one value (in one repo) may not directly map to another.

We are attempting to reuse the CMIP6 entries if they are applicable to the other projects, however this may not always be the case

**Comment by durack1** [comment]
@momipsl @taylor13 I don't believe there is anything left to do here, so will close
