### ISSUE TITLE
experiment_id: LUMIP changes

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#27]
## Indicate the Controlled Vocabulary (CV) of interest:
 experiment_id

On 7/28/16 11:26 AM, David Lawrence wrote:
> Hi Karl,
>
> In the process of revising the LUMIP paper, a few experiment names have been changed and we added a couple of experiments in the set of land-only experiments.
>
> See Table 2 in the attached document.
>
> The changes are
>
> land-crop-noManage changed to land-crop-noIrrigFert
> land-netTrans changed to land-noShiftcultivate
> added land-hist-altLu1 and land-hist-altLu2
>
> Thanks,
>
> Dave

**Comment by durack1** [comment]
@taylor13 the LUMIP experiments: `land-crop-noManage` and `land-netTrans` have been renamed, however `land-hist-altLu1` and `land-hist-altLu2` require more information - see #30 for more info.

@DaveLawrence can you take a peek at [CMIP6_experiment_id.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/d53ad8f3546645a70603df5ce1dbe6cf9373d9b5/CMIP6_experiment_id.json#L3383-L3416) and provide the required details for the two new experiments above?

It would also be great to review all the `LUMIP` experiments currently included:
[deforest-globe](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/d53ad8f3546645a70603df5ce1dbe6cf9373d9b5/CMIP6_experiment_id.json#L1763-L1789)
[esm-ssp585-ssp126Lu](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/d53ad8f3546645a70603df5ce1dbe6cf9373d9b5/CMIP6_experiment_id.json#L1916-L1941)
[hist-noLu](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/d53ad8f3546645a70603df5ce1dbe6cf9373d9b5/CMIP6_experiment_id.json#L2544-L2570)
[land-cCO2](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/d53ad8f3546645a70603df5ce1dbe6cf9373d9b5/CMIP6_experiment_id.json#L3230-L3248)
[land-cClim](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/d53ad8f3546645a70603df5ce1dbe6cf9373d9b5/CMIP6_experiment_id.json#L3249-L3267)
[land-crop-grass](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/d53ad8f3546645a70603df5ce1dbe6cf9373d9b5/CMIP6_experiment_id.json#L3268-L3286)
[land-crop-noFert](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/d53ad8f3546645a70603df5ce1dbe6cf9373d9b5/CMIP6_experiment_id.json#L3287-L3305)
[land-crop-noIrrig](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/d53ad8f3546645a70603df5ce1dbe6cf9373d9b5/CMIP6_experiment_id.json#L3306-L3324)
[land-crop-noIrrigFert](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/d53ad8f3546645a70603df5ce1dbe6cf9373d9b5/CMIP6_experiment_id.json#L3325-L3343)
[land-hist](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/d53ad8f3546645a70603df5ce1dbe6cf9373d9b5/CMIP6_experiment_id.json#L3363-L3382)
[land-hist-altStartYear](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/d53ad8f3546645a70603df5ce1dbe6cf9373d9b5/CMIP6_experiment_id.json#L3417-L3435)
[land-noFire](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/d53ad8f3546645a70603df5ce1dbe6cf9373d9b5/CMIP6_experiment_id.json#L3493-L3511)
[land-noLu](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/d53ad8f3546645a70603df5ce1dbe6cf9373d9b5/CMIP6_experiment_id.json#L3512-L3530)
[land-noPasture](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/d53ad8f3546645a70603df5ce1dbe6cf9373d9b5/CMIP6_experiment_id.json#L3531-L3549)
[land-noShiftcultivate](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/d53ad8f3546645a70603df5ce1dbe6cf9373d9b5/CMIP6_experiment_id.json#L3550-L3568)
[land-noWoodHarv](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/d53ad8f3546645a70603df5ce1dbe6cf9373d9b5/CMIP6_experiment_id.json#L3569-L3587)
[ssp126-ssp370Lu](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/d53ad8f3546645a70603df5ce1dbe6cf9373d9b5/CMIP6_experiment_id.json#L4756-L4782)
[ssp370-ssp126Lu](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/d53ad8f3546645a70603df5ce1dbe6cf9373d9b5/CMIP6_experiment_id.json#L4972-L4998)

**Comment by dlawrenncar** [comment]
I've added relevant information for these two experiments inline below.
   
 "land-hist-altLu1":{
        "activity_id":"LUMIP",
        "additional_allowed_model_components":"",
        "description":"Land only simulations",
        "end_year":"2014",
        "experiment":"historical land-only alternate land-use history",
        "min_number_yrs_per_sim":"165",
        "parent_activity_id":"",
        "parent_experiment_id":"",
        "required_model_components":[
            "LND"
        ],
        "start_year":"1850 or 1700",
        "sub_experiment":"none",
        "sub_experiment_id":"none",
        "tier":"2"
    },
    "land-hist-altLu2":{
        "activity_id":"LUMIP",
        "additional_allowed_model_components":"",
        "description":"Land only simulations",
        "end_year":"2014",
        "experiment":"historical land-only alternate land use history",
        "min_number_yrs_per_sim":"165",
        "parent_activity_id":"",
        "parent_experiment_id":"",
        "required_model_components":[
            "LND"
        ],
        "start_year":"1850 or 1700",
        "sub_experiment":"none",
        "sub_experiment_id":"none",
        "tier":"2"
    },

**Comment by durack1** [comment]
@dlawrenncar perfect thanks! And how about the other 20 experiments - any tweaks required to them? The links included in top comment should get you directly there..

**Comment by dlawrenncar** [comment]
For deforest-globe, minimum number of years should be 81 rather than 71.  And I think that the start year and end year should be blank as it is in other idealized experiments like 1pctCO2.

land-cClim description should read "Same as land-hist except with climate held constant"

land-crop-noIrrigFert description should read "Same as land-hist except with plants in cropland area utilizing at least some form of crop management (e.g., planting and harvesting) rather than simulating cropland vegetation as a natural grassland. Irrigated area and fertilizer area/use should be held constant." 
experiment should read "historical land-only with managed crops but with irrigation and fertilization held constant"

land-noShiftcultivate description should read "Same as land-hist except shifting cultivation turned off.  An additional LUC transitions dataset will be provided as a data layer within LUMIP LUH2 dataset with shifting cultivation deactivated."
experiment should read "historical land-only with shifting cultivation turned off"

**Comment by durack1** [comment]
@dlawrenncar thanks, I'll reopen and queue those changes for editing

**Comment by durack1** [comment]
@dlawrenncar - `and-noShiftcultivate` should this be `land-noShiftCultivate` (upper case "C")?

**Comment by dlawrenncar** [comment]
Yes.  Upper case C.  Sorry.
