### ISSUE TITLE
remove js sources from repo?

### ISSUE THREAD

**Issue by doutriaux1** [WCRP-CMIP/CMIP6_CVs#271]
instead of polluting the repo (as I originally did) with datable js we might want to simply link to the cdn:
```
    <link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.10.13/css/jquery.dataTables.css">
     <script type="text/javascript" src="http://code.jquery.com/jquery-1.12.4.js"></script>
     <script type="text/javascript" charset="utf8"
    src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
```
Unless it's critical to be able to see the tables w/o internet connection.

Just a thought.

**Comment by durack1** [comment]
@doutriaux1 see https://github.com/WCRP-CMIP/CMIP6_CVs/issues/248
