### ISSUE TITLE
Missing activity_id values

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#276]
@taylor13 it seems our [CMIP6_activity_id.json](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/CMIP6_activity_id.json) file is missing the endorsed activities: `CORDEX`, `DynVarMIP`, `SIMIP` and `VIACS AB`.

Can you take another look and let me know if I am correct in adding these in?

**Comment by taylor13** [comment]
We should add COrDEX, DynVarMIP, SIMIP, and VIACSAB (no space).

**Comment by durack1** [comment]
@taylor13 did you want the `COrDEX` capitalization changed?

**Comment by taylor13** [comment]
no.  it should appear as on the WCRP website.  All caps.

**Comment by durack1** [comment]
@taylor13 exactly - see https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_activity_id.json#L3-L24
