### ISSUE TITLE
Add yrClim and decadal to frequency vocab

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#281]
`yrClim` is a valid frequency (annual climatology) but is not currently included

**Comment by taylor13** [comment]
yrClim is not needed for CMIP6 output, but apparently it is for input4MIPs??  If so, it is o.k. to add it to the CV.

**Comment by durack1** [comment]
@taylor13 we also have the decadal climatologies in the OMIP data request, so maybe we also need an `decClim`?

**Comment by taylor13** [comment]
@durack1 Martin has labeled these with frequency="dec", which I think is correct unless you are collecting monthly climatologies for each decade.  Perhaps we should change this to "decadal" to make it clearer?  (frequency is not used in file names.)

**Comment by durack1** [comment]
@taylor13 I suppose `dec` and `yr` are consistent (averages over a decade or year respectively), however, in the case of input4MIPs there are instances where the annual mean is calculated over multiple years (more than 10) and in that case I believe `yrClim` is correct.. For `dec` it's a specific time period (10-years)

@martinjuckes are you ok to change the `frequency=dec` to `frequency=decadal` to be consistent with our proposed addition to the  [CMIP6_CVs/CMIP6_frequency.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_frequency.json) file

**Comment by durack1** [comment]
`decadal` was included in 308b09e2c3c2872f361b0b65f8af648b1dee534b on the 11th July 2016, closing

@martinjuckes you will need to amend the frequency in the data request to be consistent.. We have made no change
