### ISSUE TITLE
institution_id registration of CMCC

### ISSUE THREAD

**Issue by escoccimarro** [WCRP-CMIP/CMIP6_CVs#284]
institution_id = CMCC
institution = Fondazione Centro Euro-Mediterraneo sui Cambiamenti Climatici, Italy

**Comment by durack1** [comment]
@escoccimarro your `CMCC` `institution_id` is now revised to the correct identifier. Please review the information at [CMIP6_institution_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_institution_id.html) and let me know if any amendments are required.
