### ISSUE TITLE
Updating realm format

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#285]
In preparation for changes to `source_id` some tweaks to `realm` are planned. These changes will update the current [CMIP6_realm.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_realm.json), to:
```
{
    "realm": {
        "aerosol":"aerosol",
        "atmos":"atmosphere",
        "atmosChem":"atmospheric_chemistry",
        "land":"land_surface",
        "landIce":"land_ice",
        "ocean":"ocean",
        "ocnBgChem":"ocean_biogeochemistry",
        "seaIce":"sea_ice"
    },
    "version_metadata":{
        "author":"Paul J. Durack <durack1@llnl.gov>",
        "creation_date":"Wed Apr 12 18:44:20 2017 -0700",
        "institution_id":"PCMDI",
        "latest_tag_point":"3.2.2 (175; g0c97a12)",
        "note":"Add missing activity_id values",
        "previous_commit":"c50f25d4e3856590e867ba9b36773625a7b33ca3"
    }
}
```
Note that the key `ocnBgchem` will be updated to `ocnBgChem`.

@taylor13, @dnadeau4 pinging you here.

@ehogan, @jkettleb, @alistairsellar, @senesis, @mbittner1, @jypeter, @ARadhakrishnanAtGFDL, @martinjuckes please let us know if this planned change will cause any problems. Please forward on to others if you think they may be affected

**Comment by durack1** [comment]
@momipsl and @eguil pinging you both here - I am uncertain how much ES-DOCs is dependent on this repo

**Comment by jypeter** [comment]
LGTM !

Having a translation dictionary of the realm names somewhere seems like a useful thing and I don't use _CMIP6_realm.json_ directly so I should not be affected by the change. As an end-user, I mostly use _realm_ as some extra information I can tell other end users to look for in the DR, CMOR tables or metadata in the nc files. I'm not sure I have ever explicitly used the realm information in a script

To be safe, I have also just checked the _realm_ related information in the recently updated **[CMIP6_global_attributes_filenames_CVs](https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk)** document

I expect the **ocnBgchem=>ocnBgChem change** will require an update of the DR

**Comment by momipsl** [comment]
@durack1: 

1.  What is the rationale behind this change ?
2. Impact upon ES-DOC is limited as it manages vocabularies using [pyessv](https://github.com/ES-DOC/pyessv-archive/tree/master/wcrp/cmip6) which is of course more resilient to change.

**Comment by durack1** [comment]
@momipsl 
1. There are changes planned for the `table_id` which expands on the CV just being table names and includes the associations with the data request, `Omon:monthly` etc, see #166. This change is being made to make the CV more readable, and then allows us to use just the shortened identifier (rather than the expanded entry as currently in the `source_id`)
2. Ok great, I assume you'd need to know about changes upstream however - I suppose you are "watching" this repo for changes?

**Comment by durack1** [comment]
@jypeter thanks for checking, yes we are further checking for consistency between the descriptive document [CMIP6_global_attributes_filenames_CVs](https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk) and these entries.. We've noted a number of inconsistencies and are making these changes to bring things more inline.

@martinjuckes has been pinged on this request, so we're hoping that the change (`ocnBgchem`=>`ocnBgChem`) will propagate quickly across to the dataRequest, and that any further clarifications can be completed quickly before we make the change in this repo

**Comment by durack1** [comment]
@martinjuckes 
```
On 4/14/17, 1:48 AM, "martin.juckes" wrote:

    Hi Karl,
    
    could you use "Atmospheric Chemistry" etc instead of "atmospheric_chemistry" etc? The short terms "atmosChem" etc are suitable for using in code and elsewhere when spaces are inconvenient, so we could use natural word spacing in the descriptors.
    
    regards,
    Martin
```

**Comment by durack1** [comment]
All after reviewing this, it seems the `ocnBgchem` -> `ocnBgChem` change is spurious, as the full descriptor 'Ocean Biogeochemistry' does not lead to camelCase for the chemistry 'C' (it's part of the complete second word), so will implement the list -> dictionary change but not the camelCase change as suggested above.

**Comment by momipsl** [comment]
@durack1: Yes ES-DOC is watching ... closely.
