### ISSUE TITLE
Register source_id BESM-2-6

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#287]
```
"BESM-2-6":{
    "activity_participation":[
        "CMIP"
    ],
    "aerosol":"None",
    "atmosphere":"BAM (v1.0; T062L28, 192 x 96 longitude/latitude; 28 levels; top level 3 hPa)",
    "atmospheric_chemistry":"None",
    "cohort":[
        "CMIP5"
    ],
    "institution_id":[
        "INPE"
    ],
    "label":"BESM 2.6",
    "label_extended":"BESM 2.6 (This entry is free text for users to contribute verbose information)",
    "land_ice":"None",
    "land_surface":"SSiB",
    "nominal_resolution_atmos":[
        "1.875 Degree"
    ],
    "nominal_resolution_landIce":[
        "None"
    ],
    "nominal_resolution_ocean":[
        "1.0 Degree"
    ],
    "ocean":"MOM-5 (MOM5; tripolar primarily 1 deg, 360 x 300 longitude/latitude; 50 levels; top grid cell 0-10 m)",
    "ocean_biogeochemistry":"TOPAZ",
    "release_year":"2012",
    "sea_ice":"SIS",
    "source_id":"BESM-2-6"
},
```
@besm-inpe pinging you here

**Comment by durack1** [comment]
@besm-inpe we need some additional information from you to accurately register this `source_id`, I have amended your entry above and added a `###` where additional information is required:
```
"BESM-2-6":{
    "activity_participation":[
        "CMIP"
    ],
    "aerosol":"None",
    "atmosphere":"BAM (v1.0; T062L28, 192 x 96 longitude/latitude; 28 levels; top level 3 hPa)",
    "atmospheric_chemistry":"None",
    "cohort":[
        "Registered"
    ],
    "institution_id":[
        "INPE"
    ],
    "label":"BESM 2.6",
    "label_extended":"BESM 2.6",
    "land_ice":"None",
    "land_surface":"SSiB", ### What is the version number? i.e. SSiB 1.0
    "nominal_resolution_aerosol":"None"
    "nominal_resolution_atmos":"1.875 Degree" ### This is not a valid entry
    "nominal_resolution_atmosChem":"None"
    "nominal_resolution_land":"" ### Please enter this value
    "nominal_resolution_landIce":"None"
    "nominal_resolution_ocean":"1.0 Degree" ### This is not a valid entry
    "nominal_resolution_ocnBgChem":"" ### Please enter this value
    "nominal_resolution_seaIce":"" ### Please enter this value
    "ocean":"MOM-5 (MOM5; tripolar primarily 1 deg, 360 x 300 longitude/latitude; 50 levels; top grid cell 0-10 m)",
    "ocean_biogeochemistry":"TOPAZ", ### What is the version number? i.e. TOPAZ 1.0
    "release_year":"2012",
    "sea_ice":"SIS", ### What is the version number? i.e. SIS 1.0
    "source_id":"BESM-2-6"
},
```
For the `nominal_resolution` entries, please select the closest value from the list found in [CMIP6_CVs/CMIP6_nominal_resolution.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_nominal_resolution.json#L3-L17).

Just for clarity, all the CMIP6 endorsed activities are listed at [CMIP6_CVs/CMIP6_activity_id.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_activity_id.json), please add all relevant MIPs that you will be contributing to using this model

**Comment by durack1** [comment]
@besm-inpe have you had a chance at obtaining the requested information above?

**Comment by besm-inpe** [comment]
Dear Paul
Thank you for your msg. Yes, will send the requested information asap.
Thank you for your patience,
...paulo

**Comment by besm-inpe** [comment]
"BESM-2-7":{
            "activity_participation":[
                "CMIP"
            ],
            "aerosol":"None",
            "atmosphere":"BAM (v1.0; T062L28, 192 x 96 longitude/latitude; 28 levels; top level 3 hPa)",
            "atmospheric_chemistry":"None",
            "cohort":[
                "CMIP5"
            ],
            "institution_id":[
                "INPE"
            ],
            "label":"BESM 2.7",
            "label_extended":"BESM 2.7 (This entry is free text for users to contribute verbose information)",
            "land_ice":"None",
            "land_surface":"SSiB 2.0",
            "nominal_resolution_land":[
                "250 km",
            ],
            "nominal_resolution_atmos":[
                "250 km",
            ],
            "nominal_resolution_landIce":"None",
            "nominal_resolution_ocean":[
                "1x1 degree",
            ],
            "ocean":"MOM-5 (MOM5; tripolar primarily 1 deg, 360 x 300 longitude/latitude; 50 levels; top grid cell 0-10 m)",
            "ocean_biogeochemistry":"TOPAZ 1.0",
            "nominal_resolution_ocnBgChem":"1x1 degree",
            "release_year":"2012",
            "sea_ice":"SIS 1.0",
            "nominal_resolution_seaIce":"1x1 degree",
            "source_id":"BESM-2-7"
        },

**Comment by durack1** [comment]
@besm-inpe thanks for this, I note you've amended the registration from `BESM-2-6` to `BESM-2-7` did you want to replace the existing entry, or add another?

I have rearranged some of the entries above to make it clearer what information has been provided.

Regarding the `nominal_resolution` identifier, if you do not have an explicit `1x1 degree` grid (which would is exactly 360 x 180 longitude/latitude), then this should be more correctly labeled to the closest entry in [CMIP6_nominal_resolution.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_nominal_resolution.json) for the average resolution across your grid. For your examples (ocean: 360 x 300) it would most likely be `100 km` or `250 km`. The Appendix 2 in the [CMIP6 Global Attributes, DRS, Filenames, Directory Structure, and CV’s](https://goo.gl/v1drZl) file provides more comprehensive information

**Comment by besm-inpe** [comment]
Dear Paul
Thank you for your msg and rearrangement of our entries to BESM.
Yes, please change the model version to BESM-2-7.
The ocean resolution shall then be 100 Km.
It is in fact 1 degree longitude and  1/4 degree latitude between 10S-10N,
varying to 1 degree at 40S and 40N, and then uniform 1 x 1 to the poles.
Best,
Paulo Nobre

**Comment by durack1** [comment]
@besm-inpe no problem, is `release_year = 2012` correct?

**Comment by durack1** [comment]
@besm-inpe I updated this to be `release_year = 2017`. If you want to take a peek at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and double check the entries, that would be great

**Comment by besm-inpe** [comment]
Hi Paul
Thank you for the inclusion of changes. In fact, some further changes
needed.
Will to it tomorrow morning.
Best,
...paulo

**Comment by durack1** [comment]
@besm-inpe, no problem. The current listing shows the following:
```
"BESM-2-7":
"activity_participation":[
   "CMIP"
],
"cohort":[
   "Registered"
],
"institution_id":[
   "INPE"
],
"label":"BESM 2.7",
"label_extended":"BESM 2.7",
"model_component":
"aerosol":
   "description":"none",
   "nominal_resolution":"none"
"atmos":
   "description":"BAM (v1.0, T062L28; 192 x 96 longitude/latitude; 28 levels; top level 3 hPa)",
   "nominal_resolution":"250 km"
"atmosChem":
   "description":"none",
   "nominal_resolution":"none"
"land":
   "description":"SSiB 2.0",
   "nominal_resolution":"250 km"
"landIce":
   "description":"none",
   "nominal_resolution":"none"
"ocean":
   "description":"MOM-5 (MOM5, tripolar primarily 1 deg; 360 x 300 longitude/latitude; 50 levels; top grid cell 0-10 m)",
   "nominal_resolution":"100 km"
   "ocnBgchem":
   "description":"TOPAZ 1.0",
   "nominal_resolution":"100 km"
"seaIce":
   "description":"SIS 1.0",
   "nominal_resolution":"100 km"
"release_year":"2017",
"source_id":"BESM-2-7"
```
Just make whatever amendments are required and reopen the issue below

**Comment by besm-inpe** [comment]
"BESM-2-7":{
            "activity_participation":[
                "CMIP", "DCPP", "HighResMIP", "ScenarioMIP",
            ],
            "aerosol":"None",
            "atmosphere":"BAM (v1.0; T062L28, 192 x 96 longitude/latitude; 28 levels; top level 3 hPa)",
            "atmospheric_chemistry":"None",
            "cohort":[###?
            ],
            "institution_id":"INPE"
            "label":"BESM 2.7",
            "label_extended":"BESM 2.7 (This entry is free text for users to contribute verbose information)",
            "land_ice":"None",
            "land_surface":"SSiB 2.0",
            "nominal_resolution_land":"250 km",
            "nominal_resolution_atmos":"250 km",
            "nominal_resolution_landIce":"None",
            "nominal_resolution_ocean":"100 Km",
            "ocean":"MOM-5 (MOM5; tripolar primarily 1 deg, 1/4 deg between 10S-10N, 360 x 300 longitude/latitude; 50 levels; top grid cell 0-10 m)",
            "ocean_biogeochemistry":"TOPAZ 2.0",
            "nominal_resolution_ocnBgChem":"100 Km",
            "release_year":"2017",
            "sea_ice":"SIS 1.0",
            "nominal_resolution_seaIce":"100 Km",
            "source_id":"BESM-2-7"
        },

**Comment by durack1** [comment]
@besm-inpe the revisions have been made, take a peek at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any other tweaks are required

**Comment by besm-inpe** [comment]
Dear Paul!
It looks OK now.
Thank you!
...paulo

**Comment by durack1** [comment]
@besm-inpe no problem, if you have any further tweaks before starting to write CMIP6 data we can always amend the entry..
