### ISSUE TITLE
Cleaning up "None" vs "none" instances

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#301]
@taylor13 @dnadeau4 we have instances of both "None" and "none" in the `experiment_id` and `source_id` entries and I think these should be standardised.. @dnadeau4, what tests do you have that expect one or another case?

**Comment by dnadeau4** [comment]
sub_experiment_id is always `none`.  So I think we should set everything to `none` and let `None` be python's (NULL) instance.
