### ISSUE TITLE
Missing river realm?

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#312]
In cmip6dr/CMIP6_DataRequest_VariableDefinitions#85 @senesis has noted that there may be instances where river models are running on their own grid:

```
For AOGCM models which have a river model running on its own grid, there is no way to describe it,
both for grid mesh areas and for fraction of the area occupied by rivers. This hinders
intercomparison of river models
```

I wonder whether this should be added as another `realm` to [CMIP6_realm.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_realm.json)

@senesis, please do chime in here
@taylor13 @martinjuckes pinging you both here

**Comment by senesis** [comment]
Not really sure what 'chime in' means in this context. But I take not that my DR issue is also raised as a CMIP6_CV issue

**Comment by durack1** [comment]
@senesis how many models that you are aware of have an independent river grid that differs from the `land` or `atmos` grid of the same model configuration?

**Comment by senesis** [comment]
There is at least CLM (http://www.cgd.ucar.edu/tss/clm/components/hydrocycle.html) and probably all models which atmospheric+land grid is spectral. 
We at CNRM will try to have LS3MIP leaders provide further comment

**Comment by durack1** [comment]
@senesis there are a bunch of registered models that appear to be including `CLM` in their configurations (`CIESM`, `CMCC-CM2-HR4` etc, see [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and search for "CLM") and complete registrations share the same `nominal_resolution` entry as the `atmos` realm..

If there are indeed separate `land` and `river` modules, which have differing grids, then it may be useful to add the `river` realm to the list.

I do agree, engaging the `LS3MIP` chairs on this query would be a good idea

**Comment by durack1** [comment]
@senesis @taylor13 @martinjuckes this appears to have gone quiet, so we will close the issue. If the question needs to be revisited, please reopen this issue
