### ISSUE TITLE
experiment_id inconsistencies with GMD and ES-DOC

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#316]
Here's a correspondence from the UKMO:

There are still a few small differences between es-doc and the CMIP6 Controlled Vocabulary (CV):

**CV: version 1.00.06 published 10th April**

Tier 1:
hist-1950HC, hist-piNTCF, histSST, histSST-1950HC, histSST-piCH4, histSST-piNTCF, piClim-CH4, piClim-HC, piClim-NTCF, piClim-aer, piClim-control, ssp370, ssp370-lowNTCF, ssp370SST, ssp370SST-lowCH4, ssp370SST-lowNTCF, ssp370SST-ssp126Lu

Tier 2:
hist-piAer, histSST-piAer, histSST-piN2O, histSST-piO3, piClim-2xdust, piClim-2xss, piClim-BC, piClim-N2O, piClim-O3, ssp370SST-lowAer, ssp370SST-lowBC, ssp370SST-lowO3

Tier 3:
piClim-2xDMS, piClim-2xNOx, piClim-2xVOC, piClim-2xfire, piClim-NH3, piClim-NOx, piClim-OC, piClim-SO2, piClim-VOC

**ES-Doc: version 0.9.7.2**

Tier 1:
piClim-control | hist-piNTCF | hist-1950HC | histSST | histSST-piNTCF | histSST-1950HC | histSST-piCH4 | ssp370-lowNTCF | ssp370SST | ssp370SST-lowNTCF | ssp370SST-lowAer | ssp370SST-lowBC | ssp370SST-lowO3 | ssp370SST-lowCH4 | ssp370SST-ssp126Lu | piClim-NTCF

Tier 2:
hist-piAer | histSST-piAer | histSST-piO3 | histSST-piN2O | piClim-aer | piClim-BC | piClim-O3 | piClim-CH4 | piClim-N2O | piClim-HC | piClim-2xdust | piClim-2xss

Tier 3:
piClim-NOX | piClim-VOC | piClim-2xDMS | piClim-2xfire | piClim-2xNOX | piClim-2xVOC

**Differences:**

piClim-CH4, piClim-HC, piClim-aer:
                Tier 1 in CV
                Tier 2 in ES-Doc

ssp370:
                Tier1 in CV
                “other” in ES-DOC

ssp370SST-lowAer, ssp370SST-lowBC, ssp370SST-lowO3
                Tier 2 in CV
                Tier 1 in ES-Doc

Tier 3:

               “piClim-NOX” in ES-Doc, “piClim-NOx” in CV (case of final character)
               “piClim-2xNOX” in ES-DOC, “piClim-2xNOx” in CV (case of final character)
                “piClim-NH3”, “piClim-OC”, “piClim-SO2”,  in CV missing from ES-DOC

The data request at version 1.00.07 still has no AerChemMIP experiments listed.

**Comment by durack1** [comment]
@momipsl @eguil @markelkington @charliepascoe @bnlawrence @matthew-mizielinski @martinjuckes pinging you all here.

I note the **CV version 1.00.06** noted above doesn't relate to this (CMIP6_CVs) repo directly. Rather the version information is contained in the [`version_metadata`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json#L7138-L7144) entry, with the latest being:
```json
"version_metadata":{
   "author":"Paul J. Durack <durack1@llnl.gov>",
   "creation_date":"Wed Apr 26 09:19:24 2017 -0700",
   "institution_id":"PCMDI",
   "latest_tag_point":"3.2.3 (29; g9be7426)",
   "note":"Revise source_id BESM-2-7",
   "previous_commit":"66ea1f100a70977e3400c65e14f0c91fc6590ac6"
}
```
To answer the question about `experiment_id` versioning, the last substantive change was a revision of the `piClim-aer` experiment (https://github.com/WCRP-CMIP/CMIP6_CVs/commit/bf062d96944c8bbbad2eec9e31c9addf07ed4450) on 29th March this year. Any subsequent changes have been to the versioning history (which is updated each time a change is made to any contents of the repo) or changing the internal format of contents (not the contents themselves) within the json file for consistency

**Comment by taylor13** [comment]
@momipsl @eguil @markelkington @charliepascoe @bnlawrence @matthew-mizielinski @martinjuckes 
I have consulted the GMD papers on MIP experiments and found that the CMIP6 experiment_id CV is currently consistent (and ES-DOC) is inconsistent in all cased listed above except:  "piClim-NOX" and "piClim-2xNOX" are listed with the "X" as upper case.

Since "NO" is a chemical compound, use of upper case makes sense, but the "x" is a lower case subscript, which I think should not be capitalized even when it doesn't appear as a subscript.  I think the Aerchem leaders made a mistake when they wrote their GMD paper, which they subsequently corrected when submitting the experiment info. to the CMIP6 CV.

I conclude that ES-DOC will need to make small changes for consistency with the CV.

**Comment by taylor13** [comment]
Also note that piClim-aer is considered Tier 2 by Aerchem but Tier 1 by RFMIP, so the higher Tier is indicated in the CV.  (the difference in priority between the two activities is noted in the CV's "description" of piClim-aer.

**Comment by charliepascoe** [comment]
I've made the following updates to the latest version of the ES-Doc experiment spreadsheet for CMIP6.  You should see these changes online when Mark next does his update.
 * Changed the case of the final "x" in the piClim-NOx and piClim-2xNOx experiments.  
 * Changed the tier from 2 to 1 for piClim-CH4, piClim-HC and piClim-aer experiments. 
 * Changed the tier from 1 to 2 for ssp370SST-lowAer, ssp370SST-lowBC and ssp370SST-lowO3.

I still need to add the piClim-NH3, piClim-OC and piClimSO2 experiments, I've upped the priority on our ticket for that task https://github.com/ES-DOC/esdoc-docs/issues/240

**Comment by charliepascoe** [comment]
ssp370 is listed as a tier 1 ScenarioMIP experiment.
It appears as an "other" experiment under the AerChemMIP listing because it is governed by an "other" MIP.
If we need to retain the tier information from MIP to MIP then we will need to make an update to the way we render the lists of experiments associated with each MIP.

**Comment by charliepascoe** [comment]
I believe it is not always the case when a MIP re-uses an experiment from another MIP that the experiment keeps the same tier level (but I'd need to check that).   For the time being I suggest that we re-word the "other" list of experiments in the ES-Doc interface to make it clear that these are experiments that are governed by another MIP and not experiments in an "other" tier.

**Comment by durack1** [comment]
```
From: Elkington, Mark
Date: Tuesday, May 2, 2017 at 1:18 AM
To: Taylor, Karl E., charlotte.pascoe, Eric.Guilyard, martin.juckes
Cc: Mizielinski, Matthew, Durack, Paul J.
Subject: RE: FW: AerChemMIP experiments for input into CREM

Hi Karl
 
Thanks for checking this – it is clearly important that the CVs, ES-DOC and DREQ are kept in synch as the modelling groups start their simulations.  I can see that at this stage it might be hard to do but it is really important.  It would be easier if we could just assume that one source is the master but  to take the MetOffice as an example this is not realistic:
-	We rely on the CVs to be correct as we will use CMOR to produce out output data
-	We rely on ES-DOC being correct with regard to experiment names as we will be using their experiment definition exports to populate the structure of our metadata database
-	We rely on DREQ to establish what variables we need to produce for each experiment.
 
I expect other groups will be in a similar position to us.
 
It would help a lot if there was a clear milestone set when the three sources would be checked for consistency and from then on consistency will be maintained across each release.
 
Regards
 
Mark
```

**Comment by taylor13** [comment]
@charliepascoe @durack1 @martinjuckes @momipsl @markelkington @eguil @bnlawrence @matthew-mizielinski    You are right, Charlotte, that the tier of an experiment can depend on the MIP.  If there are 2 MIPs that include the same experiment, the priority might  (and in I think 2 cases does) differ.  Perhaps Mark E. can suggest a way to handle this more gracefully.  Currently in the CV, there is a single tier given.   As I recall for the 2 cases where there are different tiers depending on the MIP, I've recorded the highest priority, which in both cases was set by the prime sponsor of the experiment (the MIP that appears in the DRS identifier).

**Comment by markelkington** [comment]
Karl/Charlotte

Before suggesting an approach I think I need to understand what the reaction of a modelling group should be to an experiment being defined (wrt tier) in different MIPS.  Lets assume experiment ABC is defined at tier1 for  MIP#1 and tier2 for MIP#2.  A modelling group might only have a policy of doing tier1 experiments and would do experiment ABC if it is participating in MIP#1 but would not do it if it is participating in MIP#2 but not in MIP#1.  Is this a correct interpretation?

Clearly this doesn’t account for the fact that the modelling group may make exceptions to its policy in certain cases.

I think it is OK to have just the highest tier in the CVs – we will not be using the CVs to determine what experiments we will run.  However I do think that ES-DOC and the DREQ need to allow modelling groups to understand the full MIP ‘dependency’ for a particular experiment  But as Charlotte mentioned yesterday, the current allocation of experiments to the “other” tier category on a MIP page doesn’t really make it clear what is meant.   Perhaps if that category was relabelled something like “Other MIP dependencies” – and each experiment in that list indicated the tier for “this” MIP.  So taking the case of ssp370 as an example – it is shown by its “owning” MIP (scenario) as Tier 1.  In AerChemMIP it is shown in the “other” category.  If it was instead shown as:

                Other MIP dependency:    picontrol(tier 1)|abrupt-4xCO2(tier 1)|historical(tier 1)|ssp370(tier 2)

ssp370 could then clearly be interpreted as tier1 in scenarioMIP, but tier2 in AerChemMIP.

In this case the decision would be very simple for us – we are doing ScenarioMIp, it is tier 1 so we would do it whether or not we are planning to do AerChemMIP.  However if the tier allocation were reversed then we would only do it if we were planning to do AerChemMIP.

I think this would be consistent with DREQ which records tier allocation for an experiment in each MIP

This approach doesn’t cover all possibilities but is probably good enough for the few cases we have.

Mark

**Comment by durack1** [comment]
Folks it seems that we're now working toward a more refined versioning system in #28, for this reason I will close this issue - please reopen if things have not been resolved completely
