### ISSUE TITLE
What is the meaning for the "grid_label" possible values?

### ISSUE THREAD

**Issue by mpmoine** [WCRP-CMIP/CMIP6_CVs#317]
Dear Paul,

`CMIP6_grid_label.json` suggests different values for the `grid_label` attribute :  "gm", "gn", "gna", "gng", "gnz",  "gr", "gr1", "gr1a", etc. 

I guess that `gn` means "native grid" and `gr` means "regular grid" but what about the others? In which case are we supposed to use them?

Thanks,
Marie-Pierre.

**Comment by durack1** [comment]
@mpmoine thanks for the question, the information you're seeking is contained in the [CMIP6 Global Attributes, DRS, Filenames, Directory Structure, and CV’s](https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit) document, specifically the Table notes 11 item.

I'll close this issue, but please reopen if these details are not what you were looking for

**Comment by mpmoine** [comment]
Ooops,  I just found this note a few minutes ago, at the same timing as your reply!
Sorry for the disturbance,

Regards,
Marie-Pierre.

**Comment by taylor13** [comment]
@mpmoine  @durack1 
Hi Marie-Pierre,
In the case of observations, it may not be obvious what to do.  I think we've agreed that "native" should be used for the grid best representing the observations (from the perspective of the data provider).  If data is also supplied on another grid, then "gr1", "gr2", ... etc. should be used.  

Not sure about this though.

Karl

**Comment by mpmoine** [comment]
@taylor13 @durack1 
Hi Karl,

Regarding data at observation sites, I understand that what is expected are the values at the closest grid points, whatever the grid we are extracting the data from. These "obs-like" data will be provided at the exact grid point location of  a "gn" or "gr" grid, so it sounds logical to keep these labels, even if only on a small subset of the grid. 

My comprehension is that `grid_label` is only an indication for the users to tell them whether the data have been remapped (or their coordinates modified as for "zonal means" case) or not. 

And we need several instance "gr1", "gr2" etc. to allow the data providers to provide the same CMOR variable on different target grids.

This attribute is a little complex to set automatically in our production workflow, but sounds correct :-)
Marie-Pierre.

**Comment by taylor13** [comment]
@mpmoine 
Hi Marie-Pierre,

Yes, I think you're interpreting things correctly.   If no interpolation is done (e.g., values just taken from the nearest grid cell center), then "gn" is correct (unless zonally averaged, or on a regional grid like Greenland or Antarctica).  

Agreed that it is not simple at all; the primary requirement is that we must produce unique file names across all files produced by CMIP6.

thanks for working through the details.
Karl

**Comment by durack1** [comment]
@mpmoine @taylor13 it seems we've settled the details here, if you have further queries @mpmoine  please reopen
