### ISSUE TITLE
source_id registration of AWI-CM-1-0-LR, AWI-CM-1-0-MR, AWI-CM-1-0-HR

### ISSUE THREAD

**Issue by tsemmler05** [WCRP-CMIP/CMIP6_CVs#319]
Since we are using three different resolutions of AWI-CM-1-0 in CMIP6, the source_id registration of AWI-CM-1-0 needs to be updated. The one which is already in the CMIP6_CVs has to be moved to AWI-CM-1-0-MR; the other two I will register separately.

**Comment by durack1** [comment]
@tsemmler05 thanks for this, peek at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further tweaks are required in the 3 new `source_id` entries
