### ISSUE TITLE
source_id registration of AWI-CM-1-0-HR

### ISSUE THREAD

**Issue by tsemmler05** [WCRP-CMIP/CMIP6_CVs#321]
"AWI-CM-1-0-HR":{
            "activity_participation":[
                "CORDEX",
                "HighResMIP",
                "OMIP",
                "SIMIP",
                "VIACSAB"
            ],
            "cohort":[
                "Registered"
            ],
            "institution_id":[
                "AWI"
            ],
            "label":"AWI-CM 1.0 HR",
            "label_extended":"AWI-CM 1.0 HR",
            "model_component":{
                "aerosol":{
                    "description":"none",
                    "nominal_resolution":"none"
                },
                "atmos":{
                    "description":"ECHAM6.3.02p4 (T127L95 native atmosphere T127 gaussian grid; 384 x 192 longitude/latitude; 95 levels; top level 80 km)",
                    "nominal_resolution":"100 km"
                },
                "atmosChem":{
                    "description":"none",
                    "nominal_resolution":"none"
                },
                "land":{
                    "description":"JSBACH 3.10",
                    "nominal_resolution":"100 km"
                },
                "landIce":{
                    "description":"none",
                    "nominal_resolution":"none"
                },
                "ocean":{
                    "description":"FESOM 1.4 (unstructured grid in the horizontal with 1306775 wet nodes; 46 levels; top grid cell 0-5 m)",
                    "nominal_resolution":"25 km"
                },
                "ocnBgchem":{
                    "description":"none",
                    "nominal_resolution":"none"
                },
                "seaIce":{
                    "description":"FESOM 1.4",
                    "nominal_resolution":"25 km"
                }
           },
            "release_year":"2017",
            "source_id":"AWI-CM-1-0-HR"
},

**Comment by durack1** [comment]
@tsemmler05 we have amended the `activity_participation` entry for `AWI-CM-1-0-HR` to include `CMIP`, as this experiment suite (`piControl` etc) is a required component of contributing to the CMIP6 project

For reference this change was made in WCRP-CMIP/CMIP6_CVs#475
