### ISSUE TITLE
ES-Doc online experiment documentation status

### ISSUE THREAD

**Issue by charliepascoe** [WCRP-CMIP/CMIP6_CVs#327]
@durack1 @taylor13 

We need a method to keep track of the current version of the online ES-Doc CMIP6 experiment info:
http://documentation.es-doc.org/cmip6/experiments
Will comments on this ticket work for you?

19th May 2017
ES-DOC software version 0.9.7.3 published against:
  1.  ES-DOC experiments spreadsheet v75
  2.  WCRP CV v3.2.3
  3.  Data request 1.00.08

**Comment by durack1** [comment]
@charliepascoe we've been trying to discuss all the moving parts in #28 and attempted to visualize this in the google slide: https://goo.gl/TdzjRC - please feel free to contribute to this

It'd be useful to work out an effective way of keeping all these linked projects in sync.

**Comment by taylor13** [comment]
@charliepascoe  Documenting the dependencies of your ES-DOC software as you suggest above seems quite clear to me.  This version information would then be transferred to a table like the one shown in the google slide 4 (see previous comment).

**Comment by taylor13** [comment]
@durack1 should this discussion be combined with https://github.com/WCRP-CMIP/CMIP6_CVs/issues/28 ?

**Comment by taylor13** [comment]
@durack1 Yes!

**Comment by durack1** [comment]
@charliepascoe @taylor13 ok, let's redirect "versioning discussions" into #28 - so will close this as a dupe
