### ISSUE TITLE
experiment_id  changes to scenarioMIP

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#329]
The correspondence from Claudia below says we need to do the following  (but wait for confirmation from Claudia before implementing):  

modify experiment sspxy to:

        "ssp119":{
            "activity_id":[
                "ScenarioMIP"
            ],
            "additional_allowed_model_components":[
                "AER",
                "CHEM",
                "BGC"
            ],
            "description":"Future scenario with low radiative forcing throughout reaching about 1.9 W/m2 in 2100 based on SSP1.  Concentration-driven",
            "end_year":"2100",
            "experiment":"low-end scenario reaching 1.9 W m-2, based on SSP1",
            "experiment_id":"ssp119",
            "min_number_yrs_per_sim":"86",
            "parent_activity_id":[
                "CMIP"
            ],
            "parent_experiment_id":[
                "historical"
            ],
            "required_model_components":[
                "AOGCM"
            ],
            "start_year":"2015",
            "sub_experiment_id":[
                "none"
            ],
            "tier":"2"
},

=====================================
Subject: Re: ScenarioMIP experiment names in the data request

Also, Martin, just wanted to confirm that what was left as a generic label, SSPXY, while the IAM groups worked out the low scenario meeting the Paris target of 1.5C, has now been specified as ssp119 (SSP1-based pathway of emissions leading to a radiative forcing level of 1.9W/m2 by the end of the century)

Thanks
Claudia

**Comment by taylor13** [comment]
received Claudia's confirmation of changes needed:

All good, nothing to change/no issues.
Thank you all
Claudia

**Comment by durack1** [comment]
@taylor13 this issue should be closed then, closing

**Comment by taylor13** [comment]
No. only after you make the changes to the CV.  see above.  changes were made to the key, the description, the experiment, and the experiment_id

**Comment by taylor13** [comment]
@durack1 -- is it necessary to include your name like this to get notice when I've commented?  Does anyone who commented automaticallty get notified?

**Comment by durack1** [comment]
taylor (note I am not using your handle), nope if you have pinged someone inline somewhere, as far as I understand they will be included on any subsequent comment

**Comment by durack1** [comment]
Reopening - changes are yet to be completed
