### ISSUE TITLE
source_id registration of CanESM5

### ISSUE THREAD

**Issue by Scinocca** [WCRP-CMIP/CMIP6_CVs#330]
"CanESM5":{
"activity_participation":[
   "C4MIP",
   "CFMIP",
   "CMIP",
   "CORDEX",
   "DAMIP",
   "DCPP",
   "DynVarMIP",
   "FAFMIP",
   "GMMIP",
   "GeoMIP",
   "ISMIP6",
   "LS3MIP",
   "LUMIP",
   "OMIP",
   "RFMIP",
   "SIMIP",
   "ScenarioMIP",
   "VIACSAB"
],
"cohort":[
   "Registered"
],
"institution_id":[
   "CCCma"
],
"label":"CanESM5",
"label_extended":"CanESM5",
"model_component":{
"aerosol":{
   "description":"interactive",
   "nominal_resolution":"500 km"
},
"atmos":{
   "description":"CanAM5 (T63L49 native atmosphere, T63 Linear Gaussian Grid 128 x 64 longitude/latitude; 49 levels, top level 1hPa)",
   "nominal_resolution":"500 km"
},
"atmosChem":{
   "description":"fast chemistry, aerosol only",
   "nominal_resolution":"500km"
},
"land":{
   "description":"CLASS3.6/CTEM1.2",
   "nominal_resolution":"500 km"
},
"landIce":{
   "description":"none",
   "nominal_resolution":"none"
},
"ocean":{
   "description":"NEMO3.4.1 (ORCA1, tripolar grid, 1 deg latitude/longitude with refinement to 1/3 deg within 20 degrees of the equator; 362x292; 41 vertical levels; top grid cell 0-10 m)",
   "nominal_resolution":"100 km"
}
"ocnBgchem":{
   "description":"CanOE",
   "nominal_resolution":"100 km"
},
"seaIce":{
   "description":"LIM2",
   "nominal_resolution":"100 km"
}
},
"release_year":"2017",
"source_id":"CanESM5"
},

**Comment by durack1** [comment]
@Scinocca thanks for this, peek at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further tweaks are required

**Comment by Scinocca** [comment]
Looks good to me.  Thanks.

**Comment by durack1** [comment]
@Scinocca we noted a formatting inconsistency with the `atmosChem` `nominal_resolution` value for `CanESM5`, and have now corrected this. Please check your complete model registration details in [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and get back to me with any further tweaks required.

For reference, this issue was caught and resolved in WCRP-CMIP/CMIP6_CVs#466
