### ISSUE TITLE
frequency: remove 3hrClim

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#334]
@durack1    Martin Juckes has confirmed in response to an email from me:  

"no, I don't believe 3hrClim is needed. It is not in the current request and I can't find any trace of it in earlier versions. 

I don't recall seeing it in any other MIPs, 

therefore 3hrClim should be removed from the list of valid frequencies.

**Comment by durack1** [comment]
@taylor13 this relates to the open issue at #166, I will have to try again to get the table list from the current dreq version to bring things into sync

**Comment by taylor13** [comment]
Peter just confirmed that they currently have no need for 3hrClim in obs4MIPs
