### ISSUE TITLE
source_id registration of HadGEM3-GC31-LM

### ISSUE THREAD

**Issue by jonseddon** [WCRP-CMIP/CMIP6_CVs#343]
label = HadGEM3-GC31-LM
label_extended = HadGEM3-GC3.1-N96ORCA025
source_id = HadGEM3-GC31-LM
institution_id = MOHC
release_year = 2016
activity_participation = HighResMIP

aerosol:
description = UKCA-GLOMAP-mode
nominal_resolution = 250 km
atmos:
description = MetUM-HadGEM3-GA7.1 (N96; **192 x 144 longitude/latitude;** 85 levels; top level 85 km)
nominal_resolution = 250 km
atmosChem:
description = none
nominal_resolution = none
land:
description = JULES-HadGEM3-GL7.1
nominal_resolution = 250 km
landIce:
description = none
nominal_resolution = none 
ocean:
description = NEMO-HadGEM3-GO6.0 (ORCA025 tripolar primarily 0.25 deg; **1440x720 longitude/latitude;** 75 levels; top grid cell 0-1 m)
nominal_resolution = 25 km
ocnBgchem:
description = none
nominal_resolution = none
seaIce:
description = CICE-HadGEM3-GSI8 (ORCA025 tripolar primarily 0.25 deg; **1440x720 longitude/latitude**)
nominal_resolution = 25 km

**Comment by durack1** [comment]
Thanks @jonseddon, we'll need the `activity_participation` and `nominal_resolution` fields completed before we can register this model

**Comment by durack1** [comment]
@jonseddon and while you're at it, please do feel free to help @alistairsellar with the amendments required in #184

**Comment by jonseddon** [comment]
activity_participation = HighResMIP

I will have to wait for #184 to complete the `nominal_resolution`. I'll give Alistair a poke the next time that I see him.

**Comment by durack1** [comment]
@alistairsellar @jonseddon are you able to provide the required info above - the missing "activity_participation" and "nominal_resolution" entries? Any other required tweaks would also be welcomed

**Comment by jonseddon** [comment]
@durack1 I have updated the above entry with the "activity_participation" and "nominal_resolution". Alistair should have the entries for the other ticket shortly.

**Comment by durack1** [comment]
@jonseddon great, thanks for this.. We are trying to keep a standard format for the description which includes the **XXXxXXX longitude/latitude;** string describing the grid. In the entry above I have tweaked your entries, I'll make sure to also make the same tweaks to #184 - can you re-check my tweaks and if they're all OK, I'll merge them tomorrow

**Comment by durack1** [comment]
@jonseddon I managed to update your info from #184 and the input from @alistairseller, so you should find that we're done - take a peek at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any other tweaks are required.

**Comment by jonseddon** [comment]
@durack1 Sorry, I've been away on holiday for a week and so have only just got your message. That all looks great. Many thanks for your help!
