### ISSUE TITLE
experiment_id  lfmip-pdL-princeton

### ISSUE THREAD

**Issue by martinjuckes** [WCRP-CMIP/CMIP6_CVs#344]
The experiment `fmip-pdL-princeton` (as LFMIP-pdLC with Land-Hist-princeton) looks as though it should have the same naming pattern as `lfmip-pdLC-cruNcep` (as LFMIP-pdLC with Land-Hist-cruNcep) and `lfmip-pdLC-wfdei` (as LFMIP-pdLC with Land-Hist-wfdei): i.e the second element should be "pdLC" rather than "pdL"?

**Comment by hyungjun** [comment]
Yes, it should be "lfmip-pdLC-princeton".
