### ISSUE TITLE
Revise frequency entries

### ISSUE THREAD

**Issue by martinjuckes** [WCRP-CMIP/CMIP6_CVs#345]
Hello Karl (@taylor13 ),

you asked me recently about new frequencies in the data request: there is one set of variables which I overlooked. On balance, I think they can be assigned frequency `3hr`, but there is some ambiguity. This is a request from RFMIP for instantaneous values of a group of variables (http://clipc-services.ceda.ac.uk/dreq/u/efc0d7ba-5629-11e6-9079-ac72891c3257.html ) at 3 hourly intervals for selected days (January 1, March 1, June 1, and September 1 from 1980 and 1992 from the historical run for Tier 1 and, additionally, the same days for 1850 and 2005 in Tier 2). The data files are potentially quite large, because they are 3-d fields on atmospheric model levels with an additional depedance on spectral band. I think that these can be stored with a single time axis with irregular increments: what do you think?

Martin

**Comment by taylor13** [comment]
Hi Martin,
Thanks for raising this issue.  I agree that these can be labeled with frequency= "3hr" only if this doesn't lead to a non-unique DRS identifier or a non-unique filename.    So, we need to make sure that there are no other 3hr variables requested that have the same variable_id *and* the same table_id.  Could you please check on that
If there is no conflict, I don't think labeling them with frequency will be a problem for users, and hopefully the data providers will notice that we only need this for 4 times of selected years.  The fact that they are functions of spectral band will help.
Karl

**Comment by martinjuckes** [comment]
Good point. There are instances of the same variables being asked for different time slices. For instance, rsdcs (surface downwelling clear sky shortwave radiation) is also requested in the CMIP core request for the last 55 years of the historical simulation (1960-2014), while RFMIP is asking for short slices from 1850, 1980, 1992 and 2005.  
We could ask them to provide the data as a single dataset, but with the 1850 data in a different file:
rsdcs_E3hrPt_model_historical_r1i1p1f1_gn_185001010000-185010020000.nc 
rsdcs_E3hrPt_model_historical_r1i1p1f1_gn_196001010000-........
.....
The 1980, 1992 and 2005 time slices requested by RFMIP would not need to be explicitly stored .. as the data will be in the files containing the whole time series from 1960 to 2014.

**Comment by durack1** [comment]
@taylor13 @martinjuckes is there an action item to update the CVs in this repo, or are we ok with the existing entries in [CMIP6_frequency.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_frequency.json)?

If we're ok, I will close this issue. Waiting to hear from you both

**Comment by taylor13** [comment]
Martin, I don't have any strong opinion on how to proceed other than what I've already brought up. If I recall correctly, the rsdscs called for by the CMIP core request is a time-mean, whereas RFMIP wants synoptic samples, so the variables will be in different tables (3hr vs. 3hrpt).  If that is true, then there won't be a duplication of file names.

**Comment by durack1** [comment]
Add new frequencies and amend existing, see https://goo.gl/JF52fu:
```
Include: "subhrPt", "1hrPt",  "3hrPt", "6hrPt", and "yrPt"
Replace "monClim" with "monC"
Replace "1hrClimMon" with "1hrCM"
Remove "subhr"
```
