### ISSUE TITLE
source_id registration of MRI-ESM2.0 -- add info

### ISSUE THREAD

**Issue by yukimotoster** [WCRP-CMIP/CMIP6_CVs#351]
label = MRI-ESM2.0
label_extended = MRI-ESM2.0
source_id = MRI-ESM2-0
institution_id = MRI
release_year = 2017
activity_participation = AerChemMIP C4MIP CFMIP CMIP CORDEX DAMIP DCPP DynVarMIP FAFMIP GMMIP GeoMIP LS3MIP OMIP PMIP RFMIP SIMIP ScenarioMIP VolMIP

aerosol:
description = MASINGAR mk2r4 (192 x 96 longitude/latitude; TL95; 80 levels; top level 0.01hPa)
nominal_resolution = 250 km
atmos:
description = MRI-AGCM3.5 (320 x 160 longitude/latitude; TL159; 80 levels; top level 0.01 hPa)
nominal_resolution = 100 km
atmosChem:
description = MRI-CCM2.1 (128 x 64 longitude/latitude; T42; 80 levels; top level 0.01hPa)
nominal_resolution = 250 km
land:
description = HAL 1.0
nominal_resolution = 100 km
landIce:
description = none
nominal_resolution = none
ocean:
description = MRI.COM4.4 (tripolar primarily 0.5 deg latitude/1 deg longitude with meridional refinement down to 0.3 deg within 10 degrees north and south of the equator; 360 x 364 longitude/latitude; 61 levels; top grid cell 0-2 m)
nominal_resolution = 100 km
ocnBgchem:
description = MRI.COM4.4
nominal_resolution = 100 km
seaIce:
description = MRI.COM4.4
nominal_resolution = 100 km

**Comment by durack1** [comment]
@yukimotoster thanks for this, peek at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further tweaks are required
