### ISSUE TITLE
Inconsistent code for biogeochemistry source_type

### ISSUE THREAD

**Issue by matthew-mizielinski** [WCRP-CMIP/CMIP6_CVs#366]
In the [source_type](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_type.json) CV the code `BGCM` is listed within the allowed source_types, but in the [experiment_id](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json) CV, the code `BGC` is used (e.g. line 10).

I suspect that as `BGC` is in v6.2.3 of the [global attributes](https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit) it is the source_type CV that is in error.

**Comment by taylor13** [comment]
Following a discussion in November 2016 (see appendix 3 of http://goo.gl/v1drZl), the decision was reached to replace BGCM with BGC.  Thus, the source_type CV needs to be corrected.

**Comment by durack1** [comment]
@matthew-mizielinski thanks for the tip-off, that change has now been merged. I have checked [CMIP6_experiment_id.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json) and can't find any other instances of `BGCM` so am closing this issue
