### ISSUE TITLE
source_type:  eliminate "ESM"

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#370]
To make consistent with  http://goo.gl/v1drZl (note 13 after table 1), "ESM" should not be included in this controlled vocabulary.  According to the release notes for 6.1.0 version of that document (see its Appendix 3), the two component name "AOGCM BGC" should be used to indicate the coupled AOGCM biogeochemical model (not "ESM")

**Comment by durack1** [comment]
@taylor13 there are no `AOGCM BGC` entries in [CMIP6_experiment_id.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json), are some tweaks also required to this CV?

**Comment by taylor13** [comment]
@durack1  Look at the "required_model_components"  Some of these lists include both "AOGCM" and "BGC" which are rendered as "AOGCM BGC" (or "BGC AOGCM") when stored in the global attribute source_type.  So, no, experiment_id.json is o.k. as is.
