### ISSUE TITLE
source_id: Miner inconsistency: GEOMIP -> GeoMIP

### ISSUE THREAD

**Issue by MartinaSt** [WCRP-CMIP/CMIP6_CVs#371]
Hi Paul,

just a minor inconsistency. Could you change 'GEOMIP' into 'GeoMIP' in line 3160 of CMIP6_source_id.jsaon?

https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L3160

Thanks
Martina

**Comment by durack1** [comment]
@MartinaSt thanks for checking this, it should now be fixed - see [here](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L3188)
