### ISSUE TITLE
realm ocnBgchem

### ISSUE THREAD

**Issue by jonseddon** [WCRP-CMIP/CMIP6_CVs#383]
There may be an inconsistency between the CV and the data request in the use of ocnBgchem. It is consistently capitalised this way in the CV. However in the data request it is consistently ocnBgChem. Is this an inconsistency and should one of them change? 

Thanks,

Jon

cc @martinjuckes

**Comment by durack1** [comment]
@jonseddon nice pickup, this issue was discussed in https://github.com/WCRP-CMIP/CMIP6_CVs/issues/285#issuecomment-294946964 and after considering the change keeping `ocnBgchem` was the final decision.

We need to get both the dataRequest and ES-DOCs updated to the latest CVs in this repo

**Comment by jonseddon** [comment]
Credit should go to @cdr30 for spotting that. Thanks for getting this sorted!

**Comment by martinjuckes** [comment]
Maybe we should wait for the final finalisation of the CVs?

**Comment by durack1** [comment]
@martinjuckes the only anticipated changes are new registrations of `institution_id` and `source_id`, the controlled vocabularies contained in the CMIP6_CVs repo are not expected to change - some formatting/informational changes are being discussed, see #166, but we are not expecting any CV changes

@taylor13 do you have anything else to add?

**Comment by taylor13** [comment]
The CV's are now completely consistent with the WIP's document on global attributes, DRS, etc.  All known issues have been addressed except that we may at some point adopt in the experiment_id CV the "descriptions" that Charlotte Pascoe has collected for ES-DOC (see https://github.com/WCRP-CMIP/CMIP6_CVs/issues/339).  We have not heard from her in a long time, so I wouldn't wait on that.

Also, as Paul indicates,  the json files where the CV's are recorded may be modified at some point in two ways:

1)  The "version" information at the bottom of each file will be augmented.  (see discussion at https://goo.gl/TdzjRC )
2)  As Paul noted, we may add some information about frequency and/or realm to the table_id CV (see #166)

**Comment by durack1** [comment]
@jonseddon @martinjuckes @taylor13 I'll attach this to the standing issue #28 which we are planning to implement soon to ensure that CV versioning is more comprehensive. When #28 is closed I will also close this issue.

@jonseddon we can only ask @martinjuckes  and the ES-DOC folks (@esdoc-system-user, @momipsl, @eguil) to sync with the stable CVs, so hopefully this occurs within the next week or so and we're all in agreement

**Comment by durack1** [comment]
@jonseddon I believe everything required is contained in #28, we'll review this issue when #28 is finalised and we are preparing to close
