### ISSUE TITLE
source_id registration of SAM0-UNICON

### ISSUE THREAD

**Issue by sjh11556** [WCRP-CMIP/CMIP6_CVs#387]
```
activity_participation = [CMIP, ScenarioMIP]
institution_id = SNU
label = SAM0-UNICON
label_extended = SAM0-UNICON
aerosol = MAM3
nominal_resolution_aerosol = 100 km
atmosphere = CAM5.3 with UNICON (1deg; 288 x 192 longitude/latitude; 30 levels; top level ~2 hPa) 
nominal_resolution_atmos = 100 km
atmospheric_chemistry = none
nominal_resolution_atmosChem = none
land = CLM4.0
nominal_resolution_land = 100 km
landIce = none
nominal_resolution_landIce = none
ocean = POP2 (Displaced Pole; 320 x 384 longitude/latitude; 60 levels; top grid cell 0-10 m)    
nominal_resolution_ocean = 100 km
ocean_biogeochemistry = none
nominal_resolution_oceanBgchem = none
seaIce = CICE4.0
nominal_resolution_seaIce = 100 km
release_year = 2017
source_id = SAM0-UNICON
```

**Comment by durack1** [comment]
@sjh11556 thanks for the submission. Please amend the entries above which include `??` entries, from the [list of `nominal_resolution` entries](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_nominal_resolution.json)

**Comment by sjh11556** [comment]
I added nominal_resolution information for the aerosol, land and sea ice model.

**Comment by durack1** [comment]
@sjh11556 thanks, peek at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further tweaks are required

**Comment by sjh11556** [comment]
@durack1 
I changed "label_extended" entry as 
label_extended = SAM0-UNICON (SNU Atmosphere Model version 0 with Unified Convection Scheme). Could you register again?

**Comment by durack1** [comment]
@sjh11556 that change has been made, peek at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further tweaks are required
