### ISSUE TITLE
Augment activity_id to provide description with identifier

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#397]
Augment `activity_id` to be self-describing, following full descriptions at https://www.wcrp-climate.org/modelling-wgcm-mip-catalogue/modelling-wgcm-cmip6-endorsed-mips e.g.
```
{
   "activity_id":{
      "AerChemMIP":"Aerosols and Chemistry Model Intercomparison Project",
      "C4MIP":"Coupled Climate Carbon Cycle Model Intercomparison Project",
      "CFMIP":"Cloud Feedback Model Intercomparison Project",
      "CMIP":"CMIP DECK: 1pctCO2, abrupt4xCO2, amip, esm-piControl, esm-historical, historical, and piControl experiments",
...
}
```

**Comment by durack1** [comment]
@momipsl, @markelkington, @martinjuckes, @MartinaSt, @ARadhakrishnanAtGFDL will it impact any of you if we make the change noted above, and similar changes captured in #396 and #395 ?

We have noted that the identifiers are not self-describing, and converting this information to a dictionary, with both key and description provides more context

@taylor13

**Comment by MartinaSt** [comment]
@durack1 Thanks for asking: source_type and grid_label are no problem for the citation. In case of activity_id there might be a minor change in the insert script required but this is no problem.

**Comment by markelkington** [comment]
Paul

No problem for me – I think it helps to have a formal description

Mark
