### ISSUE TITLE
source_id registration of MPIESM-1-2-HAM

### ISSUE THREAD

**Issue by nedavid** [WCRP-CMIP/CMIP6_CVs#403]
label = MPIESM1.2-HAM
label_extended = MPIESM1.2-HAM
source_id = MPIESM-1-2-HAM
institution_id = HAMMOZ-Consortium
release_year = 2017
activity_participation = [AerChemMIP,CMIP]
aerosol = HAM2.3
atmosphere = ECHAM6.3 (spectral T63; 192 x 96 longitude/latitude; 47 levels; top level 0.01 hPa)  
atmospheric_chemistry = sulfur chemistry (unnamed)
land_ice = none/prescribed
land = JSBACH3.20
nominal_resolution_atmos = 200 km
nominal_resolution_landIce = None
nominal_resolution_ocean = 100 km
ocean = MPIOM1.63 (bipolar GR1.5, approximately 1.5deg; 256 x 220 longitude/latitude; 40 levels; top grid cell 0-12 m)    
ocean_biogeochemistry = HAMOCC
sea_ice = unnamed (thermodynamic (Semtner zero-layer) dynamic (Hibler 79) sea ice model)

**Comment by durack1** [comment]
@nedavid we need some additional fields to correctly register your `source_id` please fill in/correct the entries below:
```
source_id = MPIESM-1-2-HAM
label = MPIESM 1.2 HAM
label_extended = MPIESM 1.2 HAM
institution_id = HAMMOZ-Consortium
release_year = 2017
activity_participation = [AerChemMIP, CMIP]

aerosol:
description = HAM2.3
nominal_resolution = 250 km !see https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_nominal_resolution.json
atmos:
description = ECHAM6.3 (spectral T63; 192 x 96 longitude/latitude; 47 levels; top level 0.01 hPa)
nominal_resolution = 250 km
atmosChem:
description = sulfur chemistry (unnamed)
nominal_resolution = 250 km
land:
description = JSBACH3.20
nominal_resolution = 250 km    
landIce:
description = none
nominal_resolution = none 
ocean:
description = MPIOM1.63 (bipolar GR1.5, approximately 1.5deg; 256 x 220 longitude/latitude; 40 levels; top grid cell 0-12 m)
nominal_resolution = 100 km
ocnBgchem:
description = HAMOCC !Is there a version to record?
nominal_resolution = 100 km
seaIce:
description = unnamed (thermodynamic (Semtner zero-layer) dynamic (Hibler 79) sea ice model)
nominal_resolution = 100 km
```

**Comment by nedavid** [comment]
@durack1 200 km would be closer to the resolution of the aerosol, atmos, atmosChem and land modules. Would it be possible to add 200 km to the list of nominal resolutions (https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_nominal_resolution.json)? If not 250 km comes closest. The HAMOCC version number is added below.

```
source_id = MPIESM-1-2-HAM
label = MPIESM1.2-HAM
label_extended = MPIESM1.2-HAM
institution_id = HAMMOZ-Consortium
release_year = 2017
activity_participation = [AerChemMIP, CMIP]

aerosol:
description = HAM2.3
nominal_resolution = 250 km
atmos:
description = ECHAM6.3 (spectral T63; 192 x 96 longitude/latitude; 47 levels; top level 0.01 hPa)
nominal_resolution = 250 km
atmosChem:
description = sulfur chemistry (unnamed)
nominal_resolution = 250 km
land:
description = JSBACH3.20
nominal_resolution = 250 km    
landIce:
description = none
nominal_resolution = none 
ocean:
description = MPIOM1.63 (bipolar GR1.5, approximately 1.5deg; 256 x 220 longitude/latitude; 40 levels; top grid cell 0-12 m)
nominal_resolution = 100 km
ocnBgchem:
description = HAMOCC6
nominal_resolution = 100 km
seaIce:
description = unnamed (thermodynamic (Semtner zero-layer) dynamic (Hibler 79) sea ice model)
nominal_resolution = 100 km
```

**Comment by durack1** [comment]
@nedavid thanks for the revision. We set the `nominal_resolution` entries many months ago, so unfortunately it's too late to amend the list. Please take a peek at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further tweaks are required

**Comment by nedavid** [comment]
Please change the names of the label, label_extended and source_id as follows (I changed the issue name as well):

label = MPI-ESM1.2-HAM
label_extended = MPI-ESM1.2-HAM
source_id = MPI-ESM-1-2-HAM

**Comment by durack1** [comment]
Reopening as changes are yet to be merged

**Comment by durack1** [comment]
@nedavid those changes are now in place, please take a peek at [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further tweaks are required

**Comment by nedavid** [comment]
**@durack1** Thank you for making the changes. No further tweaks are required.
