### ISSUE TITLE
source_id registration of MRI-AGCM3-2

### ISSUE THREAD

**Issue by ryo-mizuta** [WCRP-CMIP/CMIP6_CVs#410]
label = MRI-AGCM3-2
label_extended = MRI-AGCM3-2
source_id = MRI-AGCM3-2
institution_id = MRI
release_year = 2017
activity_participation = [DynVarMIP, HighResMIP]

aerosol:
description = Prescribed from MRI-ESM2.0
nominal_resolution = 250 km
atmos:
description = MRI-AGCM3.2S (TL959; 1920 x 960 longitude/latitude; 64 levels; top level 0.01 hPa)
nominal_resolution = 25 km
atmosChem:
description = none
nominal_resolution = none
land:
description = SIB0109
nominal_resolution = 25 km
landIce:
description = none
nominal_resolution = none 
ocean:
description = none
nominal_resolution = none
ocnBgchem:
description = none
nominal_resolution = none
seaIce:
description = none
nominal_resolution = none

**Comment by durack1** [comment]
@ryo-mizuta I appended the `CMIP` `activity_participation` as this is an entry card to CMIP6. Please take a peek at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further tweaks are required
