### ISSUE TITLE
Definition of 1hrCM

### ISSUE THREAD

**Issue by martinjuckes** [WCRP-CMIP/CMIP6_CVs#414]
The current definition of "1hrCM" in the frequency CV is inconsistent with its usage in the CMIP6 data request. The data request was using ` 1hrClimMon` to label data which consisted of monthly averages of hourly data, i.e. a monthly averaged diurnal cycle. This has recently been changed to '1hrCM', but the definition should be `monthly means of hourly mean data'. The `cell_methods` is `area: mean time: mean within days time: mean over days` (compared with `area: mean time: mean within years time: mean over years` for the monthly climatology  -- in both cases the CF specification of the frequency will be in the time axis).

**Comment by taylor13** [comment]
@martinjuckes I'm not sure I'm following.  Are you requesting 12x24 time samples (one for each hour of each month, from some multi-year climatology), or Nx12x24 time samples where N is the number of years.

If it is the latter, in the CV we should probably replace 
```
 "1hrCM":"monthly climatology of diurnal cycle computed from hourly samples",
```
with
```
"1hrCM":"monthly mean diurnal cycle computed from hourly samples",
```
Would this be correct?

**Comment by taylor13** [comment]
Perhaps a better option:
```
"1hrCM":"monthly-mean diurnal cycle resolving each day into 1-hour means"
```

**Comment by durack1** [comment]
@taylor13 how can you have a monthly-mean diurnal cycle in 1-hour means? What is the format of this data, many entries of data averaged over 1-hour, so 24 values for each day, ~30 days each year in a month..?

**Comment by durack1** [comment]
Ok so following the top https://github.com/WCRP-CMIP/CMIP6_CVs/issues/414#issue-261604832 I now get that this is 24 values which represent the average over a complete month for each of the 24-hourly values - so an average of each hour across all days in the month, with a shape (24 hour values, month, <level>, lat, lon)?

**Comment by taylor13** [comment]
Yes, (although I'm not sure the two times (24 hour value and months) aren't reversed in order.  The idea is that we are characterizing the mean diurnal cycle for each month by averaging each hour-mean-value (twenty-four 1-hour means) across all days in the month.

**Comment by martinjuckes** [comment]
Karl's last comment is correct, the idea is to have a mean day for each month, where the "mean day" is represented by 24 hourly values, so you have 24 values for each month in the time series. There is no averaging over years, it is just averaging over days within individual months.

**Comment by durack1** [comment]
@taylor13 @martinjuckes just to put everything in one place, we currently have the recorded frequencies:
```
{
    "frequency":{
        "1hr":"sampled hourly",
        "1hrCM":"monthly climatology of diurnal cycle computed from hourly samples",
        "1hrPt":"sampled hourly, at specified time point within an hour",
        "3hr":"sampled every 3 hours",
        "3hrPt":"sampled 3 hourly, at specified time point within the time period",
        "6hr":"sampled every 6 hours",
        "6hrPt":"sampled 6 hourly, at specified time point within the time period",
        "day":"daily mean samples",
        "dec":"decadal mean samples",
        "fx":"fixed (time invariant) field",
        "mon":"monthly mean samples",
        "monC":"monthly climatology computed from monthly mean samples",
        "monPt":"sampled monthly, at specified time point within the time period",
        "subhrPt":"sampled sub-hourly, at specified time point within an hour",
        "yr":"annual mean samples",
        "yrPt":"sampled yearly, at specified time point within the time period"
},
```
And the recommended change here is to update `1hrCM` to read:
```
"1hrCM":"monthly-mean diurnal cycle resolving each day into 1-hour means",
```
Am I following correctly?

**Comment by taylor13** [comment]
@martinjuckes Martin, could you please confirm that 1-hour-mean samples are used to compute the climatology, as opposed to 1-hour point samples?
thanks,
Karl

**Comment by martinjuckes** [comment]
Yes, it is defined with `cell_methods=area: mean time: mean within days time: mean over days`, which implies, I believe, the mean over the inner periods "HMS0-HMS1" to be specified in the climatological bounds variable.

**Comment by taylor13** [comment]
Thanks @martinjuckes.
@durack1 I think it is safe to update the CV as proposed in https://github.com/WCRP-CMIP/CMIP6_CVs/issues/414#issuecomment-335032399 (if you haven't already), and close this issue.
