### ISSUE TITLE
institution_id registration of NIWA

### ISSUE THREAD

**Issue by jonnyhtw** [WCRP-CMIP/CMIP6_CVs#421]
NIWA will be running some of the AerChemMIP simulations in collaboration with the MOHC (@alistairsellar, @matthew-mizielinski, @metoffice) and NERC. Both of these institutions already exist in the list. Please add NIWA to the list of institutions running the already registered model UKESM1-0-LL as part of AerChemMIP.

Thank you

`institution_id = NIWA`
`institution = National Institute of Water and Atmospheric Research, 301 Evans Bay Parade, Hataitai, Wellington 6021, New Zealand`

**Comment by durack1** [comment]
@jonnyhtw thanks for the request. The current registration of [`UKESM1-0-LL`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L3633-L3650) includes two institutions, both `MOHC` and `NERC`. We can also register `NIWA` and add this as a third registered institution for this model, however, we have no granularity in our registration as to which simulations/experiments that each registered institution is contributing toward

**Comment by durack1** [comment]
@jonnyhtw that change is now implemented, take a peek at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) (and the source json at [CMIP6_source_id.json#L3633-L3651](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L3633-L3651)) and let me know if any tweaks are required
