### ISSUE TITLE
activity_id -- add 'HighResMIP'  and remove 'CMIP'

### ISSUE THREAD

**Issue by yjyangjie** [WCRP-CMIP/CMIP6_CVs#439]
"activity_participation":[
                "CFMIP",
                "CORDEX",
                "GMMIP",
                "OMIP",
                "SIMIP",
                "ScenarioMIP”,
                “HighResMIP”
            ]

**Comment by yjyangjie** [comment]
This is Yang Jie  from Tsinghua University, China. I want to modify the activity_participation.
And  source_id: CIESM  ,institution_id: THU .
####
"activity_participation":[
"CFMIP",
"CORDEX",
"GMMIP",
"OMIP",
"SIMIP",
"ScenarioMIP”,
“HighResMIP”
]

**Comment by durack1** [comment]
@yjyangjie thanks for this update. The `CMIP` registration is compulsory, as this incorporates the DECK "entry card" simulations, piControl, 1pctCO2, historical etc. So I will keep `CMIP` and add in `HighResMIP`.

**Comment by yjyangjie** [comment]
Thanks.

**Comment by durack1** [comment]
@yjyangjie those changes are now in place, please take a peek at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further changes are required
