### ISSUE TITLE
source_id -- add NERC to two HadGEM3-GC31 models

### ISSUE THREAD

**Issue by jonseddon** [WCRP-CMIP/CMIP6_CVs#441]
Hi,

Would it be possible for the institution_id NERC be added to source_ids HadGEM3-GC31-HH and HadGEM3-GC31-HM in addition to the existing institution_id of MOHC for these two models please?

Thanks,

Jon

**Comment by taylor13** [comment]
@jonseddon 
Hi Jon,

institution_id must be a single item, not a list.  [it is used, for example, in constructing the directory structure.]   I think it would be o.k. to define a new "institution" as institution_id = "MOHC-NERC" without breaking anything.  Then the full description of the "institution" would be a semi-colon separate list similar to the EC-Earth-Consortium  (see https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_institution_id.json)

If this is what you would like to do, please submit an issue proposing a "new" institution.

thanks,
Karl

**Comment by durack1** [comment]
@taylor13 that's a problem in the existing version of the `source_id` for two models, both [`UKESM1-0-LL`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L3845-L3848) and [`UKESM1-0-MMh`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L3898-L3901) which have 3, or 2 separate `institution_id` values listed. I agree, we'll need to amend these, as in the case of `UKESM1-0-LL` two separate institutions (`MOHC` and `NIWA`] will be separately running simulations with this model, we should create `MOHC-NERC` and `MOHC-NERC-NIWA` institutions and replace these entries. @jonseddon does this seem a reasonable forward step?

**Comment by taylor13** [comment]
Let's think a bit more about this.  We *should* be able to allow multiple institutions and have either one return qualifying datasets in the search interface.  Only the first institution would be considered the "DRS" value, and it would be used in directory structures,  further_info_url, etc.  

We need to check with Denis, Sasha, Eric, and perhaps others before authorizing this modification.

**Comment by matthew-mizielinski** [comment]
For the HadGEM3-GC31 series of models we expect two institutions to be performing & submitting data; MOHC and NERC.
For the UKESM1 models I'm aware of four institutions; MOHC, NERC, NIWA and KMA.

I'm sure its important to the institutions involved that credit for performing the experiments is appropriately given, particularly in the case of some of the scenarios where current plans suggest MOHC, NERC and KMA will each perform ensemble members, and all four may be involved in AerChemMIP experiments.

I can understand keeping the institution used in the DRS constant, but propagating this through to the further_info_url would appear to require MOHC to be responsible for managing/organising the further information for other institutions (I'll have a further think about this).

I note that the EC-Earth groups have organised this differently, with a single institute_id referring to the whole consortium.

**Comment by taylor13** [comment]
Thanks for this additional information about plans for the Hadley Centre models.  In an offline discussion I noted that there are two use cases we might want to consider:

1) Two or more institutions want to claim responsibility for the same simulation produced by a model.  
2)  Different institutions want to claim responsibility for different simulations produced by a single model.

Case 1: Two or more institutions want to claim responsibility for the same simulation produced by a model:
This can currently be done only if the institutions team up and define an institution_id (and institution) containing both their acronyms/names *and* *all* simulations produced by that model are jointly sponsored by both institutions.  In short, some of the ESGF infrastructure currently assumes there is just one institution (or one collection of institutions identified by a single name) associated with each model (i.e., with each source_id).

Case 2:  Different institutions want to claim responsibility for different simulations produced by a single model:
At present this can't be done.

Further comments welcome.

**Comment by taylor13** [comment]
@jonseddon @matthew-mizielinski @durack1 
I can't promise we can do this, but is this what we would like CMOR to do?
```
1) receive a *list* of institution_id's (or a single institution_id) from the user, which are 
to be associated with a data set
2) check whether each of the i.d.'s, is found in the CV
3) extract from the CV the "institution(s)" using the "institution_id(s)" as keys
4)  construct the institution_id global attribute as a space-separated list of the institution_id(s)
(as passed by the user)
5)  write the institution global attribute for each institution_id as a semi-colon-separated string. 
6) use the first institution_id in defining the directory structure and further_info_url
```
and is this what we want PrePARe to do?
```
1) Read global attributes institution_id and institution.
2) Check that each of the institution_id's (appearing as space separated strings) is 
found in the CV
3) Check for each institution_id whether the corresponding "institution" in the CV 
appears within the institution global attribute.
4) Check that the same institution_id appears in the directory structure and in 
further_info_url, and that it also is the first id appearing in the institution_id global attribute.

As a bonus, it would be nice to
5) check that the institution_id(s) associated with the data set are included in the list 
of institution_id's found in the source_id CV for the model that produced the data set.
```
CMOR and PrePARe already do some of the above, but before checking whether it would be easy to modify them to meet the additional needs, I want to make sure we know what we want.

thanks.

**Comment by jonseddon** [comment]
From our HadGEM3/UKESM point of view, I believe that although there are multiple institution_ids defined for a source_id in the CV, we will only ever pass a single institution_id to CMOR. @matthew-mizielinski will have to confirm this. However, I can see that the ability to pass multiple institution_ids could potentially be useful for other groups.

Can I check in step 6 of the CMOR requirements, do you mean the first institution_id passed to CMOR in step 1, or the first institution_id in the CV? From the PrePARe steps I believe the former.

Thanks for looking into this. It provides very useful functionality for us.

**Comment by markelkington** [comment]
Sorry I am a bit late to this discussion - I would like to add a note of caution here before anything is changed.   I would strongly argue against combination acronyms for institute_id (e.g. MOHC-NERC).  The end user must be able to uniquely identify the institute that produced the data and ultimately be able to direct queries to that institute.  If you must use a combination acronym then a support mechanism needs to be established for the combination - and at the Met Office we don't want to have to deal with enquiries for data we didn't produce.    

The CV system needs to be able to reflect a one to many relationship between models and institutes.  In CMIP5 several institutes delivered data from the HadGEM2 model and these were all correctly handled by ESGF with the relevant institute label.  If an end-user wanted to find all data from hadGEM2 model ignoring the data provider then the ESGF search mechanisms support that.

Matthew has indicated the likely use of HadGEM-GC3 and UKESM across the CMIP6 programme and we have agreed with these partners that data will be submitted on the basis of individual institutes (as Jon indicated in his last post).

I don't fully understand the technical issues preventing the model and institute being considered independent descriptors for the supplied data as it was for CMIP5.  If they need to be dependent for PREPARE then can't we just define a one-to-many structure and allow PREPARE checks to verify that the supplied data matches one of the model->institute relationships.

**Comment by matthew-mizielinski** [comment]
In can confirm as @jonseddon suggested that each simulation will be produced by a single institution.

I had also forgotten about the ES-Doc / support query requests that @markelkington is referring to, which could significantly complicate support procedures, particularly if I have to convince scientists at other institutions (some of whom have not been particularly responsive to date) to respond to queries regarding datasets we have had no involvement in.

**Comment by taylor13** [comment]
Thanks, all, for clarifying what we need (and what we don't want).  I vaguely recall that Mark (and Martina?) and I had discussions about how we would handle this many months ago, and I think that led to the current approach (which might not have to be changed at all).  So, to summarize what we know we need at this time, for CMOR:
```
1) user passes to CMOR a single institution_id that indicates who should be contacted with
any questions about the data. 
2) CMOR checks whether the institution_id is in the CV
3) CMOR extracts from the CV the "institution" using the "institution_id" key
4) CMOR writes institution_id as a global attribute
5) CMOR writes the institution as a global attribute 
6) CMOR uses the institution_id in defining the directory structure and further_info_url
```
and for PrePARe:
```
1) Read global attributes institution_id and institution.
2) Check that the institution_id is found in the CV
3) Check that the "institution" is the same as the institution associated with institution_id
found in the CV
4) Check that the institution_id recorded as a global attribute also appears in the directory 
structure and in further_info_url
```
Note that I have not asked PrePARe or CMOR to check that the institution has been authorized to contribute results from any particular model.  As long as an institution is registered in the institution_id CV, CMOR & PrePARe will let it contribute results from any registered CMIP6 model.  I think that's probably o.k. (although, then the source_id CV might not show all the institutions contributing results from the models registered).  Any concerns?

**Comment by jonseddon** [comment]
@taylor13 that looks great to me. Many thanks!

**Comment by durack1** [comment]
@jonseddon those changes are now in place, please take a peek at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) to double check.

**Comment by jonseddon** [comment]
@durack1 That looks great. Many thanks! Jon
