### ISSUE TITLE
source_id -- activity_participation add HighResMIP to additional HadGEM3-GC31 models

### ISSUE THREAD

**Issue by jonseddon** [WCRP-CMIP/CMIP6_CVs#442]
Hi,

I would be grateful if you could add activity_participation HighResMIP to source_ids HadGEM3-GC31-MM and HadGEM3-GC31-LL please.

Many thanks,

Jon

**Comment by durack1** [comment]
@jonseddon no problem. I have also noted the issue where other `MOHC` models: `HadGEM3-GC31-HH`, `HadGEM3-GC31-HM`, `HadGEM3-GC31-LM`, `HadGEM3-GC31-MM`, `UKESM1-0-LL` and `UKESM1-0-MMh` were missing the `CMIP` `activity_id` entry. I will fix all these issues at once

**Comment by durack1** [comment]
@jonseddon please take a peek at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further tweaks are required

**Comment by jonseddon** [comment]
Hi @durack1,

That looks great now.

Many thanks!

Jon
