### ISSUE TITLE
institution_id registration of AER

### ISSUE THREAD

**Issue by pernak18** [WCRP-CMIP/CMIP6_CVs#459]
institution_id = AER
institution = Research and Climate Group, Atmospheric and Environmental Research, 131 Hartwell Avenue Lexington, MA  02421, USA

**Comment by durack1** [comment]
@pernak18 `AER` is now registered, please check the entry at [CMIP6_institution_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_institution_id.html)
