### ISSUE TITLE
source_id registration of LBLRTM

### ISSUE THREAD

**Issue by pernak18** [WCRP-CMIP/CMIP6_CVs#460]
label = LBLRTM
label_extended = Line-By-Line Radiative Transfer Model v12.8, aer_v_3.6, MT_CKD_3.2
source_id = LBLRTM-12-8
institution_id = AER
release_year = 2017
activity_participation = [RFMIP]

aerosol:
description = none
nominal_resolution = none
atmos:
description = none
nominal_resolution = none
atmosChem:
description = none
nominal_resolution = none
land:
description = none
nominal_resolution = none
landIce:
description = none
nominal_resolution = none
ocean:
description = none
nominal_resolution = none
ocnBgchem:
description = none
nominal_resolution = none
seaIce:
description = none
nominal_resolution = none

**Comment by durack1** [comment]
@RobertPincus @taylor13 this is another `RFMIP` registration we're going to have to deal with appropriately.

@pernak18 apologies for the delay in registration, we're trying to work out how to deal correctly with `RFMIP` registrations

**Comment by durack1** [comment]
@pernak18 `LBLRTM` is now registered, please review the details at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further edits are required.

**Comment by pernak18** [comment]
@durack1 it wasn't clear to me how to reopen, but i was able to edit the initial comment anyway. i've added the LBL version number

**Comment by durack1** [comment]
@pernak18 the "Reopen and comment" button works for me (below this dialogue box)

**Comment by durack1** [comment]
@pernak18 thanks for the tweaks, the revised registration is now complete - take a peek at [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know of any further tweaks required
