### ISSUE TITLE
source_id registration of KIOST-ESM

### ISSUE THREAD

**Issue by noah1004** [WCRP-CMIP/CMIP6_CVs#469]
source_id = KIOST-ESM
institution_id = KIOST
institution = Korea Institute of Ocean Science & Technology, Busan 49111, Republic of Korea
release_year = 2018
activity_participation = [CMIP,C4MIP,PMIP,DynVarMIP]

label = KIOST-ESM
label_extended = KIOST Earth System Model v2
aerosol:
description = none
nominal_resolution = none
atmos:
description = GFDL-AM2.0 (cubed sphere (C48); 32 vertical levels; 192x96 longitude/latitude; model top 2hPa)
nominal_resolution = 250km
atmosChem:
description = simple carbon aerosol model (emission type)
nominal_resolution = 250km
land:
description = NCAR-CLM4
nominal_resolution = 250km
landIce:
description = NCAR-CLM4
nominal_resolution = 250km
ocean:
description = GFDL-MOM5.0 (tripolar - nominal 1.0 deg; 360x200 longitude/latitude; 52 levels; top grid cell 0-2 m; NK mixed layer scheme)
nominal_resolution = 100km
ocnBgchem: 
description = TOPAZ2
nominal_resolution = 100km
seaIce:
description = GFDL-SIS
nominal_resolution = 100km

**Comment by durack1** [comment]
@noah1004 thanks for generating this issue.

We need the additional information registered for your model, please update the above with the complete details for each of the modeling realms - for a complete example, please see [`AWI-CM-1-0-HR`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L3-L55).

I also assume you're contributing to the `activity_participation` = `CMIP`, which will include the entry card simulations: `piControl`, `amip`, `historical` etc?

**Comment by noah1004** [comment]
@durack1 thanks for commenting
I updated with the details for our model and also added CMIP to the activity_participation.

**Comment by durack1** [comment]
@noah1004 no problem, the closest [`nominal_resolution` value is "250 km"](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_nominal_resolution.json), so I will update your entries above and get these registered.

Can you also provide a `XXX x XXX longitude/latitude` pair for the `atmos` description?

**Comment by noah1004** [comment]
@durack1 yes, I updated longitude/latitude pair for the atmos description.

**Comment by durack1** [comment]
@noah1004 `KIOST-ESM` is now registered, please review the details at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further edits are required

**Comment by noah1004** [comment]
@durack1 Thank you for your efforts.
