### ISSUE TITLE
source_id >  CNRM-CM6-1 > activity_participation -- add HighResMIP

### ISSUE THREAD

**Issue by mpmoine** [WCRP-CMIP/CMIP6_CVs#471]
@durack1 

Dear Paul,

We recently realised that **HighResMIP** was missing in the list of **activity_participation** for **CNRM-CM6-1** model:

> "CNRM-CM6-1":{
>             "activity_participation":[
>                 "CFMIP",
>                 "CMIP",
>                 "DAMIP",
>                 "DCPP",
>                 "FAFMIP",
>                 "GMMIP",
>                 "ISMIP6",
>                 "LS3MIP",
>                 "PMIP",
>                 "RFMIP",
>                 "ScenarioMIP"
> ],

Would you mind adding **HighResMIP** to the list? This request is made on behalf of our two french modelling group, CNRM and Cerfacs, forming a single institute for CMIP6 (CNRM-CERFACS).

Thanks in advance,
Marie-Pierre Moine (Cerfacs)
Stéphane Sénési (CNRM)

**Comment by durack1** [comment]
@mpmoine `activity_participation` is now updated, please review the details at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further edits are required

**Comment by mpmoine** [comment]
Thanks for the update! Yes, we are going to check in details and we let you knnow quickly in case other corrections are required.
