### ISSUE TITLE
source_id registration of CAS-ESM1-0

### ISSUE THREAD

**Issue by zhang-he** [WCRP-CMIP/CMIP6_CVs#479]
label = CAS-ESM 1.0
label_extended = CAS-ESM 1.0 (Chinese Academy of Sciences Earth System Model version 1.0)
source_id = CAS-ESM1-0
institution_id = CAS
release_year = 2015
activity_participation = [AerChemMIP][C4MIP][CFMIP][CMIP][CORDEX][DAMIP][DynVarMIP][FAFMIP][GMMIP][GeoMIP][HighResMIP][LS3MIP][LUMIP][OMIP][PMIP][SIMIP][ScenarioMIP][VIACSAB][VolMIP]

aerosol:
description = IAP AACM
nominal_resolution = 100 km
atmos:
description = IAP AGCM4.1 (Finite difference dynamical core; 256 x 128 longitude/latitude; 30 levels; top level 2.2 hPa)
nominal_resolution = 140 km
atmosChem:
description = IAP AACM
nominal_resolution = 100 km
land:
description = CoLM
nominal_resolution = 140 km    
landIce:
description = none
nominal_resolution = none 
ocean:
description = LICOM2.0 (LICOM2.0, primarily 1deg; 362 x 196 longitude/latitude; 30 levels; top grid cell 0-10 m)
nominal_resolution = 100 km
ocnBgchem:
description = IAP OBGCM
nominal_resolution = 100 km
seaIce:
description = CICE4
nominal_resolution = 100 km

**Comment by durack1** [comment]
@zhang-he `CAS-ESM1-0` is now registered, please review the details at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further edits are required.

I also note that you have not included version identifiers for the `aerosol`, `atmosChem`, `land` and `ocnBgchem` - if you would like to amend these, please just reopen this issue with the revised details and we'll update the registration
