### ISSUE TITLE
Request to add CDRMIP to GFDL-ESM4

### ISSUE THREAD

**Issue by aradhakrishnanGFDL** [WCRP-CMIP/CMIP6_CVs#483]
"GFDL-ESM4":{
            "activity_participation":[
                "AerChemMIP",
                "C4MIP",
                "CMIP",
                "DAMIP",
                "DynVarMIP",
                "LUMIP",
                "OMIP",
                "ScenarioMIP",
                "CDRMIP"
            ],
            "cohort":[
                "Registered"
            ],
            "institution_id":[
                "NOAA-GFDL"
            ],
            "label":"GFDL-ESM4",
            "label_extended":"GFDL-ESM4",
            "model_component":{
                "aerosol":{
                    "description":"interactive",
                    "nominal_resolution":"100 km"
                },
                "atmos":{
                    "description":"GFDL-AM4.1 (Cubed-sphere (c96) - 1 degree nominal horizontal resolution; 360 x 180 longitude/latitude; 49 levels; top level 1 Pa)",
                    "nominal_resolution":"100 km"
                },
                "atmosChem":{
                    "description":"GFDL-ATMCHEM4.1 (full atmospheric chemistry)",
                    "nominal_resolution":"100 km"
                },
                "land":{
                    "description":"GFDL-LM4.1",
                    "nominal_resolution":"100 km"
                },
                "landIce":{
                    "description":"GFDL-LM4.1",
                    "nominal_resolution":"100 km"
                },
                "ocean":{
                    "description":"GFDL-MOM6 (tripolar - nominal 0.5 deg; 720 x 360 longitude/latitude; 75 levels; top grid cell 0-2 m)",
                    "nominal_resolution":"50 km"
                },
                "ocnBgchem":{
                    "description":"COBALT 2.0",
                    "nominal_resolution":"50 km"
                },
                "seaIce":{
                    "description":"SIS2",
                    "nominal_resolution":"50 km"
                }
            },
            "release_year":"2017",
            "source_id":"GFDL-ESM4"
        },

**Comment by durack1** [comment]
@aradhakrishnanGFDL no problem, we can update the `activity_participation` field. Are there any other amendments - it wasn't obvious from the above?

**Comment by aradhakrishnanGFDL** [comment]
@durack1 Thank you. This should be it at this time. 
GFDL-ESM4 will be participating in CDRMIP at the Tier 1 level (3 experiments).

**Comment by durack1** [comment]
@aradhakrishnanGFDL that update is now complete, please review the details at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further edits are required.
