### ISSUE TITLE
institution_id registration of NUIST

### ISSUE THREAD

**Issue by peace2016** [WCRP-CMIP/CMIP6_CVs#487]
institution_id = NUIST
institution = Nanjing University of Information and Science & Technology, Nanjing, 210044, China

**Comment by durack1** [comment]
@peace2016 `NUIST` [was registered back on the 4th October 2016](https://github.com/WCRP-CMIP/CMIP6_CVs/commit/643f792e3d38661b8aaf93b1ced3d52f3354ffae) the current registered information is below
```
"NUIST":"Nanjing University of Information Science and Technology, Nanjing, 210044, China"
```
and can be found in [CMIP6_institution_id.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_institution_id.json#L35). As the institution is already registered, I will close this issue - please reopen if an amendment is required
