### ISSUE TITLE
source_id registration of NUIST-ESM-v3

### ISSUE THREAD

**Issue by peace2016** [WCRP-CMIP/CMIP6_CVs#488]
Label = NESM v3
label_extended = NUIST ESM v3 (This entry is free text for users to contribute verbose information)
source_id = NESM3 (an alternative could be "ACCESS1-0")
institution_id = NUIST
release_year = 2016
activity_participation = [CMIP]

aerosol:
description = none
nominal_resolution = none
atmos:
description = ECHAM v6.3 (T63; 192 x 96 longitude/latitude; 47 levels; top level 1 Pa)
nominal_resolution = 200 km
atmosChem:
description = none
nominal_resolution = none
land:
description = JSBACH v3.1
nominal_resolution = 2 km    
landIce:
description = none
nominal_resolution = none 
ocean:
description = NEMO v3.4 (NEMO v3.4, tripolar primarily 1deg; 384 x 362 longitude/latitude; 46 levels; top grid cell 0-6 m)
nominal_resolution = 100 km
ocnBgchem:
description = none
nominal_resolution = none
seaIce:
description = CICE4.1
nominal_resolution = 100 km

**Comment by peace2016** [comment]
Hi, the information fo NUIST-ESM-v3 has not been shown on https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html, although I have registered for it by generating the above issues. Is there any problem or anything else I need to do?  Thanks.

**Comment by jypeter** [comment]
I confirm I can't see **NESM3** on rawgit yet. I have updated https://pmip4.lsce.ipsl.fr/doku.php/database:participants#nuist based on the content of this issue, rather than on the rawgit page

**Comment by durack1** [comment]
@peace2016 @jypeter I've been away on leave the last couple of weeks, but should get to registering `NESM3` later today

**Comment by durack1** [comment]
@peace2016 registration of `NESM3` is now complete. Please take a look at [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further tweaks are required. In particular, I am curious whether `2016` is the correct `release_year`? I have also amended the `nominal_resolution` attributes for the `atmos` and `land` realms, as your submitted values are not valid entries as compared to the registered values found in [CMIP6_nominal_resolution.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_nominal_resolution.json)

**Comment by peace2016** [comment]
@durack1, Thanks! We have checked the information of our mode NESM3 listed on  CMIP6_source_id.html. No problem is found. Thanks a lot!
