### ISSUE TITLE
experiment_id: wrong years

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#489]
in experiment_id there are several instances where the minimum number of years is specified as 85.  In all these cases, I think the number should actually be 86.  [Note the simulation begins and the *beginning* of the first year and ends at the *end* of the last year, so minimum number of years is usually the difference between these years plus 1.  

Also the GMMIP amip-hist run should be 145 (not 144)

Also for omip1, no start year or end year should be specified, just the total number of years (300).

**Comment by durack1** [comment]
@taylor13 is there a list of experiments that I should target to ascertain these corrections?

**Comment by durack1** [comment]
@taylor13 the experiments `ism-ssp585-self`, `ism-ssp585-std` and `ssp585-withism` all have min years = 85, yet they start in 2015 and complete in 2300 - this is inconsistent

**Comment by taylor13** [comment]
From their GMD paper, it is clear that the minimum number of years is 86, with an option to extend the simulation to 2300.  So End Date should be "2100 or 2300".

**Comment by taylor13** [comment]
Looks good.  Noticed deforest-globe  has start year but no end year.  Should it be 1930?  Or since this is an idealized experiment, perhaps the start year should be missing.  I think there should be no start or end year.

**Comment by durack1** [comment]
@taylor13 the `deforest-globe` start year should now be fixed in [CMIP6_experiment_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html)
