### ISSUE TITLE
 New issue institution_id registration of IIASA

### ISSUE THREAD

**Issue by gidden** [WCRP-CMIP/CMIP6_CVs#490]
institution_id = IIASA
institution = International Institute for Applied Systems Analysis (IIASA), Schlossplatz 1 - A-2361 Laxenburg, Austria

**Comment by durack1** [comment]
@gidden `IIASA` is now registered, thanks.

**Comment by durack1** [comment]
@gidden, it now seems alot more clear that `IIASA` will not be contributing model data to CMIP6, rather forcing datasets - is that correct? If yes, we should remove `IIASA` from these CVs

@MartinaSt

**Comment by gidden** [comment]
The original issue was generated when we assumed IIASA would be the organizational CV for ScenarioMIP model data. That is now IAMC. Which forcing datasets are you referring? UoM produces the concentration data, IAMC will be producing emissions data.

**Comment by durack1** [comment]
@gidden exactly, and these are contributors to the input4MIPs project (registered at [input4MIPs-cmor-tables)](https://github.com/PCMDI/input4MIPs-cmor-tables), which is a CMIP6 sub-project, which is the same as `UoM` who are also input4MIPs contributors.

So we're good to remove `IIASA` from the CMIP6_CVs
