### ISSUE TITLE
JRA-55 possible typo

### ISSUE THREAD

**Issue by aradhakrishnanGFDL** [WCRP-CMIP/CMIP6_CVs#493]
At GFDL, we were wondering if there a typo here?JRA-55 rather than JRA-55do? 
https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json#L5019:L5021
and one  under omip2-spunup as well.

Thought we'd report it just in case. Thanks

**Comment by durack1** [comment]
@aradhakrishnanGFDL good pickup, this should in fact be `JRA55-do` as noted in [mriJRA55-do-input.json](https://github.com/PCMDI/input4MIPs-cmor-tables/blob/master/demo/MRI-JMA-JRA55-do-1-3/mriJRA55-do-input.json#L18-L26) (The input metadata being used by CMOR when rewriting these datasets)

**Comment by durack1** [comment]
@aradhakrishnanGFDL thanks for that tipoff, in addition to the typo correction I also extended the `omip2` temporal extent to 2017 (was 2016), as the complete 2017 year is now included in the v1.3 JRA55-do dataset
