### ISSUE TITLE
Should the ocean grid of HadGEM3 and UKESM1 models be eORCA1 instead of ORCA ?

### ISSUE THREAD

**Issue by jypeter** [WCRP-CMIP/CMIP6_CVs#494]
@matthew-mizielinski @durack1 I have just talked to my local ORCA specialist (@oliviermarti) and read #457, because I was wondering why [UK Academic Community PMIP4 models](https://pmip4.lsce.ipsl.fr/doku.php/database:participants#uk_academic_community) stated `Ocean grid: 360×292 (ORCA1) x L75` and why the CV for the same models say `ORCA1 [...] 360 x 330 longitude/latitude;`

Olivier told me that if you mention a 360 x 330 grid, you should then use the **eORCA1** grid name instead of _ORCA1_ . So maybe this should be corrected for the appropriate UK models

And the additional question is: will the UKESM1-0-LL and HadGEM3-GC31-LL used for PMIP4 use 360x292 or 360x330 ?

**Comment by durack1** [comment]
@alistairseller @jonseddon @markelkington can you folks chime in on this query? Once I have guidance we can update all relevant registered entries

**Comment by durack1** [comment]
@alistairsellar

**Comment by matthew-mizielinski** [comment]
@jypeter, you are probably correct on this issue it hadn't occurred to me that the extended ORCA grid should be referred to differently. I suspect you are correct in that we should replace `ORCA` with `eORCA` in all of the HadGEM3 and UKESM1 descriptions. I'll confirm this with our ocean modelling teams and get back to you asap.

**Comment by matthew-mizielinski** [comment]
> And the additional question is: will the UKESM1-0-LL and HadGEM3-GC31-LL used for PMIP4 use 360x292 or 360x330 ?
As far as I am aware all of our model configurations use the extended ORCA grid, and as such I would expect the PMIP runs to use the same grid. However, the UK PMIP leads have ultimate control of this.

**Comment by matthew-mizielinski** [comment]
I've had confirmation from our ocean model reps and yes we should state that we are using the eORCA grids. 

@durack1, I'll get you some code to tweak the model descriptions tomorrow.

Thanks for raising this @jypeter.

**Comment by matthew-mizielinski** [comment]
@durack1, The following code should make the required changes.

```
models = [
    'HadGEM3-GC31-HH', 'HadGEM3-GC31-HM', 'HadGEM3-GC31-LL', 
    'HadGEM3-GC31-LM', 'HadGEM3-GC31-MH', 'HadGEM3-GC31-MM', 
    'UKESM1-0-LL', 'UKESM1-0-MMh']

for model_source_id in models:
     source_id[model_source_id]['model_component']['ocean']['description'] = \
         source_id[model_source_id]['model_component']['ocean']['description'].replace('ORCA', 'eORCA')
     source_id[model_source_id]['model_component']['seaIce']['description'] = \
         source_id[model_source_id]['model_component']['seaIce']['description'].replace('ORCA', 'eORCA')

```

**Comment by durack1** [comment]
@matthew-mizielinski thanks for the code snippets, makes my job a lot easier! Take a peek at [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further tweaks are required.

**Comment by markelkington** [comment]
Hi Matthew

What is the significance of the eORCA – I assume this isn’t just a resolution issue as we are defining ORCA025 and ORCA1 for ES-DOC.  I’ll need to get these realigned so that the file headers are correct.  Do you have a link to some additional information on this, or somebody in the NEMO team that can explain it to me.

Mark

**Comment by oliviermarti** [comment]
ORCA grids have a southern limit at about 78°S. eORCA grids are identical to ORCA grids, except that they add points under the Antartic ice shelves up to about 86°S.

I don't know about any official documentation about that. Could NEMO system team provide a reference ?

Olivier
