### ISSUE TITLE
source_id : remove mip_era

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#50]
source_id
mip_era should *not* be included under source_id.  The mip_era is invariably "CMIP6".  Need to also decide whether parent_mip_era needs to be in some CV.

**Comment by durack1** [comment]
@taylor13 also need to change `glacier` -> `land_ice` and add an `aerosol`.

@markelkington, @momipsl, @eguil is there anything else obvious to change?

**Comment by durack1** [comment]
Dupe of #53 closing
