### ISSUE TITLE
source-id registration of GISS-E3-G

### ISSUE THREAD

**Issue by gavinny** [WCRP-CMIP/CMIP6_CVs#507]
"GISS-E3-G":{
            "activity_participation":[
                "AerChemMIP",
                "C4MIP",
                "CFMIP",
                "CMIP",
                "DAMIP",
                "DynVarMIP",
                "FAFMIP",
                "GMMIP",
                "ISMIP6",
                "LS3MIP",
                "LUMIP",
                "OMIP",
                "PAMIP",
                "PMIP",
                "RFMIP",
                "SIMIP",
                "ScenarioMIP",
                "VIACSAB",
                "VolMIP"
            ],
            "cohort":[
                "Registered"
            ],
            "institution_id":[
                "NASA-GISS"
            ],
            "label":"GISS-E3-G",
            "label_extended":"GISS-E3-G",
            "model_component":{
                "aerosol":{
                    "description":"Varies with physics-version (p==1 none, p==3 OMA, p==4 TOMAS, p==5 MATRIX)",
                    "nominal_resolution":"250 km"
                },
                "atmos":{
                    "description":"GISS-E3 (Cubed sphere (C90); 6x90x90 grid points; 102 levels; top level 0.002 hPa)",
                    "nominal_resolution":"100 km"
                },
                "atmosChem":{
                    "description":"Varies with physics-version (p==1 Non-interactive, p>1 GPUCCINI)",
                    "nominal_resolution":"100 km"
                },
                "land":{
                    "description":"GISS LSM",
                    "nominal_resolution":"100 km"
                },
                "landIce":{
                    "description":"none",
                    "nominal_resolution":"none"
                },
                "ocean":{
                    "description":"GISS Ocean (1 degree; 360 x 180 latitude/longitude; 32 levels; top grid cell 0-10 m)",
                    "nominal_resolution":"100 km"
                },
                "ocnBgchem":{
                    "description":"none",
                    "nominal_resolution":"none"
                },
                "seaIce":{
                    "description":"GISS SI",
                    "nominal_resolution":"100 km"
                }
            },
            "release_year":"2018",
            "source_id":"GISS-E3-G"
        },

**Comment by durack1** [comment]
@gavinny just a couple of tweaks:
```
"atmos":{
"description":"GISS-E3 (Cubed sphere (C90); 90 x 90 x 6 longitude/latitude/cubeface; 102 levels; top level 0.002 hPa)",
"nominal_resolution":"100 km"
```
Following the format of [VRESM-1-0](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L4246-L4248), and
```
"ocean":{
"description":"GISS Ocean (1 degree; 360 x 180 longitude/latitude; 32 levels; top grid cell 0-10 m)",
"nominal_resolution":"100 km"
```
Fixing the lat/lon -> lon/lat, I think you had these mixed up.

Can you confirm?

**Comment by gavinny** [comment]
"atmos":{

"description":"GISS-E3 (Cubed sphere (C90); 90 x 90 x 6 longitude/latitude/cubeface; 102 levels; top level 0.002 hPa)",

"nominal_resolution":"100 km"

The faces aren’t broken up by longitude and latitude so it’s misleading to say this. Surely there must be better language?

"ocean":{

"description":"GISS Ocean (1 degree; 360 x 180 longitude/latitude; 32 levels; top grid cell 0-10 m)",

"nominal_resolution":"100 km"

Fixing the lat/lon -> lon/lat, I think you had these mixed up.

Yes – thanks.

**Comment by durack1** [comment]
@gavinny how about:
```
"description":"GISS-E3 (Cubed sphere (C90); 90 x 90 x 6 longitude/latitude/cubeface, grid resolution varies for each cubeface; 102 levels; top level 0.002 hPa)",
```

**Comment by gavinny** [comment]
I realise that others have used similar language, but it’s wrong (and they should change too!). How about:


"description":"GISS-E3 (Cubed sphere, C90; 90 x 90 x 6 gridboxes/cubeface, grid resolution aligns with longitude/latitude along central lines for each cubeface; 102 levels; top level 0.002 hPa)",

**Comment by durack1** [comment]
@gavinny that's much better.. I will also update the `aerosol` `nominal_resolution` as I assume this also aligns with the `100 km` atmos grid?

**Comment by gavinny** [comment]
Sure. Thanks

**Comment by durack1** [comment]
@gavinny, ok, registrations are now complete, take a peek at [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know of any further tweaks required
