### ISSUE TITLE
source_id registration of UofT-CCSM4

### ISSUE THREAD

**Issue by dchandan** [WCRP-CMIP/CMIP6_CVs#512]
label = UofT-CCSM4
label_extended = The NCAR CCSM4 model with the ocean component run in a non-default configuration (the University of Toronto configuration) where tidal mixing and overflow parametrizations are turned off. The vertical profile of ocean diapycnal diffusivity is fixed to the POP1 profile used in CCSM3. See Peltier and Vettoretti, 2014 GRL (http://doi.wiley.com/10.1002/2014GL061413), Chandan and Peltier, 2017 Clim. Past. (https://doi.org/10.5194/cp-13-919-2017)
source_id = UofT-CCSM4
institution_id = UofT
release_year = 2014
activity_participation = [CMIP, PMIP]

aerosol:
description = unnamed
nominal_resolution = 100 km
atmos:
description = CAM4 (finite-volume dynamical core; 288 x 192 longitude/latitude; 26 levels; top level ~2 hPa)
nominal_resolution = 100 km
atmosChem:
description = none
nominal_resolution = none
land:
description = CLM4
nominal_resolution = 100 km    
landIce:
description = none
nominal_resolution = none 
ocean:
description = POP2 (displaced dipole grid, 384 x 320 longitude/latitude; 60 levels; top grid cell 0-10 m)
nominal_resolution = 100 km
ocnBgchem:
description = none
nominal_resolution = none
seaIce:
description = CICE4
nominal_resolution = 100 km

**Comment by durack1** [comment]
@dchandan it seems you might have the `latitude/longitude` around the wrong way above, most likely for the ocean component (the format we want is `longitude/latitude`) - want to edit this inline? While you're at it, you may as well add the DOI for the publication too

**Comment by dchandan** [comment]
Thanks for pointing these out. I think i've updated them all now. Cheers!

**Comment by durack1** [comment]
@dchandan apologies I mustn't have been clear, we want `atmos: 192 x 288 longitude/latitude`, and `ocean: 384 x 320 longitude/latitude` - are these correct?

**Comment by dchandan** [comment]
Ah, sorry! I believe I have done it correctly this time.

**Comment by durack1** [comment]
@dchandan yep looks good, I'll register both your `institution_id` (#511) and this `source_id` later this week

**Comment by durack1** [comment]
@dchandan registration is now complete, take a peek at [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know of any further tweaks required

**Comment by durack1** [comment]
@dchandan just wondering if you still intend to contribution simulations to the CMIP6 archive? Now that the AR6 datasets being used have been finalized, we are doing a cleanup and have noted no `UofT` data has been published.

**Comment by dchandan** [comment]
@durack1 We are participating in the PMIP sub-project only and not directly contributing to CMIP6 simulations. Our model is not CMIP6 generation. I believe I added CMIP to activity_participation field by mistake.

**Comment by durack1** [comment]
Thanks @dchandan there is no `UofT-CCSM4` entry published in the index at https://esgf-node.llnl.gov/search/cmip6/?institution_id=UofT, so therefore even for PMIP you are a non-contributor. Is that correct?

**Comment by jypeter** [comment]
@dchandan your data files seem to be in a good format (from a CMOR point of view). It would be very useful if you could publish `piControl` and `lgm` to an ESGF node, so that people can easily find/download your data (from the ESGF search nodes)

@durack1 do you have a recommendation for a (Canadian) ESGF node and a contact person there, where Deepak could publish the **UofT-CCSM4** data ?

**Comment by durack1** [comment]
@jypeter you could contact CCCma, however I am not sure that they have storage resources allocated to publishing other Canada CMIP6 contributions, @slavakharin can you please chime in?

**Comment by durack1** [comment]
@dchandan have you made any progress with this? We have started receiving queries about CMIP6 contributing modeling groups, and with no `UofT` data contributed, you're not currently being added to the list

**Comment by dchandan** [comment]
@durack1 Apologies for the very late response. We've contributed data to various PMIP4 papers but we've not been able to upload the data to an ESGF node at the moment. For these papers we've shared the data through Dropbox and through the PlioMIP2 data repository. I'm afraid that as of recently I am no longer involved with managing UofT CCSM4 data for PMIP projects so I cannot comment on our ability to upload the data to an ESGF node going forward.

**Comment by durack1** [comment]
@dchandan thanks for the update. Unless data is published in ESGF it will not be archived as part of the IPCC AR6 dataset by the IPCC Data Distribution Centre (DDC), this is not ideal. It would be great if you can raise this with your UofT colleagues to see if this can be remedied

**Comment by durack1** [comment]
Duplicated by updated content in #1086
