### ISSUE TITLE
institution_id -- modification for EC-Earth-Consortium

### ISSUE THREAD

**Issue by shutingdk** [WCRP-CMIP/CMIP6_CVs#515]
The information given in the current institution_id for EC-Earth-Consortium is inaccurate. The correct information should be as:

institution_id = EC-Earth-consortium
institution = AEMET, Spain; BSC, Spain; CNR-ISAC, Italy; DMI, Denmark; ENEA, Italy; FMI, Finland; Geomar, Germany; ICHEC, Ireland; ICTP, Italy; IDL, Portugal; IMAU, The Netherlands; IPMA, Portugal; KIT, Karlsruhe, Germany; KNMI, The Netherlands; Lund University, Sweden; Met Eireann, Ireland; NLeSC, The NetherlandsNTNU, Norway; Oxford University, UK; surfSARA, The Netherlands; SMHI, Sweden; Stockholm University, Sweden; Unite ASTR, Belgium; University College Dublin, Ireland; University of Bergen, Norway; University of Copenhagen, Denmark; University of Helsinki, Finland; University of Santiago de Compostela, Spain; Uppsala University, Sweden; Utrecht University, The Netherlands; Vrije Universiteit Amsterdam, the Netherlands; Wageningen University, The Netherlands.

**Comment by durack1** [comment]
@shutingdk is there a "master" organization in which we could gather the address details (County/Suburb, postal code), so something similar to:
```
"PCMDI":"Program for Climate Model Diagnosis and Intercomparison, Lawrence Livermore National Laboratory, Livermore, CA 94550, USA"
```

**Comment by durack1** [comment]
@shutingdk just wondering if you can provide the county/suburb, postal code etc information for the "master" organization so I can finalize this registration update - your home institution details would be ideal

**Comment by shutingdk** [comment]
We do not have an "master institute" in the consortium. Also there will be seven ESGF data nodes hosting by different institutes for EC-Earth CMIP6 data. But for the time been on could use the SMHI's address as the mailing address. So maybe we could formulate the institute as the following;

institution = AEMET, Spain; BSC, Spain; CNR-ISAC, Italy; DMI, Denmark; ENEA, Italy; FMI, Finland; Geomar, Germany; ICHEC, Ireland; ICTP, Italy; IDL, Portugal; IMAU, The Netherlands; IPMA, Portugal; KIT, Karlsruhe, Germany; KNMI, The Netherlands; Lund University, Sweden; Met Eireann, Ireland; NLeSC, The NetherlandsNTNU, Norway; Oxford University, UK; surfSARA, The Netherlands; SMHI, Sweden; Stockholm University, Sweden; Unite ASTR, Belgium; University College Dublin, Ireland; University of Bergen, Norway; University of Copenhagen, Denmark; University of Helsinki, Finland; University of Santiago de Compostela, Spain; Uppsala University, Sweden; Utrecht University, The Netherlands; Vrije Universiteit Amsterdam, the Netherlands; Wageningen University, The Netherlands. Mailing address: EC-Earth consortium, Rossby Center, Swedish Meteorological and Hydrological Institute/SMHI, SE - 601 76 NORRKÖPING, Sweden.

**Comment by durack1** [comment]
@shutingdk that update should now be complete, please review [CMIP6_institution_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_institution_id.html) and let me know if any further tweaks are required
