### ISSUE TITLE
source_id -- a few changes for MIROC6, MIROC-ES2L and MIROC-ES2H

### ISSUE THREAD

**Issue by tinoue70** [WCRP-CMIP/CMIP6_CVs#517]
Please make a few changes as follows;

- Add “PAMIP” to “activity participation” of "MIROC6"
- Add “CDRMIP” to “activity participation” of “MIROC-ES2L”
- Change “release year” of “MIROC-ES2L” and “MIROC-ES2H” from “2017” to “2018”

After modification (see bold and italic);

"MIROC6":{
            "activity_participation":[
                "CFMIP",
                "CMIP",
                "DAMIP",
                "DCPP",
                "DynVarMIP",
                "FAFMIP",
                "GMMIP",
                "HighResMIP",
                "LS3MIP",
                "OMIP",
                "RFMIP",
                "SIMIP",
                "ScenarioMIP",
                "VIACSAB",
                _**"PAMIP"**_
],

"MIROC-ES2L":{
            "activity_participation":[
                "C4MIP",
                "CMIP",
                "DynVarMIP",
                "GeoMIP",
                "LUMIP",
                "OMIP",
                "PMIP",
                "ScenarioMIP",
                "VIACSAB",
                "VolMIP",
                **_"CDRMIP"_**
            ],
            "release_year":**_"2018"_**,
},

"MIROC-ES2H":{
            "release_year":**_"2018"_**,
},

**Comment by durack1** [comment]
@tinoue70 those changes are now in place, please review the updated details in [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further tweaks are required
