### ISSUE TITLE
source_id registration of CESM2

### ISSUE THREAD

**Issue by jflamarque** [WCRP-CMIP/CMIP6_CVs#525]
label = CESM2
label_extended = CESM2
source_id = CESM-2
institution_id = NCAR
release_year = 2018
activity_participation = [CMIP]

aerosol:
description = MAM4 (same grid as atmos)
nominal_resolution = 100 km 
atmos:
description = CAM6 (0.9x1.25 finite volume grid; 288 x 192 longitude/latitude; 32 levels; top level 2.25 mb)
atmosChem:
description = MAM4 (same grid as atmos)
nominal_resolution = 100 km
land:
description = CLM5 (same grid as atmos)
nominal_resolution = 100 km
landIce: CISM2.1
description = none
nominal_resolution = 4 km 
ocean:
description = POP2 (320x384 longitude/latitude; 60 levels; top grid cell 0-10 m)
ocnBgchem:
description = MARBL (same grid as ocean)
nominal_resolution = 100 km
seaIce:
description = CICE5.1 (same grid as ocean)
nominal_resolution = 100 km

**Comment by durack1** [comment]
Thanks @jflamarque, we're requesting some more information in particular for the `atmos` and `ocean` components, following the example:
```
atmos: "Identifier (info; XX x XX longitude/latitude; XX levels; top level XX km/hpa/mb)
e.g.
atmos: "description":"ECHAM6.3.02p4 (T63L47 native atmosphere T63 gaussian grid; 192 x 96 longitude/latitude; 47 levels; top level 80 km)"

ocean "Identifier (info; XX x XX longitude/latitude; XX levels; top grid cell X-X m)
e.g.
ocean: "MOM4 (1/3 deg 30S-30N, 1/3-1 deg 30-60 N/S, and 1 deg in high latitudes; 360 x 232 longitude/latitude; 40 levels; top grid cell 0-10 m)"
```
If there are version identifiers for the other components they would also be great to grab - you can edit the entry you have provided above

**Comment by jflamarque** [comment]
Hi Paul I have updated the comment.  Thanks!

**Comment by durack1** [comment]
@jflamarque perfect, I'll get this registered today

**Comment by durack1** [comment]
@jflamarque `CESM2` is now registered, with one minor tweak, the `landIce` `nominal_resolution` value was adjusted to `5 km` as your provided value is not in our registered list (see [CMIP6_nominal_resolution.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_nominal_resolution.json)).

Please check [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) to validate your details, and if required we can update the entry (in particular, I wonder what other MIPs/activity_id entries you may want to indicate - the full list can be viewed at [CMIP6_activity_id.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_activity_id.json))

**Comment by jflamarque** [comment]
Here is the list of MIPs we will be taking part in

AerChemMIP
C4MIP
CDRMIP
CFMIP
CMIP DECK
CORDEX
DAMIP
DCPP
DynVar
GMMIP
GeoMIP
HighResMIP
ISMIP6
LS3MIP
LUMIP
OMIP
PAMIP
PMIP
RFMIP
SIMIP
ScenarioMIP
VIACSAB
VolMIP

**Comment by durack1** [comment]
@jflamarque no problem, will reopen this issue and update this information later in the week
