### ISSUE TITLE
source_id AWI-CM model version change

### ISSUE THREAD

**Issue by tsemmler05** [WCRP-CMIP/CMIP6_CVs#526]
"source_id":"AWI-CM-1-0-HR" --replace "AWI-CM-1-1-HR"
"label":"AWI-CM 1.0 HR" --replace "AWI-CM 1.1 HR"
"label_extended":"AWI-CM 1.0 HR" --replace "AWI-CM 1.1 HR"
"atmos" "description": "ECHAM6.3.02p4" --replace "ECHAM6.3.04p1"
"land" "description": "JSBACH 3.10" --replace "JSBACH 3.20"
"release_year":"2017" --replace "2018"

"source_id":"AWI-CM-1-0-LR" --replace "AWI-CM-1-1-LR"
"label":"AWI-CM 1.0 LR" --replace "AWI-CM 1.1 LR"
"label_extended":"AWI-CM 1.0 LR" --replace "AWI-CM 1.1 LR"
"atmos" "description": "ECHAM6.3.02p4" --replace "ECHAM6.3.04p1"
"land" "description": "JSBACH 3.10" --replace "JSBACH 3.20"
"release_year":"2017" --replace "2018"

"source_id":"AWI-CM-1-0-MR" --replace "AWI-CM-1-1-MR"
"label":"AWI-CM 1.0 MR" --replace "AWI-CM 1.1 MR"
"label_extended":"AWI-CM 1.0 MR" --replace "AWI-CM 1.1 MR"
"atmos" "description": "ECHAM6.3.02p4" --replace "ECHAM6.3.04p1"
"land" "description": "JSBACH 3.10" --replace "JSBACH 3.20"
"release_year":"2017" --replace "2018"

**Comment by durack1** [comment]
@tsemmler05 can you address the query above? Once the information is clear, I can then merge these changes and close this issue

**Comment by tsemmler05** [comment]
Sorry, I tried to address the query in editing the information in my original comment (source_id is included and release_year updated to 2018). If you have any additional question please let me know.

**Comment by durack1** [comment]
@tsemmler05 apologies for the delay in processing this, please check [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) which should now reflect your updated component versions
