### ISSUE TITLE
institution_id -- add homepage

### ISSUE THREAD

**Issue by momipsl** [WCRP-CMIP/CMIP6_CVs#529]
The institution_id.json file contains a list of institution identifiers and associated postal addresses.  This file should / could contain more information such as homepage.  

This would be useful in the [further-info-url ES-DOC page](https://furtherinfo.es-doc.org/cmip6.ipsl.ipsl-cm6a-lr.dcppa-hindcast-niff.s2000.r1i1p1f3).

**Comment by durack1** [comment]
@momipsl good suggestion, however not sure a format change will be something that is easy to implement, there may also be issues when there are consortia. Please add any additional suggestions to this thread

**Comment by momipsl** [comment]
I have transformed CMIP6_institution_id.json and augmented it accordingly.  You can view the transformed file [here](https://github.com/ES-DOC/pyessv/blob/master/sh/writers/wcrp/cmip6/institution_id.json).

It is used in the pyessv tooling chain.  So if CMIP6_institution_id.json changes then please let me know.

**Comment by taylor13** [comment]
@momipsl :  The CMIP panel has been recently discussing how we might better provide status information about CMIP6 simulations.  One suggestion is to include a link to a "status" page from either the source_id or institution_id json files.  "homepage" wouldn't be appropriate.  Before we decide how to proceed, I need to understand what is being suggested here.   How did you get the "homepage" urls?  What is the pyessv tooling chain?  You say "if CMIP6_institution_id.json changes then please let me know", but aren't you here suggesting a change?  If so that will also impact lots of other folks.

**Comment by durack1** [comment]
@taylor13 has there been any update on this step? Or are we still awaiting guidance from the CMIP panel?

**Comment by taylor13** [comment]
yes, the panel decided it would be good to be able to point folks to a url, when available, where they can find out status of CMIP6 simulations (or at least some information about a particular model's CMIP6 simulations (beyond what is available at ES-DOCs).  

We need to decide what to call this URL (@momipsl has used "homepage" in his transformation of CMIP6_instituion_id.json, but that URL may apply to the institution, not the model's CMIP6 simulations).  We also need to decide whether the URL should be attached to "source" or "institution".

Finally, we have to make sure if this is added, it won't break anyone's software.  When we know how to proceed, the CMIP panel will contact the modeling groups asking for URL's.

**Comment by durack1** [comment]
@taylor13 there are situations like `UKESM1-0-LL` that will be run by 4 institutions, so we'll have to think about this and how we implement it, the institution_id/source_id pair is likely the only way to manage it.

I think what @momipsl has done will be fine for a generic institution_id based webpage, but this provides no real information, that a google search wouldn't provide

**Comment by taylor13** [comment]
Good point.  Maybe for multiple institutions running a model, we could list multiple URLs.

**Comment by momipsl** [comment]
@taylor13 pyessv is a (fairly) comprehensive vocabulary management library and web-service.  I presented it at the GO-ESSP meeting in Abingdon sometime in 2015 I do believe but there was little understanding of the problem and even less of the solution.  It is used across ES-DOC land wherever controlled vocabularies are in scope (i.e. pretty much everywhere).  I have written scripts to convert the WCRP CMIP6 CV's & ESG-F .ini files to the normative pyessv form.  

It also support dataset and file id validation and facet extraction - features used in the dataset errata service.

**Comment by momipsl** [comment]
@taylor13  The [institution_id.json file](https://github.com/ES-DOC/pyessv/blob/master/sh/writers/wcrp/cmip6/institution_id.json) that I linked to is designed to simply augment the WCRP CMIP6_institution_id.json file with some further information such as institutional homepage and consortia.   Basically pyessv is downstream from the WCRP CMIP6 files and at certain points pyessv simply augments WCRP CMIP6 vocabs.

**Comment by momipsl** [comment]
@taylor13 Regarding linking to a simulation status page - the [ES-DOC further-info page](https://furtherinfo.es-doc.org/cmip6.ipsl.ipsl-cm6a-lr.dcppa-hindcast-niff.s2000.r1i1p1f3) could be extended to expose such a link to the user.

**Comment by durack1** [comment]
@momipsl regarding your query [above](https://github.com/WCRP-CMIP/CMIP6_CVs/issues/529#issuecomment-389161806)
>  if CMIP6_institution_id.json changes then please let me know

You may want to "watch" the repo for changes, so you can be notified when the `institution_id.json` file changes - see https://github.com/WCRP-CMIP/CMIP6_CVs/watchers

The latest change occurred [22nd May 4:49 AM PDT](https://github.com/WCRP-CMIP/CMIP6_CVs/commit/c6fa0442c3bf602c3d14fca4eebc4727c651c320#diff-52b16bc1af3f01439996ed53ead68054)

**Comment by momipsl** [comment]
@durack1 Actually I was considering writing a continuous deployment script that would 'watch' changes in the CMIP6_CVs repo.  Whenever a change occurred the script would update the pyessv normative vocabularies and reload the pyessv web-service vocabulary cache.  

My main concern is being notified whenever one of the CMIP6_CV JSON files changes in the structural sense rather than content.  I.E. a schema change if you will.

**Comment by durack1** [comment]
@momipsl I believe such changes will be captured in the version tag, with the current version `6.2.8.18` and these components will change according to logic defined [a while back](https://github.com/WCRP-CMIP/CMIP6_CVs/issues/28#issuecomment-319739869) and reproduced here:
```
Collection of reference CV’s (see https://github.com/WCRP-CMIP/CMIP6_CVs):
The reference CV’s build on information in the global attributes document.
The version number consists of 4 integers separated by “.” (e.g., “6.23.80.318”)
The first digit is “6”, indicating the CV applies to CMIP6
The second integer is incremented when the structure/format of any of the CV’s changes or an entirely new CV is added to the CMIP6 collection.
The third integer is incremented whenever any change to existing content is made other than the addition or amendment of a “source_id” or “institution_id”
The fourth integer is incremented whenever a new source_id and/or institution_id is added or amended
```

**Comment by durack1** [comment]
@momipsl @taylor13 reviewing the content of this issue, it seems closing is a good idea. Please reopen if you believe further discussions are required
