### ISSUE TITLE
source_id -- recommend slight modifcations to syntax and vocabulary

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#53]
source_id 

I think one of the elements included under source_id, namely "source", should be renamed "source_label" so that it isn't confused with the "source" global attribute, which combines source_label with information about all the model components.  

also would like the syntax be altered so that we can easily form the global attribute "source" from these strings (consistent with the syntax specified in  https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit ).

For example instead of 
"atmosphere":"HadGAM2 (r1.1); 192 x 145 N96; 38 levels; top level 39255m",

we should write
"atmosphere":"HadGAM2 (r1.1; 192 x 145 N96; 38 levels; top level 39255m)",

Also, I think the order should be changed to:

    "source_id":{
        "ACCESS-1-0":{
            "institution_id":[
                "CSIRO-BOM"
            ],
            "source_label":"ACCESS 1.0"
            "release_year":"2011",
            "aerosol":"CLASSIC",
            "atmosphere":"HadGAM2 (r1.1); 192 x 145 N96; 38 levels; top level 39255m",
            "atmospheric_chemistry":"None",
            "land_ice":"None",
            "land_surface":"MOSES2.2",
            "ocean":"ACCESS-OM (MOM4p1); tripolar primarily 1deg latitude/longitude; 50 levels; top grid cell 0-10m",
            "ocean_biogeochemistry":"None",
            "sea_ice":"CICE4.1",
        }
    },

Note, I've also removed mip_era as suggested in a different issue.

**Comment by durack1** [comment]
@taylor13 json key ordering is automatic, and we're using a dictionary format so the key, not the order is most important.

We should probably create a template in addition to the `ACCESS-1-0` CMIP5 example, so that if a model atmospheric component differs from the example we have enough flexibility to include that..

Oh and I also updated `glacier` -> `land_ice` in your comment above

**Comment by taylor13** [comment]
I know that when you ingest the json key it can rearrange the ordering, but for readability of the original json files by humans, I would like the modeling groups to generate the information in the order I listed.  I think that that order will also be sensible from their point of view.

**Comment by durack1** [comment]
@taylor13 this may need to be edited in the [issue template](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by taylor13** [comment]
In the example taken from above, I've corrected (below) the formatting of the atmosphere and ocean entries to be consistent with the global attribute document.  Also, I've replaced "source_label" with "label" because we might want to include labels in some other CVs to help make CMIP3 and CMIP5 searches compatible with CMIP6. 
```"source_id":{
    "ACCESS-1-0":{
        "institution_id":[
            "CSIRO-BOM"
        ],
        "label":"ACCESS 1.0"
        "release_year":"2011",
        "aerosol":"CLASSIC",
        "atmosphere":"HadGAM2 (r1.1; 192 x 145 N96; 38 levels; top level 39255m)",
        "atmospheric_chemistry":"None",
        "land_ice":"None",
        "land_surface":"MOSES2.2",
        "ocean":"ACCESS-OM (MOM4p1; tripolar primarily 1deg latitude/longitude; 50 levels; top grid cell 0-10m)",
        "ocean_biogeochemistry":"None",
        "sea_ice":"CICE4.1",
    }
},
```

**Comment by durack1** [comment]
#50 can be rolled into this issue - remove mip_era
