### ISSUE TITLE
source_id registration of UKESM1.0-LL

### ISSUE THREAD

**Issue by johanlee07** [WCRP-CMIP/CMIP6_CVs#531]
label = UKESM1.0-LL
label_extended = UKESM1.0-N96ORCA1
source_id = UKESM1-0-LL
institution_id = NIMS-KMA
release_year = 2018
activity_participation = [CMIP ScenarioMIP AerChemMIP]

aerosol:
description = UKCA-GLOMAP-mode
nominal_resolution = 250 km

atmos:
description = MetUM-HadGEM3-GA7.1 (N96; 192 x 144 longitude/latitude; 85 levels; top level 85 km)
nominal_resolution = 250 km

atmosChem:
description = UKCA-StratTrop
nominal_resolution = 250 km

land:
description = JULES-HadGEM3-GL7.1
nominal_resolution = 250 km    

landIce:
description = none
nominal_resolution = none 

ocean:
description = NEMO-HadGEM3-GO6.0 (eORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 360 x 330 longitude/latitude; 75 levels; top grid cell 0-1 m)
nominal_resolution = 100 km

ocnBgchem:
description = MEDUSA2
nominal_resolution = 100 km

seaIce:
description = CICE-HadGEM3-GSI8 (tripolar primarily 1deg; 360 x 200 longitude/latitude)
nominal_resolution = 100 km

**Comment by matthew-mizielinski** [comment]
@johanlee07, @durack1, @jcmt 

As I understand it this issue just needs `NIMS-KMA` adding to the `institution_id` section of `UKESM1-0-LL` in WCRP-CMIP/CMIP6_CVs/CMIP6_source_id.json.

**Comment by durack1** [comment]
@matthew-mizielinski that's exactly what is required, assuming the identical configuration will be run at `NIMS-KMA`

@johanlee07 I have now amended the entry, and you should check [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) to double check the update
