### ISSUE TITLE
source_id registration of KACE-1-0-G

### ISSUE THREAD

**Issue by johanlee07** [WCRP-CMIP/CMIP6_CVs#532]
label = KACE1.0-G
label_extended = KACE1.0-GLOMAP
source_id = KACE-1-0-G
institution_id = NIMS-KMA
release_year = 2018
activity_participation = [CMIP ScenarioMIP]

aerosol:
description = UKCA-GLOMAP-mode
nominal_resolution = 250 km

atmos:
description = MetUM-HadGEM3-GA7.1 (N96; 192 x 144 longitude/latitude; 85 levels; top level 85 km)
nominal_resolution = 250 km

atmosChem:
description = none
nominal_resolution = none

land:
description = JULES-HadGEM3-GL7.1
nominal_resolution = 250 km    

landIce:
description = none
nominal_resolution = none 

ocean:
description = MOM4p1 (tripolar primarily 1deg; 360 x 200 longitude/latitude; 50 levels; top grid cell 0-10 m)
nominal_resolution = 100 km

ocnBgchem:
description = none
nominal_resolution = none

seaIce:
description = CICE-HadGEM3-GSI8 (tripolar primarily 1deg; 360 x 200 longitude/latitude)
nominal_resolution = 100 km

**Comment by durack1** [comment]
@johanlee07 I have now registered this entry, and you should check [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) to double check the details
