### ISSUE TITLE
institution_id registration of UTAS

### ISSUE THREAD

**Issue by sjphipps** [WCRP-CMIP/CMIP6_CVs#535]
institution_id = UTAS
institution = Institute for Marine and Antarctic Studies, University of Tasmania, Hobart, Tasmania, TAS 7001, Australia

**Comment by sjphipps** [comment]
You're right, that's a redundancy. Please contract "Tasmania, TAS 7001" to
"Tasmania 7001".

> @sjphipps did you want a duplicate "..Tasmania, TAS.." in there?

--
Dr Steven J Phipps
Paleo Ice Sheet Modeller

Antarctic Gateway Partnership
Institute for Marine and Antarctic Studies
University of Tasmania

Private Bag 129, Hobart, TAS 7001, Australia

Tel  +61 3 6226 6902
Fax  +61 3 6226 2973

https://www.stevenphipps.com
https://twitter.com/StevenJPhipps


University of Tasmania Electronic Communications Policy (December, 2014).
This email is confidential, and is for the intended recipient only. Access, disclosure, copying, distribution, or reliance on any of it by anyone outside the intended recipient organisation is prohibited and may be a criminal offence. Please delete if obtained in error and email confirmation to the sender. The views expressed in this email are not necessarily the views of the University of Tasmania, unless clearly intended otherwise.

**Comment by durack1** [comment]
@sjphipps `UTAS` is now registered, please review [CMIP6_institution_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_institution_id.html) and let me know of any required amendments
