### ISSUE TITLE
source_id registration of CSIRO-Mk3L-1-3

### ISSUE THREAD

**Issue by sjphipps** [WCRP-CMIP/CMIP6_CVs#536]
label = CSIRO Mk3L 1.3
label_extended = CSIRO Mk3L 1.3
source_id = CSIRO-Mk3L-1-3
institution_id = UTAS
release_year = 2006
activity_participation = [CMIP, PMIP]

aerosol:
description = none
nominal_resolution = none
atmos:
description = unnamed (R21; 64 x 56 longitude/latitude; 18 levels; top level 36355 m)
nominal_resolution = 500 km
atmosChem:
description = none
nominal_resolution = none
land:
description = unnamed
nominal_resolution = 500 km    
landIce:
description = none
nominal_resolution = none 
ocean:
description = unnamed (128 x 112 longitude/latitude; 31 levels; base 5000 m)
nominal_resolution = 250 km
ocnBgchem:
description = none
nominal_resolution = none
seaIce:
description = unnamed
nominal_resolution = 500 km

**Comment by durack1** [comment]
@sjphipps can you update the format of the ocean description above? I've had a go below
```
ocean:
description = MOM2? (128 x 112 longitude/latitude; 31 levels; top grid cell 0-10 m; base level 5000 m)
```

**Comment by sjphipps** [comment]
How about:

description = MOMx (128 x 112 longitude/latitude; 31 levels; top grid cell 0-10 m; bottom grid cell 4600-5000 m)

I feel the need to be a little vague about the MOM version number. The
original CSIRO ocean model was MOM 1.x, but it's been so heavilly modified
and upgraded over the years that it no longer meaningfully corresponds to
any numbered version of MOM. If you think that "MOMx" is too confusing or
vague, then "MOM 1.x" would be adequate.

Also, I've clarified the depth of the ocean: the base of the water column
is at 5000m, but the bottom level is centred at 4800m.


> @sjphipps can you update the format of the ocean description above? I've had a go below
> ```
> ocean:
> description = MOM2? (128 x 112 longitude/latitude; 31 levels; top grid cell 0-10 m; base level 5000 m)
> ```

--
Dr Steven J Phipps
Paleo Ice Sheet Modeller

Antarctic Gateway Partnership
Institute for Marine and Antarctic Studies
University of Tasmania

Private Bag 129, Hobart, TAS 7001, Australia

Tel  +61 3 6226 6902
Fax  +61 3 6226 2973

https://www.stevenphipps.com
https://twitter.com/StevenJPhipps


University of Tasmania Electronic Communications Policy (December, 2014).
This email is confidential, and is for the intended recipient only. Access, disclosure, copying, distribution, or reliance on any of it by anyone outside the intended recipient organisation is prohibited and may be a criminal offence. Please delete if obtained in error and email confirmation to the sender. The views expressed in this email are not necessarily the views of the University of Tasmania, unless clearly intended otherwise.

**Comment by durack1** [comment]
@sjphipps is the seaice really on a different grid to the ocean (500 km vs 250 km for the ocean?) I'm assuming these grids are consistent - correct me if I am wrong. The model is now registered, so take a peek at [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) let me know if I need to tweak this

**Comment by durack1** [comment]
@sjphipps just a query, the Mk3 manual (Gordon et al., 2002 - see [here](https://publications.csiro.au/rpr/download?pid=procite:ff94db7e-ad41-40bf-b6be-2ab1ad07805c&dsid=DS1#Page=10)) notes that CSIRO Mk3 included the MOM2.2 ocean component:
"The ocean component of the Mk2 model was based on the GFDL Cox (1984) code. In the Mk3
model the ocean component has been upgraded to the GFDL MOM2.2 code (Section 20). This
has been specifically designed to match the horizontal land-sea grid of the Mk3 AGCM."

I'm just wondering why you note MOM1.x above? Is this valid?

**Comment by sjphipps** [comment]
Yes, the sea ice really is on a different grid. The CSIRO family of models
have an unusual design feature, whereby the sea ice is on the AGCM grid
rather than the OGCM grid.

The model description looks fine, thanks!

> @sjphipps is the seaice really on a different grid to the ocean (500 km
> vs 250 km for the ocean?) I'm assuming these grids are consistent -
> correct me if I am wrong. The model is now registered, so take a peek at
> [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html)
> let me know if I need to tweak this

--
Dr Steven J Phipps
Paleo Ice Sheet Modeller

Antarctic Gateway Partnership
Institute for Marine and Antarctic Studies
University of Tasmania

Private Bag 129, Hobart, TAS 7001, Australia

Tel  +61 3 6226 6902
Fax  +61 3 6226 2973

https://www.stevenphipps.com
https://twitter.com/StevenJPhipps


University of Tasmania Electronic Communications Policy (December, 2014).
This email is confidential, and is for the intended recipient only. Access, disclosure, copying, distribution, or reliance on any of it by anyone outside the intended recipient organisation is prohibited and may be a criminal offence. Please delete if obtained in error and email confirmation to the sender. The views expressed in this email are not necessarily the views of the University of Tasmania, unless clearly intended otherwise.

**Comment by sjphipps** [comment]
Yes, this is correct. There have been two different CSIRO ocean models
over time. The first was based on MOM1.x, the second on MOM2.2. The
transition happened at around Mk3.0, so the Mk3.x family of models uses
MOM2.2 while Mk3L uses MOM1.x. Hope this helps to clear things up!

> @sjphipps just a query, the Mk3 manual (Gordon et al., 2002 - see [here](https://publications.csiro.au/rpr/download?pid=procite:ff94db7e-ad41-40bf-b6be-2ab1ad07805c&dsid=DS1#Page=10)) notes that CSIRO Mk3 included the MOM2.2 ocean component:
> "The ocean component of the Mk2 model was based on the GFDL Cox (1984) code. In the Mk3
> model the ocean component has been upgraded to the GFDL MOM2.2 code (Section 20). This
> has been specifically designed to match the horizontal land-sea grid of the Mk3 AGCM."
>
> I'm just wondering why you note MOM1.x above? Is this valid?

--
Dr Steven J Phipps
Paleo Ice Sheet Modeller

Antarctic Gateway Partnership
Institute for Marine and Antarctic Studies
University of Tasmania

Private Bag 129, Hobart, TAS 7001, Australia

Tel  +61 3 6226 6902
Fax  +61 3 6226 2973

https://www.stevenphipps.com
https://twitter.com/StevenJPhipps


University of Tasmania Electronic Communications Policy (December, 2014).
This email is confidential, and is for the intended recipient only. Access, disclosure, copying, distribution, or reliance on any of it by anyone outside the intended recipient organisation is prohibited and may be a criminal offence. Please delete if obtained in error and email confirmation to the sender. The views expressed in this email are not necessarily the views of the University of Tasmania, unless clearly intended otherwise.

**Comment by durack1** [comment]
@sjphipps reopening this issue as the seaIce `nominal_resolution` information is currently incorrect. We'll also have to think about your seaice data contribution as the CMIP6 data request expects data for the [`siconc`](http://clipc-services.ceda.ac.uk/dreq/u/86119ff6-357c-11e7-8257-5404a60d96b5.html) variable on the ocean (not atmosphere) grid, and so if you are planning to contribute your seaice data, it'll have to be written as [`siconca`](http://clipc-services.ceda.ac.uk/dreq/u/71190054-faa7-11e6-bfb7-ac72891c3257.html)

**Comment by sjphipps** [comment]
Thanks for the clarification. Will you reset the seaIce
`nominal_resolution` to 500km, or do I need to take some action here?

> @sjphipps reopening this issue as the seaIce `nominal_resolution`
> information is currently incorrect. We'll also have to think about your
> seaice data contribution as the CMIP6 data request expects data for the
> [`siconc`](http://clipc-services.ceda.ac.uk/dreq/u/86119ff6-357c-11e7-8257-5404a60d96b5.html)
> variable on the ocean (not atmosphere) grid, and so if you are planning
> to contribute your seaice data, it'll have to be written as
> [`siconca`](http://clipc-services.ceda.ac.uk/dreq/u/71190054-faa7-11e6-bfb7-ac72891c3257.html)

--
Dr Steven J Phipps
Paleo Ice Sheet Modeller

Antarctic Gateway Partnership
Institute for Marine and Antarctic Studies
University of Tasmania

Private Bag 129, Hobart, TAS 7001, Australia

Tel  +61 3 6226 6902
Fax  +61 3 6226 2973

https://www.stevenphipps.com
https://twitter.com/StevenJPhipps


University of Tasmania Electronic Communications Policy (December, 2014).
This email is confidential, and is for the intended recipient only. Access, disclosure, copying, distribution, or reliance on any of it by anyone outside the intended recipient organisation is prohibited and may be a criminal offence. Please delete if obtained in error and email confirmation to the sender. The views expressed in this email are not necessarily the views of the University of Tasmania, unless clearly intended otherwise.

**Comment by durack1** [comment]
@sjphipps that change is now made, you can peruse the full details [here](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L1355-L1404)
