### ISSUE TITLE
source_id registration of ACCESS-CM2

### ISSUE THREAD

**Issue by sjmarsland** [WCRP-CMIP/CMIP6_CVs#539]
label = ACCESS-CM2
label_extended = Australian Community Climate and Earth System Simulator Climate Model Version 2
source_id = ACCESS-CM2
institution_id = CSIRO-ARCCSS-BoM
release_year = 2018
activity_participation = CMIP ScenarioMIP RFMIP OMIP FAFMIP

aerosol:
description = UKCA-GLOMAP-mode
nominal_resolution = 250 km
atmos:
description = MetUM-HadGEM3-GA7.1 (N96; 192 x 144 longitude/latitude; 85 levels; top level 85 km)
nominal_resolution = 250 km
atmosChem:
description = none
nominal_resolution = none
land:
description = CABLE2.3.5
nominal_resolution = 250 km    
landIce:
description = none
nominal_resolution = none 
ocean:
description = ACCESS-OM2 (GFDL-MOM5, tripolar primarily 1deg; 360 x 300 longitude/latitude; 50 levels; top grid cell 0-10 m)
nominal_resolution = 100 km
ocnBgchem:
description = none
nominal_resolution = none
seaIce:
description = CICE5.1 (same grid as ocean)
nominal_resolution = 100 km

**Comment by sjmarsland** [comment]
Hi Paul, 

Thanks for checking. In going from ACCESS1.x to ACCESS2.x the atmospheric component has a new dynamical core with different spatial discretisation. This means one less row of v-velocity points so the latitude component drops from 145 to 144. Since the ACCESS-ESM1.5 uses the old atmosphere it has 145, consistent with our CMIP5 submission of ACCESS1.3.

Simon

**Comment by durack1** [comment]
@sjmarsland ok great, glad to know there wasn't a typo..
