### ISSUE TITLE
source_id registration of GFDL-OM4p5B

### ISSUE THREAD

**Issue by aradhakrishnanGFDL** [WCRP-CMIP/CMIP6_CVs#554]
"GFDL-OM4p5B":{
            "activity_participation":[
                "OMIP",
            ],
            "cohort":[
                "Registered"
            ],
            "institution_id":[
                "NOAA-GFDL"
            ],
            "label":"GFDL-OM4p5B",
            "label_extended":"GFDL-OM4p5B",
             "model_component":{
                "ocean":{
                    "description":"GFDL-MOM6 (tripolar - nominal 0.5 deg; 720 x 576 longitude/latitude; 75 levels; top grid cell 0-2 m)",
                    "nominal_resolution":"50 km"
                },
                "ocnBgchem":{
                    "description":"GFDL BLING v2",
                    "nominal_resolution":"50 km"
                },
                "seaIce":{
                    "description":"SIS2",
                    "nominal_resolution":"50 km"
                }
            },
            "release_year":"2018",
            "source_id":"GFDL-OM4p5B"
        }

**Comment by durack1** [comment]
@aradhakrishnanGFDL thanks, just FYI you can use the `label` and `label_extended` entries to provide more details about the model, so for e.g.
`label_extended: GFDL-OM v4.5B ocean-only 0.5 degree model configuration for use in OMIP simulations` or whatever you like

**Comment by durack1** [comment]
@aradhakrishnanGFDL this model is now registered, take a peek at [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know of any further tweaks required
