### ISSUE TITLE
source_id -- add three more configurations for EC-Earth, and modification for release years

### ISSUE THREAD

**Issue by shutingdk** [WCRP-CMIP/CMIP6_CVs#559]
We have added three more model configurations for EC-Earth model, i.e., EC-Earth-3P, EC-Earth-3P-HR and EC-Earth-3P-VHR mostly for the HighResMIP. Also, there should be a correction for the release year for the already registered EC-Earth model configurations.

"EC-Earth3":{
"activity_participation":["CMIP", "CORDEX", "DCPP", "DynVarMIP", "LS3MIP", “RFMIP”,"SIMIP", "ScenarioMIP", "VIACSAB", "VolMIP" ],
"institution_id":["EC-Earth-Consortium"],
"label":"EC-Earth3",
"label_extended":"EC-Earth 3.3", 
 "model_component":
             "aerosol":"none",
             "atmos":
"description":"IFS cy36r4 (TL255, linearly reduced Gaussian grid equivalent to 512 x 256 longitude/latitude; 91 levels; top level: 0.01 hPa)",
"nominal_resolution":"100 km" 
              "land":
"description":"HTESSEL (land surface scheme built in IFS)",
"nominal_resolution":"100 km" 
      "land_ice":"none",
              "ocean":
"description":"NEMO3.6 (ORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 362 x 292 longitude/latitude; 75 levels; top grid cell 0 - 1 m)",
"nominal_resolution":" 100 km"
              "ocean_biogeochemistry":"none",
              "seaIce":
"description":"LIM3",
 	"nominal_resolution":" 100 km" 
"release_year":"2018",
"source_id":"EC-Earth3"
}

"EC-Earth3-AerChem":{
"activity_participation":["AeroChemMIP", "CMIP", "ScenarioMIP"],
"institution_id":["EC-Earth-Consortium"],
"label":"EC-Earth3-AerChem",
"label_extended":"EC-Earth3-AerChem", 
 "model_component":
              "aerosol":
"description":"TM5  (3 x 2 deg; 120 x 90 longitude/latitude; 34 levels; top level: 0.1 hPa)"
"nominal_resolution":"250 km”
              "atmos":
"description":"IFS cy36r4 (TL255, linearly reduced Gaussian grid equivalent to 512 x 256 longitude/latitude; 91 levels; top level: 0.01 hPa)",
"nominal_resolution":"100 km" 
              "atmospheric_chemistry":
"description":"TM5 (3 x 2 deg; 120 x 90 longitude/latitude; 34 levels; top level: 0.1 hPa)"
"nominal_resolution":"250 km”
              "land":
"description":"HTESSEL (land surface scheme built in IFS)",
"nominal_resolution":"100 km" 
      "land_ice":"none",
              "ocean":
                      "description":"NEMO3.6 (ORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 362 x 292 longitude/latitude; 75 levels; top grid cell 0 - 1 m)",
                      "nominal_resolution":" 100 km"
              "ocean_biogeochemistry":"none",
              "seaIce":
                      "description":"LIM3",
                      "nominal_resolution":" 100 km" 
"release_year":"2018",
"source_id":"EC-Earth3-AerChem"
}
"EC-Earth3-CC":{
"activity_participation":["C4MIP", "CMIP", " LUMIP"],
"institution_id":["EC-Earth-Consortium" ],
"label":"EC-Earth3-CC",
"label_extended":"EC-Earth3-CC", 
 "model_component":
              "aerosol":”none”
              "atmos":
"description":"IFS cy36r4 (TL255, linearly reduced Gaussian grid equivalent to 512 x 256 longitude/latitude; 91 levels; top level: 0.01 hPa)",
"nominal_resolution":"100 km" 
              "atmospheric_chemistry":
"description":"TM5 (3 x 2 deg; 120 x 90 longitude/latitude; 34 levels; top level: 0.1 hPa)"
"nominal_resolution":"250 km”
              "land":
"description":"HTESSEL (land surface scheme built in IFS) + LPJ-GUESS v4",
"nominal_resolution":"100 km" 
      "land_ice":"none",
              "ocean":
                      "description":"NEMO3.6 (ORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 362 x 292 longitude/latitude; 75 levels; top grid cell 0 - 1 m)",
                      "nominal_resolution":" 100 km"
              "ocean_biogeochemistry":"PISCES v2",
              "seaIce":
                      "description":"LIM3",
                      "nominal_resolution":" 100 km" 
"release_year":"2018",
"source_id":"EC-Earth3-CC"
}
"EC-Earth3-GrIS":{
"activity_participation":["CMIP", "ISMIP6", "PMIP"],
"institution_id":["EC-Earth-Consortium"],
"label":"EC-Earth3-GrIS",
"label_extended":"EC-Earth3-GrIS", 
 "model_component":
              "aerosol":"none",
              "atmos":
"description":"IFS cy36r4 (TL255, linearly reduced Gaussian grid equivalent to 512 x 256 longitude/latitude; 91 levels; top level: 0.01 hPa)",
"nominal_resolution":"100 km" 
              "land":
"description":"HTESSEL (land surface scheme built in IFS)",
"nominal_resolution":"100 km" 
      "land_ice":
"description":"PISM 0.7 (5 km x 5 km, 442 levels)",
"nominal_resolution":"5 km" 
              "ocean":
"description":"NEMO3.6 (ORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 362 x 292 longitude/latitude; 75 levels; top grid cell 0 - 1 m)",
"nominal_resolution":" 100 km"
              "ocean_biogeochemistry":"none",
              "seaIce":
"description":"LIM3",
 	"nominal_resolution":" 100 km" 
"release_year":"2018",
"source_id":"EC-Earth3-GrIS"
}
"EC-Earth3-HR":{
"activity_participation":["HighResMIP","DCPP"],
"institution_id":["EC-Earth-Consortium"],
"label":"EC-Earth3-HR",
"label_extended":"EC-Earth3-HR", 
 "model_component":
             "aerosol":"none",
             "atmos":
"description":"IFS cy36r4 (TL511, linearly reduced Gaussian grid equivalent to 1024 x 512 longitude/latitude; 91 levels; top level: 0.01 hPa)",
"nominal_resolution":"50 km" 
              "land":
"description":"HTESSEL (land surface scheme built in IFS)",
"nominal_resolution":"50 km" 
      "land_ice":"none",
              "ocean":
"description":"NEMO3.6 (ORCA025; tripolar primarily 0.25 degrees; 1442 x 1921 longitude/latitude; 75 levels; top grid cell 0-1 m)",
"nominal_resolution":"25 km"
              "ocean_biogeochemistry":"none",
              "seaIce":
"description":"LIM3",
 	"nominal_resolution":"25 km" 
"release_year":"2017",
"source_id":"EC-Earth3-HR"
}
"EC-Earth3-LR":{
"activity_participation":["CMIP","PMIP"],
"institution_id":["EC-Earth-Consortium"],
"label":"EC-Earth3-LR",
"label_extended":"EC-Earth3-LR", 
 "model_component":
             "aerosol":"none",
             "atmos":
"description":"IFS cy36r4 (TL159, linearly reduced Gaussian grid equivalent to 320 x 160 longitude/latitude; 62 levels; top level: 5 hPa)",
"nominal_resolution":"250 km" 
              "land":
"description":"HTESSEL (land surface scheme built in IFS)",
"nominal_resolution":"250 km" 
      "land_ice":"none",
              "ocean":
"description":"NEMO3.6 (ORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 362 x 292 longitude/latitude; 75 levels; top grid cell 0 - 1 m)",
"nominal_resolution":" 100 km"
              "ocean_biogeochemistry":"none",
              "seaIce":
"description":"LIM3",
 	"nominal_resolution":" 100 km" 
"release_year":"2018",
"source_id":"EC-Earth3-LR"
}
"EC-Earth3-Veg":{
"activity_participation":["CMIP", “LS3MIP”,"LUMIP",”ScenarioMIP”],
"institution_id":["EC-Earth-Consortium" ],
"label":"EC-Earth3-Veg",
"label_extended":"EC-Earth3-Veg", 
 "model_component":
              "aerosol":”none”
              "atmos":
"description":"IFS cy36r4 (TL255, linearly reduced Gaussian grid equivalent to 512 x 256 longitude/latitude; 91 levels; top level: 0.01 hPa)",
"nominal_resolution":"100 km" 
              "atmospheric_chemistry":”none”
              "land":
"description":"HTESSEL (land surface scheme built in IFS) + LPJ-GUESS v4",
"nominal_resolution":"100 km" 
      "land_ice":"none",
              "ocean":
                      "description":"NEMO3.6 (ORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 362 x 292 longitude/latitude; 75 levels; top grid cell 0 - 1 m)",
                      "nominal_resolution":" 100 km"
              "ocean_biogeochemistry":"none",
              "seaIce":
                      "description":"LIM3",
                      "nominal_resolution":" 100 km" 
"release_year":"2018",
"source_id":"EC-Earth3-Veg"
}
"EC-Earth3-Veg-LR":{
"activity_participation":["CMIP", “PMIP”,”ScenarioMIP”],
"institution_id":["EC-Earth-Consortium" ],
"label":"EC-Earth3-Veg-LR",
"label_extended":"EC-Earth3-Veg-LR", 
 "model_component":
              "aerosol":”none”
              "atmos":
"description":"IFS cy36r4 (TL159, linearly reduced Gaussian grid equivalent to 320 x 160 longitude/latitude; 62 levels; top level: 5 hPa)",
"nominal_resolution":"250 km" 	
              "atmospheric_chemistry":”none”
              "land":
"description":"HTESSEL (land surface scheme built in IFS) + LPJ-GUESS v4",
"nominal_resolution":"250 km" 
      "land_ice":"none",
              "ocean":
                      "description":"NEMO3.6 (ORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 362 x 292 longitude/latitude; 75 levels; top grid cell 0 - 1 m)",
                      "nominal_resolution":" 100 km"
              "ocean_biogeochemistry":"none",
              "seaIce":
                      "description":"LIM3",
                      "nominal_resolution":" 100 km" 
"release_year":"2018",
"source_id":"EC-Earth3-Veg-LR"
}
"EC-Earth3P":{
"activity_participation":["CMIP", "HighResMIP" ],
"institution_id":["EC-Earth-Consortium"],
"label":"EC-Earth3P",
"label_extended":"EC-Earth 3.2 in PRIMAVERA", 
 "model_component":
             "aerosol":"none",
             "atmos":
"description":"IFS cy36r4 (TL255, linearly reduced Gaussian grid equivalent to 512 x 256 longitude/latitude; 91 levels; top level: 0.01 hPa)",
"nominal_resolution":"100 km" 
              "land":
"description":"HTESSEL (land surface scheme built in IFS)",
"nominal_resolution":"100 km" 
      "land_ice":"none",
              "ocean":
"description":"NEMO3.6 (ORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 362 x 292 longitude/latitude; 75 levels; top grid cell 0 - 1 m)",
"nominal_resolution":" 100 km"
              "ocean_biogeochemistry":"none",
              "seaIce":
"description":"LIM3",
 	"nominal_resolution":" 100 km" 
"release_year":"2017",
"source_id":"EC-Earth3P"
}
"EC-Earth3P-HR":{
"activity_participation":["HighResMIP"],
"institution_id":["EC-Earth-Consortium"],
"label":"EC-Earth3P-HR",
"label_extended":"EC-Earth3P-HR in PRIMAVERA", 
 "model_component":
             "aerosol":"none",
             "atmos":
"description":"IFS cy36r4 (TL511, linearly reduced Gaussian grid equivalent to 1024 x 512 longitude/latitude; 91 levels; top level: 0.01 hPa)",
"nominal_resolution":"50 km" 
              "land":
"description":"HTESSEL (land surface scheme built in IFS)",
"nominal_resolution":"50 km" 
      "land_ice":"none",
              "ocean":
"description":"NEMO3.6 (ORCA1 tripolar, 1442x1921 longitude/latitude; 75 levels; top grid cell 0 - 1 m)",
"nominal_resolution":"25 km"
              "ocean_biogeochemistry":"none",
              "seaIce":
"description":"LIM3",
 	"nominal_resolution":"25 km" 
"release_year":"2017",
"source_id":"EC-Earth3P-HR"
}
"EC-Earth3P-VHR":{
"activity_participation":["HighResMIP"],
"institution_id":["EC-Earth-Consortium"],
"label":"EC-Earth3P-VHR",
"label_extended":"EC-Earth3P-VHR in PRIMAVERA", 
 "model_component":
             "aerosol":"none",
             "atmos":
"description":"IFS cy36r4 (TL1279, linearly reduced Gaussian grid equivalent to 2560 x 1280 longitude/latitude; 91 levels; top level: 0.01 hPa)",
"nominal_resolution":"25 km" 
              "land":
"description":"HTESSEL (land surface scheme built in IFS)",
"nominal_resolution":"25 km" 
      "land_ice":"none",
              "ocean":
"description":"NEMO3.6 (ORCA012; tripolar primarily 0.08 degrees; 4322 x 3059 longitude/latitude; 75 levels; top grid cell 0-1 m)",
"nominal_resolution":"10 km"
              "ocean_biogeochemistry":"none",
              "seaIce":
"description":"LIM3",
 	"nominal_resolution":"10 km" 
"release_year":"2017",
"source_id":"EC-Earth3P-VHR"
}

**Comment by durack1** [comment]
@shutingdk those amendments and new models are now registered. Note that a number of the entries above still have `"release_year":"2017"` and so in those cases the information above was kept. Please take a look at [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further amendments are required

**Comment by shutingdk** [comment]
These "release_year":"2017" for the specific entries are correct. But We found one mistake regarding EC-Earth3P-HR, that is the ocean model in this configuration should be ORCA025 instead of ORCA1. So the entry for EC-Earth3P-HR should be as:

"EC-Earth3P-HR":{
"activity_participation":["HighResMIP"],
"institution_id":["EC-Earth-Consortium"],
"label":"EC-Earth3P-HR",
"label_extended":"EC-Earth3P-HR in PRIMAVERA", 
 "model_component":
             "aerosol":"none",
             "atmos":
"description":"IFS cy36r4 (TL511, linearly reduced Gaussian grid equivalent to 1024 x 512 longitude/latitude; 91 levels; top level: 0.01 hPa)",
"nominal_resolution":"50 km" 
              "land":
"description":"HTESSEL (land surface scheme built in IFS)",
"nominal_resolution":"50 km" 
      "land_ice":"none",
              "ocean":
"description":"NEMO3.6 (ORCA025; tripolar primarily 0.25 degrees; 1442 x 1921 longitude/latitude; 75 levels; top grid cell 0-1 m)",
"nominal_resolution":"25 km"
              "ocean_biogeochemistry":"none",
              "seaIce":
"description":"LIM3",
 	"nominal_resolution":"25 km" 
"release_year":"2017",
"source_id":"EC-Earth3P-HR"
}

**Comment by durack1** [comment]
@shutingdk that update is now implemented, and should be visible at [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html)

**Comment by shutingdk** [comment]
EC-Earth has decided to contribute to more CMIP6-MIPs:  PAMIP, CDRMIP and OMIP. Please add on the "activity participation" for the twomodel configurations: 
EC-Earth3: PAMIP  
EC-Earth3-CC: OMIP and CDRMIP

**Comment by durack1** [comment]
@shutingdk if you want to make additional changes, please "reopen" the issue so it's prominent - that way it will be sure to be seen an acted upon

**Comment by treerink** [comment]
Hi, there are more changes then mentioned in post https://github.com/WCRP-CMIP/CMIP6_CVs/issues/559#issuecomment-452627679. 

I actually made the changes in the latest [`CMIP6_CV.json`](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json) file. Can I just do a pull request of my changed `CMIP6_CV.json` file in this repository or better in the [PCMDI/cmip6-cmor-tables](https://github.com/PCMDI/cmip6-cmor-tables) repository?

Thomas

**Comment by treerink** [comment]
This is the proposed [CMIP6_CV.sjon with ec-earth updates](https://github.com/EC-Earth/ece2cmor3/blob/fa895aa5817f14afcf0cd2b4ef4983e7bfc8dd44/ece2cmor3/resources/proposed-ece-cv-changes/original-CMIP6_CV.json). The differences can be viewed [here](https://github.com/EC-Earth/ece2cmor3/blob/fa895aa5817f14afcf0cd2b4ef4983e7bfc8dd44/ece2cmor3/resources/proposed-ece-cv-changes/gitdiff-CMIP6_CV.json).

**Comment by durack1** [comment]
@treerink thanks for this, the changes are made in this repo, and the [cmip6-cmor-tables/Tables/CMIP6_CV.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json) file is then updated nightly with revised contents. For this reason I'll implement the changes here, and we should expect an update overnight in CMIP6_CV.json

**Comment by durack1** [comment]
@shutingdk @treerink those changes are now in place. Please review changes in either #635 or in the web table at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and reopen this issue if further changes are required

**Comment by treerink** [comment]
@durack1 I checked the updated  [`CMIP6_CV.json`](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json), the changes are correct thanks a lot!
