### ISSUE TITLE
revise readme.md

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#56]
At the bottom of the code repository listing (README.md), I would replace the text starting with "UPDATE REQUESTS:" with
-----------------
UPDATE REQUESTS AND INSTITUTION/MODEL REGISTRATION:

To register an institution that will contribute a simulation to the CMIP6 archive, please submit an issue/ticket to CMIP6_institution_id registration.  [This would be a link to the institution template.]

To register a model that will perform a CMIP6 simulation, please submit an issue/ticket to CMIP6_source_id registration [This would be a link to the source template.]

Other tickets addressing issues with the CVs should be submitted on the CMIP6_CVs issue page [This would link to the "other issues" template.]

For prompt resolution in addition to creating an issue, submit a pull request/proposed issue solution for consideration by the repo admins.

Some support for CMIP participating modeling groups is available: pcmdi-cmip@llnl.gov. 
-------------------
I don't know how to link to Institution_registration_template.md, Model_registration_template, and other_issue_template.md, which I've created and placed in the .github directory.  PLEASE INSERT THESE LINKS IN THE ABOVE BRACKETED TEXT.

**Comment by taylor13** [comment]
Also please enlarge the font on the all-caps title and reduce the font size for "Some support for CMIP ...."

**Comment by durack1** [comment]
@taylor13 you can edit inline at https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/README.md - feel free to change as you require and close this issue.

I don't believe that we can have more than one `issue template` - so rather each could be placed into the same file - found at https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by durack1** [comment]
@taylor has done this inline, closing
