### ISSUE TITLE
institution_id registration of DKRZ

### ISSUE THREAD

**Issue by wachsylon** [WCRP-CMIP/CMIP6_CVs#561]
institution_id = DKRZ
institution = Deutsches Klimarechenzentrum, Hamburg 20146, Germany

**Comment by durack1** [comment]
@wachsylon `DKRZ` is now registered and should be visible at [CMIP6_institution_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_institution_id.html)

Ping @martinaSt @davidhassell - new institution
