### ISSUE TITLE
LS3MIP experiment_id corrections

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#567]
for experiment amip-lfmip-rmLC, Charlotte thinks that the correct tier is :  tier 1 for 1 member of the ensemble and tier 2 for. the remaining members.  Check with MIP leader to see if this is correct.  (currently CV has tier 2, not tier 1).

**Comment by durack1** [comment]
```
From: Karl Taylor
Date: Thursday, June 28, 2018 at 8:11 AM
To: Bart.van.den.Hurk, sonia.seneviratne, gerhard.krinner, Chris.Derkse, taikan@tokyo, hjkim@tokyo
Cc: WIP List
Subject: clarification of LS3MIP experiments needed

Hi LS3MIP Leaders,

I have recently learned from Martin Juckes (and confirmed by consulting your GMD paper) that your land-future experiment calls for land-only models to be forced in land-future experiments by two different scenarios (with 3 simulations each).  I'm not sure if the the 3 simulations are just different realizations from a single coupled model, or a single realization from each of 3 different coupled models.  In either case how will users analyzing the output know what scenario is responsible for each member of the ensemble of land-future simulations?

One way to at least distinguish between future scenario runs (you indicate they will probably be ssp5-8.5 and ssp4-3.7, but I think you mean ssp5-8.5 and ssp4-3.4) would be to define two experiments: land-ssp585 and land-ssp434 (replacing the single land-future experiment name).  Please let us know if you have an alternate suggestion on how to do this.  

If you indeed have multiple (3?) model outputs forcing your different ensemble members you could assign each model a separate "forcing index", and you would have to advertise to the participating modeling groups which index goes with with model forcing dataset, so that output would all be labeled in the same way.  (See 
https://goo.gl/v1drZl
for the definition of forcing_index.)

If there are other experiments where multiple models are used to forced a land-only model, you would have to do something similar.

Please let us know what you plan to do.

thanks and best regards,
Karl
```
@taylor13

**Comment by taylor13** [comment]
@taylor13 @momipsl @eguil @charliepascoe @bnlawrence @matthew-mizielinski @martinjuckes

In response to the following input from Bart van den Hurt:
```
Your suggestions to trim down the nr of experiments for the land-only future runs 
to 2 makes perfect sense to us. The 3 members for each of these experiments can 
reflect various aspects of the process of generating the forcings for these future 
runs (different ESMs, ensemble members from ESMs, different reference forcing, 
different postprocessing steps) which is much better to document under the 
meta-information of a forcing index, as you suggest, than to label them as a separate 
experiment.
```
it appears that it will be best in https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json (also nicely rendered in https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html ), to replace: the land-future experiment with two experiments (each with 3 ensemble members): land-ssp585 and land-ssp434 .  The "experiment" and "description" for these should be:  
```
experiment_id                      experiment                                 description
--------------                     --------------                            --------------
land-ssp585                     ssp5-8.5 land only               land only simulation for ssp5-8.5
land-ssp434                     ssp4-3.4 land only               land only simulation for ssp4-3.4
```
ES-docs should contact the LS3MIP folks to determine how they are going to distinguish between the different ESMs used to force the land-surface component.  I suggest that they assign a different forcing_index to each ESM that might be used.  The realization index for the land-forcing run should be the same as the realization index from the ESM realization used to force the land model.  Someone needs to make this convention clear to the participating modeling groups, and the modeling groups should take care to identify the ESM used to force their land-only simulation with the correct forcing_index (defined by LS3MIP leaders).

**Comment by taylor13** [comment]
I think we should send an email to ES-DOCs and Martin Juckes letting them know of this update.

**Comment by durack1** [comment]
Reopening as further changes have been requested by Hyungjun Kim, who will add further details

**Comment by hyungjun** [comment]
Considering additional conditions, including accordance with another land-related MIP such as LUMIP, we decided to have two tier 1 experiments, land-ssp126 and land-ssp585, of future land-only simulations and to place land-ssp434 on tier 2.

**Comment by durack1** [comment]
@hyungjun thanks for conforming and dropping this change into an issue.

To clarify, you want to leave `land-ssp434` as tier 2, promote `land-ssp585` to tier 1, and add a new experiment `land-ssp126` also on tier 1 and following the same details as those found in `land-ssp585` and listed in [CMIP6_experiment_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html) and reproduced below. Can you please confirm?

experiment_id | activity id | experiment | tier | sub experiment id | parent experiment id | required model components | additional allowed model components | start year | end year | min number yrs per sim | parent activity id | description
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
land-ssp434 | LS3MIP | future ssp4-3.4 land only | 2 | none | no parent | LAND | BGC | 2015 | 2100 | 86 | no parent | land only simulation for ssp4-3.4 |
land-ssp585 | LS3MIP | future ssp5-8.5 land only | 2 | none | no parent | LAND | BGC | 2015 | 2100 | 86 | no parent | land only simulation for ssp5-8.5 |

**Comment by hyungjun** [comment]
True. They are two tier 1: land-ssp126 & land-ssp585 and one tier 2: land-ssp434. 
However, it seems the table and the link above have not been updated yet.

**Comment by durack1** [comment]
@hyungjun the process we go through here is to ascertain exactly what is required, and as the data request and ES-DOC folks are also watching these discussions, we wait a couple of days to provide folks time to comment if it will cause problems, and then if there are no problems, then we make the proposed changes. These changes should then propagate from this repo across to everywhere else where they need to also be updated.

So wait until late this, early next week for the changes to be implemented.

@momipsl @charliepascoe @martinjuckes @taylor13

**Comment by hyungjun** [comment]
I see. Thank you for kind explanation. Actually, I thought so but just for double check. ;-)

**Comment by MartinaSt** [comment]
@durack1 , @taylor13 : FYI, the experiment_id changes are done in the citation database: 1 renamed experiment_id, 1 added experiment_id.

**Comment by taylor13** [comment]
I think we can go ahead and make these additional changes (having already split land-future into 2 experments):  We should now promote one of these two,  land-ssp585, to tier 1 and also add a third expt. of this kind, land-ssp126, as a tier 1 experiment.
@martinjuckes : This will require some changes to the data request, but I think if they are difficult you should simply delay making them to release 28.  Will that be o.k.?  Please let us know right away if there is a problem.  Thanks.
Karl

**Comment by durack1** [comment]
@hyungjun those changes are now in place, please review the experiments at [CMIP6_experiment_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html) and let us know if any further tweaks are required

**Comment by durack1** [comment]
@MartinaSt thanks for the heads up, I didn't realize that you were also requiring edits on the citation end
