### ISSUE TITLE
institution_id registration of ECMWF

### ISSUE THREAD

**Issue by cdr30** [WCRP-CMIP/CMIP6_CVs#570]
institution_id = ECMWF
institution = ECMWF (European Centre for Medium-Range Weather Forecasts, Reading RG2 9AX, United Kingdom)

**Comment by durack1** [comment]
@cdr30 `ECMWF` is now registered, so point your browser to [CMIP6_institution_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_institution_id.html) to cross-check the entry
