### ISSUE TITLE
source_id registration of ECMWF-IFS-LR

### ISSUE THREAD

**Issue by cdr30** [WCRP-CMIP/CMIP6_CVs#571]
Note: ideally the information below will match that in the forked version of CMIP6_CV.json we are using within the PRIMAVERA project (https://github.com/PRIMAVERA-H2020/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json#L115)  

label = ECMWF-IFS-LR
label_extended = ECMWF-IFS-LR (50 km atmosphere and 100 km ocean)
source_id = ECMWF-IFS-LR
institution_id =  ECMWF
release_year = 2017
activity_participation = [HighResMIP]

aerosol:
description = None
nominal_resolution = None
atmos:
description = IFS (IFS CY43R1, Tco199 cubic octahedral reduced Gaussian grid equivalent to 200 lines between the pole and equator using 4 grid-points per minimum wavelength; 91 levels; top level 1 hPa
nominal_resolution = 50 km
atmosChem:
description = None
nominal_resolution = None
land:
description = HTESSEL (as implemented in IFS CY43R1)
nominal_resolution = 50 km
landIce:
description = None
nominal_resolution =  None
ocean:
description = NEMO3.4 (NEMO v3.4; ORCA1 tripolar grid; 362 x 292 longitude/latitude; 75 levels; top grid cell 1m)
nominal_resolution = 100 km
ocnBgchem:
description = None
nominal_resolution = None
seaIce:
description = LIM2 (LIM v2; ORCA1 tripolar grid; 362 x 292 longitude/latitude)
nominal_resolution = 100 km

**Comment by cdr30** [comment]
Hi Paul - updated info below:

label = ECMWF-IFS-LR
label_extended = ECMWF-IFS-LR (50 km atmosphere and 100 km ocean)
source_id = ECMWF-IFS-LR
institution_id = ECMWF
release_year = 2017
activity_participation = [HighResMIP]

aerosol:
description = None
nominal_resolution = None
atmos:
description = IFS (IFS CY43R1, Tco199, cubic octahedral reduced Gaussian grid equivalent to 800 x 400 longitude/latitude; 91 levels; top level 1 hPa)
nominal_resolution = 50 km
atmosChem:
description = None
nominal_resolution = None
land:
description = HTESSEL (as implemented in IFS CY43R1)
nominal_resolution = 50 km
landIce:
description = None
nominal_resolution = None
ocean:
description = NEMO3.4 (NEMO v3.4; ORCA1 tripolar grid; 362 x 292 longitude/latitude; 75 levels; top grid cell 0-1 m)
nominal_resolution = 100 km
ocnBgchem:
description = None
nominal_resolution = None
seaIce:
description = LIM2 (LIM v2; ORCA1 tripolar grid; 362 x 292 longitude/latitude)
nominal_resolution = 100 km

**Comment by durack1** [comment]
@cdr30 `ECMWF-IFS-LR` is now in place, please review [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know of any further required tweaks
