### ISSUE TITLE
source_id registration of ECMWF-IFS-HR

### ISSUE THREAD

**Issue by cdr30** [WCRP-CMIP/CMIP6_CVs#573]
Note: ideally the information below will match that in the forked version of CMIP6_CV.json we are using within the PRIMAVERA project (https://github.com/PRIMAVERA-H2020/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json#L115)

label = ECMWF-IFS-HR
label_extended = ECMWF-IFS-HR (25 km atmosphere and 25 km ocean)
source_id = ECMWF-IFS-HR
institution_id = ECMWF
release_year = 2017
activity_participation = [HighResMIP]

aerosol:
description = None
nominal_resolution = None
atmos:
description = 
IFS (IFS CY43R1, Tco399 cubic octahedral reduced Gaussian grid equivalent to 400 lines between the pole and equator using 4 grid-points per minimum wavelength; 91 levels; top level 1 hPa
nominal_resolution = 25 km
atmosChem:
description = None
nominal_resolution = None
land:
description = HTESSEL (as implemented in IFS CY43R1)
nominal_resolution = 25 km
landIce:
description = None
nominal_resolution = None
ocean:
description = NEMO3.4 (NEMO v3.4; ORCA025 tripolar grid; 1442 x 1021 longitude/latitude; 75 levels; top grid cell 1m)
nominal_resolution = 25 km
ocnBgchem:
description = None
nominal_resolution = None
seaIce:
description = LIM2 (LIM v2; ORCA-25 tripolar grid; 1442 x 1021 longitude/latitude)
nominal_resolution = 25 km

**Comment by cdr30** [comment]
Updated info below:

label = ECMWF-IFS-HR
label_extended = ECMWF-IFS-HR (25 km atmosphere and 25 km ocean)
source_id = ECMWF-IFS-HR
institution_id = ECMWF
release_year = 2017
activity_participation = [HighResMIP]

aerosol:
description = None
nominal_resolution = None
atmos:
description =
IFS (IFS CY43R1, Tco399, cubic octahedral reduced Gaussian grid equivalent to 1600 x 800 longitude/latitude; 91 levels; top level 1 hPa)
nominal_resolution = 25 km
atmosChem:
description = None
nominal_resolution = None
land:
description = HTESSEL (as implemented in IFS CY43R1)
nominal_resolution = 25 km
landIce:
description = None
nominal_resolution = None
ocean:
description = NEMO3.4 (NEMO v3.4; ORCA025 tripolar grid; 1442 x 1021 longitude/latitude; 75 levels; top grid cell 0-1 m)
nominal_resolution = 25 km
ocnBgchem:
description = None
nominal_resolution = None
seaIce:
description = LIM2 (LIM v2; ORCA-25 tripolar grid; 1442 x 1021 longitude/latitude)
nominal_resolution = 25 km

**Comment by durack1** [comment]
@cdr30 `ECMWF-IFS-HR` is now in place, please review [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know of any further required tweaks
