### ISSUE TITLE
source_id registration of ECMWF-IFS-MR

### ISSUE THREAD

**Issue by cdr30** [WCRP-CMIP/CMIP6_CVs#574]
label = ECMWF-IFS-MR
label_extended = ECMWF-IFS-MR (50 km atmosphere and 25 km ocean)
source_id = ECMWF-IFS-MR
institution_id = ECMWF
release_year = 2017
activity_participation = [HighResMIP]

aerosol:
description = None
nominal_resolution = None
atmos:
description = IFS (IFS CY43R1, Tco199 cubic octahedral reduced Gaussian grid equivalent to 200 lines between the pole and equator using 4 grid-points per minimum wavelength; 91 levels; top level 1 hPa
nominal_resolution = 50 km
atmosChem:
description = None
nominal_resolution = None
land:
description = HTESSEL (as implemented in IFS CY43R1)
nominal_resolution = 50 km
landIce:
description = None
nominal_resolution = None
ocean:
description = NEMO3.4 (NEMO v3.4; ORCA025 tripolar grid; 1442 x 1021 longitude/latitude; 75 levels; top grid cell 1m)
nominal_resolution = 25 km
ocnBgchem:
description = None
nominal_resolution = None
seaIce:
description = LIM2 (LIM v2; ORCA-25 tripolar grid; 1442 x 1021 longitude/latitude)
nominal_resolution = 25 km

**Comment by durack1** [comment]
@cdr30 `ECMWF-IFS-MR` is now in place, please review [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know of any further required tweaks
