### ISSUE TITLE
institution_id registration of FIO-QNLM

### ISSUE THREAD

**Issue by zhenyasong** [WCRP-CMIP/CMIP6_CVs#582]
institution_id = FIO-QNLM
institution = FIO (First Institute of Oceanography, State Oceanic Administration, Qingdao 266061, China), QNLM (Qingdao National Laboratory for Marine Science and Technology, Qingdao 266237, China)

**Comment by durack1** [comment]
@zhenyasong thanks for this, is the `FIO-QNLM` registration intending on replacing the existing [`FIO-RONM`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_institution_id.json#L21) or this this an additional institution?

**Comment by zhenyasong** [comment]
Replace. Please delete FIO-QONM. Thanks.

**Comment by zhenyasong** [comment]
@durack1 As the institutional reform last year, now the headquarter of FIO is Ministry of Natural Resources, so please use "FIO (First Institute of Oceanography, Ministry of Natural Resources, Qingdao 266061, China)" insteal of "FIO (First Institute of Oceanography, State Oceanic Administration, Qingdao 266061, China)". Many thanks.

**Comment by durack1** [comment]
@zhenyasong no problem with reopen and update this registration.

**Comment by zhenyasong** [comment]
institution_id = FIO-QNLM
institution = FIO (First Institute of Oceanography, Ministry of Natural Resources, Qingdao 266061, China), QNLM (Qingdao National Laboratory for Marine Science and Technology, Qingdao 266237, China)

**Comment by durack1** [comment]
@zhenyasong that change is now implemented, please take a look at [CMIP6_institution_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_institution_id.html) and let me know of any further tweaks required

**Comment by zhenyasong** [comment]
@durack1 Thank you.
