### ISSUE TITLE
source_id -- add to "activity_participation" of "MIROC6"

### ISSUE THREAD

**Issue by tinoue70** [WCRP-CMIP/CMIP6_CVs#590]
Please add 'AerChemMIP' to "activity_participation" of "MIROC6".

**Comment by durack1** [comment]
@tinoue70 that change is now in place, please review [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further tweaks are required
