### ISSUE TITLE
Top level of the atm is either in "hPa" or "mb"

### ISSUE THREAD

**Issue by jypeter** [WCRP-CMIP/CMIP6_CVs#596]
@durack1 I have just noticed that some models in https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html use **hPa** for the top level of the atm, and others **mb**

That's not a big deal, but since you usually insist on the consistency of the information... You can close this issue directly if you want!

Well, some others also use **m** or **km**, but that's not exactly the same problem

**Comment by durack1** [comment]
@jypeter thanks for pointing this out. It's near impossible to force any modeling group to use defined units, and while there are inconsistencies these can be mapped from one to another if necessary. I'll close this as a non-issue.
