### ISSUE TITLE
source_id  rename nominal_resolution

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#597]
One descriptor under each source_id is "nominal_resolution".  In this place, it is meant to record the nominal_resolution of the *native* grid.

In each model output file we store a global attribute named "nominal_resolution", but this is supposed to record the resolution of the grid on which output is provided (which may differ from the native grid). 

I think for source_id we should rename "nominal_resolution" "native_nominal_resolution" so there won't be confusion as to what it represents.  

@momipsl @davidhassell @charliepascoe @martinjuckes @durack1 If this is o.k. please let us know before August 29th.  (everyone should be back from vacations before then, I think).

**Comment by davidhassell** [comment]
That's good with me (The search results at https://github.com/WCRP-CMIP/CMIP6_CVs/search?q=%2Fnominal&unscoped_q=%2Fnominal helped me confirm this).
