### ISSUE TITLE
modification about CMIP6_source_id of BCC models

### ISSUE THREAD

**Issue by bcccsm** [WCRP-CMIP/CMIP6_CVs#600]
In the file CMIP6_source_id, the description of BCC-CSM2-HR in "atmos":{"description":"BCC_AGCM3_LR”. Here BCC_AGCM3_LR should be BCC_AGCM3_HR. 

In the file CMIP6_source_id, for models BCC-ESM， BCC-CSM2-MR and BCC-CSM2-HR， the description of MOM4 is wrong. It should be " 1/3 deg 10S-10N, 1/3-1 deg 10-30N/S, and 1deg in higher latitude".

Please correct it for us. Thank you very much.

**Comment by durack1** [comment]
@bcccsm those changes are now in place, please review the details in [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further amendments are required

**Comment by bcccsm** [comment]
That's great. Thank you very much.
