### ISSUE TITLE
experiment_id -- ES-DOC "alternative names"

### ISSUE THREAD

**Issue by charliepascoe** [WCRP-CMIP/CMIP6_CVs#605]
We need to come up with another name for the "alternative names" field in the ES-DOC viewer.
The suggestions are:
- alias
- AKA
- working name
- previous name

See ticket https://github.com/ES-DOC/esdoc-docs/issues/271 for context.

**Comment by durack1** [comment]
Pulling in @taylor13 @charliepascoe @davidhassell @momipsl

**Comment by durack1** [comment]
Pulling in @taylor13 @charliepascoe @davidhassell @momipsl @martinjuckes

**Comment by martinjuckes** [comment]
There appear to be two use-cases covered by this field: if I've understood correctly, it contains information about **obsolete** terms which may have been used in the literature, but also, according to   Charlotte's comment in ES-DOC/esdoc-docs#271, some genuine aliases which are still in use within MIPs (who may have developed their own portals etc for managing their workflows). If it is too late to split these by adding an additional field for the obsolete terms, perhaps we could distinguish the obsolete terms by adding an asterisk (e.g. `pdSST-pdSIC:alias="1.1", volc-pinatubo-surf:alias="*volcEq-surf, *VolsShort20EQsurf").

**Comment by durack1** [comment]
@martinjuckes did you mean to delete the below?

> There appear to be two use-cases covered by this field: if I've understood correctly, it contains information about obsolete terms which may have been used in the literature, but also, according to Charlotte's comment in ES-DOC/esdoc-docs#271, some genuine aliases which are still in use within MIPs (who may have developed their own portals etc for managing their workflows). If it is too late to split these by adding an additional field for the obsolete terms, perhaps we could distinguish the obsolete terms by adding an asterisk (e.g. `pdSST-pdSIC:alias="1.1", volc-pinatubo-surf:alias="*volcEq-surf, *VolsShort20EQsurf").

**Comment by taylor13** [comment]
I think this should be discussed at https://github.com/ES-DOC/esdoc-docs/issues/271 .  In the controlled vocab. we don't plan to include the aliases, but they could help some users accessing ES-DOC.   We'll close here, but please update us when a decision has been made.
