### ISSUE TITLE
source_id -- please modify "natNomRes atmos" of NICAM16-*.

### ISSUE THREAD

**Issue by tinoue70** [WCRP-CMIP/CMIP6_CVs#606]
Following a recent email from Karl, we checked `native_nominal_resolution` (for `atmos`) of our models and found some mistakes. Please modify as follows;

- NICAM16-7S : 50km -> 100 km
- NICAM16-8S : 25km -> 50km
- NICAM16-9S : 10km -> 25km
- NICAM16-9D : 10km -> 25km

**Comment by durack1** [comment]
@tinoue70 those changes are now implemented, please review [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know of any further changes. FYI, the model `NICAM16-9D` noted above is actually registered as `NICAM16-9D-L78`, let me know if this need amending

**Comment by tinoue70** [comment]
@durack1 thank you very much, everything is OK.
Sorry for my ambiguous information, of course `NICAM16-9D-L78` is correct, and no need to amend.
