### ISSUE TITLE
experiment_id: start_year: for CDRMIP experiment esm-ssp534-over

### ISSUE THREAD

**Issue by charliepascoe** [WCRP-CMIP/CMIP6_CVs#607]
About the start date for esm-ssp534-over. 
The comparable experiment, run by ScenarioMIP, is ssp534-over which is initiated from year 2040 of the ssp585 simulation.
If CDRMIP were to follow the same protocol then esm-ssp534-over would be initiated from year 2040 of the esm-ssp585 run from C4MIP.
At the time of writing the start year for esm-ssp534-over is 2015. So if we keep things as thy are this would mean re-running the first 25 years of experiment esm-ssp585.

**Comment by durack1** [comment]
@dpkeller14 are you happy for this additional change to be made?

**Comment by taylor13** [comment]
If we change the start date to 2040 (and I think we should), then CDRMIP should make it clear that to do the complete esm-ssp534-over simulation, a group should run at leas the first 25 years of esm-ssp585, and then use the ssp535-over forcing for the remaining years starting in 2040.

If we do this, we need to set for esm-ssp534-over:
parent experiment = "esm-ssp585"
start year = 2040  (need to check whether 2040 or 2041 is correct here).

**Comment by dpkeller14** [comment]
Yes, I think that this change should be made.  I am happy to send out an email to the CDRMIP mailing list to clarify this, and to correct it in the paper.

Best regards,

David

**Comment by durack1** [comment]
@taylor13 we have both `ssp585` (ScenarioMIP sponsored) and `esm-ssp585` (C4MIP sponsored) so we need to be a little careful how we attribute the parent.

I think we need to set:
```
parent_activity_id = "ssp585"
start_year = "2041" (branched off end of year 2040, so start year is incremented by 1)
```

We also need to correct the description of `ssp534-over` as it's missing a "P" in the "SS5_85" description, should be "SSP5_85"

**Comment by taylor13** [comment]
@dpkeller14 @durack1 
In my previous https://github.com/WCRP-CMIP/CMIP6_CVs/issues/607#issuecomment-424422898.  "ssp534-over forcing" should have read "esm-ssp534-over forcing.  (I've now corrected that comment.)  All simulations with the prefix "esm" are emissions-driven.  

So, the parent of ems-ssp534-over must be the emission-driven ssp585 simulation (i.e., esm-ssp585, *not* ssp585).

Also, the GMD article states:
```
This  scenario is  of  interest  to  CDRMIP  because  after  an  initially  high
level of emissions, which follows the SSP5-8.5 unmitigated
baseline scenario until 2040, CO2 emissions are rapidly re-
duced with net CO2 emissions becoming negative after the
year 2070 and continuing to be so until the year 2190 when
they  reach  zero.
```
The "until 2040" indicates to me that the lower emissions begin at the beginning of 2040, so start_year should be "2040" (not "2041")

Also the minimum number of years should be changed to 61.

**Comment by durack1** [comment]
@taylor13 @dpkeller14 @charliepascoe do I have an all clear to implement the changes above?

**Comment by taylor13** [comment]
I have no more input to provide, but let's hear from @dpkeller14 and @charliepascoe .

**Comment by dpkeller14** [comment]
Sorry for the delayed response, I’m traveling this week and have limited wifi access.  Yes, I’m fine with you implementing the changes.

Best regards,

David

**Comment by charliepascoe** [comment]
Great.  
I'll make the appropriate changes to the ES-DOC database.
start-date: 1st January 2040
parent: esm-ssp585

**Comment by durack1** [comment]
@taylor13 @dpkeller14 @charliepascoe please take a peek at [CMIP6_experiment_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html) and let me know if any further tweaks are required

**Comment by charliepascoe** [comment]
I'm happy with that.

**Comment by taylor13** [comment]
looks correct now.
