### ISSUE TITLE
HighResMIP: CMIP6 experiment description and details verification

### ISSUE THREAD

**Issue by ReinHaarsma** [WCRP-CMIP/CMIP6_CVs#61]
control-1950 HighResMIP (page 4)
-What means BGM? Carbon cycle and biological processes are not considered in HighResMIP and are not included in the model components.  A land-surface model is included. 
-In the description is written "Coupled integrations, at least one with constant 1950"s forcing (CTL) and one or more with historic and then RCP4.5 (as in Forced_Atmos_Land, EXP)" RCP4.5 is wrong: A scenario as close to CMIP5 RCP8.5 as possible within CMIP6 (see experiment description of highres-future on page).

highres-future HighResMIP (page 8) 
- Start day should be 2015 as in description and not 2050. And number of years 36. For description see control-1950 HighresMIP
- BGM: see remarks above about control-1950 HighResMIP
- highres-future is the continuation of hist-1950 described in the next entry.

hist-1950 HighResMIP (page8)
- BGM: see remarks above about control-1950 HighResMIP
- Description: see remarks above about control-1950 HighResMIP

highresSST-4co2 (page 16)
- This is not a Tier 1 experiment, but an additional targeted experiment.
- BGM is not included here. The model is the same as in other HighResMIP experiments. See remarks above about control-1950 HighResMIP 

highresSST-future (page 16)
- BGM is not included here. The model is the same as in other HighResMIP experiments. See remarks above about control-1950 HighResMIP

highresSST-LAI (page 16)
- This is not a Tier 1 experiment, but an additional targeted experiment
  -BGM is not included here. The model is the same as in other HighResMIP experiments. See remarks above about control-1950 HighResMIP

highresSST-pk4 (page 17)
- This is not a Tier 1 experiment, but an additional targeted experiment
  -BGM is not included here. The model is the same as in other HighResMIP experiments. See remarks above about control-1950 HighResMIP

highresSST-present (page 17)
-BGM is not included here. The model is the same as in other HighResMIP experiments. See remarks above about control-1950 HighResMIP

highresSST-smoothed (page 17)
- This is not a Tier 1 experiment, but an additional targeted experiment
  -BGM is not included here. The model is the same as in other HighResMIP experiments. See remarks above about control-1950 HighResMIP

Summarizing:
Tier 1: highresSST-present
Tier 2: control-1950, hist-1950, highres-future
Tier 3: highresSST-future

The other experiments are targeted additional experiments.

The carbon cycle is not included in any of the experiments.

In the revised GMD manuscript that is still under revision we have added 2 more experiments:
- Abrupt 4xCO2 increase in coupled climate model – highres-4CO2
  CFMIP-style experiment to investigate role of ocean resolution on ocean heat uptake 
- Tier 2 and 3 using RCP8.5 instead of SSPx - highres-RCP85
  For centers that need to start their simulations before the availability of SSPx

**Comment by durack1** [comment]
Hi @ReinHaarsma, to ensure that I correctly update each of the experiments that you note above it would be easier for me if you can complete a template for each change/experiment update required - I have included my take on the changes that you require to `control-1950` below, apologies if I have incorrectly transcribed the `description` or `experiment` fields your text above was unclear to me:

```
"control-1950":{
    "activity_id":[
         "HighResMIP"
    ],
    "additional_allowed_model_components":[
         "AER",
        "CHEM",
        "LAND"
    ],
    "description":"PLEASE COMPLETE THIS FIELD",
    "end_year":"2050",
    "experiment":"coupled control with fixed 1950's forcing (HighResMIP equivalent of pre-industrial control)",
    "min_number_yrs_per_sim":"100",
    "parent_activity_id":[
        "HighResMIP"
    ],
    "parent_experiment_id":[
        "PLEASE COMPLETE THIS FIELD"
    ],
    "required_model_components":[
        "AOGCM"
    ],
    "start_year":"1951",
    "sub_experiment":"none",
    "sub_experiment_id":"none",
    "tier":"2"
},
```
You should be able to copy the text block above and update this for each change required.

**Comment by taylor13** [comment]
@ReinHaarsma I have tried to incorporate into the above the corrections suggested by you, but some questions remain:

1) I didn't understand what should be put in the "description" for the coupled model runs.  The description is supposed to be an expanded version of the "experiment".  Please insert something appropriate.  It should not be the same for all experiments.
2)  We don't have a tier = "targeted" option, so I have used tier=3 to indicate these targeted experiments.  If that's not right, please correct.
3)  Please follow the above template to provide information about the highres-4CO2 experiment
4)  Please follow the above template to provide information about each of the two other new experiments.
5) Check the start year for several of experiments starting near 1950.  It seems odd, for example, that hist-1950 should start in 1951.  Is that really correct?

No one can start writing output for these runs before the experiment information is complete and correct.
thanks.

**Comment by durack1** [comment]
@robertsmalcolm @ReinHaarsma it would be great if we can get some feedback on the above so we can resolve and close this issue

**Comment by taylor13** [comment]
@robertsmalcolm @ReinHaarsma I've added the spin-up experiment to the listing of your experiments above.  Most importantly, please check the start and end dates of each experiment.  I change several to begin in 1950, rather than 1951 and to be 65 years long (rather than 64).  Note that in your GMD paper you indicate highresSST-smooth is a 10-year experiment.  I wouldn't think that would be long enough to look at variability differences in any kind of detail.  Also you don't say which years .... I'm guessing 2005-2014.  Is this right or do you want this experiment to be 1950-2014?

Also, please provide experiment "descriptions" as needed.

thanks,
Karl
