### ISSUE TITLE
Apparent inconsistecy between intended use of models and experiment requirements

### ISSUE THREAD

**Issue by martinjuckes** [WCRP-CMIP/CMIP6_CVs#612]
Hello @taylor13 -- I think there is an inconsistency in between the range of MIPs that models are declared to be participating in and the constraints (specified by the required and allowed model components) on the type of models that are allowed in the relevant experiments. I'm looking at this to try and get a better understanding of data volumes.

The  [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) CV specifies the activities (i.e. endorsed MIPs) that each model is expected to participate in, and also describes the components of each model.

The experiment CV specifies required and additional allowed components for each experiment. A dynamic land ice component (ISM) combined with an AOGCM is only allowed in 4 experiments according to my understanding of these fields .... which may be inaccurate.

There are 12 models which combine a dynamic ice sheet model (mostly, if not all CISM) with an AOGCM. E.g NCAR's CESM2 model.  The activity participation specified for this model covers 23 MIPs, which goes far beyond the 4 experiments allowed by the current component settings.

**Comment by taylor13** [comment]
@martinjuckes The models registered in the source_id CV are supposed to include all components that *might* be active, but for some experiments some components will not be used.  For example, the source_id for a model carrying out an AMIP simulation (involving only atmospheric and land components) will be the same as the source_id of the coupled configuration of that model performing a piControl run.  This makes it easy for users to compare how much "coupling" the model degrades its simulation of the atmosphere. 
 
In each output file produced by a simulation the source_type will be recorded, which will identify which model components were activated for the experiment.  Not all the components listed as part of registration will appear in every output file from that source.  (The same information is supposed to be available from ES-Docs.)

Full rules for specifying "source_type" can be found in note 14 following the first table in  https://goo.gl/v1drZl

**Comment by taylor13** [comment]
Note also that CMOR3/PrePARE checks that the source_type for a given experiment is consistent with the required/allowed components listed in the experiment_id CV, and forbids publication unless it is.

**Comment by martinjuckes** [comment]
@taylor13 Thanks -- that does answer my question. Does that also apply to offline land and ice-sheet models? e.g. would CESM2 be used for experiments such as `ism-amip-std` with atmosphere and ocean components switched off?

**Comment by durack1** [comment]
@taylor13 is any change required here, or can we close?

**Comment by taylor13** [comment]
@martinjuckes If the offline model component is also used in coupled runs, I think the name should be the same.

@durack1 No changes are required at this time.

**Comment by durack1** [comment]
@taylor13 ok great, closing, however we can continue the conversation here and reopen if required

**Comment by martinjuckes** [comment]
Note that while ES-DOC information is not compatible at present (see https://github.com/ES-DOC/esdoc-docs/issues/272 ).

**Comment by taylor13** [comment]
I don't think any changes (related to this issue) are needed in the CV's.   Any offline-forced land or ice-sheet model should also be used in at least one run interacting with the coupled system, and they need to be identified as coming from the same source_id in order to compare their coupled and uncoupled behavior. 

@martinjuckes and @charliepascoe please let us know if you need information from us to correct any problems related to ES-DOC/esdoc-docs#272 .
