### ISSUE TITLE
experiment_id.json: incorrect parent_activity for 2 PAMIP experiments

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#614]
I noticed that for 2 of the PAMIP experiments (amip-histSST and amip-histSIC), the parent_experiment_id is "no parent", but the parent_activity_id is "CMIP".  

This is incorrect.  The correct parent_activity_id = "no parent".

Also, there are 2 possible parents listed for several of the DCPP simulations (no parent and dcppA-assim).  We need to check whether this is handled correctly by CMOR/PrePARE.

**Comment by durack1** [comment]
@taylor13 I'll queue these changes for the end of the week, and give folks a couple of days to comment if they consider problems will occur

**Comment by durack1** [comment]
@taylor13 there are no experiments registered titled `amip-histSST` and `amip-histSIC` - see [CMIP6_experiment_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html), do these need to be registered? If yes, where is this information recorded?

**Comment by taylor13** [comment]
Sorry ... it's amip-climSST and amip-climSIC.

**Comment by durack1** [comment]
@taylor13 for both these we have `parent_experiment_id = AMIP` and `parent_activity_id = CMIP`, so I don't believe there is anything to do here? [CMIP6_experiment_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html) with search entry `amip-climS`

**Comment by taylor13** [comment]
We were not very consistent in defining parent for AGCM-only simulations, so I'm not sure what we can do about it now.  All but the PAMIP experiments that begin with "amip-" in the experiment name have "no_parent".  I was trying to remedy that inconsistency.  My reasoning for omitting parent is that it doesn't matter much what the initial conditions are if you wait a couple of weeks and besides how can you say you're initializing your model from an AMIP run on January 1 1979 when those initial conditions have nothing to do with the AMIP run (they come from somewhere else).  
I noticed that there are other atmosphere-only simulations that say they are initialized from other simulations (but whose names don't begin "amip-"), so I suppose leaving PAMIP as is isn't so inconsistent after all. Let's leave this open for a few days but don't change anything now.

**Comment by durack1** [comment]
@taylor13 no problem, please close this when you are satisfied things are ok

**Comment by taylor13** [comment]
No one has commented since the last discussion ended nearly 2 weeks ago, so I'm closing.  No action is required.
