### ISSUE TITLE
CDRMIP temporal constraint discrepancies

### ISSUE THREAD

**Issue by charliepascoe** [WCRP-CMIP/CMIP6_CVs#615]
There are still a few discrepancies between the start and end dates of some experiments in the CDRMIP GMD and in the CMIP6 CV. 

yr2010CO2: 
min years: GMD = 105 years, CV = 106 years

esm-yr2010CO2-control: 
min years: GMD 265 years, CV = 266 years.

esm-yr2010CO2-noemit,
esm-yr2010CO2-cdr-pulse &
esm-yr2010CO2-CO2pulse:
start year: GMD = 2010, CV = 2015
min years: GMD = 105, CV = 101
implied end date: GMD = 31-12-2114, CV = 31-12-2115

The discrepancy in the start year for the esm-yr2010CO2-<noemit/cdr-pulse/CO2pulse> experiments
can be understood because the first 5 years of these experiments is a repeat of years 2010-2014 in the esm-yr2010CO2-control and the CMIP6 CV doesn’t expect models to generate this output again.

But there is a systematic difference in the end-year for the minimum simulation period whereby the specification in the CMIP6 CV is 1 year after the end date in the CDRMIP GMD paper.

At the time of writing the temporal constraints in the most recent ES-DOC database are consistent with the time periods in the CMIP6 CV (though the latest ES-DOC info is not published yet).

**Comment by taylor13** [comment]
I don't have time to check right now, but do either https://github.com/WCRP-CMIP/CMIP6_CVs/issues/594 or https://github.com/WCRP-CMIP/CMIP6_CVs/issues/607 already address these discrepancies?

**Comment by durack1** [comment]
@dpkeller14 do you have a comment to chime in here - in particular the 2010 start dates vs 2015 (the start of the projections, 2014 being the end of historical simulations)?

**Comment by dpkeller14** [comment]
yr2010CO2 should have min. years of 106

esm-yr2010CO2-control should have min. years of 266

For esm-yr2010CO2-noemit, esm-yr2010CO2-cdr-pulse & esm-yr2010CO2-CO2pulse
- start year should be 2015
- min. years should be 101 if starting in 2015
- the implied end date should be 31-12-2115

**Comment by durack1** [comment]
@dpkeller14 thanks for clarifying, there are no changes required in the CMIP6_experiment_id.json as these reflect your numbers above (see [here](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html))

As all details are correct I'll close this issue
