### ISSUE TITLE
activity_participation for CNRM-ESM2-1 -- add CORDEX, LS3MIP and CDRMIP

### ISSUE THREAD

**Issue by senesis** [WCRP-CMIP/CMIP6_CVs#618]
Hi Paul,
Could you please add these MIPS to CNRM-ESM2-1 activity participation
Regards
S

**Comment by durack1** [comment]
@senesis this change is now in place, please take a peek at [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know of any further tweaks

**Comment by durack1** [comment]
@senesis there was an indexing issue in the previous version, please review [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html), which should now correctly reflect both `CNRM-CM6-1` and `CNRM-ESM2-1`

**Comment by senesis** [comment]
That looks fine for this attribute. Thanks
