### ISSUE TITLE
CMIP6_experiment_id.json : experiment amip-hist misses allowed component "BGC"

### ISSUE THREAD

**Issue by senesis** [WCRP-CMIP/CMIP6_CVs#623]
Component BGC should be allowed for this experiment, for those centers which chose to use their ESM (so including BGC)  also in non-ocean-coupled simulations

**Comment by durack1** [comment]
@senesis thanks for this, we also note that in addition to `amip-hist`, we'll need to also amend `amip-hld`, `amip-TIP`, `amip-TIP-nosh` as these experiments should also include `BGC` as an allowed component

**Comment by durack1** [comment]
@senesis thanks again for this, the revised experiment details are now live in [CMIP6_experiment_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html), please review and let me know of any other tweaks required
