### ISSUE TITLE
institution id registration of AS-RCEC

### ISSUE THREAD

**Issue by rceclccr** [WCRP-CMIP/CMIP6_CVs#625]
institution_id = AS-RCEC
institution = Research Center for Environmental Changes, Academia Sinica, Taipei, Taiwan

**Comment by durack1** [comment]
Research Center for Environmental Changes Building, Nankang, Taipei 11529, Taiwan

**Comment by durack1** [comment]
@rceclccr `AS-RCEC` is now registered, please review these details at [CMIP6_institution_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_institution_id.html) and let me know if any further amendments are required.

**Comment by durack1** [comment]
@rceclccr can you please send an email to `durack1 .at. llnl .dot. gov` so we can correctly register you, or another member of the `AS-RCEC` team across a number of the other infrastructure components?

**Comment by durack1** [comment]
@rceclccr can you please send an email to `durack1 .at. llnl .dot. gov` so we can correctly register you, or another member of the `AS-RCEC` team across a number of the other infrastructure communication components?

@MartinaST ping

**Comment by durack1** [comment]
@rceclccr can you please send an email to `durack1 .at. llnl .dot. gov` so we can correctly register you, or another member of the `AS-RCEC` team across a number of the other infrastructure communication components?

@MartinaST @davidhassell ping

**Comment by durack1** [comment]
```
From: AS CCliCS
Date: Wednesday, December 19, 2018 at 8:27 PM
To: "Durack, Paul J." 
Subject: institution id registration of AS-RCEC

Dear Dr Durack,

Sorry for the late reply. This letter is to register AS-RCEC for the institution. 

Could you please add Dr. Wei-Liang Lee ( leelupin@xxx.edu.tw ) as the contact of the institution?

Also the Institution description of AS-RCEC on https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_institution_id.html misses the "Academia Sinica" from our initial registration. It should be " Research Center for Environmental Changes, Academia Sinica, Nankang, Taipei 11529, Taiwan ". Could you please change that or should I submit to the issue tracking?

Thanks so much and really appreciate your help. 

Best regards,

Laboratory for Climate Change Research
Research Center for Environmental Changes
Academia Sinica
Taipei
Taiwan
Tel: +886-2-278758xx
Fax: +886-2-278335xx
email: cclica.as@xx.com
```
