### ISSUE TITLE
Model registration of TaiESM 1.0

### ISSUE THREAD

**Issue by rceclccr** [WCRP-CMIP/CMIP6_CVs#626]
label = TaiESM 1.0
label_extended = Taiwan Earth System Model 1.0
source_id = TaiESM1
institution_id = AS-RCEC
release_year = 2018
activity_participation = AerChemMIP CFMIP CMIP GMMIP LUMIP PMIP ScenarioMIP

aerosol:
description = SNAP (same grid as atmos)
nominal_resolution = 100 km
atmos:
description = TaiAM1 (0.9x1.25 degree; 288 x 192 longitude/latitude; 30 levels; top level ~2 hPa)
nominal_resolution = 100 km
atmosChem:
description = SNAP (same grid as atmos)
nominal_resolution = 100 km
land:
description = CLM4.0 (same grid as atmos)
nominal_resolution = 100 km    
landIce:
description = none
nominal_resolution = none 
ocean:
description = POP2 (320x384 longitude/latitude; 60 levels; top grid cell 0-10 m)
nominal_resolution = 100 km
ocnBgchem:
description = none
nominal_resolution = none
seaIce:
description = CICE4
nominal_resolution = 100 km

**Comment by durack1** [comment]
@rceclccr `TaiESM1` is now registered, please review these details at [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further amendments are required.

I am curious if the `SNAP` model has a version identifier, this was not included in the registered details.
