### ISSUE TITLE
experiment_id: add additional start date for  two dcppC pacemaker expts.

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#631]
Guillaume requests (and I concur) that for experiment_id="dcppC-atl-pacemaker" and "dcppC-pac-pacemaker",  we should add  start year 1920 as an acceptable start date.

**Comment by durack1** [comment]
@glevava @taylor13 those changes are now in place, please review [CMIP6_experiment_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html) to cross-check

**Comment by glevava** [comment]
Thanks @durack1 and @taylor13 !
That's perfect, IPSL-CM DCCPC data will be soon published ; )
