### ISSUE TITLE
LS3MIP: amip-lfmip-rmLC overview

### ISSUE THREAD

**Issue by gkrinner** [WCRP-CMIP/CMIP6_CVs#632]
Experiment overview is misleading.

**Long Name** should be: "prescribed land surface climatology from historical+scenario 30 yr running mean, prescribed SST and SIC from historical+scenario runs"

**Description** should be: "Scenario forced experiment with prescribed land surface climatology derived from 30 year running mean from the first ensemble members of the historical and ssp585 experiments. SST and SIC from the first ensemble members of the historical and ssp585 experiments."

**Comment by durack1** [comment]
@gkrinner thanks for this, the changes are now in place. I updated a couple of your characters as these were not acceptable in the JSON format we're using. Please review the details, and changes to the `description` and `experiment` identifiers for both `amip-lfmip-rmLC` and `amip-lfmip-pdLC` - you can view this easily at [CMIP6_experiment_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html). Please reopen the issue for any further required tweaks.
