### ISSUE TITLE
LS3MIP: amip-lfmip-pdLC overview

### ISSUE THREAD

**Issue by gkrinner** [WCRP-CMIP/CMIP6_CVs#633]
Experiment overview is misleading.

**Long Name** should be: "prescribed modern land surface climatology from historical, prescribed SST and SIC from historical+scenario runs"

**Description** should be: "Scenario forced experiment with prescribed land surface climatology derived from modern conditions from the first historical ensemble member (1980-2014). SST and SIC from the first ensemble members of the historical and ssp585 experiments."

**Comment by durack1** [comment]
@gkrinner thanks for this, the changes are now in place. I updated a couple of your characters as these were not acceptable in the JSON format we're using. Please review the details, and changes to the `description` and `experiment` identifiers for both `amip-lfmip-rmLC` and `amip-lfmip-pdLC` - you can view this easily at [CMIP6_experiment_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html). Please reopen the issue for any further required tweaks.
