### ISSUE TITLE
LS3MIP point of contact

### ISSUE THREAD

**Issue by gkrinner** [WCRP-CMIP/CMIP6_CVs#634]
In the LS3MIP description (CMIP6 Sub MIP : LS3MIP), please add a new point of contact under **Responsible Parties** :

**Name**: Hyungjun Kim (link to: https://www.researchgate.net/profile/Hyungjun_Kim6)
**Address**: Institute of Industrial Science, The University of Tokyo, Japan
**Email**: hjkim@iis.u-tokyo.ac.jp

**Comment by durack1** [comment]
@gkrinner thanks for this.

The format of the `experiment_id` identifier is:
```
    "experiment_id":{
        "1pctCO2":{
            "activity_id":[
                "CMIP"
            ],
            "additional_allowed_model_components":[
                "AER",
                "CHEM",
                "BGC"
            ],
            "description":"DECK: 1pctCO2",
            "end_year":"",
            "experiment":"1 percent per year increase in CO2",
            "experiment_id":"1pctCO2",
            "min_number_yrs_per_sim":"150",
            "parent_activity_id":[
                "CMIP"
            ],
            "parent_experiment_id":[
                "piControl"
            ],
            "required_model_components":[
                "AOGCM"
            ],
            "start_year":"",
            "sub_experiment_id":[
                "none"
            ],
            "tier":"1"
        },
"1pctCO2-4xext":{
...
```
And we don't have any contact information for privacy reasons primarily. ES-DOC is providing more comprehensive documentation (including email contacts) and you can see the LS3MIP info [here](https://view.es-doc.org/?renderMethod=id&project=cmip6&id=ec9243df-26b7-4ed5-ba77-beb65bc13276&version=1&client=esdoc-search). If you want to add Hyungjun, then I suggest reaching out to the ES-DOC folks.

For the input4MIPs contributions, we have a similar format registration accessible at https://github.com/PCMDI/input4MIPs-cmor-tables

I'll close this issue as there is no action to be taken in this repo.
