### ISSUE TITLE
source_id -- add "cohort" list to each

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#64]
We need to record the names of each "cohort" each model belongs to.  The following cohorts are defined:  

1. A model that completes all the DECK simulations belongs to the "DECK" cohort.
2. A model that completes the DECK and CMIP6 historical simulations belongs to the "CMIP6" cohort.  The CMIP Panel may choose to relax this requirement on a case by case basis and designate some models as belonging to the CMIP6 cohort even if all the simulations have not been completed.   
3. A model that fails to qualify for the “DECK” or “CMIP6” cohorts but performs at least one of the CMIP6 experiments and *does* meet the criteria of at least one of the endorsed MIPs in CMIP6 belongs to the "CMIP6-fringe" cohort..
4. A model that participated in CMIP5, CMIP3, CMIP2, and/or CMIP1, belongs to the correspondingly named cohort.

All models will initially be designated as cohort = "None".  The PCMDI will need to work with the CMIP panel and endorsed-MIP chairs to keep this list updated.

**Comment by durack1** [comment]
@taylor13 can you please amend the [issue template](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/.github/ISSUE_TEMPLATE.md) to capture this information.. I will then update the existing `ACCESS-1-0` example in the current [CMIP6_source_id.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json)

**Comment by taylor13** [comment]
I updated source_id.json, but I don't think we should include "cohort" in the registration form.  All models will initially have "cohort = none".  I don't want to confuse anyone with what "cohort" means.  Only the CMIP Panel or its representative (PCMDI) are permitted to assign a model to a cohort.   I think we can close this.

**Comment by durack1** [comment]
@taylor13 I will pull that back into the script so your edits aren't clobbered the next time that it runs.. We have traceability in this issue for the default:
```
"cohort":[
    "None"
],
```
I'll close this when the `cohort` is included in a reproducible version of the repo
