### ISSUE TITLE
Model registration of CESM2-SE

### ISSUE THREAD

**Issue by strandwg** [WCRP-CMIP/CMIP6_CVs#640]
label = CESM2-SE
label_extended = CESM2-SE spectral element (cubed-sphere grid)
source_id = CESM2-SE
institution_id = NCAR
release_year = 2019
activity_participation = CMIP HighResMIP

aerosol:
description = MAM4 (same grid as atmos)
native_nominal_resolution = 25 km

atmos:
description = CAM6 (0.25 degree spectral element; 777602 cells; 30 levels; top level 2.25 mb)
native_nominal_resolution = 25 km

atmosChem:
description = MAM4 (same grid as atmos)
native_nominal_resolution = 25 km

land:
description = CLM5 (same grid as atmos)
native_nominal_resolution = 25 km

landIce:
description = CISM2.1
native_nominal_resolution = 5 km

ocean:
description = POP2 (320x384 longitude/latitude; 60 levels; top grid cell 0-10 m)
native_nominal_resolution = 100 km

ocnBgchem:
description = MARBL (same grid as ocean)
native_nominal_resolution = 100 km

seaIce:
description = CICE5.1 (same grid as ocean)
native_nominal_resolution = 100 km

**Comment by durack1** [comment]
@strandwg thanks for the info, the registration is now complete - take a peek at [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know of any tweaks required
