### ISSUE TITLE
source_id Registration of RRTMG-SW

### ISSUE THREAD

**Issue by pernak18** [WCRP-CMIP/CMIP6_CVs#641]
label = RRTMG-SW
label_extended = RRTM for GCMs v4.02, shortwave
source_id = RRTMG-LW-4-2
institution_id = AER
release_year = 2017
activity_participation = [RFMIP]

aerosol:
description = none
nominal_resolution = none
atmos:
description = none
nominal_resolution = none
atmosChem:
description = none
nominal_resolution = none
land:
description = none
nominal_resolution = none
landIce:
description = none
nominal_resolution = none
ocean:
description = none
nominal_resolution = none
ocnBgchem:
description = none
nominal_resolution = none
seaIce:
description = none
nominal_resolution = none

**Comment by durack1** [comment]
@pernak18 thanks for the info, the registration is now complete - take a peek at [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know of any tweaks required. I took the liberty to fix a couple of `*LW*` -> `*SW*` typos above
