### ISSUE TITLE
source_id Registration of RTE+RRTMGP

### ISSUE THREAD

**Issue by pernak18** [WCRP-CMIP/CMIP6_CVs#642]
label = RTE+RRTMGP
label_extended = Radiative Transfer for Energetics using RRTM for GCM applications - Parallel
source_id = RTE+RRTMGP-2018-12-04-full-res
institution_id = RTE-RRTMGP-Consortium
release_year = 2019
activity_participation = [RFMIP]

aerosol:
description = none
nominal_resolution = none
atmos:
description = none
nominal_resolution = none
atmosChem:
description = none
nominal_resolution = none
land:
description = none
nominal_resolution = none
landIce:
description = none
nominal_resolution = none
ocean:
description = none
nominal_resolution = none
ocnBgchem:
description = none
nominal_resolution = none
seaIce:
description = none
nominal_resolution = none

**Comment by durack1** [comment]
@pernak18 is there a version identifier missing here?

**Comment by pernak18** [comment]
@durack1 i've consulted @RobertPincus about this and have updated the source ID field as he advised. regarding the institution ID: "You can ask Durack if we can combine two existing institutions in this field. I suspect we will have to create a third, new institution that's a combination, or a consortium, ..." For now, I have our two separate institutions. suggestions?

**Comment by durack1** [comment]
@pernak18 a new `institution_id` registration will be best - take a peek at https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_institution_id.json for some consortia examples

**Comment by pernak18** [comment]
@durack1 do you have to add an institution to that json file, or can i? we decided on RTE-RRTMGP-Consortium, which is "Atmospheric and Environmental Research, Lexington, USA and University of Colorado, Boulder, USA"

**Comment by durack1** [comment]
@pernak18 just open a new issue with `"institution_id registration RTE-RRTMGP-Consortium"` as the title, and I presume the entry for this institution_id registration is:

`"AER (Atmospheric and Environmental Research, Lexington, MA 02421, USA); UColorado (University of Colorado, Boulder, CO 80309, USA). Mailing address: AER, c/o SOME DUDE,  131 Hartwell Avenue, Lexington, MA 02421, USA"`

**Comment by durack1** [comment]
@pernak18 I'll replace the `+` symbol with `-`, so the `source_id` value will be `RTE-RRTMGP-181204-full-res`... Actually this seems kinda over the top for a `source_id`, would you rather this be `RTE-RRTMGP-181204` with the `label` being `RTE+RRTMGP (2018-12-04 full-resolution)`?

So the new lineup:
```
source_id = RTE-RRTMGP-181204
label = RTE+RRTMGP (2018-12-04 full-resolution)
label_extended = Radiative Transfer for Energetics using RRTM for GCM applications - Parallel (2018-12-04 full-resolution)
```

**Comment by durack1** [comment]
@pernak18 please take a look at [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) to double check your new `source_id`

**Comment by pernak18** [comment]
@durack1 sorry, this fell off my radar temporarily. thanks for taking care of everything -- it all looks good to me

**Comment by pernak18** [comment]
@durack1 my mistake -- could we change the institution_id for this source_id to the "RTE-RRTMGP-Consortium" that you generated? please and thanks

**Comment by durack1** [comment]
@pernak18 good catch, not sure how that slipped past, will reopen until it's resolved

**Comment by durack1** [comment]
@pernak18 thanks for checking, the revised details are now in place, see [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html)

**Comment by pernak18** [comment]
@durack1 looks good, thanks!
