### ISSUE TITLE
institution_id registration RTE-RRTMGP-Consortium

### ISSUE THREAD

**Issue by pernak18** [WCRP-CMIP/CMIP6_CVs#650]
AER (Atmospheric and Environmental Research, Lexington, MA 02421, USA); UColorado (University of Colorado, Boulder, CO 80309, USA). Mailing address: AER c/o Eli Mlawer, 131 Hartwell Avenue, Lexington, MA 02421, USA

**Comment by durack1** [comment]
@pernak18 thanks for this, I'll get onto pulling #642 and this issue (#650) across later today

**Comment by durack1** [comment]
@pernak18 please take a look at [CMIP6_institution_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_institution_id.html) to double check your new `institution_id`
