### ISSUE TITLE
source_id Registration of MPI-ESM1.2-XR

### ISSUE THREAD

**Issue by mbittner1** [WCRP-CMIP/CMIP6_CVs#654]
Dear all,
could you please register the following model version of MPI-ESM1.2 which will be used in HighResMIP. Thank you very much!

MPI-ESM1-2-XR":{
            "activity_participation":[
                "HighResMIP" 
            ],
            "cohort":[
                "Registered"
            ],
            "institution_id":[
                "MPI-M"
            ],
            "label":"MPI-ESM1.2-XR",
            "label_extended":"MPI-ESM1.2-XR",
            "model_component":{
                "aerosol":{
                    "description":"none, prescribed MACv2-SP",
                    "native_nominal_resolution":"50 km"
                },
                "atmos":{
                    "description":"ECHAM6.3 (spectral T255; 768 x 384 longitude/latitude; 95 levels; top level 0.01 hPa)",
                    "native_nominal_resolution":"50 km"
                },
                "atmosChem":{
                    "description":"none",
                    "native_nominal_resolution":"none"
                },
                "land":{
                    "description":"JSBACH3.20",
                    "native_nominal_resolution":"50 km"
                },
                "landIce":{
                    "description":"none/prescribed",
                    "native_nominal_resolution":"none"
                },
                "ocean":{
                    "description":"MPIOM1.63 (tripolar TP04, approximately 0.4deg; 802 x 404 longitude/latitude; 40 levels; top grid cell 0-12 m)",
                    "native_nominal_resolution":"50 km"
                },
                "ocnBgchem":{
                    "description":"HAMOCC",
                    "native_nominal_resolution":"50 km"
                },
                "seaIce":{
                    "description":"unnamed (thermodynamic (Semtner zero-layer) dynamic (Hibler 79) sea ice model)",
                    "native_nominal_resolution":"50 km"
                }
            },
            "release_year":"2017",
            "source_id":"MPI-ESM1-2-XR"
        }

**Comment by durack1** [comment]
@mbittner1 your model is now registered, see [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) for details. I did wonder if a number of the unlabeled components had a version number e.g. `HAMOCC`? and was also wondering whether a `release_year = 2017` was accurate?

**Comment by mbittner1** [comment]
@durack1 Thank you for registering the model. Yes, the release year is accurate, but you are right concerning the missing version number of HAMOCC (in fact in all the MPI-ESM1.2 models I submitted).

Could you change the following

 "MPI-ESM1-2-HR":{
                 "ocnBgchem":{
                    "description":"HAMOCC6",

 "MPI-ESM1-2-LR":{
                 "ocnBgchem":{
                    "description":"HAMOCC6",

 "MPI-ESM1-2-XR":{
                 "ocnBgchem":{
                    "description":"HAMOCC6",

thank you very much!

**Comment by durack1** [comment]
@mbittner1 changes made, see [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) for details
