### ISSUE TITLE
source_id registration of CanESM5-CanOE

### ISSUE THREAD

**Issue by slavakharin** [WCRP-CMIP/CMIP6_CVs#656]
"CanESM5-CanOE":{
            "activity_participation":[
                "C4MIP",
                "CDRMIP",
                "CMIP",
                "OMIP",
                "ScenarioMIP",
            ],
            "cohort":[
                "Registered"
            ],
            "institution_id":[
                "CCCma"
            ],
            "label":"CanESM5-CanOE",
            "label_extended":"CanESM5-CanOE",
            "model_component":{
                "aerosol":{
                    "description":"interactive",
                    "native_nominal_resolution":"500 km"
                },
                "atmos":{
                    "description":"CanAM5 (T63L49 native atmosphere, T63 Linear Gaussian Grid; 128 x 64 longitude/latitude; 49 levels; top level 1 hPa)",
                    "native_nominal_resolution":"500 km"
                },
                "atmosChem":{
                    "description":"specified oxidants for aerosols",
                    "native_nominal_resolution":"500 km"
                },
                "land":{
                    "description":"CLASS3.6/CTEM1.2",
                    "native_nominal_resolution":"500 km"
                },
                "landIce":{
                    "description":"specified ice sheets",
                    "native_nominal_resolution":"500 km"
                },
                "ocean":{
                    "description":"NEMO3.4.1 (ORCA1 tripolar grid, 1 deg with refinement to 1/3 deg within 20 degrees of the equator; 361 x 290 longitude/latitude; 45 vertical levels; top grid cell 0-6.19 m)",
                    "native_nominal_resolution":"100 km"
                },
                "ocnBgchem":{
                    "description":"Canadian Ocean Ecosystem (CanOE) with OMIP prescribed carbon chemistry",
                    "native_nominal_resolution":"100 km"
                },
                "seaIce":{
                    "description":"LIM2",
                    "native_nominal_resolution":"100 km"
                }
            },
            "release_year":"2019",
            "source_id":"CanESM5-CanOE"
        },

**Comment by durack1** [comment]
@slavakharin your registration is complete - please take a peek at [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know of any further tweaks - I do wonder whether `CanOE` for e.g. has a version identifier
