### ISSUE TITLE
institution_id.html default table length

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#658]
I would like to change the default table length in CMIP6_institution_id.html from 10 to 50.  I don't want anyone to miss that there are many more than 10 groups.

This can apparently be easily done by adding ``data-page-length='50'`` to ``<table id="table_id" class="display">``, so that it reads:
```
<table id="table_id" class="display" data-page-length='50'>
```
IF that is o.k., how do I do it?

**Comment by durack1** [comment]
@taylor13 this is set by default in the jquery.dataTables-1.10.13.min.js file (in the src) subdir, and currently the 10 default is set for all the html files. Changing this would impact all entries source_id, institution_id and experiment_id

**Comment by durack1** [comment]
@taylor13 take a peek at https://datatables.net/download/index to figure out how to drive a change

**Comment by taylor13** [comment]
According to https://datatables.net/reference/option/pageLength , we should edit https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/src/json_to_html.py and in line 32 replace 
```
 $('#table_id').DataTable();
```
with
```
  $('#example').dataTable( {
  "pageLength": 50
} );
```
You can also change the menu of page length options (see https://datatables.net/reference/option/lengthMenu):
```
$('#example').dataTable( {
  "pageLength": 50,
  "lengthMenu": [ [10, 25, 50, -1], [10, 25, 50, "All"] ]
} );
```

**Comment by durack1** [comment]
@taylor13 as this doesn't impact the versioning code feel free to make the change in the browser, next time the code is run the json_to_html.py will be called and we'll see if the change is made

**Comment by durack1** [comment]
@taylor13 this change broke the html, so will revert

**Comment by taylor13** [comment]
might need the latest version of "datatables".  I noticed there was slightly different syntax used for a legacy version.

**Comment by durack1** [comment]
@taylor13 I tried and failed with your edits. The sources are up-to-date, but the syntax to change defaults to 50 still eludes me, reopen if you want to continue to persist with this edit
