### ISSUE TITLE
institution_id registration of CCCma (revised)

### ISSUE THREAD

**Issue by slavakharin** [WCRP-CMIP/CMIP6_CVs#662]
institution_id = CCCma
institution = Canadian Centre for Climate Modelling and Analysis, Environment and Climate Change Canada, Victoria, BC V8P 5C2, Canada

**Comment by durack1** [comment]
@slavakharin this change is now in place, see [CMIP6_institution_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_institution_id.html)
