### ISSUE TITLE
experiment_id: Correction to 3 geoMIP experiment parents and start years

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#665]
Ben Kravitz has approved the following changes to experiment_id info. associated with 3 experiments: G6solar, G6sulfur, and G7cirrus.

For each of these replace `parent_experiment_id="historical"` with `parent_experiment_id="ssp585"` and replace start_year of 2015 with 2020.

**Comment by durack1** [comment]
These changes are now in place, please take a peek at [CMIP6_experiment_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html) and let us know of any further tweaks required

@taylor13 @glevava @bkravitz

**Comment by bkravitz** [comment]
I think it looks good.  Thanks for your help!
