### ISSUE TITLE
CNRM-CM6-1  & CNRM-CM6-1-HR source_ids --- add OMIP

### ISSUE THREAD

**Issue by mpmoine** [WCRP-CMIP/CMIP6_CVs#668]
@durack1
Dear Paul, 

Would you mind adding OMIP in the list of activity_participation for CNRM-CM6-1 and CNRM-CM6-1-HR source_ids ? We just found it was missing in CMIP6_source_id.json (master branch).

Thanks,
Marie-Pierre (for CNRM-CERFACS group)

**Comment by durack1** [comment]
@mpmoine that change is now implemented, please take a peek at [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know of any further issues to resolve
