### ISSUE TITLE
omip2-spinup requires a BGC component

### ISSUE THREAD

**Issue by charliepascoe** [WCRP-CMIP/CMIP6_CVs#670]
The "required realm" for the omip2-spinup experiment is "OGCM" with optional "BGC".
However, I think that the omip2-spinup experiment specification should also require that the model have a bio-geo-chemistry component.
The OMIP companion paper Orr et al (2017) says that the spin-up experiment "is only for OMIP-BGC groups."  
https://www.geosci-model-dev.net/10/2169/2017/gmd-10-2169-2017.pdf 

For context see Martin's issue on Realms and model configurations 
https://github.com/ES-DOC/esdoc-docs/issues/272

**Comment by durack1** [comment]
@charliepascoe thanks for pointing this out. I believe it's both [`omip1-spunup`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json#L5538-L5564) and [`omip2-spunup`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json#L5592-L5618) experiments that require this, but will defer to @jamesorr and @stephengriffies to confirm

**Comment by jamesorr** [comment]
Yes, the _omip1-spunup_ and _omip2-spunup_ experiments should both have ocean BGC output, as specified in Orr et al. (2017).
