### ISSUE TITLE
RFMIP simulations need BGC

### ISSUE THREAD

**Issue by charliepascoe** [WCRP-CMIP/CMIP6_CVs#671]
Ten of the RFMIP experiments require that the models have interactive vegetation.  
However the CMIP6 CV lists the "required realm" for the experiments as AGCM only.
I think these experiments also require a BGC component if they are to have the capacity for interactive vegetation. 
This applies to experiments listed in Tables 1 and 2 of https://www.geosci-model-dev.net/9/3447/2016/gmd-9-3447-2016.pdf
namely:
piClim-control
piClim-anthro
piClim-ghg
piClim-aerO3
piClim-lu
piClim-4xCO2
piClim-histall
piClim-histnat
piClim-histghg
piClim-histaerO3

For context see https://github.com/ES-DOC/esdoc-docs/issues/272

**Comment by taylor13** [comment]
I have reviewed the GMD paper where it says:  
```
Land-surface  models  including  interactive  vegetation,  if
available, should be applied as in other CMIP integrations.
```
"if available" sounds like it is *not* a requirement.

Also, in general, interactive vegetation may or may not include keeping track of the carbon.  A BGC component is defined in  https://goo.gl/v1drZl  :
```
BGC (for a model component that includes a biogeochemical treatment which  at the very 
least can account for carbon reservoirs and fluxes in the atmosphere, terrestrial biosphere, 
and ocean; for some model configurations, only part of the BGC component will be active.  
For example, in a BGC model coupled to an AGCM, the ocean component of the BGC might 
be inactive, but the source_type would be “AGCM BGC”.   For a BGC model run coupled to 
an AOGCM, the source_type should include “AOGCM BGC”  both when atmospheric 
concentrations are calculated and when they are  prescribed),
```
Vegetation can respond to temperature, humidity, etc., for example opening and closing of stomata (which affects evapotranspiration and other things) without keeping track of the carbon fluxes.  Thus, this would be "interactive vegetation".

**Comment by durack1** [comment]
@charliepascoe @taylor13 should this be closed? There would seem to be no need for any changes, as many physical modeling systems include the interactive vegetation as part of the land model, which is not explicitly BGC?

**Comment by charliepascoe** [comment]
Thanks for looking into this.  
I'm happy to close with no further action.

**Comment by durack1** [comment]
@charliepascoe thanks for cleaning up.
