### ISSUE TITLE
source_id registration for GFDL models used in RFMIP, GFDL-GRTCODE, GFDL-RFM-DISORT , GFDL-GLOBAL-LBL

### ISSUE THREAD

**Issue by aradhakrishnanGFDL** [WCRP-CMIP/CMIP6_CVs#673]
As part of GFDLs contribution to RFMIP we need to perform runs with Radiation models that are district (and much simpler) from the GFDL GCMs.  With input from David Painter and Jasmin at GFDL, I am submitting a request to add 3 source configurations to support this. 

"GFDL_RFM_DISORT":{
                "activity_participation":[
                    "RFMIP"
                ],
                "cohort":[
                    "Registered"
                ],
             "institution_id":[
             "NOAA-GFDL"
             ],
             "label" : "GFDL_RFM_DISORT",
              "label_extended": "GFDL Reference Forward Model Line-by-Line with DISORT solver (March 2019)",
"model_component":{
"aerosol":{
"description":"none",
"native_nominal_resolution":"none"
},
"atmos":{
"description":"none",
"native_nominal_resolution":"none"
},
"atmosChem":{
"description":"none",
"native_nominal_resolution":"none"
},
"land":{
"description":"none",
"native_nominal_resolution":"none"
},
"landIce":{
"description":"none",
"native_nominal_resolution":"none"
},
"ocean":{
"description":"none",
"native_nominal_resolution":"none"
},
"ocnBgchem":{
"description":"none",
"native_nominal_resolution":"none"
},
"seaIce":{
"description":"none",
"native_nominal_resolution":"none"
},
“release_year”:”2019”,
                "source_id":"GFDL_RFM_DISORT"
},

            "GFDL-GRTCODE ":{
                "activity_participation":[
                    "RFMIP"
                ],

                "cohort":[
                    "Registered"
                ],
                "institution_id":[
                    "NOAA-GFDL"
                ],
 "label":GFDL-GRTCODE,
 "label_extended":"GFDL GPU radiative transfer code with two stream solver (March 2019)",
"model_component":{
"aerosol":{
"description":"none",
"native_nominal_resolution":"none"
},
"atmos":{
"description":"none",
"native_nominal_resolution":"none"
},
"atmosChem":{
"description":"none",
"native_nominal_resolution":"none"
},
"land":{
"description":"none",
"native_nominal_resolution":"none"
},
"landIce":{
"description":"none",
"native_nominal_resolution":"none"
},
"ocean":{
"description":"none",
"native_nominal_resolution":"none"
},
"ocnBgchem":{
"description":"none",
"native_nominal_resolution":"none"
},
"seaIce":{
"description":"none",
"native_nominal_resolution":"none"
},
“release_year”:”2019”,
                "source_id":"GFDL_GRTCODE",
                            },

            "GFDL-GLOBAL-LBL":{
                "activity_participation":[
                    "RFMIP"
                ],
                "cohort":[
                    "Registered"
                ],
                "institution_id":[
                    "NOAA-GFDL"
                ],
 "label":"GFDL-GLOBAL-LBL",
 "label_extended":"GFDL  Reference Forward Model Line-by-Line with DA/DISORT solver  (March 2019)",
"model_component":{
"aerosol":{
"description":"none",
"native_nominal_resolution":"none"
},
"atmos":{
"description":"none",
"native_nominal_resolution":"none"
},
"atmosChem":{
"description":"none",
"native_nominal_resolution":"none"
},
"land":{
"description":"none",
"native_nominal_resolution":"none"
},
"landIce":{
"description":"none",
"native_nominal_resolution":"none"
},
"ocean":{
"description":"none",
"native_nominal_resolution":"none"
},
"ocnBgchem":{
"description":"none",
"native_nominal_resolution":"none"
},
"seaIce":{
"description":"none",
"native_nominal_resolution":"none"
},
“release_year”:”2019”,
"source_id":"GFDL-GLOBAL-LBL",
                            }

**Comment by durack1** [comment]
@aradhakrishnanGFDL thanks those `source_id` entries are now registered. Just FYI, the `GFDL_RFM_DISORT` was corrected to `GFDL-RFM-DISORT` (underscores replaced with hyphens) as we don't allow spaces or underscores in the model names. Take a peek at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know of any tweaks required
