### ISSUE TITLE
source_id -- please modify "natNomRes atmos" of MIROC*

### ISSUE THREAD

**Issue by tinoue70** [WCRP-CMIP/CMIP6_CVs#675]
We have checked `native_nominal_resolution` for `atmos` of our models and found mistakes.

Please modify as follows:

- MIROC-ES2H : 100 km -> 250 km 
- MIROC-ES2L : 250 km -> 500 km
- MIROC6 : 100 km -> 250 km

Thanks in advance.

**Comment by taylor13** [comment]
thanks, @tinoue70, for taking care of this detail.  Much appreciated!  
 It may be a few weeks before it is reflected in the CV's.  Let me know if that will be a problem for you.

**Comment by durack1** [comment]
@tinoue70 apologies for the delay in getting these details updated. Your registrations are now revised, please take a look at [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let us know if any further changes are required
