### ISSUE TITLE
RFMIP experiments description to be updated

### ISSUE THREAD

**Issue by chrisroadmap** [WCRP-CMIP/CMIP6_CVs#676]
Following confusion from some modelling groups I am requesting that ES-Doc, the CMIP6 CV, and the RFMIP website (https://rfmip.leeds.ac.uk) are all made consistent. Therefore I am wondering if changes below can be incorporated:

In https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html

- *piClim-control* -- experiment: effective radiative forcing in **pre-industrial** (note: I do not know if the AerChemMIP protocol is pre-industrial or present-day)
- *piClim-anthro* -- description: As in **piClim-control** but with present-day anthropogenic forcing (greenhouse gases, **ozone,** aerosols and land-use)
- *piClim-ghg* -- description: As in **piClim-control** but with present-day **non-ozone** greenhouse gases
- *piClim-4xCO2* -- description: As in **piClim-control** but with 4xCO2
- *piClim-lu* -- description: As in **piClim-control** but with present-day land use
- *piClim-aer* -- description: As in **piClim-control** but with with present-day aerosols. Note that this experiment is considered to be tier 1 by RFMIP but tier 2 by AerChemMIP
- *piClim-histghg* -- description: Time-varying forcing by **non-ozone** GHGs. SST and sea ice fixed at preindustrial control. Interactive vegetation
- *piClim-SpAer-aer* -- description: *Delete "and ozone"*
- *piClim-SpAer-histaer* -- description: *Delete "and ozone"*
- *piClim-SpAer-histall* -- description: Prescribed anthropogenic aerosol optical properties. **All anthropogenic and natural** forcings

**Comment by taylor13** [comment]
@chrisroadmap  @martinjuckes  I will reviewing the above and possibly iterate with you starting Tuesday when I return from vacation.  Have you emailed the folks at ES-DOC  ( support@es-doc.org) requesting changes there?  I think they have additional information that needs correction or clarification.  Thanks.

**Comment by chrisroadmap** [comment]
Yes, we've made ES-Doc aware.

**Comment by taylor13** [comment]
@chrisroadmap : 
I think a better name of the piClim-control experiment is: "Control simulation providing baseline for evaluating effective radiative forcing (ERF)."  Do you agree?

The other changes I think are improvements (and also corrections of some errors).  Thank you for that.

Please let us know if we can use the piClim-control experiment words just above.

**Comment by chrisroadmap** [comment]
Yes, completely agree with this proposed change to piClim-control: it's not the pre-industrial forcing, of course.

**Comment by taylor13** [comment]
Final list of changes ready to be implemented:

    piClim-control -- experiment: control simulation providing baseline for evaluating effective radiative forcing (ERF)
    piClim-anthro -- description: As in piClim-control but with present-day anthropogenic forcing (greenhouse gases, ozone, aerosols and land-use)
    piClim-ghg -- description: As in piClim-control but with present-day non-ozone greenhouse gases
    piClim-4xCO2 -- description: As in piClim-control but with 4xCO2
    piClim-lu -- description: As in piClim-control but with present-day land use
    piClim-aer -- description: As in piClim-control but with with present-day aerosols. Note that this experiment is considered to be tier 1 by RFMIP but tier 2 by AerChemMIP
    piClim-histghg -- description: Time-varying forcing by non-ozone GHGs. SST and sea ice fixed at preindustrial control. Interactive vegetation
    piClim-SpAer-aer -- description: Delete "and ozone"
    piClim-SpAer-histaer -- description: Delete "and ozone"
    piClim-SpAer-histall -- description: Prescribed anthropogenic aerosol optical properties. All anthropogenic and natural forcings

**Comment by durack1** [comment]
@chrisroadmap @taylor13 note the `piClim-spAer-*` experiments do not have an upper-case `*SpAer*` rather than are `*spAer*`. I am not changing this case

**Comment by durack1** [comment]
@chrisroadmap those edits are now in place, take a peek at [CMIP6_experiment_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html) and let us know of any further tweaks required

**Comment by charliepascoe** [comment]
I have just adapted the description updates into the ES-DOC database.

**Comment by chrisroadmap** [comment]
@durack1 This looks good to me, thanks.

**Comment by durack1** [comment]
@chrisroadmap it appears that a `piClim-histlu` was another experiment that some email discussion back in May 2019 mentioned, but it never made it into a formal request or issue in this repo - did you guys want to add this additional?

ping @RobertPincus @martinjuckes @taylor13

**Comment by chrisroadmap** [comment]
Assuming that this gets the nod from @RobertPincus:

Experiment description: An uncoupled (atmosphere and land) experiment with interactive vegetation in which sea surface temperatures (SST) and sea ice concentrations (SIC) are fixed at model-specific pre-industrial control climatology. Transient land-use change to be consistent with historical forcing used in the DAMIP hist-all experiment and future land-use forcing to be consistent with the ScenarioMIP SSP2 RCP4.5 scenario forcing. Other forcings to be kept at pre-industrial. A small ensemble of three simulations from 1850-2100.
Start year: 1850
Duration: 251 years (until 2100)
Ensemble size: 3

I wonder if there's an inconsistency here in some models between specifying the land use dataset and allowing vegetation to vary interactively. This protocol is specified for the `piClim-lu` time slice Tier 1 experiment, so perhaps it is not an issue.

**Comment by taylor13** [comment]
Additional information will be needed, similar to:
```
        "piClim-histaer":{
            "activity_id":[
                "RFMIP"
            ],
            "additional_allowed_model_components":[
                "AER",
                "CHEM",
                "BGC"
            ],
            "description":"Time-varying forcing by aerosols. SST and sea ice fixed at preindustrial control. Interactive vegetation",
            "end_year":"2100",
            "experiment":"transient effective radiative forcing by aerosols",
            "experiment_id":"piClim-histaer",
            "min_number_yrs_per_sim":"251",
            "parent_activity_id":[
                "CMIP"
            ],
            "parent_experiment_id":[
                "piControl"
            ],
            "required_model_components":[
                "AGCM"
            ],
            "start_year":"1850",
            "sub_experiment_id":[
                "none"
            ],
            "tier":"2"
},
```

**Comment by RobertPincus** [comment]
After some discussions between LUMIP, AerChemMIP, and RFMIP it seems that AerChemMIP will likely propose a piClim-HistNoLU instead. Let’s wait a few days for the dust to settle and Bill Collins to reply to emails but I think this aspect of #676 can be considered resolved.

**Comment by durack1** [comment]
As noted by @RobertPincus this issue can be closed - resolved
