### ISSUE TITLE
experiment_id additional C4MIP experiments registered

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#679]
Chris Jones has submitted seven additional tier2 and tier3 experiments.  see  https://docs.google.com/document/d/1ctqge_WS-KMQKbRbFVx8K9PbV_KiLgPnDTVnRYGBniw/edit

**Comment by durack1** [comment]
@taylor13 those changes are now in place, take a peek at [CMIP6_experiment_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html) which now includes 294 experiments

**Comment by taylor13** [comment]
looks good to me.
