### ISSUE TITLE
source_id -- add ScenarioMIP to HadGEM3-GC31-LL & -MM

### ISSUE THREAD

**Issue by matthew-mizielinski** [WCRP-CMIP/CMIP6_CVs#699]
Could `ScenarioMIP` be added to the `activity_participation` listfor the `HadGEM3-GC31-LL` and `HadGEM3-GC31-MM` source_ids. 

Python code that would make the change
```
source_id = json.load(open('CMIP6_source_id.json'))
source_id['source_id']['HadGEM3-GC31-LL']['activity_participation'].append('ScenarioMIP')
source_id['source_id']['HadGEM3-GC31-MM']['activity_participation'].append('ScenarioMIP')
```

**Comment by durack1** [comment]
@matthew-mizielinski thanks for the request, that's now done, see [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) to double check.

This change will be synced into the [cmip6-cmor-tables](https://github.com/PCMDI/cmip6-cmor-tables/) overnight (PDT time)

**Comment by matthew-mizielinski** [comment]
> @matthew-mizielinski thanks for the request, that's now done, see [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) to double check.
> 
> This change will be synced into the [cmip6-cmor-tables](https://github.com/PCMDI/cmip6-cmor-tables/) overnight (PDT time)

Marvellous, thanks.
