### ISSUE TITLE
source_id registration of MRI-AGCM3-2-H and 

### ISSUE THREAD

**Issue by ryo-mizuta** [WCRP-CMIP/CMIP6_CVs#707]
I want to register MRI-AGCM3-2-H as below. 
Additionally, is it possible to change the existing id of MRI-AGCM3-2 to  MRI-AGCM3-2-S for consistency of naming ? (or maybe register MRI-AGCM3-2-S and remove MRI-AGCM3-2) No data of MRI-AGCM3-2 has been uploaded to ESGF yet.

label = MRI-AGCM3-2-H
label_extended = MRI-AGCM3-2-H
source_id = MRI-AGCM3-2-H
institution_id = MRI
release_year = 2017
activity_participation = [DynVarMIP, HighResMIP]

aerosol:
description = Prescribed from MRI-ESM2.0
nominal_resolution = 250 km
atmos:
description = MRI-AGCM3.2H (TL319; 640 x 320 longitude/latitude; 64 levels; top level 0.01 hPa)
nominal_resolution = 50 km
atmosChem:
description = none
nominal_resolution = none
land:
description = SIB0109
nominal_resolution = 50 km
landIce:
description = none
nominal_resolution = none
ocean:
description = none
nominal_resolution = none
ocnBgchem:
description = none
nominal_resolution = none
seaIce:
description = none
nominal_resolution = none

**Comment by durack1** [comment]
@ryo-mizuta those changes are now in place. I note that you have not included `CMIP` as an activity you are participating in (the DECK experiments, piControl, historical etc). If this is incorrect, please let me know and we can revise the registration. Please take a look at [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further changes are required

**Comment by ryo-mizuta** [comment]
@durack1 Thank you !
