### ISSUE TITLE
parent experiment id -- C4MIP ssp534-over-bgc initialisation discrepancy

### ISSUE THREAD

**Issue by charliepascoe** [WCRP-CMIP/CMIP6_CVs#708]
The C4MIP GMD paper indicates that ssp534-over-bgc be initialised from ssp585-bgc in the year 2040.  However the CMIP6-CV indicates that this experiment be initialised from hist-bgc in the year 2015.  The ES-DOC description has this experiment being initialised from ssp585-bgc in the year 2040.

See table 1 in the C4MIP GMD paper
https://www.geosci-model-dev.net/9/2853/2016/gmd-9-2853-2016.pdf

**Comment by MartinaSt** [comment]
@charliepascoe Do you know the C4MIP project page? http://c4mip.net . Maybe it is worthwhile to check the information there as well.

**Comment by charliepascoe** [comment]
Thanks @MartinaSt, the C4MIP project page also indicates that ssp534-over-bgc be initialised in 2040.
http://c4mip.net/index.php?id=3455

**Comment by ChrisJones-MOHC** [comment]
Hi - the C4MIP experiments here are intended to be parallel to the ScenarioMIP ssp ones. So I think the parent should mirror that - how does the ssp534 appear? I assume it branches from ssp585 at 2040 and not goes back to 2014 to restart from historical. In practice model groups will branch at 2040 because there's no point repeating teh same portion of run - the forcing is the same in ssp534 and ssp585 up to 2040

**Comment by taylor13** [comment]
@ChrisJones-MOHC  
Yes, I'm not sure why we failed to notice ssp534-over-bgc had the same problem as esm-ssp534-over, which was addressed in https://github.com/WCRP-CMIP/CMIP6_CVs/issues/607. 

We should change the entry for ssp534-over-bgc as follows:
parent experiment: ssp585-bgc
start year: 2040
minimum number of years simulated: 61

[To be sure:  this should branch at the beginning of 2040 from ssp585-bgc, not from ssp585.

**Comment by ChrisJones-MOHC** [comment]
yes - thanks Karl @taylor13 that's right. This is the "bgc" coupled set of runs to complement the scenarioMIP runs. So ssp534-over-bgc branches off ssp585-bgc at 2040

**Comment by durack1** [comment]
@ChrisJones-MOHC thanks for the clarification, the details should now be corrected, please take a peek at [CMIP6_experiment_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html) and let us know of any further inconsistencies that need to be ironed out

@charliepascoe @MartinaSt @taylor13 ping

**Comment by ChrisJones-MOHC** [comment]
thanks Paul - looks good to me
