### ISSUE TITLE
parent experiment id -- CFMIP initialisation discrepancies

### ISSUE THREAD

**Issue by charliepascoe** [WCRP-CMIP/CMIP6_CVs#709]
There are some initialisation discrepancies for the following CFMIP experiments, in some cases the CMIP6-CV, ES-DOC and CFMIP GMD information are all different.

CFMIP experiment name | CMIP6-CV parent experiment id | ES-DOC is_initialized_by | CFMIP GMD start year
-- | -- | -- | --
piSST | piControl | no parent | year 111 of abrupt-4xCO2
piSST-pxK | piControl | no parent | year 111 of abrupt-4xCO2
piSST-4xCO2-rad | piControl | no parent | year 111 of abrupt-4xCO2
piSST-4xCO2 | piControl | no parent | year 111 of abrupt-4xCO2
a4SST | abrupt-4xCO2 | no parent | year 111 of abrupt-4xCO2
a4SSTice | abrupt-4xCO2 | no parent | year 111 of abrupt-4xCO2
a4SSTice-4xCO2 | abrupt-4xCO2 | no parent | year 111 of abrupt-4xCO2

See table 2 of https://www.geosci-model-dev.net/10/359/2017/gmd-10-359-2017.pdf

**Comment by taylor13** [comment]
We will need Mark Webb's input here.  I *think* the piSST simulations need to be initialized from the *piControl* run not the abrupt-4xCO2 run.  Ideally these runs would be spawned from the point in the piControl run that is 111 years after the initialization date of the abrupt-4XCO2.  If the atmosphere were initialized from year 111 of abrupt-4XCO2 run, the "fast" responses of the climate system to the various imposed forcing changes (e.g. abrupt increase of 4xCO2 in the piSST-4xCO2 experiment) would largely be obscured.

For the A4SST simulations, I'm not sure whether the atmosphere should be initialized from the piControl (as in the previous paragraph) or from abrupt-4xCO2.

I'll Write Mark and ask him to advise.

Note:  The parent experiment serves to initialize the atmosphere in these prescribed SST experiments.  It *doesn't* indicate where the SSTs come from.

**Comment by RobChadwick** [comment]
My intention was for the piSST and a4SST experiments to all be initialised from piControl, apologies for the confusion in the documentation.

Note also that we didn't explicitly specify a spin-up period for these experiments, but I plan to include a 3 year spin-up period for each experiment with HadGEM3, so I will initialise with year 108 of piControl in each case.

**Comment by taylor13** [comment]
@RobChadwick I haven't thought about this extensively, and I'm not completely familiar with the objectives of these experiments, but during the spin-up period do you specify the piControl SSTs or the 4xCO2 SSTs?  I presume the piControl SSTs, yes?

In either case, I think we need the following changes to the experiment_id CV:

For experiments a4SST, a4SSTice, and A4SSTice-4xCO2:
parent_experiment_id: piControl
parent_activity_id: CMIP

**Comment by RobChadwick** [comment]
@taylor13 There isn't any intention to look at the transient adjustment to forcing in these experiments, so the initial conditions should be unimportant as long as a spin-up period is applied. In order to properly spin-up each experiment I think it would be best to use piControl SSTs during spin-up for the piSST experiments and abrupt4xCO2 SSTs during spin-up for the a4SST experiments.

In fact, I don't see any problem with the a4SST experiments being initialised from abrupt4xCO2, so perhaps we can just leave the experimental protocol as it is, do you see any issues with that? My original thinking behind initialising all experiments with piControl was just to keep it simple.

**Comment by taylor13** [comment]
@RobChadwick -- I agree that if you don't care about the initial radiative responses (e.g., tropospheric "adjustment"), then where the initial conditions are gotten probably doesn't matter (but we shouldn't forget that in some models "soil moisture" has important effects and relatively long time constants).

When you suggest we might "leave the experimental protocol as it is", are you referring to column 2 or column 3 in the above table (https://github.com/WCRP-CMIP/CMIP6_CVs/issues/709#issue-452457022)?  That is, shall we declare these experiments as having "no parent" as in the CV?  That would be fine if that's what you want.  (It would also be o.k. to specify how you want to intitialize the simulations, but then for each experiment you'd have to decide between piControl and abrupt-4xCO2; different parents could apply to different experiments, as in column 3.)  I would lean toward "no parent", and leave initialization up to the modeling groups.

**Comment by RobChadwick** [comment]
@taylor13 I've been in touch with my co-lead on these experiments, Hervé Douville, and in fact he initialised his runs (with CNRM-CM6) from amip, with a spin-up period. So I think the best option is to have "no parent" as you suggest, and leave initialisation at the discretion of each group.

**Comment by taylor13** [comment]
Thanks. We can now proceed.  It looks like there is no need to modify the CV, but @charliepascoe will have to modify the ES-DOC descriptions.  I'll close this.

**Comment by taylor13** [comment]
Paul noticed I was confused.  The ES-DOC descriptions are already correct, and it is the CV that needs editing:  For the experiments listed in the table above (https://github.com/WCRP-CMIP/CMIP6_CVs/issues/709#issue-452457022), the parent_experiment_id should be set to "no parent", and the parent_activity_id should be set to "no parent".

**Comment by durack1** [comment]
@RobChadwick those changes are now in place. Please review the updated details at [CMIP6_experiment_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html) and let us know of any other tweaks required

@charliepascoe ping

**Comment by RobChadwick** [comment]
Thanks @durack1 and @taylor13, that all looks fine to me now.
