### ISSUE TITLE
parent experiment id -- GeoMIP timeslice experiments

### ISSUE THREAD

**Issue by charliepascoe** [WCRP-CMIP/CMIP6_CVs#710]
There are initialisation discrepancies between CMIP6-CV and ES-DOC for the GeoMIP timeslice experiments G6SST2-sulfur (G6SulfurSlice2), G6SST2-solar (G6SolarSlice2) and G7SST2-cirrus (G7CirrusSlice2) which take place in year 2100 of G6sulfur, G6solar and G7cirrus.

GeoMIP experiment | CMIP6-CV parent experiment id | ES-DOC is_initialized_by | GeoMIP GMD
-- | -- | -- | --
G6SST2-sulfur (G6SulfurSlice2) | ssp585 | G6sulfur | "Each Tier 1 experiment will have two associated time-slice simulations, one at the beginning of the coupled simulation and one at the end."
G6SST2-solar (G6SolarSlice2) | ssp585 | G6solar | ditto |
G7SST2-cirrus (G7CirrusSlice2) | ssp585 | G7cirrus | ditto |

I think the description of these second timeslice experiments in section 3.1 of the GeoMIP GMD paper implies that the simulations should be taken from the end of experiments: G6sulfur, G6solar and G7cirrus and not from ssp585.

**Comment by taylor13** [comment]
Haven't looked at it yet, but we should note that Ben Kravitz, leader of GeoMIP, sent this email out yesterday:

"I'm getting a couple of inquiries about G6solar and G6sulfur.  The specifications document that I sent around a few months ago is now online:
http://climate.envsci.rutgers.edu/GeoMIP/doc/G6specs.docx "

**Comment by taylor13** [comment]
I will alert Ben Kravitz to check this, but I think that the ES-DOC parent experiment is correct (and the CV is wrong).  I also noticed that some of the parent activities are wrong in the CV.  If Ben concurs, I think we need to make the following changes to the CV:

For G6SST2-sulfur
parent experiment id: G6sulfur
parent activity id: GeoMIP

For G6SST2-solar
parent experiment id: G6solar
parent activity id: GeoMIP

For G7SST2-cirrus
parent experiment id: G7cirrus
parent activity id: GeoMIP

For G6sulfur, G6solar, and G7cirrus
parent activity id: ScenarioMIP  (not CMIP)

**Comment by bkravitz** [comment]
I concur with @charliepascoe 's assessment and with @taylor13 's suggested changes.  I'll admit I'm not entirely sure what "parent activity id" is supposed to do, so I'm trusting you on that one.

**Comment by durack1** [comment]
@bkravitz thanks for confirming. Those changes are now in place, take a peek at [CMIP6_experiment_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html) and let me know if anything else needs tweaking

@charliepascoe @taylor13 ping
