### ISSUE TITLE
SOURCE_ID registration subtitution of BESM 2.7 to BESM 2.9

### ISSUE THREAD

**Issue by andrelanfer** [WCRP-CMIP/CMIP6_CVs#711]
We updated our model to an operational version, with so, our model new name is BESM 2.9 instead of BESM2.7. It is possible to re-generated with this final version?

Thanks in advance,
andre

 "BESM-2-9":{
            "activity_participation":[
                "CMIP",
                "DCPP",
                "ScenarioMIP"
            ],
            "cohort":[
                "Registered"
            ],
            "institution_id":[
                "INPE"
            ],
            "label":"BESM 2.9",
            "label_extended":"BESM 2.9",
            "model_component":{
                "aerosol":{
                    "description":"none",
                    "native_nominal_resolution":"none"
                },
                "atmos":{
                    "description":"BAM (v1.0, T062L42; 192 x 96 longitude/latitude; 42 levels; top level 3 hPa)",
                    "native_nominal_resolution":"250 km"
                },
                "atmosChem":{
                    "description":"none",
                    "native_nominal_resolution":"none"
                },
                "land":{
                    "description":"SSiB 2.0",
                    "native_nominal_resolution":"250 km"
                },
                "landIce":{
                    "description":"none",
                    "native_nominal_resolution":"none"
                },
                "ocean":{
                    "description":"MOM-5 (MOM5, tripolar, primarily 1 deg, 1/4 deg between 22.5S-22.5N, downgrading from 1/4 deg at 22.5N(S) to  1 deg at 45N(S), 1 deg between 22.5N(S) and 45N(S), upgrading from 1 deg at 45N(S) to 0.5 deg at 90N(S)   ; 360 x 192 longitude/latitude; 50 levels; top grid cell 0-10 m)",
                    "native_nominal_resolution":"100 km"
                },
                "ocnBgchem":{
                    "description":"TOPAZ 2.0",
                    "native_nominal_resolution":"100 km"
                },
                "seaIce":{
                    "description":"SIS 1.0",
                    "native_nominal_resolution":"100 km"
                }
            },
            "release_year":"2019",
            "source_id":"BESM-2-9"

**Comment by durack1** [comment]
@andrelanfer thanks, those changes are now in place. Please review [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know of any further tweaks required
