### ISSUE TITLE
DCPP controlled volcabulary for sub-experiment-id missing experiments

### ISSUE THREAD

**Issue by epitome76** [WCRP-CMIP/CMIP6_CVs#716]
Activity DCPP has experiment dcppA-hindcast which currently (6.2.24.1) has sub-experiment-ids s1960..s2016. The DCPP paper in Geosci Model Dev says there should be 60 sub-experiments (Tabel A1). Hence, s2017, s2018 and s2019 should also be included in the allowed values for sub-experiment-id.

@DougSmithMO, co-author of the DCPP paper, agrees.

**Comment by taylor13** [comment]
@epitome76 @DougSmithMO -- Thanks for bringing this to our attention.  I presume s2019 can't be initialized from observations until later this year.  Also, should the dcppA-hindcast-niff (A4.1) and dcppA-historical-niff (A4.2) also include sub-experiments s2017, s2018, and s2019?

@charliepascoe  Will these changes be a problem on your end?

**Comment by epitome76** [comment]
Yes, I'd say dcppA-hindcast-niff (A4.1) and dcppA-historical-niff (A4.2) should also be allowed to have sub-experiment-ids with values s2017, s2018 and s2019. 

I'm guessing not all groups will run s2019 and those that do, it will be later in this year.

**Comment by taylor13** [comment]
So in summary:  for dcppA-hindcast, dcppA-hindcast-niff, and dcppA-historical-niff, add sub-experioments s2017, s2018, and s2019.

**Comment by durack1** [comment]
@epitome76 @DougSmithMO those changes are now in place. Please review the updated details at [CMIP6_experiment_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html) and let us know of any other tweaks required

@charliepascoe ping
