### ISSUE TITLE
Add s1920 sub_experiment_id

### ISSUE THREAD

**Issue by glevava** [WCRP-CMIP/CMIP6_CVs#720]
Hi @durack1 here is a copy of an email sent in January about dcppC sub-experiment IDs:

"In the final version of the article describing the DCCP protocol (https://pure.mpg.de/rest/items/item_2365756_6/component/file_2365767/content) we can read "Experiments should cover the period from 1950 to 2014, but starting from 1910 is desirable if possible."
This requirement has changed from an old version of the article where it was "starting from 1920 is desirable".

Unfortunately, we run IPSL-CM pacemaker experiments from 1920 to 2014 and PrePARE complains because the sub_experiment_id is not properly set.

Our understanding is that 1950-2014 is the shortest period to cover and starting before 1950 is more like a nice to have. If this is right, could it possible to update the WCRP JSON files accordingly (at least by adding "s1920" as allowed sub_experiment_id)"

This was approved by @taylor13, would it be possible to update the CMIP6_sub_experiment_id.json accordingly?

Many thanks !

**Comment by durack1** [comment]
@glevava thanks for raising this, it's not completely clear what change you are recommending.

The DCPP activity_id includes 26 separate experiments, and there are two identified "pacemaker" experiments, both `dcppC-atl-pacemaker` and `dcppC-pac-pacemaker` and both include sub_experiment_id of s1910, s1920, s1950.

Can you be more clear as to what change is required?

**Comment by glevava** [comment]
@durack1 Yes you're right but the "CMIP6_sub_experiment_id.json" should also have `"s1920":"initialized near end of year 1920",`. Thus the `s1920` value will be propagated to the `esg.cmip6.ini` that is not currently the case.

**Comment by durack1** [comment]
@glevava I see what you mean, so `CMIP6_sub_experiment_id.json` needs to be amended to include:
```
{
    "sub_experiment_id":{
        "none":"none",
        "s1910":"initialized near end of year 1910",
+       "s1920":"initialized near end of year 1920",
        "s1950":"initialized near end of year 1950",
...
```
That's an easy fix, will do this now

**Comment by glevava** [comment]
Exactly. Thanks !

**Comment by durack1** [comment]
@glevava thanks for raising this, the change is now in place, take a peek at [CMIP6_sub_experiment_id.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_sub_experiment_id.json) and let me know if you see anything else awry
