### ISSUE TITLE
source_id > CNRM-CM6-1 > landice

### ISSUE THREAD

**Issue by mpmoine** [WCRP-CMIP/CMIP6_CVs#723]
@durack1 

Dear Paul,
Sorry to come back late with this issue, but we just realized that CNRM-CM6-1 entry in source_id has a landice component that should not exist (we have no landice model at all, in none of our model configurations).

Consequently, for **"CNRM-CM6-1"** entry, this description:
```
"landIce":{
                    "description":"GRISLI: Collaborating with l'Institut des Geosciences de l'Environnement in Grenoble on offline ice-sheet simulations",
                    "native_nominal_resolution":"10 km"
                },
```
should be replaced by:
```
"landIce":{
                    "description":"none",
                    "native_nominal_resolution":"none"
                },
```
Thanks,
Marie-Pierre (on behalf of the CNRM-CERFACS  group)

**Comment by durack1** [comment]
@mpmoine apologies for the delay. That change is now in place, please take a peek at [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know of any further required tweaks

**Comment by durack1** [comment]
@mpmoine for some reason the HTML representation of the table hasn't updated (see https://github.com/WCRP-CMIP/CMIP6_CVs/issues/726) so rather take a peek at https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L1287-L1348 that will provide the up-to-date registration info
