### ISSUE TITLE
HTML tables are not currently updating

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#726]
`CMIP6_institution_id.html` and `CMIP6_source_id.html` do not appear to be updating - need to check this out

**Comment by durack1** [comment]
This may provide a clue
```
(cdat80py2) bash-3.2$ python json_to_html.py 6.2.30.1
** HTML Write mode -  6.2.30.1  will be written **
None
Traceback (most recent call last):
  File "json_to_html.py", line 115, in <module>
    print >> fo, "<td>%s</td>" % st
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 552: ordinal not in range(128)
```

**Comment by durack1** [comment]
To resolve this issue, some additional checks and reporting will need to be implemented. While this is happening, verifying valid entries of activity and parent* should also be undertaken to ensure the repo is self-consistent

**Comment by matthew-mizielinski** [comment]
I also note that the search box on the experiment_id page has gone (I think it is still there for 6.2.28.0)

**Comment by durack1** [comment]
@matthew-mizielinski thanks, that was the original behavior that tipped me off there was a problem, I think it’s due to an incorrectly written file. When I fix the source of the problem I’m hoping everything is back to normal

**Comment by durack1** [comment]
The offending line is [here](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json#L5796) 
```
...(e.g., 1653 for the 6-cycle simulation) as the\u2018base time\u2019of the time axis...
```

**Comment by durack1** [comment]
@matthew-mizielinski @HiroyukiTsujino that fix is now implemented. Would you both mind taking a peek of [CMIP6_experiment_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html), [CMIP6_institution_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_institution_id.html) and [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) to make sure all the content/html parsing is working correctly?

**Comment by HiroyukiTsujino** [comment]
@durack1 thanks for this. I am fine with the fix. Sorry again for having included non-unicode characters.

**Comment by matthew-mizielinski** [comment]
@durack1 looks good to me.
