### ISSUE TITLE
institution_id registration of CAMS

### ISSUE THREAD

**Issue by camscmip6** [WCRP-CMIP/CMIP6_CVs#728]
Hello,

My colleague Li Jianduo have register our institution on Mar 15 2017.
Here I repeat the information again:

institution_id = CAMS

institution = Chinese Academy of Meteorological Sciences, Beijing 100081, China

Thank you!

Best regards,
Xinayo Rong

**Comment by durack1** [comment]
Hi @camscmip6 we have `CAMS` registered already, see https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_institution_id.json#L8 - as you note this was registered on the 20th March 2017 https://github.com/WCRP-CMIP/CMIP6_CVs/issues/245

For this reason I will close this issue
