### ISSUE TITLE
source_id registration of CAMS-CSM

### ISSUE THREAD

**Issue by camscmip6** [WCRP-CMIP/CMIP6_CVs#729]
Hello,

My colleague Li Jianduo have registered our model CAMS-CSM on Mar 15, 2017, but he missed some MIPs we intent to participate.  Here I modified the information of the CAMS-CSM model as follows:
 
label = CAMS-CSM 1.0
label_extended = CAMS-CSM 1.0
source_id = CAMS-CSM1-0 
institution_id = CAMS
release_year = 2016
activity_participation = [CMIP CFMIP ScenarioMIP HighResMIP GMMIP]

aerosol: 
description = none
nominal_resolution = none

atmos:
description = ECHAM5_CAMS (T106, 320 x 160; 31 levels; top level 10 mb)
nominal_resolution = 100 km

atmosChem:
description = none
nominal_resolution = none

land:
description = CoLM
nominal_resolution = 100 km

landIce:
description = none
nominal_resolution = none 

ocean:
description = MOM4 (tripolar, 360x200, primarily 1deg latitude/longitude, down to 1/3deg within 30deg of the equatorial tropics; 50 levels; top grid cell 0-10 m)
nominal_resolution = 100 km

ocnBgchem:
description = none
nominal_resolution = none

seaIce:
description = SIS1.0
nominal_resolution = 100 km

**Comment by durack1** [comment]
@camscmip6 thanks for this, your new activity_participation is now updated. Take a peek at [CMIP6_source_id.html](rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further tweaks are required
