### ISSUE TITLE
experiment_id -- problem with expt. 1pctCO2Ndep

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#73]
1pctCO2Ndep  --  the BGCM "component" is both "required" and "additional"  find out which if either it should be.

**Comment by durack1** [comment]
@taylor13 who is the contact for this issue - we need input to resolve this

**Comment by taylor13** [comment]
Note that BGCM has been recently changed to "BGC", so the question is for the 1pctCO2Ndep experiment, is the BGC component "required" or "optional"?
thanks.

**Comment by pierrefriedlingstein** [comment]
BGC component is required for the 1pctCO2Ndep. 
BGC component is required for ALL C4MIP experiments
