### ISSUE TITLE
source_id -- add RFMIP to UKESM1-0-LL

### ISSUE THREAD

**Issue by matthew-mizielinski** [WCRP-CMIP/CMIP6_CVs#731]
Our AerChemMIP team would like to submit data for some RFMIP experiments from our UKESM1 model. Could you please add `RFMIP` to the `activity_participation` list for `UKESM1-0-LL`? The following code should make this change;

```
source_id = json.load(open('CMIP6_source_id.json'))
source_id['source_id']['UKESM1-0-LL']['activity_participation'].append('RFMIP')
```

**Comment by durack1** [comment]
@matthew-mizielinski thanks that change is now implemented. Take a peek at [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) which should reflect the recent update
