### ISSUE TITLE
source_id -- fix native_nominal_resolution for submodels using MPIOM GR1.5 

### ISSUE THREAD

**Issue by kwieners** [WCRP-CMIP/CMIP6_CVs#734]
we noticed that the nominal resolution settings in the 'source id' part
of CMIP6 Controlled Vocabulary data are inconsistent among different
users of MPIOM GR1.5, and sometimes not in line with the 'official'
computation.

MPIOM GR1.5 has (by CMIP6 definitions) a native nominal resolution of "250 km",
and so do the dependent 'HAMOCC6' and 'seaIce' models.

Please find attached a patch containing the according changes to CMIP6_source_id.json
These changes are proposed in accordance with the HAMMO
Z Consortium whose source description is also affected.

Thanks for your work,
Karl (for the MPI for Meteorology, Hamburg)

[CMIP6_source_id.json.patch.txt](https://github.com/WCRP-CMIP/CMIP6_CVs/files/3376644/CMIP6_source_id.json.patch.txt)

**Comment by durack1** [comment]
@kwieners thanks for this, it would be more helpful for me if you can indicate which source_id entries require changing, from your patch it would appear that this is two, but without the source_id key and version of the CMIP6_source_id.json file you aimed to patch there is too little information. It also seems you have a release_year update for one of these?

**Comment by kwieners** [comment]
@durack1 Sorry, I forgot to mention the commit hash. But as there already was a new commit on master, and to minimize communicative friction, I decided to create a proper git fork and pull request (#737). Hope that answers your questions.

**Comment by durack1** [comment]
@kwieners thanks for the #737, I pulled these changes into our code (which manages the versioning) and now have your changes implemented. Please take a peek at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any other tweaks are required
