### ISSUE TITLE
Add histSST-noLu experiment to AerChemMIP

### ISSUE THREAD

**Issue by wjcollins** [WCRP-CMIP/CMIP6_CVs#739]
We wish to add a further experiment to AerChemMIP - histSST-noLu

Experiment description: An uncoupled (atmosphere and land) experiment in which sea surface temperatures (SST) and sea ice concentrations (SIC) are taken from historical (as in existing histSST experiment). All forcing agents to follow historical except LULCC. LULCC set to 1850 (exactly following hist-noLu prescription).

Experimental set up and diagnostics as histSST (except AER component is only "optional"):-
ID: histSST-noLu
Experiment: historical SSTs and historical forcing, but with pre-industrial LULCC
Start year: 1850
Duration: 165 years (until 2014)
Ensemble size: 1
Parent: piControl
Required components: AOGCM
Optional components: AER CHEM BGC

**Comment by durack1** [comment]
@wjcollins thanks, I have transcribed this below. You omitted the tier entry, I have assumed "1", please correct if required
```
        "histSST-noLu":{
            "activity_id":[
                "AerChemMIP"
            ],
            "additional_allowed_model_components":[
                "AER",
                "CHEM",
                "BGC"
            ],
            "description":"An uncoupled (atmosphere and land) experiment in which sea
surface temperatures (SST) and sea ice concentrations (SIC) are taken from historical
(as in existing histSST experiment). All forcing agents to follow historical except LULCC.
LULCC set to 1850 (exactly following hist-noLu prescription).",
            "end_year":"2014",
            "experiment":"historical SSTs and historical forcing, but with pre-industrial
LULCC",
            "experiment_id":"histSST-noLu",
            "min_number_yrs_per_sim":"165",
            "parent_activity_id":[
                "CMIP"
            ],
            "parent_experiment_id":[
                "piControl"
            ],
            "required_model_components":[
                "AOGCM"
            ],
            "start_year":"1850",
            "sub_experiment_id":[
                "none"
            ],
            "tier":"1"
        },
```

**Comment by wjcollins** [comment]
This looks fine. Thank you.

**Comment by durack1** [comment]
@wjcollins `histSST-noLu` is now registered. Please peruse [CMIP6_experiment_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html) and let us know of any issues

ping @taylor13 @charliepascoe @RobertPincus @chrisroadmap @martinjuckes

**Comment by MartinaSt** [comment]
@durack1: 25 corresponding entries for 16 citation managers have been added in the citation database.

**Comment by durack1** [comment]
@MartinaSt thanks for the heads up, for my interest can you provide a URL to point me to view this in action?

**Comment by MartinaSt** [comment]
@durack1 I don't understand what you mean by "in action". I have prepared the entries for those citation managers, who registered their model with AerChemMIP. Now they can enter their citation details. There is a blank (No citation manager have had time to enter any details, yet.) landing page for every experiment entry, e.g.
http://cera-www.dkrz.de/WDCC/meta/CMIP6/CMIP6.AerChemMIP.NOAA-GFDL.GFDL-ESM4.histSST-noLu

**Comment by taylor13** [comment]
a bit early in the day for this.  Can't help with this, but thanks for your dedication.

**Comment by MartinaSt** [comment]
Good morning, @taylor13 , I don't think there is any action required. This is just my normal procedure for adding new entries in the citation database. I just answered to raise awareness to notify me in such cases.

**Comment by durack1** [comment]
@MartinaSt you provided exactly what I was curious to see, the URL of the citation page [above](https://github.com/WCRP-CMIP/CMIP6_CVs/issues/739#issuecomment-513097779). Thanks!

**Comment by taylor13** [comment]
@martinjuckes @davidhassell @wjcollins  -- As agreed at the WIP meeting 2020-02-25, I am reopening this issue because:
1) The experiment has not yet been included in ES-DOC
2) To my knowledge it hasn't be added to the data request.  (I think the data request for this experiment should be identical to other aerChemMIP histsst-* experiments.  Is that right, @wjcollins?)

**Comment by wjcollins** [comment]
Yes, the data request should be as other AerChemMIP histSST-*

**Comment by charliepascoe** [comment]
Is there some online information about this experiment that I can link to from ES-DOC?

Should the Land Use and Land Use Cover forcing for this experiment be the same as is used in the LUMIP hist-noLu experiment?

The CMIP6-CV database lists this experiment as requiring an AOGCM model config but I think it should be AGCM AER for compatibility with the histSST experiment.

**Comment by taylor13** [comment]
@charliepascoe I can't find in the experiment_id a single histSST-* experiment with AOGCM.  The ones I found have either "AGCM AER" or "AGCM AER CHEM".  Could you please check and clarify what needs changing in the CMIP6-CV?

**Comment by wjcollins** [comment]
Apologies, this should indeed have been AGCM. The other component requirements should be as hist-noLu.
SST and SIC are as histSST
All other forcings to follow hist-noLu.

**Comment by charliepascoe** [comment]
@taylor13 I responded from notes I made for myself a couple of weeks ago, looks like it has been corrected since then.

**Comment by charliepascoe** [comment]
histSST-noLu should have required model components "AGCM" and additional allowed components "AER CHEM BGC" for consistency hist-noLu.
 
Bill Collins wrote "This should be AGCM. I don’t think there needs to be an “AER” requirement unless hist-noLU does."

**Comment by durack1** [comment]
@charliepascoe just so we're on the same page, this is the latest version of the CMIP6_CVs 6.2.48.1 with the 3 *-noLu experiments listed:
![Screenshot_2020-03-04 CMIP6 experiment_id values](https://user-images.githubusercontent.com/3229632/75923034-1e135c00-5e19-11ea-9396-fd13b4e5be23.png)

**Comment by charliepascoe** [comment]
Thanks @durack1, 
at version 6.2.48.1 
LUMIP hist-noLu lists AER as one of the additional allowed components.
Therefore AerChemMIP histSST-noLu should also list AER as an additional component.
(assuming that's what @wjcollins intends).

**Comment by wjcollins** [comment]
Yes, this should have the same components as hist-noLu

**Comment by durack1** [comment]
@taylor13 this opens a can of worms, as `LUMIP: hist-noLu` is suggesting a fully coupled AOGCM will be used, rather than an AGCM with a slab ocean for e.g. I think the LUMIP crowd are planning non-interactive ocean simulations, but this would be good to clarify

**Comment by durack1** [comment]
@wjcollins @charliepascoe that change is now in place.

@martinjuckes please ping us here once the data request has been updated to reflect this `histSST-noLu` experiment so we can close out this issue

**Comment by durack1** [comment]
@martinjuckes I presume this can now be closed out? @charliepascoe has implemented this in ES-DOCs

**Comment by durack1** [comment]
Closing as noted in email earlier this week
