### ISSUE TITLE
experiment_id : ES-DOC start year for historical-ext is incorrect

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#740]
@charliepascoe:  We noticed that Start Date for historical-ext in ES-DOC is given as 2014-01-01, which is incorrect.   The correct Date should be 2015-01-01 (as given in https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json)

**Comment by charliepascoe** [comment]
I've just corrected the start dates for historical-ext and esm-hist-ext experiments, the correction will be carried through to the online ES-DOC info very soon.
All other 2015 start dates in the CMIP6-CV are consistent with the ES-DOC database.

**Comment by taylor13** [comment]
Thanks for checking, and noticing the same problem in esm-hist-ext .

**Comment by durack1** [comment]
@taylor13 to maintain consistency between these experiments, we need to add `end_year = present` to `esm-hist-ext` so this is completely consistent with `historical-ext`. I will keep this issue open until that change is implemented

**Comment by durack1** [comment]
@charliepascoe @taylor13 that change is implemented, so closing - 6.2.35.0 solves it [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html)
