### ISSUE TITLE
source_id registration of AWI-ESM-2-1-LR

### ISSUE THREAD

**Issue by christian-stepanek** [WCRP-CMIP/CMIP6_CVs#745]
label = AWI-ESM 2.1 LR
label_extended = AWI-ESM 2.1 LR
source_id = AWI-ESM-2-1-LR
institution_id = AWI
release_year = 2019
activity_participation = [CMIP, PMIP]

aerosol:
description = none
nominal_resolution = none
atmos:
description = ECHAM6.3.04p1 (T63L47 native atmosphere T63 gaussian grid; 192 x 96 longitude/latitude; 47 levels; top level 80 km)
nominal_resolution = 250 km
atmosChem:
description = none
nominal_resolution = none
land:
description = JSBACH 3.20 with dynamic vegetation
nominal_resolution =  250 km
landIce:
description = none
nominal_resolution = none 
ocean:
description = FESOM2 (unstructured grid in the horizontal with 126858 wet nodes; 46 levels; top grid cell 0-5 m)
nominal_resolution = 50 km
ocnBgchem:
description = none
nominal_resolution = none
seaIce:
description = FESOM2
nominal_resolution = 50 km

**Comment by durack1** [comment]
@christian-stepanek did you want to deregister `AWI-ESM-1-1-LR`? Or will both models be contributing?

**Comment by christian-stepanek** [comment]
Both models will be contributing. The AWI-ESM-2-1-LR is just a recent addition.Christian StepanekScientistClimate SciencesPaleoclimate DynamicsBussestrasse 2427570 BremerhavenGermanytelephone: +49/ (0) 471 4831-1591sent from my mobile deviceOn 23 Jul 2019 23:31, "Paul J. Durack" <notifications@github.com> wrote:@christian-stepanek did you want to deregister AWI-ESM-1-1-LR? Or will both models be contributing?

**Comment by durack1** [comment]
@christian-stepanek your registration has been completed, please take a peek at [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know of any changes

**Comment by christian-stepanek** [comment]
@durack1 Thanks for your effort. There are two problems:

- there is the typo with regard to FESOM2 levels - it should read 48 instead of 46, I mentioned this in an earlier email, but this might have gotten lost.

- For AWI-ESM-2-1 the nodes differ by one from AWI-ESM-1-1 The text
  "FESOM 2 (unstructured grid in the horizontal with 126859 wet nodes; 46 levels; top grid cell 0-5 m)"
  should read
  "FESOM 2 (unstructured grid in the horizontal with 126858 wet nodes; 46 levels; top grid cell 0-5 m)"
  
Could you please fix this? Thanks a lot!

**Comment by durack1** [comment]
@christian-stepanek the 46 vs 48 persists in your "should read" text above, I will replace with:
```
FESOM 2 (unstructured grid in the horizontal with 126858 wet nodes; 48 levels; top grid cell 0-5 m)
```

**Comment by christian-stepanek** [comment]
That is correct - I should have been more precise. Thanks.

**Comment by durack1** [comment]
@christian-stepanek take another peek, this time we should be good [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html)

**Comment by christian-stepanek** [comment]
... looks good now. Thank you for your help!
