### ISSUE TITLE
Add activity PMIP to source_id EC-Earth3

### ISSUE THREAD

**Issue by shutingdk** [WCRP-CMIP/CMIP6_CVs#749]
Our Paleo climate team would like to contribute to PMIP also using EC-Earth3. Could you please add PMIP to the activity_participation list for EC-Earth3? We will continue to contribute to PMIP using EC-Earth3-LR and EC-Earth3-Veg-LR and EC-Earth3-GrIS.

**Comment by durack1** [comment]
@shutingdk that change is now in place, take a peek at [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know of any other edits

**Comment by shutingdk** [comment]
Looks good. Thank you.
