### ISSUE TITLE
experiment_id: "volc-cluster-mill" requested changes

### ISSUE THREAD

**Issue by davidezanchettin** [WCRP-CMIP/CMIP6_CVs#75]
experiment_id: “volc-cluster-mill”, "description":"Parallel experiment to volc-cluster-ctrl but with initial conditions taken from last millennium simulation to account for the effects of a more realistic history of past natural forcing. All forcings except volcanic kept constant from year AD 1790 on",“start_year”:"1790", “end_year”:"1858","min_number_yrs_per_sim":"69"

**Comment by taylor13** [comment]
O.K.
