### ISSUE TITLE
ES-Doc: Incorrect boundary conditions for histSST-xx experiments

### ISSUE THREAD

**Issue by wjcollins** [WCRP-CMIP/CMIP6_CVs#751]
The boundary conditions (SSTs and sea ice) for the histSST-xx experiments: (histSST, histSST-piNTCF, histSST-1950HC) should all come from historical, and not hist-piNTCF as suggested in ES-DOC.
e.g.
https://view.es-doc.org/index.html?renderMethod=id&project=cmip6&id=7c445c93-4376-4e77-b6e6-e8178602629e&version=1

hist-piNTCF should have no entries in "Provides Constraints to"

Note also that the "control" for hist-piAer should be historical. Consequently in histSST: hist-piAer should be removed from the list "provides control to".

The siblings seems slightly confused in all these experiments too, but I'm not sure whether this is important or used. It would seem to make sense that the siblings should be taken from each table in the AerChemMIP paper (Collins et al. 2017).

**Comment by charliepascoe** [comment]
I've made the corrections you requested to the histSST-xx experiments.
These all now reference the "historical" experiment in their "is_constrained_by" field.
I've updated the forcing constraints for all the histSST-xx so that they reference "time-evolving monthly SST/sea ice distribution taken from a coupled historical simulation". 
I agree that the sibling experiments are confusing, I've removed them.

The updates should appear online soon.

**Comment by durack1** [comment]
@wjcollins @charliepascoe if all the outstanding issues have been addressed, we can close this issue. @wjcollins can you confirm all details present in the CMIP6_CVs and visible at [CMIP6_experiment_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html) are correct? We don't capture the forcing information outside of the description and experiment attributes

**Comment by wjcollins** [comment]
The changes to ES-Doc don't seem to have propagated through yet. The CMIP6_experiment_id.html page didn't have any issues.

**Comment by durack1** [comment]
@wjcollins thanks for the update. I'll leave this open and @charliepascoe can update when the information in ES-DOCs is up-to-date and correct

**Comment by durack1** [comment]
@charliepascoe just pinging you here to see if we can close this issue?

**Comment by durack1** [comment]
@charliepascoe just pinging you again here to see if we can close this issue?

**Comment by durack1** [comment]
@charliepascoe just pinging you again on this - the ES-DOC page info still appears incorrect, see screenshot below from [https://view.es-doc.org](https://view.es-doc.org/index.html?renderMethod=id&project=cmip6&id=7c445c93-4376-4e77-b6e6-e8178602629e)
![Screen Shot 2019-09-04 at 2 15 55 PM](https://user-images.githubusercontent.com/3229632/64292178-9f4b6e00-cf1e-11e9-9d37-0bf25106c753.png)

@eguil @momipsl @atefbn @bnlawrence @glevava @taylor13

**Comment by charliepascoe** [comment]
Hi @durack1, the latest version of the spreadsheet is still waiting to be published.  Once it happens I'll add a note on here.

**Comment by durack1** [comment]
@charliepascoe thanks for the update. Any indication of when the spreadsheet update will be done? The issue was reported on 1st August and it would be great to clean up the incorrect details as promptly as possible so modeling groups don't waste resources with incorrect configurations

**Comment by durack1** [comment]
@charliepascoe @momipsl any luck getting the AerChemMIP hist-XX experiments updated?

FYI, we've also got a bunch of new experiment_ids registered, take a peek at #797 for details, with a merge in #804. For reference the total experiment count is now 299 (see [CMIP6_experiment_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_experiment_id.html))

@eguil @bnlawrence @martinjuckes ping

**Comment by davidhassell** [comment]
New ES-DOC Experiment documentation has been published: https://search.es-doc.org/

**Comment by taylor13** [comment]
@davidhassell @charliepascoe I think this issue can now be closed.  I would wait to update es-doc the next time until *all* the new experiments being discussed on other issues are in the CV.  That may be a couple of weeks.  Do you agree @durack1 ?  [We still need to get approval to list one of the FAFMIP runs as "tier 1", and we need to decide on naming and "era" questions for the CMIP5 experiments.

**Comment by davidhassell** [comment]
Fine by me. I should just say that we think that the delay in updating the ES-DOC materials was an unfortunate anomaly in this case (exacerbated by people not being around much over the summer). Previous ES-DOC updates have been very timely, I think. Thanks for your patience!

**Comment by durack1** [comment]
@davidhassell perfect, thanks again for this. I can confirm that I also see `historical` rather that `hist-piNTCF` are previous.

We can close this out.

P.S. @davidhassell @charliepascoe have the new FAFMIP experiments (#804) also been updated on ES-DOC? As @taylor13 notes, we also have a number of other experiments under discussion in #805 that will likely be registered within the next week or so
