### ISSUE TITLE
Add activity ScenarioMIP to source_id KIOST-ESM

### ISSUE THREAD

**Issue by pandland-kiost** [WCRP-CMIP/CMIP6_CVs#752]
KIOST team would like to contribute ScenarioMIP by using KIOST-ESM. Could you add ScenarioMIP to the activity participation list for KIOST-ESM?

Thank you!!

**Comment by durack1** [comment]
@pandland-kiost thanks for the update. This change is now in place, please review [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let us know of any further changes required
