### ISSUE TITLE
activity_id- add DAMIP for GFDL-CM4

### ISSUE THREAD

**Issue by aradhakrishnanGFDL** [WCRP-CMIP/CMIP6_CVs#758]
Requesting for DAMIP activity to be added to GFDL-CM4, based on the decision conveyed by GFDL CMIP coordinator.

**Comment by durack1** [comment]
@aradhakrishnanGFDL thanks for the request, you should find the latest [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) now correctly reflects `DAMIP` participation
