### ISSUE TITLE
Add ssp370pdSST experiment to AerChemMIP

### ISSUE THREAD

**Issue by wjcollins** [WCRP-CMIP/CMIP6_CVs#759]
We wish to add a further experiment to AerChemMIP - ssp370pdSST

Experiment description: An uncoupled (atmosphere and land) experiment in which sea surface temperatures (SST) and sea ice concentrations (SIC) are fixed to present day (2005-2014 mean climatology). All forcing agents to follow SSP3-7.0.

Experimental set up as ssp370SST except SST and SIC are from a 2005-2014 climatology.  Diagnostics are as ssp370SST
ID: ssp370pdSST
Experiment: SSP3-7.0, with SSTs prescribed as present day 
Start year: 2015
Duration: 86 years (until 2100)
Ensemble size: 1
Parent: historical
Required components: AOGCM AER 
Optional components: CHEM BGC

**Comment by durack1** [comment]
@wjcollins the required components `AOGCM` is defined as a `coupled atmosphere-ocean global climate model..`, so rather I'll change this to `AGCM` defined as `atmospheric general circulation model run with prescribed ocean surface conditions`

@taylor13 ping

**Comment by durack1** [comment]
@wjcollins that registration is now complete, please take a peek at [CMIP6_experiment_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html) to cross-check all experiment details

@charliepascoe @taylor13 @martinjuckes ping

**Comment by wjcollins** [comment]
That all looks correct.
Thanks, Bill

**Comment by wjcollins** [comment]
My AOGCM request was wrong because I copied it from histSST-noLu - which I now spot is wrong too. Can histSST-noLu be changed to AGCM?

**Comment by durack1** [comment]
Reopening due to error to be fixed in`histSST-noLu`

**Comment by durack1** [comment]
@wjcollins can you take a peek over all the other experiments to make sure the only `AGCM` correction is isolated to `histSST-noLu`?

**Comment by durack1** [comment]
@wjcollins I assume all is in order, we've fixed all the outstanding issues and can close this issue?

**Comment by wjcollins** [comment]
Yes, all others look correct.

**Comment by durack1** [comment]
@wjcollins perfect, closing this issue out

**Comment by taylor13** [comment]
@martinjuckes @davidhassell @wjcollins -- As agreed at the WIP meeting 2020-02-25, I am reopening this issue because:

    The experiment has not yet been included in ES-DOC
    To my knowledge it hasn't be added to the data request. (I think the data request for this experiment should be identical to other aerChemMIP ssp370* experiments. Is that right, @wjcollins?)

**Comment by charliepascoe** [comment]
Is there some online information about these two experiments that I can link to from ES-DOC?

This experiment requires present day SST and Sea Ice Concentration calculated from a 2005-2014 Climatology.
How should the groups calculate the climatology?
Will AerChemMIP provide an input data file instead?

Note that the PAMIP experiment pdSST-pdSIC has present day SI and SICONC climatologies with data provided by PAMIP, might those fields be suitable for this experiment?

The PAMIP contact for the SST and SICONC data files in the input4mips database is Yannick Peings ypeings@uci.edu

**Comment by wjcollins** [comment]
The SST and SIC should be from the models own historical.

**Comment by charliepascoe** [comment]
I think this experiment should have required model component AGCM for compatibility with ssp370 which has AOGCM.

**Comment by durack1** [comment]
@charliepascoe if the experiment is atmos-only, then AGCM is the most appropriate. For AerChemMIP, the `ssp370-lowNTCF` is the only single MIP experiment that lists `AOGCM` as the required component. The `ssp370` experiment is shared with ScenarioMIP, so this should be `AOGCM`

I searched for "ssp370" at https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_experiment_id.html

**Comment by durack1** [comment]
Closing as noted in email earlier this week
