### ISSUE TITLE
Increase duration of ssp370SST in AerChemMIP

### ISSUE THREAD

**Issue by wjcollins** [WCRP-CMIP/CMIP6_CVs#760]
Please can you increase the duration of ssp370SST.

Start year: 2015
Duration: 86 years (until 2100)

**Comment by durack1** [comment]
@wjcollins that change is now in place, please peek [CMIP6_experiment_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html) to review

@charliepascoe @taylor13 @martinjuckes ping

**Comment by wjcollins** [comment]
That all looks correct.
Thanks, Bill

**Comment by taylor13** [comment]
@martinjuckes @davidhassell @wjcollins -- As agreed at the WIP meeting 2020-02-25, I am reopening this issue because:

1.  The correction to experiment duration has not yet been propagated to ES-DOC
2.   Is there also a correction needed in the data request?

**Comment by durack1** [comment]
Closing as noted in email earlier this week
