### ISSUE TITLE
institution_id registration of RUBISCO-Project

### ISSUE THREAD

**Issue by climate-dude** [WCRP-CMIP/CMIP6_CVs#761]
institution_id = RUBISCO
institution = ORNL (Oak Ridge National Laboratory, Oak Ridge, TN 37831, USA); ANL (Argonne National Laboratory, Argonne, IL 60439, USA); BNL (Brookhaven National Laboratory, Upton, NY 11973, USA); LANL (Los Alamos National Laboratory, Los Alamos, NM 87545); LBNL (Lawrence Berkeley National Laboratory, Berkeley, CA 94720, USA); NAU (Northern Arizona University, Flagstaff, AZ 86011, USA); NCAR (National Center for Atmospheric Research, Boulder, CO 80305, USA); UCI (University of California Irvine, Irvine, CA 92697, USA); UM (University of Michigan, Ann Arbor, MI 48109, USA). Mailing address: ORNL Climate Change Science Institute, c/o Forrest M. Hoffman, Laboratory Research Manager, Building 4500N Room F106, 1 Bethel Valley Road, Oak Ridge, TN 37831-6301, USA

**Comment by durack1** [comment]
@climate-dude did you want this registered as `RUBISCO` as above, or rather `RUBISCO-Project` (which follows the same format as [`E3SM-Project`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_institution_id.json#L19))?

**Comment by climate-dude** [comment]
@durack1 it doesn't matter to me. It felt like `RUBISCO-Project` was more typing, but it's fine with me to maintain naming symmetry with the E3SM-Project.

**Comment by durack1** [comment]
@climate-dude I don't have a preference either, dropping the `-Project` would shortened the ESGF pathnames as a counter point.. It's your institution so happy for you to have the last word

**Comment by climate-dude** [comment]
@durack1 Ok, let's go with shorter pathnames. Just call it `RUBISCO`. Thanks!

**Comment by durack1** [comment]
@climate-dude `RUBISCO` is now registered, take a peek at [CMIP6_institution_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_institution_id.html) to double check the details
