### ISSUE TITLE
source_id registration of E3SM-1-1-ELM

### ISSUE THREAD

**Issue by climate-dude** [WCRP-CMIP/CMIP6_CVs#762]
label = E3SM 1.1 Land Model
label_extended = E3SM 1.1 (Energy Exascale Earth System Model) ELM (E3SM Land Model) Offline
source_id = E3SM-1-1-ELM
institution_id = RUBISCO
release_year = 2019
activity_participation = [LS3MIP]

aerosol:
description = none
nominal_resolution = none
atmos:
description = none
nominal_resolution = none
atmosChem:
description = none
nominal_resolution = none
land:
description = ELM (v1.1, 0.5 degree latitude/longitude grid, active biogeochemistry mode where p1=CTC (Converging Trophic Cascade) and p2=ECA (Equilibrium Chemical Approximation))
nominal_resolution = 50 km    
landIce:
description = none
nominal_resolution = none 
ocean:
description = none
nominal_resolution = none
ocnBgchem:
description = none
nominal_resolution = none
seaIce:
description = none
nominal_resolution = none

**Comment by durack1** [comment]
Awaiting info from #761

**Comment by durack1** [comment]
@climate-dude I'm a little confused how this relates to [`E3SM-1-0`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L1860-L1862) which includes the description:
```
ELM (v1.0, cubed sphere spectral-element grid; 5400 elements with p=3;
1 deg average grid spacing; 90 x 90 x 6 longitude/latitude/cubeface;
satellite phenology mode), MOSART (v1.0, 0.5 degree latitude/longitude grid)
```
Surely v1.1 of the same code is also on a cubed sphere grid? And what is the river routing scheme? Also how does RUBISCO relate to E3SM-Project

@mccoy20 @taylor13 pinging you both here

**Comment by climate-dude** [comment]
@durack1 @mccoy20 @taylor13 The proposed source_id (`E3SM-1-1-ELM`) is for a model configuration using ELM from E3SM v1.1 in offline mode for LS3MIP simulations that are performed on a regular 0.5 degree lat/lon grid, not in satellite phenology mode but with active biogeochemistry.

We presently have CTC biogeochemistry, but may in the future have ECA biogeochemistry simulations; hence the note about these two "physics" options (which should be "biology" options).

I am working to confirm if we used MOSART for those simulations or not. If we did, we should add the MOSART description as well.

We did not use the cubed sphere spectral-element grid for these simulations and there are no other active component models, which are described in the `E3SM-1-0` source_id.

**Comment by taylor13** [comment]
This is a wrinkle that wasn't anticipated in that output from a component model that is not yet being used in a coupled simulation is submitted to CMIP6.  Normally, the offline component model should have a source_id that is the same as the coupled host.  (That way users can check whether some behavior in coupled mode can be traced to an isolated component.)  The specifications for source_id are given in note 13 following Table 1 of https://goo.gl/v1drZl .

If ELM is indeed the land model used in the coupled model E3SM v1.1, and if it is not expected that a different v1.1 of E3SM will be released, then I think the source_id should simply be ``E3SM-1-1`` (without the ELM suffix).  The fact that a simulation was produced only by the land surface model run offline would be indicated in the output files with the global attribute ``source_type = "LAND"``.  

If multiple variants on E3SM v1.1 are anticipated, they could be distinguished by different values being assigned to the global attribute ``physics_index``.

Please also note that multiple institutions can run the same model (source_id).  As an example, see ``HadGEM3-GC31-HM``.  So if ``RUBISCO`` performs the land-only simulations, and later ``E3SM-Project`` submits coupled runs, that's o.k.

If you think there is a better way to handle this, please let us know.

**Comment by climate-dude** [comment]
@taylor13 Thank you for the guidance. It makes sense that the `source_id` should not change when some model components are inactive as described in note 13 following Table 1 of https://goo.gl/v1drZl. This suggests that we might want to register a `source_id` of `E3SM-1-1` and fully describe the typical coupled model configuration therein.

Since `source_id`s appear to include grid information in component model descriptions, it's not clear to me how to correctly identify different native grids that may be used for various sets of experiments in different model configurations. Does this information belong somewhere else? Table 1 of https://goo.gl/v1drZl does not appear to allow for having `gn1`, `gn2`, ..., as native grid specifiers, but implies there is only one native grid and that other options are regridded results. Do we specify all potential native grids and `nominal_resolution`s in the `source_id` record?

For these land model simulations, we are turning on biogeochemistry, so it is different physics from the land model described in `E3SM-1-0`, besides being a later version of the modeling system. So I take it that if we propose `E3SM-1-1`, its default configuration would have land biogeochemistry on (instead of using satellite phenology). Then, since there are two major terrestrial biogeochemical schemes that each can be run in three different modes, we would denote this:

`physics_index = 1` for CTC with C, N, P
`physics_index = 2` for CTC with C, N
`physics_index = 3` for CTC with C
`physics_index = 4` for ECA with C, N, P
`physics_index = 5` for ECA with C, N
`physics_index = 6` for ECA with C

Does that seem reasonable? Then if another institution uses this same model, they should also use the same physics specifications, adding any others they wish to define?

Thanks for your time and consideration!

**Comment by mccoy20** [comment]
Hi @taylor13 , @climate-dude, @durack1,
I will be registering Coupled E3SM-1-1 (model with CTC as default E3SM 1.1 model), and E3SM-1-1-ECA ( model with ECA). I need to check for the final decision on the exact naming scheme, make sure everyone agrees. Then Forrest can register the ELM component as part of the appropriate Coupled model. I will finalize the names next week and then proceed with the registration.
Cheers,
Renata

**Comment by durack1** [comment]
@mccoy20 @climate-dude just circling around on this, is there any progress on the `E3SM-1-1` registration? @climate-dude I assume the registration in limbo is not holding you up in submitting simulations?

**Comment by mccoy20** [comment]
@climate-dude @durack1 - two E3SM-1-1 issues for registration are now open, see  
E3SM-1-1 (as default model with CTC) #775 
E3SM-1-1-ECA (model with experimental ECA ) #776

**Comment by durack1** [comment]
@climate-dude now that we have the registrations for the `E3SM-1-1` #775 in place, what amendments are required to the above to get this finalized so I can process the registration?

**Comment by durack1** [comment]
@climate-dude I assume this is no longer needed, and if so, I'll close at the end of the week. If the registration is still required, please let us know

**Comment by climate-dude** [comment]
@durack1 Yes, I think this one can go away. I do have some comments/suggestions about the other registrations (#775 and #776) for `E3SM-1-1` that I will add comments for on those issues.
