### ISSUE TITLE
Add AerChemMIP to experiment ssp370

### ISSUE THREAD

**Issue by wjcollins** [WCRP-CMIP/CMIP6_CVs#77]
experiment_id:"ssp370", activity id:"ScenarioMIP AerChemMIP"

**Comment by taylor13** [comment]
I agree

**Comment by durack1** [comment]
@wjcollins to confirm this addition should be to all `ssp370*` experiments, so:
```
ssp370SST-ssp126Lu
ssp370SST-lowO3
ssp370SST-lowNTCF
ssp370SST-lowCH4
ssp370SST-lowBC
ssp370SST-lowAer
ssp370SST
```
And these all then include:
```
"activity_id":[
     "AerChemMIP",
     "ScenarioMIP"
],
```
At the moment we have `"activity_id":["AerChemMIP"]` listed for each of these, take a peek at the [html file](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html) (and you can search for `ssp370`

**Comment by durack1** [comment]
@wjcollins apologies my mistake, instead I will just amend the `ssp370` experiment_id to show:
```
        "ssp370":{
            "activity_id":[
                "AerChemMIP",
                "ScenarioMIP"
],
```
