### ISSUE TITLE
Revise minimum model configuration for hist-piNTCF, histSST-piNTCF, ssp370SST-lowNTCF, piClim-NTCF

### ISSUE THREAD

**Issue by wjcollins** [WCRP-CMIP/CMIP6_CVs#78]
experiment_id:"hist-piNTCF",
required model components:"AOGCM AER",
allowed model components:"CHEM BGM"

experiment_id:"histSST-piNTCF",
required model components:"AGCM AER",
allowed model components:"CHEM BGM"

experiment_id:"ssp370SST-lowNTCF",
required model components:"AGCM AER",
allowed model components:"CHEM BGM"

experiment_id:"piClim-NTCF",
required model components:"AGCM AER",
allowed model components:"CHEM BGM"

**Comment by taylor13** [comment]
@wjcollins at least one of these mentions emissions of ozone precursors.  Doesn't that require a "CHEM" component be included?  Please check all 4 again, and confirm/revise.
thanks, Karl

**Comment by durack1** [comment]
@wjcollins can you address the query above of @taylor13? Once these details are clarified we can make the amendments and close this issue

**Comment by wjcollins** [comment]
The "NTCF" experiments can still be run by AER-only models. But, in that case the ozone precursors emissions won't change.

**Comment by durack1** [comment]
@wjcollins @taylor13 so the proposed amendments above are good to go?

**Comment by wjcollins** [comment]
Yes

**Comment by taylor13** [comment]
@wjcollins @durack1  yes, I think, the mods can be made (but change "BGM" to "BGC" for consistency with latest specs).  Then we can close, I guess.
