### ISSUE TITLE
experiment_id question: RFMIP hist-spAer-all and hist-spAer-aer

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#781]
We received this by email:

Is there a reason why the "BGC" component is disallowed for the "hist-spAer*" experiment_id?   From the data request, the "hist-spAer" experiments use an "AOGCM" configuration model. In my understanding this allows the "BGC" component as it's the case for other RFMIP experiment as "piClim-histall"

Am I'm wrong?

**Comment by durack1** [comment]
```
From: Piers Forster
Date: Thursday, September 12, 2019 at 10:56 PM
To: "Taylor, Karl E.", "Robert.Pincus", "bjorn.stevens"
Cc: Guillaume LEVAVASSEUR, Martin Juckes, "Durack, Paul J."
Subject: Re: BGC component for "hist-spAer*"

Yes Karl - sorry the was our mistake. We wanted to try to fix ozone - but it’s better to do this directly - please can you change and thank you
```

**Comment by durack1** [comment]
@bnlawrence @eguil pinging you both on this thread

**Comment by durack1** [comment]
@RobertPincus (and RFMIP co-chairs, will email the thread after this) these entries are cleaned up, please take a careful peek at [CMIP6_experiment_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_experiment_id.html) and let us know if there are any other corrections required

**Comment by durack1** [comment]
The change in #782 will need to be reverted, awaiting further guidance before these changes are implemented

**Comment by taylor13** [comment]
Some subsequent emails:
9/13/19
```
Thanks, Piers.

I'm not sure what you mean when you say "we wanted to try to fix ozone - but it's better to do 
this directly".  It's the "directly" that puzzles me.  Does it mean to let the model itself 
directly  *calculate* ozone concentration?

If you want everyone to have the same ozone field, don't they have to prescribe it?

If you want folks to use a specifed ozone concentration field, then I think we would want to 
exclude "CHEM" as a model component because that's perhaps the main purposes of atmos.
 chem. treatments (as defined in my previous email): to calculate, rather than prescribe ozone
 concentrations.

best wishes,
Karl
```
9/13/19
```
Dear Karl, 

Sorry, I confused myself about which set of experiments you were talking about. Please ignore
 my last email. These are Bjorn’s aerosol plume setup experiments not the standard ERF ones.
 You are right we want to compare them to DAMIP and keep everything as close to the full
 AOGCM aside from prescribing aerosol with the plume method. So I think CHEM, AER and BGC
 should all be on, but I’ll let someone else correct me 
Bests 
Piers 
```

**Comment by taylor13** [comment]
As noted in the [global attributes definition document]( https://goo.gl/v1drZl )  "AER" is used as follows:
```
AER (appears with AOGCM or AGCM in models that calculate tropospheric aerosols driven 
            by emission fluxes, rather than relying on prescribed concentrations),
```
So, for a simulation with a MACv2-SP prescription of aerosols (rather than prescribing emissions), "AER" should *not* be included as a model component.  (On the other hand, both "BGC" and "CHEM" should be alllowed.)

So, in the .json file for the hist-spAER-all and hist-spAER-aer experiments, we need to set:

"additional_allowed_model_components":["CHEM", "BGC"]

**Comment by durack1** [comment]
@taylor13 the current CVs list `additional_allowed_model_components = [CHEM BGC]` for `hist-spAer-aer` and `hist-spAer-all`, see [CMIP6_experiment_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_experiment_id.html).

From my reading above, there is nothing to change here

**Comment by durack1** [comment]
It seems the changes implemented in #782 have solved this issue, so will close - MIP chairs (@RobertPincus you're the solitary one I can ping), if any inconsistencies remain please reopen this, or generate a new issue

**Comment by taylor13** [comment]
@martinjuckes @davidhassell -- As agreed at the WIP meeting 2020-02-25, I am reopening this issue because I don't think the changes to the experiment_id CV have propagated to ES-DOC or the data request.

**Comment by charliepascoe** [comment]
ES-Doc only lists the minimum required model configuration.
So ES-Doc would only need to be updated if the minimum requirement changes.
Both of these experiments are listed as requiring AOGCM configuration in ES-DOC.
If that is compatible with the minimum components in the CMIP6-CV then no change is needed to the ES-DOC information.

**Comment by RobertPincus** [comment]
Charlotte -

I can confirm that the AOGCM configuration is what’s required for these experiments.
---
Robert Pincus
University of Colorado/NOAA Earth System Research Lab
http://cires.colorado.edu/researcher/robert-pincus

On Feb 28, 2020, at 7:07 PM, Charlotte <notifications@github.com<mailto:notifications@github.com>> wrote:


ES-Doc only lists the minimum required model configuration.
So ES-Doc would only need to be updated if the minimum requirement changes.
Both of these experiments are listed as requiring AOGCM configuration in ES-DOC.
If that is compatible with the minimum components in the CMIP6-CV then no change is needed to the ES-DOC information.

**Comment by durack1** [comment]
@charliepascoe @RobertPincus [both these experiments list](https://github.com/WCRP-CMIP/CMIP6_CVs/pull/782/files#diff-6642f67f4f38024deabaa41b20af5e65):
```
"required_model_components":[
                "AOGCM"
            ],
...
            "additional_allowed_model_components":[
                "CHEM",
                "BGC"
            ],
```

So I think this issue is resolved against ES-DOCs. We'll need to get clearance from @martinjuckes against the data request before the issue can be closed

**Comment by durack1** [comment]
Closing as noted in email earlier this week
