### ISSUE TITLE
source id registration of NorESM1-F

### ISSUE THREAD

**Issue by ChunchengGuo** [WCRP-CMIP/CMIP6_CVs#786]
"NorESM1-F":{
"label":"NorESM1-F",
"label_extended":"NorESM1-F (a fast version of NorESM that is designed for paleo and multi-ensemble simulations)"
"source_id":"NorESM1-F"
"release_year":"2018",
"institution_id":["NCC"],
"activity_participation":"PMIP"
"aerosol": None,
"atmos":{
                    "description":"CAM (2 degree resolution; 144 x 96; 32 levels; top level 3 mb)",
                    "native_nominal_resolution":"250 km"
                },
"atmospheric_chemistry": None,
"land":{
                    "description":"CLM",
                    "native_nominal_resolution":"250 km"
                },
"landIce":{
                    "description":"CISM",
                    "native_nominal_resolution":"250 km"
                },
"ocean":{
                    "description":"MICOM (1 degree resolution; 360 x 384; 70 levels; top grid cell minimum 0-2.5 m [native model uses hybrid density and generic upper-layer coordinate interpolated to z-level for contributed data])",
                    "native_nominal_resolution":"100 km"
                },
"ocnBgchem":{
                    "description":"HAMOCC",
                    "native_nominal_resolution":"100 km"
                },
"seaIce":{
                    "description":"CICE",
                    "native_nominal_resolution":"100 km"
                },
}

**Comment by durack1** [comment]
@ChunchengGuo `NorESM1-F` is now registered. I tweaked your `activity_participation` to include `CMIP` as it is expected that the required DECK simulations for this model will also be contributed. You can review the registered details at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html). I note that we have not recorded any of the version information for any of the models, e.g. `CICE` rather than `CICE4` for e.g. It would be useful to revise these details if you are yet to write much of the data for the models already registered

**Comment by ChunchengGuo** [comment]
@durack1 Thanks for your quick response.

We did perform DECK+historical simulations with NorESM1-F, however, the historical forcing is the CMIP5 not the CMIP6 forcing, which (strictly speaking) disqualifies NorESM1-F as a CMIP6 model. 

We intend to upload several PMIP simulations with NorESM1-F and the reference PI experiment ONLY (e.g. no 1%CO2, 4XCO2, historical). Would this be OK?

**Comment by ChunchengGuo** [comment]
@durack1 I forgot to add that the versions for the model components are CAM4, CICE4, CLM4, HAMOCC5.1 

Would be great if you could help implement these tweaks; thanks!

**Comment by durack1** [comment]
@ChunchengGuo good question, I think all the DECK experiments are formally required, but for contributions such as this to a defined sub-MIP (PMIP) you can only do what is practical, pinging @taylor13 for this comment

For the model subversions (CAM4, CICE4 etc), did you want to update all the NorESM* models, it seems these details are missing from all 7 variants already registered

**Comment by ChunchengGuo** [comment]
> For the model subversions (CAM4, CICE4 etc), did you want to update all the NorESM* models, it seems these details are missing from all 7 variants already registered

please only update NorESM1-F for now. The other NorESM models are based on different versions for some of the components - hopefully some of my colleagues will update them at some point soon.

**Comment by durack1** [comment]
Sub-model version descriptions need tweaking as contained in https://github.com/WCRP-CMIP/CMIP6_CVs/issues/786#issuecomment-535216026

**Comment by durack1** [comment]
@ChunchengGuo those tweaks are made, we're still missing versioning info for `MICOM` and `CISM`, but at least some improvement was made

**Comment by taylor13** [comment]
It will be acceptable for you to carry out PMIP simulations with your model (which carried out the CMIP5 core experiments, but not the CMIP6 DECK) and place your output in the CMIP6 archive.  In searches of the archive, your model will belong to the "CMIP6-fringe" cohort (when the cohort labels get assigned; currently all registered models belong to the "Registered" cohort.

**Comment by ChunchengGuo** [comment]
@taylor13 thanks for clarifying.

@durack1  according to the comment by @taylor13, it seems that we need to re-assign the cohort of NorESM1-F from "registered" to "CMIP6-fringe". May I ask you to do the tweak in the CMIP6_souce_id.html? Thanks!

**Comment by durack1** [comment]
@taylor13 can you make a comment about the cohort updating timeline?

**Comment by taylor13** [comment]
For now everything is "Registered".  I would say some time in the next half year we might be able to transition to designating different cohorts depending on participation levels.  By the way, I think before you become part of "CMIP6-fringe", I think the rule is that you should complete *all* of the tier 1 PMIP experiments.

**Comment by ChunchengGuo** [comment]
@taylor13 could we proceed with "Registered" for now if possible? Some groups in the PMIP community have been requesting data for synthesis papers with imminent deadlines..

I am not sure if we need to complete all the PMIP tier 1 experiments; according to Table 1 in the PMIP protocol paper (https://www.geosci-model-dev.net/11/1033/2018/) -

"It is not mandatory to perform all Tier 1 experiments to take part in PMIP4-CMIP6, but it is mandatory to run at least one of the PMIP4-CMIP6 entry cards."

The tier1 has five experiments, whereas the entry cards are lig127k and lgm, and we've performed the lig127ka experiment.

**Comment by taylor13** [comment]
Yes, you and all other models will (for now) be "Registered".  We want to get the data out there.

thanks,
Karl

**Comment by ChunchengGuo** [comment]
OK, thanks, Paul.

**Comment by tomorrgod** [comment]
Hi, do you know how to transform the grid of the tos into lat/lon grid?
![image](https://user-images.githubusercontent.com/37427804/104884877-077ae280-59a2-11eb-8fc1-f39d1a7705af.png)

**Comment by taylor13** [comment]
I am not familiar with the NorESM1-F model and don't know how to transform the coordinates.

I *am* interested in knowing which file the above "header" information came from.  It says it was generated by CMOR, but the metadata seems a bid odd (e.g.,  the declared dimensions for latitude_bnds and longitude_bnds).  Could you please provide the name of the file, and possibly a full header listing (including global attributes?
