### ISSUE TITLE
experiment_id -- Omit piClim-aerO3x0p1 and piClim-aerO3x2

### ISSUE THREAD

**Issue by RobertPincus** [WCRP-CMIP/CMIP6_CVs#79]
Dear colleagues - 

In the final version of the RFMIP protocol (http://www.geosci-model-dev.net/9/3447/2016/) we have omitted the experiments listed in the title (fixed-SST experiments with fractional present-day aerosol loadings). These should also be omitted from the JSON file. 

Best regards - 
Robert Pincus

**Comment by taylor13** [comment]
o.k.
