### ISSUE TITLE
source_id registration of GISS-E2.1-G-CC

### ISSUE THREAD

**Issue by gavinny** [WCRP-CMIP/CMIP6_CVs#793]
"GISS-E2-1-G-CC":{
   "activity_participation":[
      "C4MIP" 
   ],
"model_component":
"aerosol":
   "description":"varies with physics-version (p==1 none, p==3 OMA, p==4 TOMAS, p==5 MATRIX)",
   "nominal_resolution":"250km" 
"atmos":
   "description":"GISS-E2.1 (2 x 2.5 degrees; 144 x 90 longitude/latitude; 40 levels; top level 0.1 hPa)",
   "nominal_resolution": "250 km" 
"atmosChem":
   "description":"varies with physics-version (p==1 Non-interactive, p>1 GPUCCINI)",
   "nominal_resolution": "250 km" 
"land":
   "description":"GISS LSM",
   "nominal_resolution":"250 km" 
"landIce":
   "description":"Fixed",
   "nominal_resolution":"250 km" 
"ocean":
   "description":"GISS Ocean (1 deg; 360 x 180 longitude/latitude;### 40 levels; top grid cell 0-10m)",
   "nominal_resolution":"100km" 
"seaIce":
   "description":"GISS SI",
   "nominal_resolution":"250km" 
}

**Comment by gavinny** [comment]
also:

"ocnBgchem":
description = "NOBM (NASA Ocean Biogeochemistry Model)"
nominal_resolution = "100 km"

**Comment by durack1** [comment]
@gavinny `GISS-E2-1-G-CC` is now registered, with a couple of tweaks that I assumed as you did not provide these details above (release_year, label*). Please take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know of any tweaks required. Also it seems we're missing version identifiers for the `LSM`, `GISS Ocean` etc, if you wanted we could add these
