### ISSUE TITLE
edit of source_id for GISS-E2.1-G

### ISSUE THREAD

**Issue by gavinny** [WCRP-CMIP/CMIP6_CVs#794]
ocean:
description = GISS Ocean (GO1, 1 degree; 360 x 180 longitude/latitude; 40 levels; top grid cell 0-10 m) 
nominal_resolution = 100 km
ocnBgchem:
description = none
nominal_resolution = none

**Comment by durack1** [comment]
@gavinny `GISS-E2-1-G` is now revised, with a the `release_year` also updated. Please take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know of any tweaks required. Ditto the #793 comments about version info for other components
