### ISSUE TITLE
edit for source_id GISS-E2-1-MA-G

### ISSUE THREAD

**Issue by gavinny** [WCRP-CMIP/CMIP6_CVs#795]
Please rename this as (or delete GISS-E2-1-MA-G, and register GISS-E2-2-G).

"GISS-E2-2-G":{
"activity_participation":[
"AerChemMIP CFMIP CMIP DAMIP DynVarMIP FAFMIP GMMIP ISMIP6 LS3MIP LUMIP OMIP PAMIP PMIP RFMIP SIMIP ScenarioMIP VIACSAB VolMIP"
],
"model_component":
"aerosol":
"description":"varies with physics-version (p==1 none, p==3 OMA, p==4 TOMAS, p==5 MATRIX)",
"nominal_resolution":"250km"
"atmos":
"description":"GISS-E2.2 (High-top, 2 x 2.5 degrees; 144 x 90 longitude/latitude; 102 levels; top level 0.002 hPa)",
"nominal_resolution": "250 km"
"atmosChem":
"description":"varies with physics-version (p==1 Non-interactive, p>1 GPUCCINI)",
"nominal_resolution": "250 km"
"land":
"description":"GISS LSM",
"nominal_resolution":"250 km"
"landIce":
"description":"Fixed",
"nominal_resolution":"250 km"
"ocean":
"description":"GISS Ocean (GO1, 1 deg; 360 x 180 longitude/latitude;### 40 levels; top grid cell 0-10m)",
"nominal_resolution":"100km"
"ocnBgchem":
"description": "none"
"nominal_resolution": "none"
"seaIce":
"description":"GISS SI",
"nominal_resolution":"250km"
}

**Comment by durack1** [comment]
@gavinny so this is just a straight rename `GISS-E2-1-MA-G` -> `GISS-E2-2-G`? Or are there also submodule changes that are also required? I see your `activity_participation` has expanded considerably

**Comment by durack1** [comment]
For reference:
```
        "GISS-E2-1-MA-G":{
            "activity_participation":[
                "CMIP",
                "RFMIP",
                "VolMIP"
            ],
            "cohort":[
                "Registered"
            ],
            "institution_id":[
                "NASA-GISS"
            ],
            "label":"GISS-E2.1MA-G",
            "label_extended":"GISS-E2.1MA-G",
            "model_component":{
                "aerosol":{
                    "description":"Varies with physics-version (p==1 none, p==3 OMA, p==4 TOMAS, p==5 MATRIX)",
                    "native_nominal_resolution":"250 km"
                },
                "atmos":{
                    "description":"GISS-E2.1MA (2.5x2 degree; 144 x 90 longitude/latitude; 102 levels; top level 0.002 hPa)",
                    "native_nominal_resolution":"250 km"
                },
                "atmosChem":{
                    "description":"Varies with physics-version (p==1 Non-interactive, p>1 GPUCCINI)",
                    "native_nominal_resolution":"250 km"
                },
                "land":{
                    "description":"GISS LSM",
                    "native_nominal_resolution":"250 km"
                },
                "landIce":{
                    "description":"none",
                    "native_nominal_resolution":"none"
                },
                "ocean":{
                    "description":"GISS Ocean (1 degree; 360 x 180 longitude/latitude; 32 levels; top grid cell 0-10 m)",
                    "native_nominal_resolution":"100 km"
                },
                "ocnBgchem":{
                    "description":"none",
                    "native_nominal_resolution":"none"
                },
                "seaIce":{
                    "description":"GISS SI",
                    "native_nominal_resolution":"100 km"
                }
            },
            "release_year":"2018",
            "source_id":"GISS-E2-1-MA-G"
        },
```

**Comment by gavinny** [comment]
Not quite. There is a correction needed in ocean (to 40 levels):

"ocean":{
                    "description":"GISS Ocean (1 degree; 360 x 180 longitude/latitude; 40 levels; top grid cell 0-10 m)",
                    "native_nominal_resolution":"100 km"


And we can probably update the “release_year” to 2019.

Thanks

Gavin

--
Gavin A. Schmidt
NASA Goddard Institute for Space Studies
2880 Broadway, New York NY 10025
Tel: 212 678 5627
Email: gavin.a.schmidt@nasa.gov<mailto:gavin.a.schmidt@nasa.gov>
URL: http://www.giss.nasa.gov/staff/gschmidt

**Comment by durack1** [comment]
thanks @gavinny I'll work with what you have submitted in https://github.com/WCRP-CMIP/CMIP6_CVs/issues/795#issue-500407478 and update the `release_year = 2019`. Happy for your label* entries to be the same as the registered `source_id`?

**Comment by gavinny** [comment]
Yes, thanks.

--
Gavin A. Schmidt
NASA Goddard Institute for Space Studies
2880 Broadway, New York NY 10025
Tel: 212 678 5627
Email: gavin.a.schmidt@nasa.gov<mailto:gavin.a.schmidt@nasa.gov>
URL: http://www.giss.nasa.gov/staff/gschmidt

**Comment by durack1** [comment]
@gavinny `GISS-E2-2-G` is now renamed and revised, with a the `release_year` also updated. Please take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know of any tweaks required. Ditto the #793 comments about version info for other components
