### ISSUE TITLE
experiment_id - please add new FAFMIP experiments

### ISSUE THREAD

**Issue by JonathanGregory** [WCRP-CMIP/CMIP6_CVs#797]
Please could you add the following three entries to the experiment_id table. This change to the experimental design was agreed by the steering committee and project participants at a meeting in Reading in April 2019.

"faf-heat-NA50pct":{
            "activity_id":[
                "FAFMIP"
            ],
            "additional_allowed_model_components":[
                "AER",
                "CHEM",
                "BGC"
            ],
            "description":"1xCO2 experiment, parallel to piControl, forced over the ocean by the same method and with the same surface net heat flux perturbation field as in faf-heat, except that within part of the North Atlantic ocean the perturbation is multiplied by 0.5",
            "end_year":"",
            "experiment":"control plus perturbative surface flux of heat into ocean",
            "experiment_id":"faf-heat-NA50pct",
            "min_number_yrs_per_sim":"70",
            "parent_activity_id":[
                "CMIP"
            ],
            "parent_experiment_id":[
                "piControl"
            ],
            "required_model_components":[
                "AOGCM"
            ],
            "start_year":"",
            "sub_experiment_id":[
                "none"
            ],
            "tier":"1"
},
"faf-heat-NA0pct":{
            "activity_id":[
                "FAFMIP"
            ],
            "additional_allowed_model_components":[
                "AER",
                "CHEM",
                "BGC"
            ],
            "description":"1xCO2 experiment, parallel to piControl, forced over the ocean by the same method and with the same surface net heat flux perturbation field as in faf-heat, except that within part of the North Atlantic ocean the perturbation is zero",
            "end_year":"",
            "experiment":"control plus perturbative surface flux of heat into ocean",
            "experiment_id":"faf-heat-NA0pct",
            "min_number_yrs_per_sim":"70",
            "parent_activity_id":[
                "CMIP"
            ],
            "parent_experiment_id":[
                "piControl"
            ],
            "required_model_components":[
                "AOGCM"
            ],
            "start_year":"",
            "sub_experiment_id":[
                "none"
            ],
            "tier":"2"
},
"faf-antwater-stress experiment":{
            "activity_id":[
                "FAFMIP"
            ],
            "additional_allowed_model_components":[
                "AER",
                "CHEM",
                "BGC"
            ],
            "description":"1xCO2 experiment, parallel to piControl, forced over the ocean with the momentum flux perturbation field of faf-stress and a surface freshwater flux of 0.1 Sv in total to be applied uniformly around the coast of Antarctica in whatever way is most suitable in the model",
            "end_year":"",
            "experiment":"control plus perturbative surface fluxes of momentum and freshwater into ocean, the latter around the coast of Antarctica only",
            "experiment_id":"faf-antwater-stress",
            "min_number_yrs_per_sim":"70",
            "parent_activity_id":[
                "CMIP"
            ],
            "parent_experiment_id":[
                "piControl"
            ],
            "required_model_components":[
                "AOGCM"
            ],
            "start_year":"",
            "sub_experiment_id":[
                "none"
            ],
            "tier":"2"
},

**Comment by durack1** [comment]
@JonathanGregory thanks for this. @taylor13 @veyring any comments? I plan to complete these registrations along with a number of model registrations later today

**Comment by taylor13** [comment]
@veyring, @JonathanGregory (See last paragraph for bottom line.)    I have no strong feelings about this, but I think the formal rule is that experiments can be added, but only if they are lower than tier 1.  ( faf-heat-NA50pct above is specified as tier 1.)  As I recall, this rule was put in place because modeling groups interested in a MIP had to commit to perform *all* the tier 1 experiments defined by that MIP.  It seems to me to be unfair to the modeling groups at this point to insist they perform additional experiments to participate in a MIP.

On the other hand if the experiment is really essential for understanding the suite of already-defined FAFMIP experiments, then I definitely think the rule should be bent.

Reading the experiment description, I can see this is an important but perhaps not essential additional experiment.  For the sake of following the rules, would it be o.k. to change the designation from tier 1 to tier 2 above, and by other means communicate to FAFMIP participants what priority you assign to each of the FAFMIP experiments?

All that being said, we are clearly not monitoring which modeling groups are living up to their commitments, so these commitments are somewhat meaningless.  Given that reality, perhaps we should let tier 1 experiments be added to accurately reflect their priority in the eyes of the MIPs.  I would favor that.

**Comment by durack1** [comment]
@JonathanGregory those 3 new experiments are now registered, please take a peek at [CMIP6_experiment_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_experiment_id.html) and let us know of any issues.

As an aside, your 3 new experiments have pushed the total CMIP6 experiment count to a total of 299,  it's almost a 300-strong experiment behemoth CMIP phase..

**Comment by JonathanGregory** [comment]
Dear Paul @durack1
Thanks for adding them - that looks just right. Would you like us to think of a further experiment to bring it to a round number? If the ocean is the bulk of the monstrous effort of CMIP6, I'd prefer to call it a leviathan.
Best wishes
Jonathan

**Comment by durack1** [comment]
@JonathanGregory thanks for the offer, however there is no need, there will be string of additional experiments registered before the end of the year I am sure, 300 will be blown past in no time.

Regarding naming, I would assume that the 3D ocean output is going to account for a fairly large proportion of the project storage footprint, ***Leviathan*** should be raised at the next CMIP panel meeting as a candidate

**Comment by durack1** [comment]
@charliepascoe @eguil @bnlawrence @martinjuckes just pinging you all that there are now 3 new FAFMIP experiments which should be updated on ES-DOCs. Also note #805 which will likely add another 6 experiments

**Comment by JonathanGregory** [comment]
Sorry I didn't answer Karl's comment, which I hadn't noticed. Yes, I understand the rule about not adding to Tier 1. I'd like to reassure you that this change was made with the agreement of FAFMIP participants. We did discuss at some length whether it was reasonable to add a requirement, and everyone agreed that it was.

**Comment by taylor13** [comment]
@martinjuckes @davidhassell @wjcollins -- As agreed at the WIP meeting 2020-02-25, I am reopening this issue because I don't think the changes made to the experiment_id CV have propagated to ES-DOC and the data request.

**Comment by durack1** [comment]
Closing as noted in email earlier this week
