### ISSUE TITLE
experiment_id: case sensitive? 

### ISSUE THREAD

**Issue by RobertPincus** [WCRP-CMIP/CMIP6_CVs#81]
Dear colleagues - 

Are values of experiment_id case sensitive? I ask because the capitalization in the RFMIP protocol paper is, in some cases, inconsistent with the value in the controlled vocabulary. As one example, we specify an experiment called "piClim-histall" (http://www.geosci-model-dev.net/9/3447/2016/gmd-9-3447-2016.pdf, table 2) that is listed as "piClim-histAll" in the controlled vocabulary. 

If differing capitalization might be problematic I will provide a detailed list of spelling changes, but if the controlled vocabulary is case-insensitive I won't bother. 

Thanks - Robert Pincus

**Comment by taylor13** [comment]
@RobertPincus   I *hope* software will be case insensitive, but can't guarantee it.  If I could trouble you to provide the list of spelling changes, I would be much obliged.  
thanks,
Karl

**Comment by RobertPincus** [comment]
@taylor13  - 

To follow the protocol paper please make the following changes to the experiment_ids 

piClim-GHG	 -> piClim-ghg
piClim-histAll -> piClim-histall
piClim-histNat -> piClim-histnat
piClim-histGHG -> piClim-histghg 

- @RobertPincus
