### ISSUE TITLE
experiment_ids missing

### ISSUE THREAD

**Issue by RobertPincus** [WCRP-CMIP/CMIP6_CVs#82]
Dear colleagues - 

The RFMIP protocol includes two coupled historical simulations with specified aerosol optical properties, listed in Table 5 of the RFMIP protocol (http://www.geosci-model-dev.net/9/3447/2016/gmd-9-3447-2016.pdf). These are hist-spAerO3_all and hist-spAerO3_aer. The current controlled vocabulary, alas, includes neither of these, but does include an experiment_id "hist-spAerO3". 

Thanks - Robert Pincus

**Comment by durack1** [comment]
Copied from #95 by @RobertPincus and closed

Hello there - 

Based on interactions with DAMIP, we have changed the experiment titles and experiment_ids for some of the RFMIP experiments. Please change all instances of "spAerO3" in experiment_ids to "spAer". 

Thanks - Robert Pincus
