### ISSUE TITLE
institution_id registration of UCI

### ISSUE THREAD

**Issue by ypeings** [WCRP-CMIP/CMIP6_CVs#826]
+ institution_id = UCI
+ institution = Department of Earth System Science, University of California Irvine, Irvine, CA 92697, USA

**Comment by durack1** [comment]
@ypeings thanks for this, will `UCI` be contributing simulations to CMIP6?

**Comment by ypeings** [comment]
Yes Paul we are running simulations for PAMIP with a model that has not yet been registered as a CMIP6 model, SC-WACCM4.

**Comment by durack1** [comment]
@ypeings no problem, I'll await the `SC-WACCM4` registration and batch process these together

**Comment by durack1** [comment]
@ypeings we should also update your input4MIPs registration so it's consistent with this one, see [input4MIPs_institution_id.json](https://github.com/PCMDI/input4MIPs-cmor-tables/blob/master/input4MIPs_institution_id.json#L16)

**Comment by ypeings** [comment]
Done

**Comment by durack1** [comment]
@ypeings it will need a change to the file in [https://github.com/PCMDI/input4MIPs-cmor-tables/input4MIPs_institution_id.json](https://github.com/PCMDI/input4MIPs-cmor-tables/blob/master/input4MIPs_institution_id.json#L16), I'll add an issue to that repo

**Comment by durack1** [comment]
@ypeings that registration is in place, take a peek at [CMIP6_institution_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_institution_id.html) and let me know if any tweaks are required
