### ISSUE TITLE
source_id registration of CESM1-WACCM-SC

### ISSUE THREAD

**Issue by ypeings** [WCRP-CMIP/CMIP6_CVs#827]
label = CESM1-WACCM-SC
label_extended = Community Earth System Model 1, with the Whole Atmosphere Community Climate Model and Specified Chemistry
source_id = CESM1-WACCM-SC
institution_id = UCI
release_year = 2011
activity_participation = PAMIP

aerosol:
description = MOZART-specified (same grid as atmos)
nominal_resolution = 250 km
atmos:
description = WACCM4 (1.9x2.5 finite volume grid; 144 x 96 longitude/latitude; 66 levels; top level 5.9e-06 mb)
nominal_resolution = 250 km
atmosChem:
description = MOZART-specified (same grid as atmos)
nominal_resolution = 250 km
land:
description = CLM4.0
nominal_resolution = 250 km    
landIce:
description = none
nominal_resolution = none 
ocean:
description = POP2 (320x384 longitude/latitude; 60 levels; top grid cell 0-10 m)
nominal_resolution = 100 km
ocnBgchem:
description = BEC (same grid as ocean)
nominal_resolution = 100 km
seaIce:
description = CICE4 (same as grid as ocean)
nominal_resolution = 100 km

**Comment by durack1** [comment]
@ypeings the `institution_id` will need to be `UCI` as you are running and publishing the simulations, right? Also, you can use the `label` and `label_extended` attributes to record a much more verbose model description if you like, while `*WACCM-*` may mean something to folks in the know, the `-SC` intrigues me and could do with a better descriptor.

You can edit the issue directly above

**Comment by ypeings** [comment]
Done, thanks Paul. I had put NCAR because this is were the model has been developed, we are only users here at UCI.

**Comment by durack1** [comment]
@ypeings no problem. You'll also need to bring yourself up to speed on preparing model results for submission to ESGF, I assume you'll be using CMOR which should streamline the workload a little - more info can be obtained from https://pcmdi.llnl.gov/CMIP6/Guide/modelers.html

**Comment by durack1** [comment]
@ypeings that registration is in place, take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know if any tweaks are required
