### ISSUE TITLE
institution_id registration of NCC

### ISSUE THREAD

**Issue by IngoBethke** [WCRP-CMIP/CMIP6_CVs#83]
```
institution_id = NCC
institution = Norwegian Climate Centre c/o Norwegian Meteorological Institute, P.O. Box 43, Blindern, Oslo 0313, Norway
```

**Comment by durack1** [comment]
@IngoBethke we currently have listed:
```
'NCC': 'UNI Bjerknes Centre for Climate Research, Norwegian Climate Centre, Bergen 5007, Norway'
```
Is this incorrect? In addition we are aiming for a standard format that includes a `city zip/postcode`, `country` format. So if you wish for edits, please follow this format

**Comment by IngoBethke** [comment]
Hello Paul, 

(cc to our PIs Christoph Heinze and Trond Iversen)
> 'NCC': 'UNI Bjerknes Centre for Climate Research, Norwegian Climate Centre, Bergen 5007, Norway'
> Is this incorrect? In addition we are aiming for a standard format that includes a city zip/postcode, country format. So if you wish for edits, please follow this format
> 

I’m not exactly sure where that information comes from. We should probably revise it. 

To explain: There are around 10 institutions in Norway that contribute to the development of NorESM and there is no one institution that has a clear “leading” role. Therefore we created the virtual organisation Norwegian Climate Centre (NCC) which can be seen as a collaborative agreement of the partners that develop NorESM. NCC is however not a legal nor physical entity.    

If a physical contact address is required then I’d suggest to use 
‘NCC’ : 'Norwegian Climate Centre c/o Norwegian Meteorological Institute, P.O. Box 43, Blindern, Oslo 0313, Norway'

Regards, 
Ingo

**Comment by durack1** [comment]
@IngoBethke no problems, I now understand the issue.. FYI there are a number of other "consortia" based institutions that we have registered, see the [`MIROC`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_institution_id.json#L15) and [`EC-Earth-Consortium`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_institution_id.json#L10) entries in the current `CMIP6_institution_id.json` file.

Feel free to revise your `NCC` registration as you see fit - we are trying to maintain the same format (including a postal code) so that these `ids` and the details inside can be used systematically (for e.g. to plot on a global map etc)

**Comment by durack1** [comment]
@IngoBethke any chance you've been able to resolve the query above?

**Comment by IngoBethke** [comment]
Hello Paul 

Our PI’s are currently discussing it and hopefully will reach a consensus either today or tomorrow. Very likely we will follow your suggestion to define a NorESM consortium but we are still a bit unsure concerning the level of detail in the institutional_id.  

Regards, 
Ingo

**Comment by durack1** [comment]
@IngoBethke great, looking forward to resolving this along with the outstanding `NorESM-*` issues

**Comment by IngoBethke** [comment]
Hello Paul, 

Our entry for the institution_id is now finalised to 

institution_id = NCC
institution = NorESM Climate modeling Consortium consisting of CICERO (Center for International Climate and Environmental Research - Oslo), MET-Norway (Norwegian Meteorological Institute), NERSC (Nansen Environmental and Remote Sensing Center), NILU (Norwegian Institute for Air Research), UiB (University of Bergen), UiO (University of Oslo) and UNI (Uni Research), Norway

I will look into the NorESM-* issues but as already mentioned our model configurations are not finalised at this stage. I can specify "TBD" at places where we don't have information yet if that that would be of any value. 

Cheers, 
Ingo

**Comment by durack1** [comment]
@IngoBethke great thanks for getting closer on the `institution_id`. We've been including postal codes in the format, so how does the below suit?
```"NCC": "NorESM Climate modeling Consortium consisting of CICERO (Center for International Climate and Environmental Research, Oslo 0349), MET-Norway (Norwegian Meteorological Institute, Oslo 0313), NERSC (Nansen Environmental and Remote Sensing Center, Bergen 5006), NILU (Norwegian Institute for Air Research, Kjeller 2027), UiB (University of Bergen, Bergen 5007), UiO (University of Oslo, Oslo 0313) and UNI (Uni Research, Bergen 5008), Norway"
```

**Comment by IngoBethke** [comment]
This looks perfect. Thanks for putting effort into this.

**Comment by durack1** [comment]
@IngoBethke ok great, I'll get that merged in today.. Regarding the `NorESM-*` entries, yes please do complete whatever we can finalise to date.. If you leave some TBD entries in there that's fine, we can always come back and revise/amend them once the details are finalised. It would be good to get the open issues resolved (#84, #85, #86, #87 and #88)

**Comment by IngoBethke** [comment]
Hi Paul, 

I've received a request to add one more partner to the NCC definition (see below). I hope this can be fixed. 

Best, Ingo 

"NCC": "NorESM Climate modeling Consortium consisting of 
BCCR (Bjerknes Centre for Climate Research, Bergen 5007), 
CICERO (Center for International Climate and Environmental Research, Oslo 0349), 
MET-Norway (Norwegian Meteorological Institute, Oslo 0313), 
NERSC (Nansen Environmental and Remote Sensing Center, Bergen 5006), 
NILU (Norwegian Institute for Air Research, Kjeller 2027), 
UiB (University of Bergen, Bergen 5007), 
UiO (University of Oslo, Oslo 0313) and 
UNI (Uni Research, Bergen 5008), Norway"

**Comment by durack1** [comment]
Reopening

**Comment by durack1** [comment]
@IngoBethke is there a "master" institution for which we can use the post/zip code? For [`NCC'](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_institution_id.json#L16), we've included this for the last listed "master" institution. We'd would like to follow this example for `NCC`

**Comment by IngoBethke** [comment]
If not absolutely necessary I'd prefer not to single out any one partner. NCC is just a virtual entity (created for the purpose of CMIP and similar comparisons) and doesn't have any headquarter. The core development of NorESM is funded through research council projects (i.e. soft funding), with each project having a life time of a couple of years and a different partner taking the lead. As a consequence, functions like model governance, support etc are rotating between the partners. Therefore I'm afraid that the EC-EARTH example does not suit NorESM.  

Also, our contribution to CMIP6 MIPs is strictly distributed, meaning that one partner institute will be in charge of producing output for a certain subset of MIPs with a certain model configuration while another partner will be in charge of producing output for another subset using a different model configuration. Therefore the contact information provided should be specific for each model configuration and MIP.

**Comment by durack1** [comment]
@IngoBethke the reason that we're pushing for this is so we can easily parse information for each institution and represent these on a map, with the current format it doesn't easily facilitate this use case. For the purposes noted above, would your institution be suitable?

**Comment by durack1** [comment]
@IngoBethke that change is now in place, please review [CMIP6_institution_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_institution_id.html) and let me know if any further changes are required
