### ISSUE TITLE
source_id registration of 4AOP

### ISSUE THREAD

**Issue by yntellier** [WCRP-CMIP/CMIP6_CVs#831]
label = 4AOP
label_extended = Line-By-Line Radiative Transfer Model v1.5, Laboratoire Meteorologie Dynamique, GEISA spectroscopic database
source_id = 4AOP-v1.5
institution_id = IPSL
release_year = 2019
activity_participation = [RFMIP]

aerosol:
description = none
nominal_resolution = none
atmos:
description = none
nominal_resolution = none
atmosChem:
description = none
nominal_resolution = none
land:
description = none
nominal_resolution = none
landIce:
description = none
nominal_resolution = none
ocean:
description = none
nominal_resolution = none
ocnBgchem:
description = none
nominal_resolution = none
seaIce:
description = none
nominal_resolution = none

**Comment by durack1** [comment]
@yntellier that registration is now complete, note that periods are not valid characters and so your model is now registered as `4AOP-v1-5`, please take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know if any further changes are required
