### ISSUE TITLE
source_id INM-CM5-0 add activity_participation ScenarioMIP

### ISSUE THREAD

**Issue by volodin1** [WCRP-CMIP/CMIP6_CVs#833]
Please add activity_participation ScenarioMIP for INM-CM5-0 model

**Comment by durack1** [comment]
@volodin1 that change has now been made, please take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know of any further tweaks required
