### ISSUE TITLE
Proposed hist-totalO3 experiment for DAMIP

### ISSUE THREAD

**Issue by npgillett** [WCRP-CMIP/CMIP6_CVs#838]
hist-totalO3 | DAMIP | historical total-ozone-only run | tier 3 | none| piControl | AOGCM AER BGC | 1850 | 2020 | 171 | CMIP | 
 
Historical total-ozone-only. In models with coupled chemistry, the chemistry scheme should be turned off, and the simulated ensemble mean monthly mean 3D ozone concentrations from the CMIP6 historical simulations should be prescribed through the depth of the atmosphere. In models without coupled chemistry the same ozone prescribed in the CMIP6 historical simulations should be prescribed.

This is simulation is being documented in a GMD paper currently in preparation.

**Comment by slavakharin** [comment]
I inserted the above information into experiment template

        "hist-O3":{
            "activity_id":[
                "DAMIP"
            ],
            "additional_allowed_model_components":[
                "AER",
                "BGC"
            ],
            "description":"Historical total-ozone-only. In models with coupled chemistry, the chemistry scheme should be turned off, and the simulated ensemble mean monthly mean 3D ozone concentrations from the CMIP6 historical simulations should be prescribed through the depth of the atmosphere. In models without coupled chemistry the same ozone prescribed in the CMIP6 historical simulations should be prescribed.",
            "end_year":"2020",
            "experiment":"historical total-ozone-only run",
            "experiment_id":"hist-totalO3",
            "min_number_yrs_per_sim":"171",
            "parent_activity_id":[
                "CMIP"
            ],
            "parent_experiment_id":[
                "piControl"
            ],
            "required_model_components":[
                "AOGCM"
            ],
            "start_year":"1850",
            "sub_experiment_id":[
                "none"
            ],
            "tier":"3"
        },

**Comment by durack1** [comment]
@martinjuckes @charliepascoe @davidhassell @momipsl pinging you all so that the data request and ES-Docs can be updated to reflect this new experiment when it is finalized and merged

**Comment by durack1** [comment]
@npgillett I assume the data request for this experiment will follow the same template as `hist-aer` etc?

**Comment by taylor13** [comment]
I think to avoid any additional work for Martin, it is probably essential that the data request for the "new" CMIP5 experiments to be identical to their counterparts in CMIP6.  Is that o.k.?

**Comment by durack1** [comment]
@npgillett @slavakharin the DAMIP experiment_id `hist-totalO3` is now registered, take a peek at the latest [CMIP6_experiment_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_experiment_id.html) and let me know if any further tweaks are required

**Comment by taylor13** [comment]
@martinjuckes @davidhassell -- As agreed at the WIP meeting 2020-02-25, I am reopening this issue because I don't think the changes made to the experiment_id CV have propagated to ES-DOC and the data request.

**Comment by durack1** [comment]
Closing as noted in email earlier this week

**Comment by charliepascoe** [comment]
I have assumed that this experiment requires 3 ensemble members. Similar experiments have 3 ensemble members, also @npgillett commented that the data request should follow the hist-aer experiment which also has 3 members.  
@npgillett Nathan mentioned a GMD paper that describes this experiment which is in preparation, is there a link to that that we can use?
