### ISSUE TITLE
Clean up experiment_id grammar inconsistencies in hist-aer, hist-stratO3, ssp245-stratO3 and hist-1950

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#839]
The following tweaks should be implemented to clean up some inconsistent formatting:

hist-aer [`"description":"Historical anthropogenic-Aerosols-only run"`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json#L3744) should be `"Historical anthropogenic aerosols-only run"`

hist-stratO3 [`"description":"Historical stratospheric-ozone-only...`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json#L4118) should be `"Historical stratospheric ozone-only..."` also true for `experiment` field

ssp345-strat03 [`"description":"Extension of stratospheric-ozone-only run under SSP2-4.5...`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json#L7924) should be `"Extension of stratospheric ozone-only run under SSP2-4.5..."` also true for experiment field

Ref https://github.com/WCRP-CMIP/CMIP6_CVs/pull/837#discussion_r349688547

**Comment by durack1** [comment]
@martinjuckes @charliepascoe @davidhassell @momipsl pinging you all so that the data request and ES-Docs can be updated to reflect these tweaked experiments when they are finalized and merged

**Comment by durack1** [comment]
Also adding `hist-1950` `"description":"Coupled integrationswith historic external forcings (as in highresSST-present)"` needs a space

**Comment by taylor13** [comment]
@martinjuckes @davidhassell -- As agreed at the WIP meeting 2020-02-25, I am reopening this issue because I don't think the changes made to the experiment_id CV have propagated to ES-DOC and the data request.

**Comment by charliepascoe** [comment]
ES-Doc updates done for experiments hist-stratO3 and ssp245-stratO3.
No changes made to hist-1950 and hist-aer.
These changes will go online once the details of histSST-noLu and ssp370pdSST have been approved by the AerChemMIP PI.

**Comment by durack1** [comment]
@charliepascoe thanks for the update, once @martinjuckes confirms the data request is also updated to account for these new/revised experiments we can close out this issue

**Comment by durack1** [comment]
Closing as noted in email earlier this week
