### ISSUE TITLE
activit_id - Add activity CORDEX to source_id EC-Earth3-Veg

### ISSUE THREAD

**Issue by shutingdk** [WCRP-CMIP/CMIP6_CVs#843]
The EC-Earth modelling group is going to contribute to CORDEX using both EC-Earth3 and EC-Earth3-Veg. Currently CORDEX is only registered under EC-Earth3. Could you please add CORDEX to the activity_participation list for EC-Earth3-Veg? Thanks!

**Comment by durack1** [comment]
@shutingdk that change is now in place, please review [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know of any further tweaks required
