### ISSUE TITLE
external_variables missing from CMIP6_required_global_attributes

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#849]
Following PCMDI/CMOR#541 and https://github.com/PCMDI/cmip6-cmor-tables/issues/278 `external_variables` will need to be added to the [CMIP6_required_global_attributes.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_required_global_attributes.json)

@mauzey1 @taylor13

**Comment by taylor13** [comment]
external_variables is only *conditionally* required.  It is required when areacella and/or areacello and/or volcella and/or volcello are included in the cell_measures attribute.  Can PrePARE do a conditional test?  

In any case I *think* but am not sure that  "required_global_attributes" includes only those that are *invariably* require, not conditionally required.

**Comment by durack1** [comment]
@taylor13 good point, however I think this will need to be solved downstream as it was an omission that needed updating. @mauzey1 let me know if this is an incorrect assumption

**Comment by mauzey1** [comment]
@taylor13 @durack1 
Okay, I will instead make a test in PrePARE that will check for `external_variables` if values are present in `cell_measures`.

Including `external_variables` in `required_global_attributes` was causing issues with other tests so we should revert that change.

**Comment by durack1** [comment]
@mauzey1 thanks for the heads up, I had not realized how intricate this was and so will revert WCRP-CMIP/CMIP6_CVs#849

**Comment by durack1** [comment]
Reopening as `external_variables` is a *conditional* attribute, and consequently is causing problems when defined as required
