### ISSUE TITLE
source_id registration of CAS-ESM2-0 -- based on CAS-ESM1-0

### ISSUE THREAD

**Issue by czypku** [WCRP-CMIP/CMIP6_CVs#852]
label = CAS-ESM 2.0
label_extended = CAS-ESM 2.0 (Chinese Academy of Sciences Earth System Model version 2.0)
source_id = CAS-ESM2-0
institution_id = CAS
release_year = 2019
activity_participation = [AerChemMIP][C4MIP][CFMIP][CMIP][CORDEX][DAMIP][DynVarMIP][FAFMIP][GMMIP][GeoMIP][HighResMIP][LS3MIP][LUMIP][OMIP][PMIP][SIMIP][ScenarioMIP][VIACSAB][VolMIP]

aerosol:
description = IAP AACM
nominal_resolution = 100 km
atmos:
description = IAP AGCM 5.0 (Finite difference dynamical core; 256 x 128 longitude/latitude; 35 levels; top level 2.2 hPa)
nominal_resolution = 140 km
atmosChem:
description = IAP AACM
nominal_resolution = 100 km
land:
description = CoLM
nominal_resolution = 140 km
landIce:
description = none
nominal_resolution = none
ocean:
description = LICOM2.0 (LICOM2.0, primarily 1deg; 362 x 196 longitude/latitude; 30 levels; top grid cell 0-10 m)
nominal_resolution = 100 km
ocnBgchem:
description = IAP OBGCM
nominal_resolution = 100 km
seaIce:
description = CICE4
nominal_resolution = 100 km

**Comment by czypku** [comment]
@durack1 
CAS-ESM 1.0 refers to 
source_id registration of CAS-ESM1-0 #479

Thanks.

**Comment by durack1** [comment]
@czypku just clarifying, did you want the existing registration of `CAS-ESM1-0` to be renamed, along with the changes above to `CAS-ESM2-0` or is this altogether a new registration that sits alongside the existing v1.0?

**Comment by czypku** [comment]
@durack1 Thanks for your reply. It's better to rename the existing registration of CAS-ESM1-0, along with the changes above to CAS-ESM2-0.

**Comment by czypku** [comment]
@durack1 By the way, the changes are as follows:

label = CAS-ESM 2.0
label_extended = CAS-ESM 2.0 (Chinese Academy of Sciences Earth System Model version 2.0)
source_id = CAS-ESM2-0
institution_id = CAS
release_year = 2019

atmos:
description = IAP AGCM 5.0 (Finite difference dynamical core; 256 x 128 longitude/latitude; 35 levels; top level 2.2 hPa)
nominal_resolution = 140 km

Other information is not changed.

**Comment by durack1** [comment]
@czypku those changes are now in place, just to note the registered `nominal_resolution` entries (see [CMIP6_nominal_resolution.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_nominal_resolution.json)) don't include 140 km, so I have reset this to 100 km. Please take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know of any further tweaks required

**Comment by czypku** [comment]
@durack1 OK. Thanks very much. A question is that, will the DRS Name of the model be automatically changed to  CAE-ESM2-0([https://cera-www.dkrz.de/ords/f?p=127:72:116125468441063:::::](https://cera-www.dkrz.de/ords/f?p=127:72:116125468441063:::::))? 

I have checked the DRS name and found that it didn't change.

**Comment by durack1** [comment]
@czypku the citation information is managed by DRKZ. I imagine this will be updated once folks return from the holiday break.

@martinast

**Comment by czypku** [comment]
@durack1 Thanks for your reply. I will wait until the citation information is updated.

Yes. We haven't published any data yet using the source_id CAS-ESM1-0.

**Comment by MartinaSt** [comment]
@czypku @durack1 The citation entries have been changed. 

As this change is a change of the DRS_id or the identifier of the data used as criteria for changes, this cannot be done automatically because there is no possibility to distinguish between a new model and a change of the identifier of an existing model. 

Thus it is a manual process. I monitor changes but it sometimes take a little while...

**Comment by czypku** [comment]
@MartinaSt @durack1 Thanks a lot for your help and explanations. I checked and found that DRS name was updated. The problem has been solved. Happy new year!

**Comment by durack1** [comment]
@MartinaSt thanks from me too and happy 2020!
