### ISSUE TITLE
source_id registration of MIROC-ES2H-NB

### ISSUE THREAD

**Issue by tinoue70** [WCRP-CMIP/CMIP6_CVs#856]
label = MIROC-ES2H-NB
label_extended =  MIROC-ES2H with No BiogenicCycle
source_id = MIROC-ES2H-NB
institution_id = MIROC
release_year = 2019
activity_participation = [AerChemMIP, CMIP]

aerosol: 
  description = SPRINTARS6.0
  native_nominal_resolution = 100 km
atmos: 
  description = CCSR AGCM (T85; 256 x 128 longitude/latitude; 81 levels; top level 0.004 hPa)
  native_nominal_resolution = 250 km
atmosChem: 
  description = CHASER4.0
  native_nominal_resolution = 250 km
land: 
  description = MATSIRO6
  native_nominal_resolution = 100 km
landIce: 
  description = none
  native_nominal_resolution = none
ocean: 
  description = COCO4.9 (tripolar primarily 1deg; 360 x 256 longitude/latitude; 63 levels; top grid cell 0-2 m)
  native_nominal_resolution = 100 km
ocnBgchem: 
  description = none
  native_nominal_resolution = none
seaIce: 
  description = COCO4.9
  native_nominal_resolution = 100 km

**Comment by durack1** [comment]
@tinoue70 just checking, is the `aerosol` component really on a different grid to the `atmos`? I would have guessed all the atmospheric model components would all share the atmos grid resolution of 250 km. Same question for land.

**Comment by durack1** [comment]
@tinoue70 wondering if you can clarify my question above https://github.com/WCRP-CMIP/CMIP6_CVs/issues/856#issuecomment-570294465. I would like to confirm details before registering this additional model

**Comment by tinoue70** [comment]
@durack1 sorry to be late. It seems that `atmos` grid resolution is wrong. And if so,  MIROC-ES2H has the same mistake. I'm now asking our model guys to check them again, please wait for a few days.

**Comment by tinoue70** [comment]
@durack1 our model guy checked and found that the resolution of `atmos` is wrong, the true value is **100km**, not 250km. Others are OK.

And MIROC-ES2H has the same mistake. I'll raise another issue about this later.

**Comment by durack1** [comment]
@tinoue70 apologies for the delay, that registration of MIROC-ES2H-NB and resolution correction for MIROC-ES2H is now implemented. Please take another look at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know if there's anything else requiring a tweak
