### ISSUE TITLE
Correction to source_id GISS-E2-1-H

### ISSUE THREAD

**Issue by gavinny** [WCRP-CMIP/CMIP6_CVs#858]
Fix incorrect layering in ocean model_component description (from 26 to 32). 

"GISS-E2-1-H":{  
            "model_component":{
                "ocean":{
                    "description":"HYCOM Ocean (~1 degree tripolar grid; 360 x 180 latitude/longitude; 32 levels; top grid cell 0-10 m)",
                    "native_nominal_resolution":"100 km"
                },

**Comment by durack1** [comment]
@gavinny probably also need to correct the `360 x 180 latitude/longitude` -> `360 x 180 longitude/latitude`, right?

**Comment by gavinny** [comment]
Good catch!

--
Gavin A. Schmidt
NASA Goddard Institute for Space Studies
2880 Broadway, New York NY 10025
Tel: 212 678 5627
Email: gavin.a.schmidt@nasa.gov<mailto:gavin.a.schmidt@nasa.gov>
URL: http://www.giss.nasa.gov/staff/gschmidt

**Comment by durack1** [comment]
@gavinny that should be fixed, take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know if any other details need updating

**Comment by gavinny** [comment]
Thanks. Two other possible tweaks to the release years:

GISS-E2-1-H
NASA-GISS
2016
Should be 2019

GISS-E3-G
NASA-GISS
2018

Should be 2020

Thanks again.

Gavin

--
Gavin A. Schmidt
NASA Goddard Institute for Space Studies
2880 Broadway, New York NY 10025
Tel: 212 678 5627
Email: gavin.a.schmidt@nasa.gov<mailto:gavin.a.schmidt@nasa.gov>
URL: http://www.giss.nasa.gov/staff/gschmidt

**Comment by durack1** [comment]
@gavinny apologies for the delay, those changes are now implemented. Please take another look at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know if there's anything else requiring a tweak
