### ISSUE TITLE
source_id registration of HiRAM-SIT

### ISSUE THREAD

**Issue by rceclccr** [WCRP-CMIP/CMIP6_CVs#860]
label = HiRAM-SIT-HR
label_extended = HiRAM Coupling 1-D SIT (25 km atmosphere and 25 km ocean)
source_id = HiRAM-SIT-HR
institution_id = AS-RCEC
release_year = 2018
activity_participation = HighResMIP

aerosol:
description = none
nominal_resolution = none
atmos:
description = GFDL-HiRAM (Cubed-sphere (c384) - 0.25 degree nominal horizontal resolution; 1536 x 768 longitude/latitude; 32 levels; top level 1 hPa)
nominal_resolution = 25 km
atmosChem:
description = none
nominal_resolution = none
land:
description = GFDL-LM3 (same grid as atmos)
nominal_resolution = 25 km    
landIce:
description = none
nominal_resolution = none 
ocean:
description = SIT (1-D, tripolar - nominal 0.25 deg; 1440 x 1080 longitude/latitude; 50 levels with skin layer & 1-m resolution for uppermost 10m)
nominal_resolution = 25 km
ocnBgchem:
description = none
nominal_resolution = none
seaIce:
description = none
nominal_resolution = none

-----------------------------------------------------------------------------------------

label = HiRAM-SIT-LR
label_extended = HiRAM Coupling 1-D SIT (50 km atmosphere and 25 km ocean)
source_id = HiRAM-SIT-LR
institution_id = AS-RCEC
release_year = 2018
activity_participation = HighResMIP

aerosol:
description = none
nominal_resolution = none
atmos:
description = GFDL-HiRAM (Cubed-sphere (c192) - 0.5 degree nominal horizontal resolution; 768 x 384 longitude/latitude; 32 levels; top level 1 hPa)
nominal_resolution = 50 km
atmosChem:
description = none
nominal_resolution = none
land:
description = GFDL-LM3 (same grid as atmos)
nominal_resolution = 50 km    
landIce:
description = none
nominal_resolution = none 
ocean:
description = SIT (1-D, tripolar - nominal 0.25 deg; 1440 x 1080 longitude/latitude; 50 levels with skin layer & 1-m resolution for uppermost 10m)
nominal_resolution = 25 km
ocnBgchem:
description = none
nominal_resolution = none
seaIce:
description = none
nominal_resolution = none

**Comment by durack1** [comment]
@rceclccr apologies for the delay, those two registrations are now implemented. Please take another look at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know if there's anything requiring a tweak
