### ISSUE TITLE
source_id -- correct IPSL-CM atmos description

### ISSUE THREAD

**Issue by glevava** [WCRP-CMIP/CMIP6_CVs#861]
Hi @durack1 , we made a mistake in the description of the atmos realm of the IPSL models.
`top level 40000m` must be changed to `top level 80000m` at lines 4419, 4481, 4530 and 4579.

Thanks for your help

**Comment by durack1** [comment]
@glevava thanks for this, I just noticed you have 4 models which look similar, but while we're changing this should `IPSL-CM6A-LR` be renamed `IPSL-CM6A-ATM-LR` to keep consistency with the other 3 `IPSL-CM6A-ATM-HR`, `IPSL-CM7A-ATM-HR` and `IPSL-CM7A-ATM-LR`. I also wonder whether the model description, which is `DYNAMICO-LMDZ (NPv6; ..` for the *CM7A* models and `LMDZ (NPv6, ..` should be homogenized?

**Comment by glevava** [comment]
Hi @durack1 no we have 4 models as expected. `IPSL-CM6A-LR` is different from `IPSL-CM6A-ATM-LR` in many ways. Also, we would keep `DYNAMICO-LMDZ` for `IPSL-CM7A` which is a new atmospheric component. You only need to accept the PR with the modification regarding the top level value for LMDZ only. Many thanks !

**Comment by durack1** [comment]
@glevava no problems, I had also not considered that `IPSL-CM6A-LR` has already had data published on the ESGF (as has `IPSL-CM6A-ATM-HR`). Those changes are now in place, please take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know if any further tweaks are required.
