### ISSUE TITLE
source_id -- correction to the native_nominal_resolution of MIROC-ES2H

### ISSUE THREAD

**Issue by tinoue70** [WCRP-CMIP/CMIP6_CVs#863]
For MIROC-ES2H, `native_nominal_resolution` of `atmos` must be **100 km**, not 250 km. Please correct it.

Others are OK.

**Comment by durack1** [comment]
@tinoue70 apologies for the delay, that registration of MIROC-ES2H-NB and resolution correction for MIROC-ES2H is now implemented. Please take another look at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know if there's anything else requiring a tweak
