### ISSUE TITLE
Increase duration of ssp370SST-low* in AerChemMIP

### ISSUE THREAD

**Issue by wjcollins** [WCRP-CMIP/CMIP6_CVs#867]
Please can you increase the duration of ssp370SST-lowNTCF, ssp370SST-lowAer, ssp370-lowBC, ssp370-lowO3, ssp370-lowCH4. These should all match ssp370SST (this was extended in #760 ).

Start year: 2015
Duration: 86 years (until 2100

**Comment by charliepascoe** [comment]
I'll update the duration of these experiments in the ES-DOC database once the changes have been made to the CMIP6-CV.

**Comment by durack1** [comment]
@charliepascoe thanks for chiming in, we plan to get this update completed today. While we're on the topic, issue #845 will also likely require some coincident ES-DOC changes, once we have ascertained with the associated MIP-chairs what their preferred updated values should be

**Comment by charliepascoe** [comment]
@durack1 Thanks, I'll keep a watch on it for any changes.

**Comment by charliepascoe** [comment]
@wjcollins Do you intend to change the duration specification for ssp370-lowNTCF as well? 
It currently has start year=2015, end year=2055 and min yrs=41.

**Comment by durack1** [comment]
@wjcollins happy to process this change this week, IF we can resolve the open question above.

**Comment by wjcollins** [comment]
Yes, let's increase that as well .

**Comment by durack1** [comment]
@wjcollins we omitted some additional experiments, I'll add `ssp370-lowBC`, `ssp370-lowCH4`, `ssp370-lowNTCF`, `ssp370-lowO3`, `ssp370SST-lowAer`, `ssp370SST-lowBC`, `ssp370SST-lowCH4`, `ssp370SST-lowNTCF`, `ssp370SST-lowO3`, `ssp370SST-ssp126Lu` to the list

**Comment by durack1** [comment]
@wjcollins strike that, there were a number of typos/duplicates above, so `ssp370-lowBC` should be `ssp370SST-lowBC`, `ssp370-lowCH4` -> `ssp370-lowCH4, `ssp370-lowO3` -> `ssp370SST-lowO3`.

The process list is more correctly: `ssp370-lowNTCF`, `ssp370SST-lowAer`, `ssp370SST-lowBC`, `ssp370SST-lowCH4`, `ssp370SST-lowNTCF`, `ssp370SST-lowO3`, `ssp370SST-ssp126Lu`

**Comment by durack1** [comment]
@wjcollins those changes are now in place, please take a peek at [CMIP6_experiment_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_experiment_id.html) and let me know of any corrections required

**Comment by taylor13** [comment]
@martinjuckes @davidhassell -- As agreed at the WIP meeting 2020-02-25, I am reopening this issue because I don't think the changes made to the experiment_id CV have propagated to ES-DOC and the data request.

**Comment by durack1** [comment]
Closing as noted in email earlier this week
