### ISSUE TITLE
required model components: AerChemMIP histSST-noLu has an incorrect model component spec

### ISSUE THREAD

**Issue by charliepascoe** [WCRP-CMIP/CMIP6_CVs#868]
The "required model components" for histSST-noLu are listed as AOGCM  with additional allowed components AER CHEM BGC.
I think it should be AGCM AER with additional allowed components CHEM BGC.

histSST-noLU is a prescribed SST experiment with a set up that is similar to histSST, therefore it follows that it should have the same model components as histSST.

**Comment by taylor13** [comment]
well-spotted.  I agree that at least AGCM and AER are required.  Looks likely that CHEM is *not* required, so I agree:
required:  AGCM AER
allowed:  CHEM BGC

**Comment by durack1** [comment]
@charliepascoe thanks for catching this, it's fixed in `6.2.46.0` see [CMIP6_experiment_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_experiment_id.html)
