### ISSUE TITLE
source_id registration of UKESM1-ice-LL

### ISSUE THREAD

**Issue by matthew-mizielinski** [WCRP-CMIP/CMIP6_CVs#869]
Hi @durack1, The UK model configuration being used for ISMIP6 has diverged sufficiently from UKESM1-0-LL that we would like to register it separately in order to be able to properly identify and document it in ES-Doc. As such I would like to register "UKESM1-ice-LL" with the following properties;

    label = UKESM1.ice-LL
    label_extended = UKESM1.ice-N96ORCA1
    source_id = UKESM1-ice-LL
    institution_id = MOHC, NERC
    release_year = 2019
    activity_participation = [ISMIP6]

    aerosol:
    description = UKCA-GLOMAP-mode
    nominal_resolution = 250 km
    atmos:
    description = MetUM-HadGEM3-GA7.1 (N96; 192 x 144 longitude/latitude; 85 levels; top level 85 km)
    nominal_resolution = 250 km
    atmosChem:
    description = none
    nominal_resolution = none
    land:
    description = JULES-ISMIP6-1.0
    nominal_resolution = 250 km    
    landIce:
    description = BISICLES-UKESM-ISMIP6-1.0
    nominal_resolution = 5 km
    ocean:
    description = NEMO-HadGEM3-GO6.0 (eORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 360 x 330 longitude/latitude; 75 levels; top grid cell 0-1 m)
    nominal_resolution = 100 km
    ocnBgchem:
    description = none
    nominal_resolution = none
    seaIce:
    description = CICE-HadGEM3-GSI8 (eORCA1 tripolar primarily 1 deg; 360 x 330 longitude/latitude)
    nominal_resolution = 100 km

@rssmith -- please double check the above and shout if I've made any mistakes.

**Comment by durack1** [comment]
@matthew-mizielinski thanks for this, just checking the `label` handles, did you really want a period?

Also, as the "original" model is named `UKESM1-0-LL`, I wonder, for future-proofing yourself whether `UKESM1-0-ice-LL` might be a better bet, it then allows you to tweak things and release `UKESM1-1-ice-LL` etc into the future?

**Comment by rssmith** [comment]
Hi @durack1, the label, and everything else, is correct, and is a (possibly misguided) deliberate attempt to fudge the sub-version number for this model. This ice configuration has non-ice components different enough from UKESM1.0-LL that it felt a bit misleading to simply add -ice- into that. It's also very likely that future versions of the ice configuration /will/ be much more similar to  UKESM1.x-LL, at which point a naming convention of UKESM1.x-ice-LL will be more appropriate.

**Comment by durack1** [comment]
@rssmith no problem, we can proceed with what you have.

**Comment by durack1** [comment]
@matthew-mizielinski @rssmith that registration is now in place. Please take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know of any further tweaks required

**Comment by matthew-mizielinski** [comment]
Thanks Paul!

**Comment by rssmith** [comment]
@matthew-mizielinski @durack1 that all looks right. Thank you
