### ISSUE TITLE
Add ssp370-lowNTCFCH4 and ssp370SST-lowNTCFCH4 experiments to AerChemMIP

### ISSUE THREAD

**Issue by wjcollins** [WCRP-CMIP/CMIP6_CVs#873]
We wish to add two further experiments to AerChemMIP: ssp370-lowNTCFCH4 and ssp370SST-lowNTCFCH4.

ssp370-lowNTCFCH4

Experimental set up and diagnostics as ssp370-lowNTCF
ID: ssp370-lowNTCFCH4
Description: This experiment is identical to ssp370-lowNTCF  except that the methane concentrations also follow the "low" scenario from SSP3-7.0_lowNTCF.
Experiment: SSP3-7.0, with low NTCF emissions and CH4 concentrations
tier: 3
Start year: 2015
End year: 2100
Duration: 86 years
Parent: historical
Required components: AOGCM AER
Optional components: CHEM BGC

ssp370SST-lowNTCFCH4

Experimental set up and diagnostics as ssp370SST-lowNTCF
Experiment description: This experiment is identical to ssp370SST-lowNTCF except that the CH4 concentration also follow the "low" scenario i.e. SSP3-7.0_lowNTCF.
ID: ssp370SST-lowNTCFCH4
Experiment: SSP3-7.0, prescribed SSTs, with low NTCF emissions and methane concentrations
tier: 3
Start year: 2015
End year: 2100
Duration: 86 years
Parent: historical
Required components: AGCM AER
Optional components: CHEM BGC

**Comment by durack1** [comment]
@wjcollins those new experiments are now registered, please take a look at the new vs existing experiments in [CMIP6_experiment_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_experiment_id.html) and let me know of any further tweaks required

**Comment by durack1** [comment]
@charliepascoe @taylor13

**Comment by taylor13** [comment]
@martinjuckes @davidhassell -- As agreed at the WIP meeting 2020-02-25, I am reopening this issue because I don't think the changes made to the experiment_id CV have propagated to ES-DOC and the data request.

**Comment by charliepascoe** [comment]
@wjcollins The new AerChemMIP experiments are on lines 70 and 71 of the "experiment" tab: https://github.com/ES-DOC/esdoc-docs/blob/master/cmip6/experiments/spreadsheet/experiments.xlsx

**Comment by durack1** [comment]
@charliepascoe great thanks for the heads up, so ES-DOC is now in sync. I'll wait for an update from @martinjuckes that the data request is up-to-date and then we can close this issue

**Comment by durack1** [comment]
Closing as noted in email earlier this week
