### ISSUE TITLE
source_id -- correction to the native_nominal_resolution of MIROC*, again

### ISSUE THREAD

**Issue by tinoue70** [WCRP-CMIP/CMIP6_CVs#874]
I'm so sorry that recently I've made wrong requests to modify `native_nominal_resolution` in source_id, because of  mis-understanding and mis-communication in our team members.

Please fix `native_nominal_resolution` of MIROC* models as follows:

MIROC-ES2H:
aerosol: "250 km"
atmos: "250 km"
atmosChem: "500 km"
land: "250 km"

MIROC-ES2H-NB
aerosol: "250 km"
atmos: "250 km"
atmosChem: "500 km"
land: "250 km"

MIROC-ES2L
aerosol: "500 km" 
land: "500 km"

MIROC6
aerosol: "250km"
land: "250km"

**Comment by durack1** [comment]
@tinoue70 thanks for following this up. Those changes are now in place, please review the details are [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know of any further tweaks required
