### ISSUE TITLE
source_id -- Please modify description of MIROC-ES2H-NB/atmosChem

### ISSUE THREAD

**Issue by tinoue70** [WCRP-CMIP/CMIP6_CVs#880]
After the correction of `native_nominal_resolution` (#874), we noticed that it is unclear that the resolution of `atmosChem `is different from `atmos`, `aerosol ` and `land`.

So please modify `description` of `atmosChem` for MIROC-ES2H-NB as follows:

`"description":"CHASER4.0 (T42; 128 x 64 longitude/latitude; 81 levels; top level 0.004 hPa)"`

**Comment by durack1** [comment]
@tinoue70 apologies for the delay in getting this updated. The change is now implemented, so please take a look at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know if there is anything else requiring a tweak
