### ISSUE TITLE
Statement of backward/forward compatibility

### ISSUE THREAD

**Issue by zklaus** [WCRP-CMIP/CMIP6_CVs#885]
Some changes to the CV would induce changes to the directories and/or filenames of data. An example of such a change is [here](https://github.com/WCRP-CMIP/CMIP6_CVs/commit/915a010f8495d61a795fbbb4ff5064e191b0e5b5). Looking at [the standards document](http://goo.gl/v1drZl) this problem seems to be limited to changes to `source_id` and `institution_id`.

Could we add a formal statement that such changes are no longer possible once data has been published on the ESGF?
Perhaps just in the README of this repository?

Opening this issue I now see that the issue template already says
> We can update details iteratively, until you begin writing CMIP6 data.

but it would be reassuring to know that we can always update the CV without fear of losing access to our existing local data due to changed paths.

Thanks for you consideration!

**Comment by taylor13** [comment]
Yes, I think we have tried to avoid changing anything in the CV that would impact files already written, if the changes made would affect file names, search facets, or anything else relied on by the ESGF infrastructure or by users to find and obtain the data.  
Does anyone know of any exceptions to this rule?  (There might be a few things in the "data request" that have changed that might have some impact on the earliest files published.)

**Comment by durack1** [comment]
@zklaus in principle the workflow for modeling groups would be to download the latest version of [CMOR](https://cmor.llnl.gov/) along with the latest version of the [cmip6-cmor-tables](https://github.com/PCMDI/cmip6-cmor-tables/) as inputs to CMOR, and then write their data. This would ensure that only registered institution_id's, along with registered source_id's, experiment_id's, activity_id's etc would be accepted.

In practice it is up to a modeling group to meet the conformance standards of their data however they like, considering available compute and storage. Even during ESGF publication of the data, while definitely not advised there are instances of groups editing the contents of the [input file](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json) to [PrePARE](https://cmor.llnl.gov/mydoc_cmip6_validator/) which subverts the conformance checks that are a required step of publication.

If you notice inconsistent entries, please do raise an errata, along with opening a specific issue on this repo (and link these). While most issues can be caught and fixed, catching these early before they propagate is the key.

I will close this issue as there is no immediate action associated with it.

**Comment by zklaus** [comment]
Yet the latest release of cmor and the associated tables is from 5 Aug 2019 and does not contain the change I mention in the OP, however, the data on ESGF does follow that new version and also adds a host of things (mostly new `source_id`s) that cannot be understood with the officially released version.

This is mostly fine where only new things are added. In that case, people should be working with the CV straight from this repository, as advised [in the cmip6 table repository](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/README.md).

But where the change is backward-incompatible, ie invalidates data that was written with an earlier version of the CV, I feel that such a change should generally not be allowed, at least when data has been published already.

Adding a note to that effect to the README in this repository would be the associated immediate action.

**Comment by taylor13** [comment]
Would the following sentence satisfy everyone?
"The controlled vocabularies for CMIP6 will be augmented (e.g., as new models and experiments are registered), but there should be no changes in the existing vocabulary that would impair searches of and access to already published data or that would in any way invalidate published data."

**Comment by durack1** [comment]
@zklaus just to clarify, the [cmip6-cmor-tables](https://github.com/PCMDI/cmip6-cmor-tables) used by CMOR, merge information from the [CMIP6 data request](http://clipc-services.ceda.ac.uk/dreq/index.html) (primarily variable definitions), coordinate, formula_terms and grid information which is defined by [CF conventions metadata standards](http://cfconventions.org/) along with harvested registered CMIP6 information from the [CMIP6_CVs](https://github.com/WCRP-CMIP/CMIP6_CVs) (the activity_id, experiment_id, institution_id and source_id/model etc info) which is harvested nightly and embedded in the [`CMIP6_CV.json` file](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json), and not "released".

The function of "releases" with the `cmip6-cmor-tables` is to ensure that versions of [CMOR (latest v3.5.0)](https://anaconda.org/conda-forge/cmor) work with co-tagged versions of the table file inputs.

This may have not been clear. It would be useful to know how you folks are using these as inputs

**Comment by durack1** [comment]
@zklaus @taylor13 that tweak to the [README.md](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/README.md) is now in place, let me know if any further tweaks/clarifications are required
