### ISSUE TITLE
"activity_id -- add 'PMIP'" to CSIRO ACCESS-ESM1-5

### ISSUE THREAD

**Issue by sjmarsland** [WCRP-CMIP/CMIP6_CVs#889]
"activity_id -- add 'PMIP'" to CSIRO ACCESS-ESM1-5

**Comment by durack1** [comment]
@sjmarsland that change is now in place, take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know if any other tweaks are required

**Comment by sjmarsland** [comment]
Thanks Paul. Looks good
