### ISSUE TITLE
institution_id edit of MIROC

### ISSUE THREAD

**Issue by kodamail** [WCRP-CMIP/CMIP6_CVs#89]
institution_id =  MIROC

institution = JAMSTEC (Japan Agency for Marine-Earth Science and Technology, Kanagawa, Japan), AORI (Atmosphere and Ocean Research Institute, The University of Tokyo, Chiba, Japan), NIES (National Institute for Environmental Studies, Ibaraki, Japan), and AICS (RIKEN Advanced Institute for Computational Science, Kobe, Japan)

**Comment by durack1** [comment]
@kodamail we're trying to maintain consistency across the contributed information, so in addition to your entry above can you provide a post/zip code similar to:
```
"PCMDI":"Program for Climate Model Diagnosis and Intercomparison,
Lawrence Livermore National Laboratory,
Livermore, CA 94550, USA"
```
Would the revision:
```
"MIROC":"JAMSTEC (Japan Agency for Marine-Earth Science and Technology, Kanagawa),
AORI (Atmosphere and Ocean Research Institute, The University of Tokyo, Chiba),
NIES (National Institute for Environmental Studies, Ibaraki),
and AICS (RIKEN Advanced Institute for Computational Science, Kobe), Kanagawa 237-0061, Japan"
```

Be suitable?

**Comment by kodamail** [comment]
No. It should be like:
`"MIROC":"JAMSTEC (Japan Agency for Marine-Earth Science and Technology, Kanagawa 236-0001, Japan), AORI (Atmosphere and Ocean Research Institute, The University of Tokyo, Chiba 277-8564, Japan), NIES (National Institute for Environmental Studies, Ibaraki 305-8506, Japan), and AICS (RIKEN Advanced Institute for Computational Science, Hyogo 650-0047, Japan)"`
