### ISSUE TITLE
Add activity_id C4MIP, CDRMIP and PAMIP to source_id NorESM2-LM

### ISSUE THREAD

**Issue by matsbn** [WCRP-CMIP/CMIP6_CVs#890]

**Comment by durack1** [comment]
Also add CDRMIP and PAMIP (Ref #891, #892)

**Comment by durack1** [comment]
@matsbn those changes are now in place, take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know if any other tweaks are required
