### ISSUE TITLE
source_id -- Please modify description of MIROC-ES2H/atmosChem

### ISSUE THREAD

**Issue by tinoue70** [WCRP-CMIP/CMIP6_CVs#896]
After modification (#880) it seems that `atmosChem` of MIROC-ES2H and MIROC-ES2H-NB is different in [source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html), but these are the same. So please modify `description` of `atomChem` as follows:

`"description":"CHASER4.0 (T42; 128 x 64 longitude/latitude; 81 levels; top level 0.004 hPa)"`

**Comment by durack1** [comment]
@tinoue70 just so we catch all the outstanding issues, can you please review all the `MIROC` contributions by browsing [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and using the search entry "MIROC". This way I can minimize my workload but catching any outstanding issues at once

**Comment by durack1** [comment]
@tinoue70 just checking if the above is the only change required? If yes, I will get this done by the end of the week

**Comment by tinoue70** [comment]
@durack1 sorry to be late. I asked our modeling people again, and found nothing else to be changed for now. Please do it.

**Comment by durack1** [comment]
@tinoue70 thanks for clarifying, the change is now in place. Please review [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know of any further changes
