### ISSUE TITLE
appropriate value for mfo when not defined?

### ISSUE THREAD

**Issue by markcollier** [WCRP-CMIP/CMIP6_CVs#899]
Hard to know where is the appropriate forum for my simple question. When defining a quantity like mfo (mass transport in the ocean) where a value is normally required but perhaps is not resolved in the model (e.g. the english channel in my case), what value should be used? I suppose I am meaning missing or 0? I have noticed that ACCESS-CM2 used 0 however a missing value would be more informative and useful in terms of generating stats.? 
Thanks in advance

**Comment by durack1** [comment]
@markcollier that variable does exist, see http://clipc-services.ceda.ac.uk/dreq/u/baa60bf2-e5dd-11e5-8482-ac72891c3257.html and [PCMDI/cmip6-cmor-tables/Tables/CMIP6_Omon.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_Omon.json#L2897-L2914).

If a model doesn't resolve this field, then I would use the missing value identifier which is more accurate than 0. In the case that a user wanted to generate a multi-model mean, a NaN will be a far better value to assess than 0 if the transport is not resolved.

**Comment by markcollier** [comment]
i'll send a message to the ACCESS folk in response to their oversight...
