### ISSUE TITLE
ESGF data with incomplete CMIP6_CV

### ISSUE THREAD

**Issue by MartinaSt** [WCRP-CMIP/CMIP6_CVs#900]
Hi Paul (@durack1)

I have repeated issues with data users wanting to cite CMIP6 data, which I do not have in the system because of an incomplete CMIP6_CV source_id registration. MIPs missing in the activity_participation for a certain source_id are the issue.
[Current example is DAMIP for IPSL-CM6A-LR:
https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L4598 ]

Can you assist me in getting an overview over CMIP6 datasets published in the ESGF with incomplete registrations? And in nagging on your points of contact to complete their registration?
Afterwards I can take over to get the data citation information provided by the citation managers.

Thanks a lot and best wishes,
Martina

**Comment by durack1** [comment]
@MartinaSt no problem, we may have to open an issue for each incomplete registration. It may also require an email to modeling groups to let them know that their registered content (contained in the CMIP6_CVs) is being depended upon by other infrastructure, so details need to be consistent.

So for ref:
https://esgf-node.llnl.gov/search/cmip6/?source_id=IPSL-CM6A-LR&activity_id=DAMIP
https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L4598-L4614

@taylor13 pinging you on this thread

**Comment by MartinaSt** [comment]
Thanks @durack1!
Could you and maybe Sasha investigate, which data in the ESGF has incomplete registration information? It would also be good to have a regular check of these inconsistencies.

**Comment by MartinaSt** [comment]
Ok, I got an overview of the inconsistencies between data in ESGF and CMIP6 CV registration. It is a bit tricky with the experiments belonging to different MIPs. Missing in the CV are:


Date | source_id | institution_id | MIP | comment   
-- | -- | -- | -- | -- 
21.04.2020 | CMCC-ESM2-SR5 | CMCC | OMIP | DOI; known issue of wrong source_id in ESGF publication   
21.04.2020 | CNRM-CM6-1-HR | CNRM-CERFACS | GMMIP |   
21.04.2020 | CNRM-ESM2-1 | CNRM-CERFACS | GMMIP |   
21.04.2020 | CanESM5 | CCCma | PAMIP |   
21.04.2020 | FIO-ESM-2-0 | FIO-QLNM | ISMIP6 | DOI; single dataset seemingly wrongly ESGF published 
21.04.2020 | GFDL-AM4 | NOAA-GFDL | RFMIP |     
21.04.2020 | GISS-E2-1-H | NASA-GISS | CFMIP |     
21.04.2020 | INM-CM5-H | INM | HighResMIP |     
21.04.2020 | IPSL-CM6A-LR | IPSL | DAMIP,HighResMIP,PAMIP |     
21.04.2020 | MCM-UA-1-0 | UA | ScenarioMIP |   
21.04.2020 | MPI-ESM1-2-HR | MPI-M | RFMIP | completely retracted data, wrongly ESGF published   

I would not deal with the commented ones, as for CMCC and MPI-M these are known issues; and it seems to be an error in ESGF publication for FIO as well.

**Comment by durack1** [comment]
@sashakames pinging you on this thread

**Comment by MartinaSt** [comment]
@durack1 Could you open issues for the other modeling centers as you have done for IPSL, please?

- CCCma
- CNRM-CERFACS
- NOAA-GFDL
- NASA-GISS
- INM
- UA

(see my comment above for the details on source_id and missing activity_participation).

Thanks!

**Comment by durack1** [comment]
@sashakames can we add this validation to the publication update, so that these issues don't happen again? Instead of allowing publication, an error should be thrown indicating that this `activity_id` is not registered and must be before publication will complete

**Comment by taylor13** [comment]
Yes, I agree with this recommendation.  If implementing it would be as easy as it would seem, then we should enforce things at publication time to avoid infrastructure problems down the road.

**Comment by durack1** [comment]
@MartinaSt are you happy for this issue to be closed? As we now have an issue defined for each of the problems you have defined, these will be dealt with within each specific issue

@sashakames to catch this publication tweak, should we open a linked issue in an ESGF repo somewhere, I am reluctant to close this issue BEFORE we have assigned the appropriate tasks/issues across the relevant repos. I think this check is a key augmentation to prevent future problems propagating

**Comment by MartinaSt** [comment]
@durack1 @sashakames thanks for your support.

Could we leave this issue open until the registrations are completed? The table above is useful for me to keep track. I will close this issue when I have added the citation entries. Is this ok with you?

**Comment by durack1** [comment]
@MartinaSt sure thing, it would also be good for an issue to be generated so our publisher tweak is implemented. Such a change (if folks also update their publisher version after it is released) should catch this issue before it occurs moving forward

**Comment by MartinaSt** [comment]
@durack1 @sashakames I totally agree that we should catch problems where they occur. The implementation of a check in the ESGF publisher is the right location to avoid the publication of data with incomplete registrations. 

Until this is implemented and installed at the data nodes, I can do +/- monthly semi-automated checks for missing MIP registrations.

**Comment by durack1** [comment]
@MartinaSt all referenced issues are now closed, so please amend this issue as required and close once you're done.

@sashakames did we need to open and issue in [ESGF/esg-publisher](https://github.com/ESGF/esg-publisher) to make sure we get the `activity_id` checked, or is that already done?

**Comment by MartinaSt** [comment]
@durack1 Ok, I will close this issue. Thanks for your support!

@sashakames Please notify me once the activity_id check is implemented. Thanks.
