### ISSUE TITLE
Update CNRM-* registration to include ALL activity_id entries

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#903]
@rigoudyg it appears that [`CNRM-CM6-1-HR` has published `GMMIP` data on ESGF](https://esgf-node.llnl.gov/search/cmip6/?activity_id=GMMIP&source_id=CNRM-CM6-1-HR), but this is not listed in the [activity participation field of the model registration](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L1556-L1563).

In addition [`CNRM-ESM2-1` has published `GMMIP` data on ESGF](https://esgf-node.llnl.gov/search/cmip6/?activity_id=GMMIP&source_id=CNRM-ESM2-1), but this is not listed in the [activity participation field of the model registration](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L1609-L1622).

Are there any other missing *MIPs/activity_id entries that we should also add for either of these source_id registrations? Or any other details that require amendment whilst this correction is implemented?

ping @esgpub @Mpmoine @senesis @MartinaSt

Ref https://github.com/WCRP-CMIP/CMIP6_CVs/issues/900#issuecomment-617085459

**Comment by rigoudyg** [comment]
@durack1, sorry for those incoherences. They passed through several checks.

We have checked the list once more for CNRM-Cerfacs contribution and we did not notice other changes to be done.

**Comment by durack1** [comment]
@rigoudyg thanks for this. The changes are now in place, please take a look at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know of any other fixes or tweaks required
