### ISSUE TITLE
institution_id registration of PNNL-WACCEM

### ISSUE THREAD

**Issue by beharrop** [WCRP-CMIP/CMIP6_CVs#912]
institution_id = WACCEM-PNNL
institution = PNNL (Pacific Northwest National Laboratory, Richland, WA 99352, USA)

**Comment by durack1** [comment]
@beharrop just curious if just `PNNL` is what you want, I understand this is the  WACCEM project which is hosted at `PNNL`, but not sure it's in the right order. It also means that if `PNNL` (non-WACCEM) wants to contribute any other simulations to CMIP6, doesn't give you much leeway.

Take a peek at the other registrations and their format at [CMIP6_institution_id.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_institution_id.json).

Just a question here, you can register what you like

Following other examples the registration would look like:
```
"institution_id":"institution"
"PNNL":"Pacific Northwest National Laboratory, Richland, WA 99352, USA",
```

**Comment by beharrop** [comment]
@durack1 Thanks for the suggestions.  We discussed this, and have decided to keep in line with the other DOE projects in the registrations that include the name of the project instead of just the institution.  We will go ahead and switch the order of PNNL and WACCEM in the institution_id.  Please use

institution_id = PNNL-WACCEM
institution = PNNL (Pacific Northwest National Laboratory, Richland, WA 99352, USA)

**Comment by durack1** [comment]
@beharrop no problem, in addition to PNNL being expanded, did you want to expand WACCEM in the institution description field?

**Comment by beharrop** [comment]
@durack1 I don't think it is necessary.  E3SM and RUBISCO don't expand their acronyms.

**Comment by durack1** [comment]
No problem, it’s up to you. The `institution_id` field is used in directory structure, the long description remains in our CV registration, with no active use within file or directory names

**Comment by durack1** [comment]
@beharrop all done, please take a peek at [CMIP6_institution_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_institution_id.html) and let me know of any further tweaks required

**Comment by beharrop** [comment]
Looks great, thanks @durack1 !
