### ISSUE TITLE
source_id registration of CAM-MPAS

### ISSUE THREAD

**Issue by beharrop** [WCRP-CMIP/CMIP6_CVs#913]
label = CAM-MPAS
label_extended = CAM MPAS (Community Atmosphere Model – Model for Prediction Across Scales)
source_id = CAM-MPAS
institution_id = WACCEM-PNNL
release_year = 2018
activity_participation = [HighResMIP]

aerosol:
description = MACv2-SP prescribed aerosol optical properties and cloud droplet concentration modifiers (same grid as atmos )
nominal_resolution = 25 km
atmos:
description = CAM-MPAS (CAMv5.4 with Grell-Freitas deep convection; MPASv4, C-grid staggered centroidal Voronoi tesselation atmosphere 30 km mesh; 32 vertical levels)
nominal_resolution = 25 km
atmosChem:
description = none
nominal_resolution = 25 km
land:
description = CLM (v4.0, same grid as atmos), River Transport Model (v1.0)
nominal_resolution = 25 km
landIce:
description = none
nominal_resolution = none
ocean:
description = input4MIPs SSTs and SeaIce for HighResMIP data input
nominal_resolution = 25 km
ocnBgchem:
description = none
nominal_resolution = none
seaIce:
description = input4MIPs SSTs and SeaIce for HighResMIP data input
nominal_resolution = 25 km

**Comment by durack1** [comment]
@beharrop thanks for the submission, normally the "description" fields are used to define the model version, grid and longitude x latitude information - for examples see [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) the "description" field is shown under each realm heading, so "ocean" is the ocean, description field for e.g.

An example from `ACCESS-ESM1-5` ocean is `ACCESS-OM2 (MOM5, tripolar primarily 1deg; 360 x 300 longitude/latitude; 50 levels; top grid cell 0-10 m)`, there are some other examples that use unstructured grids also contained in the link above

**Comment by beharrop** [comment]
@durack1 thanks for the clarification.  I have modified the descriptors to better match the examples you provided.  I am pinging my collaborator @kosaka90 to double check my cell and edge counts for the mesh we used.  Does this work, or should I change ocean and ice to something like "prescribed"?

aerosol:
description = MACv2-SP (same grid as atmos )
nominal_resolution = 25 km
atmos:
description = CAM-MPAS (CAMv5.4 with Grell-Freitas deep convection; MPASv4, C-grid staggered centroidal Voronoi tesselation atmosphere 30 km mesh with 655362 cells and 1966080 edges; 32 vertical levels)
nominal_resolution = 25 km
atmosChem:
description = none
nominal_resolution = 25 km
land:
description = CLM (v4.0, same grid as atmos), River Transport Model (v1.0)
nominal_resolution = 25 km
landIce:
description = none
nominal_resolution = none
ocean:
description = none
nominal_resolution = 25 km
ocnBgchem:
description = none
nominal_resolution = none
seaIce:
description = none
nominal_resolution = 25 km

**Comment by durack1** [comment]
@beharrop so I assume that you are not running an interactive 3D ocean or sea-ice for this model? If so, there's no need to define a resolution as there is no model component to describe and these entries should be "none".

For the atmos, what is the `atmos` upper-most level, so following the `ACCESS-ESM1-5` model again we have HadGAM2 (r1.1, N96; 192 x 145 longitude/latitude; 38 levels; **top level 39255 m**)

**Comment by beharrop** [comment]
@durack1 that's right, no interactive ocean or sea-ice for our model.  I have modified these entries accordingly, as well as added the top level into the atmos entry.

aerosol:
description = MACv2-SP (same grid as atmos )
nominal_resolution = 25 km
atmos:
description = CAM-MPAS (CAMv5.4 with Grell-Freitas deep convection; MPASv4, C-grid staggered centroidal Voronoi tesselation atmosphere 30 km mesh with 655362 cells and 1966080 edges; 32 vertical levels, model top 40363 m)
nominal_resolution = 25 km
atmosChem:
description = none
nominal_resolution = 25 km
land:
description = CLM (v4.0, same grid as atmos), River Transport Model (v1.0)
nominal_resolution = 25 km
landIce:
description = none
nominal_resolution = none
ocean:
description = none
nominal_resolution = none
ocnBgchem:
description = none
nominal_resolution = none
seaIce:
description = none
nominal_resolution = none

**Comment by durack1** [comment]
@beharrop you may want to also check the `aerosol` and `atmosChem` fields for tweaks, look like they also need a refresh. The MACv2-SP is one of the input4MIPs datasets, not an atmospheric model component, so that field should also be "none"

**Comment by beharrop** [comment]
@durack1 Good catch, thanks.  I have updated the `aerosol` and `atmosChem` fields.

aerosol:
description = none
nominal_resolution = none
atmos:
description = CAM-MPAS (CAMv5.4 with Grell-Freitas deep convection; MPASv4, C-grid staggered centroidal Voronoi tesselation atmosphere 30 km mesh with 655362 cells and 1966080 edges; 32 vertical levels, model top 40363 m)
nominal_resolution = 25 km
atmosChem:
description = none
nominal_resolution = none
land:
description = CLM (v4.0, same grid as atmos), River Transport Model (v1.0)
nominal_resolution = 25 km
landIce:
description = none
nominal_resolution = none
ocean:
description = none
nominal_resolution = none
ocnBgchem:
description = none
nominal_resolution = none
seaIce:
description = none
nominal_resolution = none

**Comment by durack1** [comment]
@beharrop all done, please take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know of any further tweaks required

**Comment by beharrop** [comment]
@durack1 This looks great.  I do have a question regarding the aerosol portion.  I thought you had suggested removing the MACv2-SP specification, but maybe I misunderstood you.  I noticed that quite a few models in the source_id link you posted have "prescribed MACv2-SP" for their aerosol component.  If this is the appropriate way to specify how aerosols were handled, could we have the same text appear for our aerosol treatment?

**Comment by durack1** [comment]
@beharrop the registration was from the content in https://github.com/WCRP-CMIP/CMIP6_CVs/issues/913#issuecomment-620250456. As the model doesn't have an interactive aerosol component, I was suggesting leave this as "none", but if you want to follow other model entries we could add `none, prescribed MACv2-SP` if you like? Let me know

**Comment by beharrop** [comment]
@durack1 That sounds good to me.

**Comment by beharrop** [comment]
@durack1 one other thing.  @kosaka90 pointed out that many of the models in this list distinguish HR and LR in their source_id names.  We are also planning to publish a lower resolution version of the same model.  Do you think it would be best to adopt a similar naming convention to other modeling groups?  In other words, this entry would be CAM-MPAS-HR and then, presumably, we would open another issue for a CAM-MPAS-LR that is nearly identical except for the grid information.

**Comment by durack1** [comment]
@beharrop @kosaka90 good call, it's best that we plan ahead as much as possible so that it creates less work for you down the road, I'll update the `source_id = CAM-MPAS-HR` while updating `aerosol` too

**Comment by durack1** [comment]
@beharrop @kosaka90 take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) which should now be all fixed

**Comment by beharrop** [comment]
Thanks @durack1 Does it matter that the label and source_id no longer match?

**Comment by durack1** [comment]
That’s really up to you. The `source_id` is used as the infrastructure identifier, and labels are intended for use in documentation with no character limits or limitations. Consequently, you could have “CAM MPAS” for a label, with the `label_extended` a more verbose identifier. If this is your default model, then “CAM-MPAS” is fine, the low res could be “CAM-MPAS (low resolution)” for e.g.

**Comment by beharrop** [comment]
@durack1 Thanks for the clarification.  I think it would be more transparent to use CAM-MPAS-HR for both source_id and label.

**Comment by kosaka90** [comment]
Thanks, @durack1 . I agree with @beharrop to make source_id and label consistent. Could you do that?

**Comment by durack1** [comment]
Sure, please take another look over all the entries and confirm the only change is the label update. Once this is confirmed I’ll drop it in the to-do queue

**Comment by beharrop** [comment]
Looks good to me; do you see anything else @kosaka90.  Thanks for all your help with this @durack1 .  I hope we haven't been too difficult to work with :)

**Comment by kosaka90** [comment]
Same here, the only thing to update is the label. Thank you so much for your help, @durack1 !

**Comment by durack1** [comment]
@beharrop @kosaka90 all done. Take one last peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) to double check, but I assume we're all good now

**Comment by beharrop** [comment]
@durack1 Looks great.  Thanks again!

**Comment by kosaka90** [comment]
Yes, thank you so much @durack1 !
