### ISSUE TITLE
Missing activity_id registrations

### ISSUE THREAD

**Issue by MartinaSt** [WCRP-CMIP/CMIP6_CVs#923]
@durack1 @sashakames : I have checked the completeness of activity_id registrations again and found one new and one, which I probably missed last time because of these experiments belonging to multiple MIPs.

institution_id | source_id | MIP | comment | issue | citation
 -- | -- | -- | -- | -- | -- |
NCAR | CESM2 | FAFMIP | [ESGF link](https://esgf-node.llnl.gov/search/cmip6/?activity_id=FAFMIP&source_id=CESM2) 20200428 | #924 | done | 
NCAR | CESM2-WACCM | RFMIP | [ESGF link](https://esgf-node.llnl.gov/search/cmip6/?activity_id=RFMIP&source_id=CESM2-WACCM) 20191120 | #925 |  done | 
MIROC | MIROC-ES2H-NB | RFMIP | exp. belonging to AerChemMIP and RFMIP was published for RFMIP (drs_id) [ESGF link](https://esgf-node.llnl.gov/search/cmip6/?activity_id=RFMIP&source_id=MIROC-ES2H-NB) 20200428 | #926 | Error in ESGF publication |

@taylor13 ping!

**Comment by durack1** [comment]
@sashakames it's these issues that we were hoping could be caught by augmenting the publisher to check for a valid `activity_id` in the `activity_participation` as per ESGF/esg-publisher#156

**Comment by MartinaSt** [comment]
@durack1 Can you close this issue after closing #926 ? Thanks, I am done.
