### ISSUE TITLE
New source_id: CESM1-3-CAM5-SE-CMIP5-LR

### ISSUE THREAD

**Issue by strandwg** [WCRP-CMIP/CMIP6_CVs#931]
"CESM1-3-CAM5-SE-CMIP5-LR":{
            "activity_participation":[
                "HighResMIP",
            ],
            "cohort":[
                "Registered"
            ],
            "institution_id":[
                "NCAR"
            ],
            "label":"CESM1-3-CAM5-SE-CMIP5-LR",
            "label_extended":"CESM1-3-CAM5-SE-CMIP5-LR",
            "model_component":{
                "aerosol":{
                    "description":"MAM3 (same grid as atmos)",
                    "native_nominal_resolution":"100 km"
                },
                "atmos":{
                    "description":""CAM5.2 (1 degree spectral element; 48602 cells; 30 levels; top level 2.25 mb)",
                    "native_nominal_resolution":"100 km"
                },
                "atmosChem":{
                    "description":"MAM3 (same grid as atmos)",
                    "native_nominal_resolution":"100 km"
                },
                "land":{
                    "description":"CLM4 (same grid as atmos)",
                    "native_nominal_resolution":"100 km"
                },
                "ocean":{
                    "description":"POP2 (320x384 longitude/latitude; 60 levels; top grid cell 0-10 m)",
                    "native_nominal_resolution":"100 km"
                },
                "ocnBgchem":{
                    "description":"BEC (same grid as ocean)",
                    "native_nominal_resolution":"100 km"
                },
                "seaIce":{
                    "description":"CICE4 (same grid as ocean)",
                    "native_nominal_resolution":"100 km"
                }
            },
            "release_year":"2012",
            "source_id":"CESM1-3-CAM5-SE-CMIP5-LR"
        },

**Comment by durack1** [comment]
Thanks @strandwg we have guidance to limit the `source_id` to 16 characters (see [CMIP6 Global Attributes, DRS, Filenames, Directory Structure, and CV's](https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit#bookmark=id.kvz9ddoklgm1)).

Also the `label` and `label_extended` fields are meant for more human readable formats without character type or count limitations. For example for `label_extended` you could have `CESM1.3 (CAM5-SE, CMIP5-era model run at low resolution)` and for `label` a shorter variant of the same, so `CESM1.3 (CAM5-SE, low res)`

**Comment by strandwg** [comment]
Thanks, Paul. I'll iterate with my colleagues and take advantage of what you recommend.

**Comment by strandwg** [comment]
Interestingly, our DCPP submission has a source_id of length 19 (CESM1-1-CAM5-CMIP5) but I guess we got lucky with that!

**Comment by durack1** [comment]
@strandwg we've been cleaning as we go with updates, as it became clear that as the `source_id` is used across the infrastructure (directory and filenames) we had to limit the character length (and type) somehow. At 24 for the current registrations this was caught BEFORE registration

**Comment by strandwg** [comment]
I completely understand that!

**Comment by strandwg** [comment]
"CESM1-CAM5-SE-LR":{
            "activity_participation":[
                "HighResMIP",
            ],
            "cohort":[
                "Registered"
            ],
            "institution_id":[
                "NCAR"
            ],
            "label":"CESM1-CAM5-SE-LR",
            "label_extended":"CESM 1.3 CAM5 spectral element configuration with CMIP5 forcings, lo res",
            "model_component":{
                "aerosol":{
                    "description":"MAM3 (same grid as atmos)",
                    "native_nominal_resolution":"100 km"
                },
                "atmos":{
                    "description":""CAM5.2 (1 degree spectral element; 48602 cells; 30 levels; top level 2.25 mb)",
                    "native_nominal_resolution":"100 km"
                },
                "atmosChem":{
                    "description":"MAM3 (same grid as atmos)",
                    "native_nominal_resolution":"100 km"
                },
                "land":{
                    "description":"CLM4 (same grid as atmos)",
                    "native_nominal_resolution":"100 km"
                },
                "ocean":{
                    "description":"POP2 (320x384 longitude/latitude; 60 levels; top grid cell 0-10 m)",
                    "native_nominal_resolution":"100 km"
                },
                "ocnBgchem":{
                    "description":"BEC (same grid as ocean)",
                    "native_nominal_resolution":"100 km"
                },
                "seaIce":{
                    "description":"CICE4 (same grid as ocean)",
                    "native_nominal_resolution":"100 km"
                }
            },
            "release_year":"2012",
            "source_id":"CESM1-CAM5-SE-LR"
        },

**Comment by strandwg** [comment]
Hopefully this and the HR version work. Thanks!

**Comment by durack1** [comment]
@strandwg all done. Please take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know of any further tweaks

**Comment by strandwg** [comment]
Looks good. Thanks, Paul.
