### ISSUE TITLE
New source_id: CESM1-3-CAM5-SE-CMIP5-HR

### ISSUE THREAD

**Issue by strandwg** [WCRP-CMIP/CMIP6_CVs#932]
"CESM1-3-CAM5-SE-CMIP5-HR":{
            "activity_participation":[
                "HighResMIP",
            ],
            "cohort":[
                "Registered"
            ],
            "institution_id":[
                "NCAR"
            ],
            "label":"CESM1-3-CAM5-SE-CMIP5-HR",
            "label_extended":"CESM1-3-CAM5-SE-CMIP5-HR",
            "model_component":{
                "aerosol":{
                    "description":"MAM3 (same grid as atmos)",
                    "native_nominal_resolution":"25 km"
                },
                "atmos":{
                    "description":""CAM5.2 (0.25 degree spectral element; 777602 cells; 30 levels; top level 2.25 mb)",
                    "native_nominal_resolution":"25 km"
                },
                "atmosChem":{
                    "description":"MAM3 (same grid as atmos)",
                    "native_nominal_resolution":"25 km"
                },
                "land":{
                    "description":"CLM4 (same grid as atmos)",
                    "native_nominal_resolution":"25 km"
                },
                "ocean":{
                    "description":"POP2 (3600x2400 longitude/latitude; 62 levels; top grid cell 0-10 m)",
                    "native_nominal_resolution":"10 km"
                },
                "ocnBgchem":{
                    "description":"BEC (same grid as ocean)",
                    "native_nominal_resolution":"10 km"
                },
                "seaIce":{
                    "description":"CICE4 (same grid as ocean)",
                    "native_nominal_resolution":"10 km"
                }
            },
            "release_year":"2012",
            "source_id":"CESM1-3-CAM5-SE-CMIP5-HR"
        },

**Comment by durack1** [comment]
Thanks @strandwg we have guidance to limit the `source_id` to 16 characters (see [CMIP6 Global Attributes, DRS, Filenames, Directory Structure, and CV's](https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit#bookmark=id.kvz9ddoklgm1)).

Also the `label` and `label_extended` fields are meant for more human readable formats without character type or count limitations. For example for `label_extended` you could have `CESM1.3 (CAM5-SE, CMIP5-era model run at high resolution)` and for `label` a shorter variant of the same, so `CESM1.3 (CAM5-SE, hi res)`

**Comment by strandwg** [comment]
"CESM1-CAM5-SE-HR":{
            "activity_participation":[
                "HighResMIP",
            ],
            "cohort":[
                "Registered"
            ],
            "institution_id":[
                "NCAR"
            ],
            "label":"CESM1-CAM5-SE-HR",
            "label_extended":"CESM 1.3 CAM5 spectral element configuration with CMIP5 forcings, hi res",
            "model_component":{
                "aerosol":{
                    "description":"MAM3 (same grid as atmos)",
                    "native_nominal_resolution":"25 km"
                },
                "atmos":{
                    "description":""CAM5.2 (0.25 degree spectral element; 777602 cells; 30 levels; top level 2.25 mb)",
                    "native_nominal_resolution":"25 km"
                },
                "atmosChem":{
                    "description":"MAM3 (same grid as atmos)",
                    "native_nominal_resolution":"25 km"
                },
                "land":{
                    "description":"CLM4 (same grid as atmos)",
                    "native_nominal_resolution":"25 km"
                },
                "ocean":{
                    "description":"POP2 (3600x2400 longitude/latitude; 62 levels; top grid cell 0-10 m)",
                    "native_nominal_resolution":"10 km"
                },
                "ocnBgchem":{
                    "description":"BEC (same grid as ocean)",
                    "native_nominal_resolution":"10 km"
                },
                "seaIce":{
                    "description":"CICE4 (same grid as ocean)",
                    "native_nominal_resolution":"10 km"
                }
            },
            "release_year":"2012",
            "source_id":"CESM1-CAM5-SE-HR"
        },

**Comment by durack1** [comment]
@strandwg all done. Please take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know of any further tweaks
