### ISSUE TITLE
experiment_id -- ssp370-lowNTCF

### ISSUE THREAD

**Issue by lwhorowitz** [WCRP-CMIP/CMIP6_CVs#938]
Experiment ssp370-lowNTCFCH4 (AerChemMIP) lists required_model_components as ["**AGCM**","AER"]. But, this should be ["**AOGCM**","AER"] instead. Please correct.

Thanks!
--Larry

**Comment by durack1** [comment]
@lwhorowitz we have circled on this before, I will defer to @wjcollins for clarity.

@taylor13 ping

**Comment by lwhorowitz** [comment]
As far as I can tell, model components for ssp370-lowNTCFCH4 should match those for ssp370-lowNTCF (which they currently do not). And, likewise, the companion experiments, ssp370SST-lowNTCFCH4 and ssp370SST-lowNTCF, should match (as they do).

**Comment by taylor13** [comment]
According to the brief experiment descriptions recorded in the CV, the first pair don't mention SST and should have the same name (most likely with AOGCM), and the second pair are described as fixed SST experiments, and as noted both have "AGCM", which is correct.

So, I think @lwhorowitz is correct.

**Comment by durack1** [comment]
It seems that no data is currently written (see https://esgf-node.llnl.gov/search/cmip6/?activity_id=AerChemMIP&experiment_id=ssp370-lowNTCFCH4) and I imagine this is holding you up @lwhorowitz so I'll process this update now and @wjcollins can let us know if there is an issue

**Comment by durack1** [comment]
Thanks for the report @lwhorowitz, that issue should now be fixed. Please take a peek at [CMIP6_experiment_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_experiment_id.html) and let me know if you see any remaining issues
