### ISSUE TITLE
activity_id PMIP experiment_id have no parent?

### ISSUE THREAD

**Issue by chrisdane** [WCRP-CMIP/CMIP6_CVs#939]
Hi
As far as I understand [Otto-Bliesner et al. 2017](https://www.geosci-model-dev.net/10/3979/2017/) (p. 3988):

> 2.6 Setup and documentation of simulations
To provide initial conditions for the [midHolocene] simulations, it is recommended that a spin-up simulation is performed departing from the CMIP6 piControl experiment.

the PMIP experiments such as `midHolocene` should branch from the `piControl` run from the DECK simulations. Is that correct?

If yes, I do not understand, why e.g. the `experiment_id` `midHolcene` (line 5911 in `CMIP6_experiment_id.json`) reads
```
        "midHolocene":{
            "activity_id":[
                "PMIP"
            ],
            "parent_activity_id":[
                "no parent"
            ],
            "parent_experiment_id":[
                "no parent"
            ],
```
As far as I understand the paper above, `midHolocene`s parent activitiy and experiment should be `CMIP` and `piControl`?

Thanks a lot for help
Chris

**Comment by charliepascoe** [comment]
Hi Chris,
My understanding is that this experiment is listed as having no parent experiment because the period for which data is archived follows on from the spin-up.
Charlotte

**Comment by chrisdane** [comment]
But am I right that `midHolocene` must branch from `piControl`? Or may I initialize `midHolocene` from any other (spinup) run?
```
? --> spinup --> midHolocene
```

**Comment by charliepascoe** [comment]
The spin-up for the midHolocene experiment should be forced with "mid-Holocene (6 kyr ago) boundary conditions for orbital parameters and the atmospheric concentration of well-mixed greenhouse gases."
And that spin-up should branch from the piControl.

**Comment by chrisdane** [comment]
So
```
piControl (quasi-equilibrium) --> midHolocene (x years spinup) --> midHolocene (min 200 years for cmor)
```
? 
Ok I understand that, still, I think it is a little counter-intuitive to say that `midHolocene` has no parent. For me that implies that the `piControl` and `modHolocene` experiments of one model are totally independent of each other. But, in fact, they are not?

**Comment by charliepascoe** [comment]
Yes that is how I understand it, @jypeter can you confirm.
And yes, I agree, the connection between experiments could be more intuitive but it's difficult to fit that subtlety into the data model.

**Comment by durack1** [comment]
Just to throw it out there, there is the [`piControl-spinup`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json#L7691-L7719) experiment defined, which following the thread above may be just the experiment you're looking for

**Comment by chrisdane** [comment]
Ok and what would you say if you have a `midHolocene` run that was never in touch with any `piControl` or `piControl-spinup` experiment? Would you regard this as a valid `midHolocene` experiment?
Thanks a lot for all your help.

**Comment by taylor13** [comment]
If a model was not directly branched from a simulation listed in the list of CMIP6 experiment i.d.'s it is said to have "no parent", even though it might have been branched from some simulation external to the suite of CMIP experiments (and even if some of them had a CMIP6 parent).  

As I understand it the recommended procedure is what you summarized in https://github.com/WCRP-CMIP/CMIP6_CVs/issues/939#issuecomment-631387635 above.  It therefore has no parent because midHolocine-spinup is not an official CMIP6 experiment.  

I do not know whether following a different spin-up procedure would disqualify the simulation.

**Comment by chrisdane** [comment]
Thank you all very much for your help. I close this for now.
