### ISSUE TITLE
source_id registration of NASA-GSFC-ACCESS1-3-rcp85-1-0 for input4MIP

### ISSUE THREAD

**Issue by geresie** [WCRP-CMIP/CMIP6_CVs#945]
label = NASA-GSFC-ACCESS1-3-rcp85-1-0
source_id = NASA-GSFC-ACCESS1-3-rcp85-1-0
institution_id = NASA-GSFC
release_year = 2020
activity_participation = ISMIP6
contact = ismip6@gmail.com
further_info_url = http://www.climate-cryosphere.org/wiki/index.php?title=ISMIP6_wiki_page
institution_id = NASA-GSFC
references = Experimental protocol for sealevel projections from ISMIP6 standalone ice sheet models, S. Nowicki et al, 2020, https://doi.org/10.5194/tc-2019-322

**Comment by durack1** [comment]
Hi @geresie you might want to take a peek at the `source_id` submission template, which can be viewed at https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/.github/Model_registration_template.md - you can directly edit your entry above to conform to the requested details.

The contact, further_info_url etc fields will be those that you write to the output netcdf files, following the guidance contained in http://goo.gl/v1drZl

**Comment by durack1** [comment]
@geresie also I note that as the `source_id` is used in directory structures and the ESGF search keys (see https://esgf-node.llnl.gov/search/cmip6/) we limit the length to 16 characters

**Comment by durack1** [comment]
@geresie I am also guessing that you are registering forcing data, right? If so no need to enter anything here, we are managing the CMIP6 forcing data in the [input4MIPs cmor tables repo](https://github.com/PCMDI/input4MIPs-cmor-tables), and it's not as formal a process as the CMIP6 model registration

**Comment by geresie** [comment]
Thanks Paul. Yes, I am trying to register the source_id for the ISMIP6 forcing data.

**Comment by durack1** [comment]
No problem, let's close out this issue and move the discussion along to https://github.com/PCMDI/input4MIPs-cmor-tables

**Comment by geresie** [comment]
Thanks Paul.
I started a new issue on the input4MIP side.

Cheers,
Erika

------------------------------------------------------------
Dr. Erika G. Simon
NASA Goddard Space Flight Center
615 Cryospheric Sciences Laboratory
Bldg. 33 / Rm. B209B
Ph: (o) 301.614.5932
    (c) 601.415.7356
E:  erika.g.simon@nasa.gov<mailto:erika.g.simon@nasa.gov>
    esimon@innovim.com<mailto:esimon@innovim.com>
[cid:7ff57f78-d7d7-43bd-96e2-613a81843046]
------------------------------------------------------------
________________________________
