### ISSUE TITLE
"activity_id -- add ‘DAMIP'" to "source_id ACCESS-CM2”

### ISSUE THREAD

**Issue by sjmarsland** [WCRP-CMIP/CMIP6_CVs#947]
"activity_id -- add ‘DAMIP'" to "source_id ACCESS-CM2”

**Comment by durack1** [comment]
@sjmarsland that second tweak is now in place, take a look at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know of any further tweaks required
