### ISSUE TITLE
Some RFMIP experiment_ids have changed

### ISSUE THREAD

**Issue by RobertPincus** [WCRP-CMIP/CMIP6_CVs#95]
Hello there - 

Based on interactions with DAMIP, we have changed the experiment titles and experiment_ids for some of the RFMIP experiments. Please change all instances of "spAerO3" in experiment_ids to "spAer". 

Thanks - Robert Pincus

**Comment by durack1** [comment]
Duplicated issue - info migrated to #82 and closing
