### ISSUE TITLE
model

### ISSUE THREAD

**Issue by faeze88135** [WCRP-CMIP/CMIP6_CVs#952]
Here are instructions both for registering your institution and model for CMIP6 and for raising other issues concerning CMIP6 controlled vocabularies. We can update details iteratively, until you begin writing CMIP6 data.

PLEASE DELETE THESE INSTRUCTIONS BEFORE SUBMITTING YOUR REGISTRATION/ISSUE

*********************************************
## Registering your institution and model
*********************************************
Before publishing CMIP6 model output on ESGF, you must register information about your institution and  model as described in the registration guidance documents available at https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/.github/Institution_registration_template.md and https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/.github/Model_registration_template.md. 

*********************************************
## Raising other issues
*********************************************
Your issue "title" should begin with the name of the Controlled Vocabulary of interest and also include a terse indication of the issue (e.g., "activity_id -- add 'PMIP'").

**Comment by durack1** [comment]
@faeze88135 there is no actionable information above, was this an error, or do you need to edit the contents above to register a model or institution?

**Comment by durack1** [comment]
@faeze88135 as there has been no change to the status, will close this issue. If you require a model/institution registration, please reopen and edit this issue (or open a new issue)
