### ISSUE TITLE
Register MOHC models for LS3MIP and LUMIP

### ISSUE THREAD

**Issue by matthew-mizielinski** [WCRP-CMIP/CMIP6_CVs#953]
Could you please add LS3MIP to the `activity_participation` list for HadGEM3-GC31-LL and UKESM1-0-LL, and LUMIP to HadGEM3-GC31-LL.

python code to modify CMIP6_source_id.json;
```#!python
source_id = json.load(open('CMIP6_source_id.json'))

source_id['source_id']['UKESM1-0-LL']['activity_participation'].append('LS3MIP')
source_id['source_id']['HadGEM3-GC31-LL']['activity_participation'] += ['LS3MIP', 'LUMIP']

# sort elements
source_id['source_id']['UKESM1-0-LL']['activity_participation'].sort()
source_id['source_id']['HadGEM3-GC31-LL']['activity_participation'].sort()
```

TIA,

Matt

**Comment by durack1** [comment]
@matthew-mizielinski thanks for the tweak, changes are implemented so please cross-check [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) to make sure everything else is in order

**Comment by matthew-mizielinski** [comment]
Perfect, thanks Paul!
