### ISSUE TITLE
IPSL-CM6A-LR-INCA: missing activity RFMIP

### ISSUE THREAD

**Issue by MartinaSt** [WCRP-CMIP/CMIP6_CVs#955]
@durack1: This fortnight, there is a new issue of an unregistered activity for a source_id:
Activity RFMIP is missing in the registration of source_id=IPSL-CM6A-LR-INCA.

Thanks Martina

**Comment by durack1** [comment]
@glipsl it seems the above registration has also not been completed. Can you confirm that `RFMIP` should be added to the activity participation for `IPSL-CM6A-LR-INCA` [it appears it is currently only registered for `AerChemMIP`](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html)

**Comment by durack1** [comment]
@glevava it seems the above registration has also not been completed. Can you confirm that `RFMIP` should be added to the activity participation for `IPSL-CM6A-LR-INCA` [it appears it is currently only registered for `AerChemMIP`](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html)

**Comment by glevava** [comment]
Hi @durack1 yes, that's a mistake from us. RFMIP should be added to the activity participation of IPSL-CM6A-LR-INCA as some RFMIP experiments have been published already (ex. piClim-aer). That's for fixing this and sorry again : )

**Comment by durack1** [comment]
@glevava no problem, that change is now in place. Please take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know if any further tweaks are required.

Apologies about the delay with this, the CA fires are miles from home, so we evacuated earlier this week, now catching back up with the backlog
