### ISSUE TITLE
GeoMIP

### ISSUE THREAD

**Issue by OBASolo** [WCRP-CMIP/CMIP6_CVs#956]
Here are instructions both for registering your institution and model for CMIP6 and for raising other issues concerning CMIP6 controlled vocabularies. We can update details iteratively, until you begin writing CMIP6 data.

PLEASE DELETE THESE INSTRUCTIONS BEFORE SUBMITTING YOUR REGISTRATION/ISSUE

*********************************************
## Registering your institution and model
*********************************************
Before publishing CMIP6 model output on ESGF, you must register information about your institution and  model as described in the registration guidance documents available at https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/.github/Institution_registration_template.md and https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/.github/Model_registration_template.md. 

*********************************************
## Raising other issues
*********************************************
Your issue "title" should begin with the name of the Controlled Vocabulary of interest and also include a terse indication of the issue (e.g., "activity_id -- add 'PMIP'").

**Comment by durack1** [comment]
@OBASolo there is no actionable information above, consequently, I will close this issue. If you do need to register or amend the information, please reopen and edit this issue with the appropriate content
