### ISSUE TITLE
Activity PAMIP missing for source_id: HadGEM3-GC31-MM of institution_id: MOHC

### ISSUE THREAD

**Issue by MartinaSt** [WCRP-CMIP/CMIP6_CVs#959]
@durack1 : There is a new missing activity for ESGF-published data from MOHC:

activity_id: PAMIP missing for source_id: HadGEM3-GC31-MM of institution_id: MOHC

Could you please contact the responsible person at MOHC?

Btw, I have thought that the latest ESGF publisher version catches this?

**Comment by matthew-mizielinski** [comment]
Apologies @MartinaSt  I should have caught this one.

As per previous issues, e.g. #953 the code changes needed would be

```
source_id = json.load(open('CMIP6_source_id.json'))

source_id['source_id']['HadGEM3-GC31-MM']['activity_participation'].append('PAMIP')

# sort elements
source_id['source_id']['HadGEM3-GC31-MM']['activity_participation'].sort()
```

@taylor13 , @doutriaux1 ,

Given that Paul may be unavailable are either of you able to address this issue? If it would be preferable I can set up a pull request instead.

@MartinaSt ,

I'll arrange for the citation service to be updated, and check with CEDA as to whether the pre-publication checks raised anything about this

**Comment by MartinaSt** [comment]
Thanks @matthew-mizielinski ! 
I will keep an eye on this issue to provide you with the corresponding citation entries after the update of the CV.

**Comment by taylor13** [comment]
Paul is indeed now away for at least a few weeks.  I can modify the CV, but I would do it by simply editing the .json file.  I think Paul likes to use a code (perhaps using commands like those you suggested above) to edit the file.  I don't understand the procedure.  Is there a way to postpone updating the CV and still create the citation entries?  Or what other options are there?   Do you think it safe to proceed with Matt setting up a pull request?  Would I then have to do something to grant the request?  Sorry I haven't yet learned more about github.

**Comment by MartinaSt** [comment]
@taylor13 @matthew-mizielinski No, I need the CV content to create entries in the citation DB. Then Jeremy needs to provide author details before a DOI can be registered. I do not know enough about Paul's scripts to answer your second question. The CV should be fine with a pull request and a commit. The question is if there is other content updated by Paul's scripts like e.g. the CMOR tables.

**Comment by taylor13** [comment]
Yes, I understand you need the content to create the entry.  Do you have codes that read that content directly from the  CV or do you input the content to your citation database by other means?  

Regarding CMOR, its tables are indeed created by reading in the CV json file content, so @matthew-mizielinski would not be able to get the new CMOR tables until the CV is updated.  At least that's my understanding.

**Comment by durack1** [comment]
@taylor13 @MartinaSt @matthew-mizielinski I'll do this later today.

Long story short, in order to enforce a version across elements it has to be run through the code (the code does the version increments). Regarding the CMOR tables ([cmip6-cmor-tables](https://github.com/PCMDI/cmip6-cmor-tables/)) these will be updated at midnight through a cronjob

**Comment by durack1** [comment]
@MartinaSt @matthew-mizielinski that change is now in place, please take a peek at [](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) to double-check, the [cmip6-cmor-tables](https://github.com/PCMDI/cmip6-cmor-tables/) should be updated overnight

**Comment by matthew-mizielinski** [comment]
Thanks @durack1 this looks good to me.

I'll check for the update in the MIP tables next week and follow up with with @MartinaSt  on getting the MOHC entry for PAMIP in the citation service sorted.

**Comment by MartinaSt** [comment]
@matthew-mizielinski The citation entries have been made available for Jeremy this morning.

**Comment by matthew-mizielinski** [comment]
Thanks @MartinaSt.
