### ISSUE TITLE
source_id registration of IITM-ESM

### ISSUE THREAD

**Issue by manmeet3591** [WCRP-CMIP/CMIP6_CVs#96]
Label : IITM-ESM
Source_id:  IITM-ESM
Institution_id: “CCCR-IITM” : "Centre for Climate Change Research, Indian Institute of Tropical Meteorology Pune, Maharashtra 411 008, India",
Release_year : 2015

full_coupled_model_id = IITM-ESM
    aerosol = unnamed (prescribed MAC-v2)
    atmosphere = GFS( 192 x 94 T62; 64 levels;  top level : 0.2 mb)
    atmospheric_chemistry = None
    land_surface = Noah LSM
    ocean = MOM4p1(tripolar,360x200 ; 50 levels; top grid cell 5m)
    ocean_biogeochemistry = TOPAZ
    sea_ice = SIS

**Comment by durack1** [comment]
@manmeet3591 I have amended your request above:
```
"IITM-ESM":{
            "aerosol":"unnamed (prescribed MAC-v2)",
            "atmosphere":"GFS( 192 x 94 T62; 64 levels; top level : 0.2 mb)",
            "atmospheric_chemistry":"None",
            "institution_id":[
                "CCCR-IITM"
            ],
            "label":"IITM-ESM",
            "label_extended":"IITM-ESM", (we have renamed this from full_coupled_model_id)
            "land_ice":"None",
            "land_surface":"Noah LSM",
            "ocean":"MOM4p1(tripolar,360x200 ; 50 levels; top grid cell 5m)",
            "ocean_biogeochemistry":"TOPAZ",
            "release_year":"2015",
            "sea_ice":"SIS"
}
```
I will also register the `institution_id`:
```
"CCCR-IITM":"Centre for Climate Change Research, Indian Institute of Tropical Meteorology Pune, Maharashtra 411 008, India",
```
Please let me know if this amended entry is suitable and if so I will process the registration

**Comment by manmeet3591** [comment]
@durack1 Thanks for amending the request. It's suitable and you can process the registration.

**Comment by durack1** [comment]
@manmeet3591 I am just trying to process this and was wondering if some additional details are available, particularly for the fields below?:
```
"IITM-ESM":{
            "land_surface":"Noah LSM", # Is there a version number or further info
            "ocean_biogeochemistry":"TOPAZ", # Is there a version number or further info
}
```

**Comment by durack1** [comment]
@manmeet3591 the latest `NOAH LSM` version appears to be [`3.4.1`](http://www.ral.ucar.edu/research/land/technology/lsm.php), how about `TOPAZ` and `GFS`? If these details are not available, or will be finalised later we can always amend before data is written

**Comment by durack1** [comment]
@manmeet3591 we can add the version information for the `atmosphere`, `land_surface` and 'ocean_biogeochemistry` later if required - for now your model information can be viewed in [here](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html)

**Comment by durack1** [comment]
@manmeet3591 please review the entries in [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) for accuracy, and if any revisions are required please reopen and detail the amendments in this issue

**Comment by durack1** [comment]
@manmeet3591 we have augmented the fields that we are capturing in our `source_id`registrations. Can you please add in the `activity_participation" and "nominal_resolution" fields missing in [your `IITM-ESM` registration](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L1978-L2026) - there are some guidance notes for completing these fields found in [Model_registration_template.md](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/.github/Model_registration_template.md)

**Comment by durack1** [comment]
@manmeet3591 we have augmented the fields that we are capturing in our `source_id`registrations. Can you please add in the `activity_participation` and `nominal_resolution` fields missing in [your `IITM-ESM` registration](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L1978-L2026) - there are some guidance notes for completing these fields found in [Model_registration_template.md](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/.github/Model_registration_template.md)

**Comment by manmeet3591** [comment]
@durack1 The activity_participation is "CMIP6 DECK and historic simulation"  and the nominal_resolution is Atmosphere (T62) and Ocean (~1deg tripolar)

**Comment by durack1** [comment]
@manmeet3591 thanks - so to confirm:
```
        "IITM-ESM":{
            "activity_participation":[
                "CMIP"
            ],
            "cohort":[
                "Registered"
            ],
            "institution_id":[
                "CCCR-IITM"
            ],
            "label":"IITM-ESM",
            "label_extended":"IITM-ESM",
            "model_component":{
                "aerosol":{
                    "description":"unnamed (prescribed MAC-v2)",
                    "nominal_resolution":"250 km"
                },
                "atmos":{
                    "description":"GFS (T62; 192 x 94 longitude/latitude; 64 levels; top level 0.2 mb)",
                    "nominal_resolution":"250 km"
                },
                "atmosChem":{
                    "description":"none",
                    "nominal_resolution":"none"
                },
                "land":{
                    "description":"NOAH LSM",
                    "nominal_resolution":"250 km"
                },
                "landIce":{
                    "description":"none",
                    "nominal_resolution":"none"
                },
                "ocean":{
                    "description":"MOM4p1 (tripolar ~1degree; 360 x 200 longitude/latitude; 50 levels; top grid cell 0-10 m)",
                    "nominal_resolution":"100 km"
                },
                "ocnBgchem":{
                    "description":"TOPAZ",
                    "nominal_resolution":"100 km"
                },
                "seaIce":{
                    "description":"SIS",
                    "nominal_resolution":"100 km"
                }
            },
            "release_year":"2015",
            "source_id":"IITM-ESM"
},
```
Is correct?

**Comment by durack1** [comment]
@manmeet3591 while you are considering this - it would also be useful to include version info for the components - so `GFS` v?, `NOAH LSM` v?, `TOPAZ` v?, `SIS` v?

**Comment by manmeet3591** [comment]
@durack1 Please find the final details 


     "IITM-ESM":{
            "activity_participation":[
                "CMIP
                 GMMIP"
            ],
            "cohort":[
                "Registered"
            ],
            "institution_id":[
                "CCCR-IITM"
            ],
            "label":"IITM-ESM",
            "label_extended":"IITM-ESM",
            "model_component":{
                    "aerosol":{
                    "description":"prescribed MAC-v2",
                    "nominal_resolution":"200km"
                },
                "atmos":{
                    "description":"IITM-GFSv1 (T62L64 Linearly Reduced Gaussian Grid; 192 x 94 longitude/latitude; 64 )",
                    "nominal_resolution":"200km"
                },
                "atmosChem":{
                    "description":"none",
                    "nominal_resolution":"none"
                },
                "land":{
                    "description":"NOAH LSMv2.7.1",
                    "nominal_resolution":"200km"
                },
                "landIce":{
                    "description":"none",
                    "nominal_resolution":"none"
                },
                "ocean":{
                    "description":"(MOM4p1; tripolar primarily 1deg, 360 x 200 longitude/latitude; 50 levels; top grid cell 0-10m)",
                    "nominal_resolution":"100km"
                },
                "ocnBgchem":{
                    "description":"TOPAZ 2.0",
                    "nominal_resolution":"100km"
                },
                "seaIce":{
                    "description":"SIS 1.0",
                    "nominal_resolution":"100km"
                }
            },
            "release_year":"2015",
            "source_id":"IITM-ESM"
        },

**Comment by durack1** [comment]
Thanks @manmeet3591 your model registration is revised, take a look at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further changes are required
