### ISSUE TITLE
institution_id -- register 'CSIRO-COSIMA'

### ISSUE THREAD

**Issue by sjmarsland** [WCRP-CMIP/CMIP6_CVs#961]
institution_id = CSIRO-COSIMA
institution = CSIRO (Commonwealth Scientific and Industrial Research Organisation, Australia), COSIMA (Consortium for Ocean-Sea Ice Modelling in Australia)

**Comment by durack1** [comment]
@sjmarsland thanks for this, I will tweak to be:

`institution = "CSIRO (Commonwealth Scientific and Industrial Research Organisation, Australia), COSIMA (Consortium for Ocean-Sea Ice Modelling in Australia). Mailing address: CSIRO, c/o Simon J. Marsland, 107-121 Station Street, Aspendale, Victoria 3195, Australia"`

**Comment by durack1** [comment]
I'll also clean up `CSIRO-ARCCSS` as it also has no postal/location address

**Comment by durack1** [comment]
@sjmarsland ok complete. Please take a peek at the new and revised entries at [CMIP6_institution_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_institution_id.html) and let me know of any further tweaks requires

**Comment by sjmarsland** [comment]
@durack1 All good, many thanks for your help.
