### ISSUE TITLE
source_id -- register ''ACCESS-OM2"

### ISSUE THREAD

**Issue by sjmarsland** [WCRP-CMIP/CMIP6_CVs#962]
label = ACCESS-OM2
label_extended = Australian Community Climate and Earth System Simulator Ocean Model Version 2
source_id = ACCESS-OM2
institution_id = CSIRO-COSIMA
release_year = 2020
activity_participation = OMIP
aerosol:
description = none
nominal_resolution = none
atmos:
description = none
nominal_resolution = none
atmosChem:
description = none
nominal_resolution = none
land:
description = none
nominal_resolution = none
landIce:
description = none
nominal_resolution = none
ocean:
description = ACCESS-OM2 (MOM5, tripolar primarily 1deg; 360 x 300 longitude/latitude; 50 levels; top grid cell 0-2.3 m)
nominal_resolution = 100 km
ocnBgchem:
description = WOMBAT (same grid as ocean)
nominal_resolution = 100 km
seaIce:
description = CICE5.1.2 (same grid as ocean)
nominal_resolution = 100 km

**Comment by durack1** [comment]
@sjmarsland another registration complete, I was curious about the WOMBAT version but didn't want to hold up registration. Take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know of any additional tweaks

**Comment by sjmarsland** [comment]
Thanks @durack1. No, WOMBAT does not have an official version number so all good.
