### ISSUE TITLE
Missing activity_ids for data published by EC-Earth-Consortium and CCCR-IITM

### ISSUE THREAD

**Issue by MartinaSt** [WCRP-CMIP/CMIP6_CVs#964]
@durack1 (@taylor13 ): We have missing activity_id registrations for ESGF-published data for two institutions, where we need to get in touch with the responsible persons:

EC-Earth-Consortium: 
source_id=EC-Earth3 missing activity_id=OMIP

CCCR-IITM:
source_id=IITM-ESM missing activity_id=ScenarioMIP

**Comment by taylor13** [comment]
@MartinaSt (@durack1)  I assume you mean they haven't included the activity in the activity_participation list for these models??  I will contact the responsible person at each institution and ask them to raise an issue to add the activities to "activity_participation".  

Could you also remind me how you become alerted when an activity is missing?  How do you know these models are participating in an activity if they haven't declared it yet?  (I'm sure you've explained this to me before, so apologies.)

**Comment by MartinaSt** [comment]
@taylor13 (@durack1 ): yes, the activities are missing in the "activity_participation" section of the source_id. Thanks for taking this up.

I do a fortnightly check, which I thought to be integrated in the latest ESGF Publisher version.

**Comment by durack1** [comment]
@shutingdk it appears that you have a missing `activity_participation` entry for `EC-Earth3`, `OMIP` should be included see https://esgf-node.llnl.gov/search/cmip6/?source_id=EC-Earth3&activity_id=OMIP - can you please confirm before we amend your registration?

**Comment by durack1** [comment]
@manmeet3591 it appears that you have a missing `activity_participation` entry for `IITM-ESM`, `ScenarioMIP` should be included, see https://esgf-node.llnl.gov/search/cmip6/?source_id=IITM-ESM&activity_id=ScenarioMIP - can you please confirm before we amend the registration?

**Comment by shutingdk** [comment]
> @shutingdk it appears that you have a missing `activity_participation` entry for `EC-Earth3`, `OMIP` should be included see https://esgf-node.llnl.gov/search/cmip6/?source_id=EC-Earth3&activity_id=OMIP - can you please confirm before we amend your registration?

Yes.  Please add activity OMIP to EC-Earth3. And could you please also add activity DAMIP to EC-Earth3? We have recently decided to also contribute to DAMIP with EC-Earth3. Thank you!

**Comment by manmeet3591** [comment]
> @manmeet3591 it appears that you have a missing `activity_participation` entry for `IITM-ESM`, `ScenarioMIP` should be included, see https://esgf-node.llnl.gov/search/cmip6/?source_id=IITM-ESM&activity_id=ScenarioMIP - can you please confirm before we amend the registration?

Yes @durack1 ScenarioMIP should be included.

**Comment by durack1** [comment]
@shutingdk thanks for confirming, please take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html), the two new MIPs are now listed

**Comment by durack1** [comment]
@manmeet3591 thanks for confirming, please take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html), ScenarioMIP is now listed

**Comment by manmeet3591** [comment]
> @manmeet3591 thanks for confirming, please take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html), ScenarioMIP is now listed

@durack1 Thanks for listing. Can you please also add GMMIP for IITM-ESM registration?

**Comment by MartinaSt** [comment]
@durack1: I reopen this issue because of the github notification (received at Sun, 04 Oct 2020 11:21:47 -0700) below with a request from @manmeet3591, which has not been recorded here:

> @durack1 Thanks for listing. Can you please also add GMMIP for IITM-ESM registration?

**Comment by manmeet3591** [comment]
> @durack1, please reopen this issue because of the github notification (received at Sun, 04 Oct 2020 11:21:47 -0700) below with a request from @manmeet3591, which has not been recorded here:
> 
> > @durack1 Thanks for listing. Can you please also add GMMIP for IITM-ESM registration?

@MartinaSt @durack1 I just checked and GMMIP is listed for IITM-ESM at https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html Thank you.

**Comment by durack1** [comment]
@manmeet3591 thanks for checking, you're right, nothing to do here, so will close
