### ISSUE TITLE
"activity_id -- add ‘RFMIP'" to "source_id MPI-ESM-1-2-HAM”

### ISSUE THREAD

**Issue by nedavid** [WCRP-CMIP/CMIP6_CVs#965]
According to #951 MPI-ESM-1-2-HAM needs to have the activity_id RFMIP to publish the piClim-aer and piClim-control experiments co-sponsered by AerChemMIP.

activity_id: RFMIP
source_id: MPI-ESM-1-2-HAM
institution_id: HAMMOZ-Consortium

**Comment by taylor13** [comment]
Yes, that is my understanding, but I think you meant we need to add "RFMIP" to the _**activity_participation**_ list for MPI-ESM-1-2-HAM.

**Comment by durack1** [comment]
@nedavid thanks for the tweak, your registration is now updated, please take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know of any further tweaks required
