### ISSUE TITLE
experiment_id: deforest_globe

### ISSUE THREAD

**Issue by dlawrenncar** [WCRP-CMIP/CMIP6_CVs#97]
experiment_id: "deforest_globe", "start_year":"1850", "end_year":" "

**Comment by durack1** [comment]
@dlawrenncar we currently have [`deforest-globe` as a listed experiment](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json#L1764-L1790):
```
        "deforest-globe":{
            "activity_id":[
                "LUMIP"
            ],
            "additional_allowed_model_components":[
                "AER",
                "CHEM",
                "BGCM"
            ],
            "description":"Idealized deforestation experiment, 20 million km2 forest removed linearly over a period of 50 years, with an additional 30 years with no specified change in forest cover; all other forcings held constant",
            "end_year":"1920",
            "experiment":"idealized transient global deforestation",
            "min_number_yrs_per_sim":"81",
            "parent_activity_id":[
                "CMIP"
            ],
            "parent_experiment_id":[
                "piControl"
            ],
            "required_model_components":[
                "AOGCM"
            ],
            "start_year":"",
            "sub_experiment":"none",
            "sub_experiment_id":"none",
            "tier":"1"
},
```
Is this issue still relevant?

**Comment by durack1** [comment]
@dlawrenncar should this experiment be amended to include:
```
            "start_year":"1850",
```
Are there any other edits required? The `end_year = 1920` is also something to clarify?

**Comment by dlawrenncar** [comment]
Start year should be 1850 to imply that this simulation should be
initialized from a pre-industrial control run.  I suggested to remove the
end_year specification because in this simulation, we ask that the users
run for 80 years with everything as in the pre-industrial control run
except with a specified idealized deforestation scenario.  So, the end_year
has nothing to do with the actual year 1920.
