### ISSUE TITLE
source_id registration of CAM-MPAS-LR

### ISSUE THREAD

**Issue by beharrop** [WCRP-CMIP/CMIP6_CVs#971]
label = CAM-MPAS-LR
label_extended = CAM MPAS (Community Atmosphere Model – Model for Prediction Across Scales)
source_id = CAM-MPAS-LR
institution_id = PNNL-WACCEM
release_year = 2018
activity_participation = [HighResMIP]

aerosol:
description = none, prescribed MACv2-SP
nominal_resolution = none
atmos:
description = CAM-MPAS (CAMv5.4 with Grell-Freitas deep convection; MPASv4, C-grid staggered centroidal Voronoi tesselation atmosphere 120 km mesh with 40962 cells and 122880 edges; 32 vertical levels, model top 40363 m)
nominal_resolution = 100 km
atmosChem:
description = none
nominal_resolution = none
land:
description = CLM (v4.0, same grid as atmos), River Transport Model (v1.0)
nominal_resolution = 100 km
landIce:
description = none
nominal_resolution = none
ocean:
description = none
nominal_resolution = none
ocnBgchem:
description = none
nominal_resolution = none
seaIce:
description = none
nominal_resolution = none

**Comment by beharrop** [comment]
The above is the accompanying LR version of the CAM-MPAS-HR source_id registered in the spring.  Pinging @kosaka90 to double check that things are good here.

**Comment by kosaka90** [comment]
It looks good to me, except for the model top height... Checking the source code again, I found that 40363m is the height of the middle of the top model layer. It's upper interface is located at 44569 m. Do we need to change it, or it is too much detail, or maybe we are supposed to report the height of the middle layer...? If we need to change the model top height for LR, the same change has to be made for HR.

**Comment by beharrop** [comment]
I imagine the upper most level midpoint is probably OK.  I do agree that if this detail should strictly be the uppermost interface level, then we would have to modify the HR simulation too.

**Comment by kosaka90** [comment]
Sounds good to me, let's keep it as it is.

**Comment by durack1** [comment]
@beharrop @kosaka90 thanks for the update, you should find `CAM-MPAS-LR` is now registered, please take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know if any other tweaks are required

**Comment by beharrop** [comment]
Thanks @durack1 .  The CMIP6 source_id page you linked looks good to me.
