### ISSUE TITLE
New "CovidMIP" experiments proposed under DAMIP activity_id

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#973]
A series of new experiments focused on changes throughout the COVID shutdown has been requested. The path forward to this is that 4 (see below) experiments will be registered under the existing `DAMIP` activity_id, to facilitate prompt publication for use in the IPCC AR6 report, and subsequently, on a far longer timeline (as yet undefined) ~8 additional experiments will likely be published at a later stage, potentially under a new mip_era (not CMIP6):

| exp_id | act_id | exp | tier | sub-exp | parent exp_id | req mod components | addi components | start yr | end yr | min num yrs | parent act_id | description |
|--|--|--|--|--|--|--|--|--|--|--|--|--|
| ssp245-covid | DAMIP | 2-year blip | 2 | none | ssp245 | AOGCM | AER, CHEM, BGC | 2020 | 2024 or 2050 | 5 | ScenarioMIP | Future scenario based on ssp245, but with 2-year perturbation to emissions for 2020 and 2021 due to Covid-19 pandemic restrictions. Emissions revert to ssp245 after this. Concentration-driven |
| ssp245-cov-strgreen | DAMIP | strong green stimulus | 2 | none | ssp245 | AOGCM | AER, CHEM, BGC | 2020 | 2050 | 31 | ScenarioMIP | Future scenario based on ssp245, but following a path of reduced emissions due to a strong-green stimulus economic recovery from the Covid-19 pandemic restrictions. Concentration-driven |
| ssp245-cov-modgreen | DAMIP | moderate green stimulus | 3 | none | ssp245 | AOGCM | AER, CHEM, BGC | 2020 | 2050 | 31 | ScenarioMIP | Future scenario based on ssp245, but following a path of reduced emissions due to a moderate-green stimulus economic recovery from the Covid-19 pandemic restrictions. Concentration-driven |
| ssp245-cov-fossil | DAMIP | fossil-fuel rebound | 3 | none | ssp245 | AOGCM | AER, CHEM, BGC | 2020 | 2050 | 31 | ScenarioMIP | Future scenario based on ssp245, but following a path of increased emissions due to a fossil-fuel rebound economic recovery from the Covid-19 pandemic restrictions. Concentration-driven |

@matthew-mizielinski @martinjuckes @MartinaSt @taylor13 @charliepascoe @momipsl @glevava @davidhassell

If anyone else needs to be in this loop, please ping them on this issue

Source information is available from the [google doc](https://docs.google.com/document/d/1JhebHwH5uEP9ZRbH6-sH8P3zjLAOGSR4/edit#)

**Comment by slavakharin** [comment]
I propose to add 2 more single-forcing experiments to the 4 experiments listed above


| exp_id | act_id | exp | tier | sub-exp | parent exp_id | req mod components | addi components | start yr | end yr | min num yrs | parent act_id | description |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
| ssp245-cov-aer | DAMIP | 2-year blip anthropogenic aerosols-only | 3 | none | ssp245 | AOGCM | AER, CHEM,BGC | 2020 | 2024 | 5 | ScenarioMIP | Detection and attribution experiment: aerosol-only run based on ssp245-covid, with 2-year perturbation to emissions for 2020 and 2021 due to Covid-19 pandemic restrictions. Concentration-driven |
| ssp245-cov-GHG | DAMIP | 2-year blip well-mixed GHG-only | 3 | none | ssp245 | AOGCM | AER, CHEM,BGC | 2020 | 2024 | 5 | ScenarioMIP | Detection and attribution experiment: well-mixed GHG-only run based on ssp245-covid, with 2-year perturbation to emissions for 2020 and 2021 due to Covid-19 pandemic restrictions. Concentration-driven |

**Comment by ChrisJones-MOHC** [comment]
for background we have 12 model groups committed to do these simulaitons. Details of protocol and aprticipation here:
https://drive.google.com/file/d/1Uj0aVoS-LIi0eBU7tuWyfultuAu8tfkX/view?usp=sharing
https://docs.google.com/spreadsheets/d/1PsmQz8v4YcYelnITtBVz5_-YP-cnnVZDi1g-nuEig84/edit?usp=sharing 

I support Slava's request to include the 2 additional D&A runs in this. We have 6 further ERF/fixed-SST runs which we can defer to later mip_era

thanks,
Chris

**Comment by matthew-mizielinski** [comment]
@durack1, I've put together some code [here](https://gist.github.com/matthew-mizielinski/7639596fb243112a1f1210dc1e22c4f2) that you could pick up to add all six of these experiments in, along with the resulting dictionary entries that would appear in `CMIP6_experiment_id.json`.

@ChrisJones-MOHC, @slavakharin,  As the `experiment` field is the one that ends up in the file metadata I have expanded the corresponding text to make it a little more verbose than in the tables above, but shorter than the description fields. For comparison see the entry for [ssp245 here](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json#L8234). If you would prefer the original text, or the full description, please comment.

**Comment by durack1** [comment]
@matthew-mizielinski very helpful thanks. To be honest, it might be high time that we diversify our contributor base on this. The versioning is managed by the [src/writeJson.py](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/src/writeJson.py) script in this repo, so I normally just edit entries and run that script (which updates all the html/md versions etc), would you like to try cloning the latest version and seeing if you can get it to work for you? If yes, submit a PR and we can double check and then merge and tag (which is the manual part).

**Comment by ChrisJones-MOHC** [comment]
@matthew-mizielinski - I'm happy with that description text. thanks

**Comment by matthew-mizielinski** [comment]
> @matthew-mizielinski very helpful thanks. To be honest, it might be high time that we diversify our contributor base on this. The versioning is managed by the [src/writeJson.py](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/src/writeJson.py) script in this repo, so I normally just edit entries and run that script (which updates all the html/md versions etc), would you like to try cloning the latest version and seeing if you can get it to work for you? If yes, submit a PR and we can double check and then merge and tag (which is the manual part).

Good idea -- See #974

**Comment by slavakharin** [comment]
@matthew-mizielinski @durack1 Please change `ssp245-cov-ghg` to `ssp245-cov-GHG` to be consistent with capital notation `GHG` for DAMIP experiments.

**Comment by matthew-mizielinski** [comment]
> @matthew-mizielinski @durack1 Please change `ssp245-cov-ghg` to `ssp245-cov-GHG` to be consistent with capital notation `GHG` for DAMIP experiments.

Done. Thanks for identifying this @slavakharin.

**Comment by durack1** [comment]
The **6** new experiments are now defined and can be viewed at [](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_experiment_id.html), this takes the total experiment number to 322.

I will leave this issue open waiting for feedback from @martinjuckes (Data Request) and @charlottepascoe (ES-DOCs) to make sure that all the CMIP6 infrastructure is updated to reflect the updated experiment count. @martinjuckes and @charlottepascoe please ping us here when you have made your changes and this issue will be closed

**Comment by charliepascoe** [comment]
Who are the PIs for these experiments?

**Comment by taylor13** [comment]
Not sure, but Chris Jones (@ChrisJones-MOHC ) seems to be one.  Perhaps he can tell us.   (Also note: https://github.com/WCRP-CMIP/CMIP6_CVs/issues/973#issuecomment-713412542 provides some experiment details).

**Comment by MartinaSt** [comment]
@charliepascoe There is a google folder for the covid-MIP coordination, where you can find a spreadsheet containing information on the participants:  https://drive.google.com/drive/folders/1m5WA9dpCL8o63ENOv_JH1JrzKlt200J-

**Comment by durack1** [comment]
@martinjuckes and @charliepascoe just checking to see whether your CMIP6 Data Request and ES-DOCs have been updated to reflect these new registered experiments, if yes, I will close this issue

**Comment by durack1** [comment]
New experiments exist on [ES-DOCs](https://view.es-doc.org/?renderMethod=name&project=cmip6&type=cim.2.designing.NumericalExperiment&client=esdoc-url-rewrite&name=ssp245-covid) and the latest 01.00.33 CMIP6 Data Request release (see the old [01.00.31](http://clipc-services.ceda.ac.uk/dreq/index.html) which needs a refresh), so will close this issue
