### ISSUE TITLE
Register UKESM1-0-LL for DAMIP

### ISSUE THREAD

**Issue by matthew-mizielinski** [WCRP-CMIP/CMIP6_CVs#975]
To allow the publication of UKESM1-0-LL data for `ssp245-covid` and similar experiments defined in #973  I would like to add DAMIP to the corresponding list of activities

**Comment by matthew-mizielinski** [comment]
[Branch prepared](https://github.com/matthew-mizielinski/CMIP6_CVs/tree/issue975_add_ukesm1_damip), but need #974 to be merged and writeJson.py to be re-run to get the correct version number

**Comment by durack1** [comment]
@matthew-mizielinski thanks for this, tweaked and you can see the new registration info at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html).

As an aside you've also been added to this repo, so should be able to submit PRs directly next time

**Comment by matthew-mizielinski** [comment]
Thanks Paul!
