### ISSUE TITLE
MPI-ESM-LR CMIP6_source_id add 'DAMIP'

### ISSUE THREAD

**Issue by johann-git** [WCRP-CMIP/CMIP6_CVs#978]
please include 'DAMIP' for MPI-ESM-LR
regards
Johann Jungclaus

**Comment by durack1** [comment]
@johann-git I presume you mean `source_id = MPI-ESM1-2-LR`?

**Comment by durack1** [comment]
@johann-git that assumed change is now in place, please take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know if any further tweaks are required
