### ISSUE TITLE
institution_id registration of LLNL

### ISSUE THREAD

**Issue by qinyia** [WCRP-CMIP/CMIP6_CVs#983]
institution_id = PCMDI
institution = LLNL (Lawrence Livermore National Laboratory, Livermore, CA 94550, USA). Mailing address: LLNL Climate Program, c/o David C. Bader, Principal Investigator, L-103, 7000 East Avenue, Livermore, CA 94550, USA

**Comment by durack1** [comment]
@qinyia this appears to be an erroneous request, the `PCMDI` institution is included in the CVs, see [CMIP6_institution_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_institution_id.html).

Consequently, I will close the issue

**Comment by qinyia** [comment]
oh, I didn't notice it. Thanks!

**Comment by durack1** [comment]
This should be updated to reflect:
institution_id = LLNL
institution = LLNL (Lawrence Livermore National Laboratory, Livermore, CA 94550, USA). Mailing address: LLNL Climate Program, c/o Stephen A. Klein, Principal Investigator, L-103, 7000 East Avenue, Livermore, CA 94550, USA

**Comment by durack1** [comment]
@matthew-mizielinski just an FYI, with the #985 PR a bunch of changes were made to allow Py3 to function. In the case that you want to run this again, I would hope that Py3 should work without an issue for you as well. I have managed to keep Py2 functionality as well, but will likely stop using this python variant altogether soon

**Comment by matthew-mizielinski** [comment]
Thanks @durack1, I've had a quick scan over the changes related in #985 and tested it out and I think it all works with python3 for me, so feel free to drop python2 at your leisure.
