### ISSUE TITLE
activity_id ScenarioMIP missing for ESM1-1 of E3SM-Project

### ISSUE THREAD

**Issue by MartinaSt** [WCRP-CMIP/CMIP6_CVs#989]
@durack1 The E3SM-Project contributes data to ScenarioMIP. The registration for source_id: E3SM-1-1 needs to be completed by adding activity_id:ScenarioMIP.

**Comment by durack1** [comment]
@mccoy20 can you confirm the above please (that `E3SM-1-1` is contributing to ScenarioMIP), and while we are updating the registration are any other updates required?

**Comment by chengzhuzhang** [comment]
@sterlingbaldwin would you check on this?

**Comment by sterlingbaldwin** [comment]
I can confirm that E3SM is publishing to the ScenarioMIP, all the E3SM related source IDs should be added, E3SM-1-0, E3SM-1-1, and E3SM-1-1-ECA.

**Comment by durack1** [comment]
@MartinaSt @mccoy20 @chengzhuzhang @sterlingbaldwin I can confirm those changes are now complete, please take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know of any other tweaks required

**Comment by sterlingbaldwin** [comment]
@durack1 I think the "institution_id" for all of these should be "E3SM Project".

**Comment by durack1** [comment]
@sterlingbaldwin the `E3SM1-0` model is being used for CFMIP simulations by @qinya (and @mzelinka) see #983 and #984, and for `E3SM1-1` @climate-dude is running [specific LS3MIP](https://esgf-node.llnl.gov/search/cmip6/?institution_id=RUBISCO) simulations, see #761, #775, and #776
