### ISSUE TITLE
source_id registration of BNU-ESM-1-1

### ISSUE THREAD

**Issue by duoying** [WCRP-CMIP/CMIP6_CVs#99]
```
label = BNU-ESM 1.1
source_id = BNU-ESM-1-1
institution_id = BNU
release_year = 2016

label_extended = BNU-ESM 1.1
aerosol = unnamed
atmosphere = CAM4
atmospheric_chemistry = unnamed
land_ice = None
land_surface = CoLM
ocean = MOM4p1
ocean_biogeochemistry = unnamed
sea_ice = CICE4.1
```

**Comment by durack1** [comment]
@duoying I am just trying to finalise this, do you have some additional information that you wanted to add in below (specified by # entries below - sample text in () are taken from the CMIP5 contributing model ACCESS-1-0)?
```
        "BNU-ESM-1-1":{
            "aerosol":"unnamed", # Is there a version number or further info
            "atmosphere":"CAM4", # Is there additional information available i.e (r1.1; 192 x 145 N96; 38 levels; top level 39255m) or similar?
            "atmospheric_chemistry":"unnamed", # Is there a version number or further info
            "cohort":[
                ""
            ],
            "institution_id":[
                "BNU"
            ],
            "label":"BNU-ESM 1.1",
            "label_extended":"BNU-ESM 1.1",
            "land_ice":"None",
            "land_surface":"CoLM", # Is there a version number or further info
            "ocean":"MOM4p1", # is there additional information available i.e (MOM4p1; tripolar primarily 1deg latitude/longitude; 50 levels; top grid cell 0-10m)
            "ocean_biogeochemistry":"unnamed", # Is there a version number or further info
            "release_year":"2016",
            "sea_ice":"CICE4.1",
            "source_id":"BNU-ESM-1-1"
},
```

**Comment by duoying** [comment]
@durack1 we revised to the following form:

        "BNU-ESM-1-1":{
            "aerosol":"CAM-chem",
            "atmosphere":"CAM4 (FV 144x96; 26 levels)",
            "atmospheric_chemistry":"CAM-chem",
            "cohort":[
                ""
            ],
            "institution_id":[
                "BNU"
            ],
            "label":"BNU-ESM 1.1",
            "label_extended":"BNU-ESM 1.1",
            "land_ice":"None",
            "land_surface":"CoLM with carbon-nitrogen interactions",
            "ocean":"MOM4p1 (360x200, tripolar, primarily 1deg latitude/longitude, down to 1/3deg  within 30deg of the equatorial tropics; 50 levels)
            "ocean_biogeochemistry":"Dynamic ecosystem-carbon model"
            "release_year":"2016",
            "sea_ice":"CICE4.1",
            "source_id":"BNU-ESM-1-1"
}

**Comment by durack1** [comment]
@duoying great I'll start pulling this across.. Just because I am interested do you have some additional information for the ??UPPERCASE?? fields below, and version numbers for the specific modules noted below?
```
        "BNU-ESM-1-1":{
            "aerosol":"CAM-chem", # Is there a version number
            "atmosphere":"CAM4 (FV 144x96; 26 levels, ??TOP LEVEL: XXMB??)",
            "atmospheric_chemistry":"CAM-chem", # Is there a version number
            "land_surface":"CoLM with carbon-nitrogen interactions", # Is there a version number
            "ocean":"MOM4p1 (360x200, tripolar, primarily 1deg latitude/longitude, down to 1/3deg  within 30deg of the equatorial tropics; 50 levels, ??TOP [VERTICAL] LEVEL 0-10M??)
            "ocean_biogeochemistry":"Dynamic ecosystem-carbon model" # Is there a version number
}
```

**Comment by duoying** [comment]
@durack1 Please check the following revisions:

        "BNU-ESM-1-1":{
            "aerosol":"Semi-interactive",
            "atmosphere":"CAM4 (FV 144x96; 26 levels, TOP LEVEL: 2.194 MB)",
            "atmospheric_chemistry":"None", # It's off for CMIP6
            "land_surface":"CoLM with carbon-nitrogen interactions", # Is there a version number
            "ocean":"MOM4p1 (360x200, tripolar, primarily 1deg latitude/longitude, down to 1/3deg  within 30deg of the equatorial tropics; 50 levels, TOP 1 LEVEL 0-10M),
            "ocean_biogeochemistry":"Dynamic ecosystem-carbon model" # Is there a version number
}

**Comment by durack1** [comment]
@duoying any chance you can provide an answer to the remaining queries so I can register your model?
```
"BNU-ESM-1-1":{
 "land_surface":"CoLM with carbon-nitrogen interactions", # Is there a version number
 "ocean_biogeochemistry":"Dynamic ecosystem-carbon model" # Is there a version number
}
```

**Comment by duoying** [comment]
@durack1 please check the following revisions:

"BNU-ESM-1-1":{
 "land_surface":"CoLM version 2014 with carbon-nitrogen interactions", # Is there a version number
 "ocean_biogeochemistry":"Dynamic ecosystem-carbon model version 1" # Is there a version number
}

**Comment by durack1** [comment]
@duoying please review the entries in [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) for accuracy, and if any revisions are required please reopen and detail the amendments in this issue

**Comment by durack1** [comment]
@duoying we've amended the information that we're collecting about models and require some additional information from you. The values below need some revision or new information - I've noted `### some text ###` below where I have revised the format between the `#` symbols, or a ### marker where web links to the information sources for new fields that we require additional information from you:
```
"BNU-ESM-1-1":{
  "activity_participation":[
    "" ### See activity list at https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_activity_id.json
  ],
  "atmosphere":"CAM4 (FV; ###144 x 96 longitude/latitude###; 26 levels; top level 2.194 mb)",
  "nominal_resolution_atmos":"", ### See Appendix 2 in https://goo.gl/v1drZl
  "nominal_resolution_landIce":"", ### See Appendix 2 in https://goo.gl/v1drZl
  "nominal_resolution_ocean":"", ### See Appendix 2 in https://goo.gl/v1drZl
},
```

**Comment by durack1** [comment]
@duoying have you had a chance to obtain the additional information we require above?

**Comment by duoying** [comment]
@durack1 please see the following revisions:

"BNU-ESM-1-1":{
  "activity_participation":[ "C4MIP","CMIP","GMMIP","GeoMIP","OMIP","ScenarioMIP" ],
  "atmosphere":"CAM4 (2deg; 144 x 96 longitude/latitude; 26 levels; top level 2.194 mb)",
  "nominal_resolution_aerosol":"250 km",
  "nominal_resolution_atmos":"250 km",
  "nominal_resolution_land":"250 km", 
  "nominal_resolution_ocean":"100 km",
  "nominal_resolution_oceanBgchem":"100 km",
  "nominal_resolution_seaIce":"100 km"
},

**Comment by durack1** [comment]
@duoying thanks for this, peek at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further tweaks are required

**Comment by durack1** [comment]
@duoying no problem, I will amend these details in the next update (and am re-opening this issue until the changes are in place)

**Comment by durack1** [comment]
@duoying please review the updated details in [CMIP6_source_id.html](https://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further tweaks are required
