### ISSUE TITLE
experiment_id -- add 'ssp585-GHG'

### ISSUE THREAD

**Issue by chengzhuzhang** [WCRP-CMIP/CMIP6_CVs#990]
Hi, The E3SM team are looking to publish 3 ensembles of E3SM v1 ssp585-GHG experiment but 'ssp585-GHG' is not included in current https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_experiment_id.html. Would you please check to add this? Thank you!

**Comment by durack1** [comment]
@chengzhuzhang what is the `ssp585-GHG` experiment? It's not part of CMIP6 as you have noted above

**Comment by chengzhuzhang** [comment]
My understanding is it's similar to ssp245-GHG only, but used ssp585 scenario. I'm ccing @tangq, who conducted the simulations for supplying with more details of these simulations. If they are not part of DAMIP, I guess we will only be able to publish to E3SM's project space.

**Comment by tangq** [comment]
These 3 ssp585-GHG experiments are DAMIP well-mixed greenhouse-gas-only future projection simulations with 1850 tropospheric and stratospheric ozone (see [Gillett et al., 2016](https://gmd.copernicus.org/articles/9/3685/2016/) for details). I am not sure if it is part of CMIP6 though.

**Comment by taylor13** [comment]
Just to confirm that ssp585-GHG is not a CMIP6 experiment (but ssp245-GHG is a CMIP6 experiment).

**Comment by chengzhuzhang** [comment]
Hi @taylor13, Thank you for confirming!
