### ISSUE TITLE
source_id -- add "DAMIP" for MIROC-ES2L

### ISSUE THREAD

**Issue by tinoue70** [WCRP-CMIP/CMIP6_CVs#993]
Please add "**DAMIP**" to "_activity_participation_" of "**MIROC-ES2L**". 

We will publish "CovidMIP" related experiments.

**Comment by durack1** [comment]
@tinoue70 that change is now in place, please take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and confirm all other details are correct
