### ISSUE TITLE
Which types of CMIP6 Climate models to select for a specific region

### ISSUE THREAD

**Issue by wh19971014** [WCRP-CMIP/CMIP6_CVs#996]
Here are instructions both for registering your institution and model for CMIP6 and for raising other issues concerning CMIP6 controlled vocabularies. We can update details iteratively, until you begin writing CMIP6 data.

I want to know which  Climate models to select at a specific region,**for example The upper reaches of the Yangtze River**,as we know, there are many kinds of climate models in the cmip6 data(the following photo),I want to select the most appropriate several climate models for a specific region.
![微信截图_20201214102123](https://user-images.githubusercontent.com/60054308/102791673-56088180-43e2-11eb-80ed-4614911e0bdd.png)
.

**Comment by durack1** [comment]
@wh19971014 this repo is being used for collecting information regarding **contributors** to CMIP6, not for QandA.

I suggest you redirect your browser to the CMIP6 Guide, see https://pcmdi.llnl.gov/CMIP6/Guide/dataUsers.html. In addition, considering a literature review of how previous studies have assessed global model performance (for e.g. Yangtze river and CMIP5) for regional use may be a good starting point
